### ISSUE TITLE
Import/Export: Implement handling of import of duplicates

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#1244]
If we import an event and we want to import a newer version of it through the same user, what happens? Currently we will have the same event set up again. Please implement a better option. If a user re-imports the same event - with the same name and date -, please
- [ ] offer the user to overwrite the previous event or
- [ ] give the possibility to merge the data (please explain your ideas about that)

**Comment by aviaryan** [comment]
@mariobehling 
Overwriting an event on import seems possible but merging can get tricky. 

Current Event (on server) - A
Event going to be imported - B

The following challenges exist - 

1. Identifying an object - How to identify a track, session, microlocation, speaker, session types etc. As we can't rely on IDs here, we will have to rely on `name`/`title` type of fields. But in that case, if the `name`/`title` fields are changed in both copies, it may lead to unwanted data duplicacy. And if a `name` field is modified in A and it equals another `name` field in B, it will result in data loss. 
And we can't rely on name/title fields for uniqueness as they can be edited. 
There are other things like session_types which can have non-unique name fields (Workshop 1h, 2h) and it gets very tough to decide whether a session type was deleted or edit or newly created. This too can lead in data duplicacy.  

2. Which version to keep ? - Suppose a speaker profile gets modified in A and B. (Supposing we identify speaker profile by email) Suppose that the `website` and the `bio` fields differ in the 2 speaker profiles. In that case, which field values to keep ? `website` of A and `bio` of B or what ?

These are the problems I see now but more problems may arise when we start coding.

I think even if we make it carefully, merging has a possiblity to lead into unwanted data loss and duplicacy. Not to mention, it **will** take lots of time and testing.
That being said, I don't think it is a good idea to keep such a feature. (Sorry I don't get why this feature is needed)

**Comment by mariobehling** [comment]
@aviaryan Good points. This needs to be thought-through and is not the top priority now, but would be a nice feature for the future.

Let's keep this issue in mind and move it to the end of this GSoC.
