### ISSUE TITLE
Server implementation for news feed feature in Open Event Android and Orga app

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-server#4074]
**I'm submitting a ...**  
- [ ] bug report
- [x] feature request
- [ ] support request 

**Current behavior:**
Currently, there is a problem when organisers want to send announcements and notify the attendees of something, as it has to be done through word-of-mouth generally, which is a cumbersome process and not everyone gets notified on time. This was faced in the FOSSASIA 2017 summit as well.

**Expected behavior:**
Now that we have a robust platform, there should be a feature wherein, the organisers can notify attendees about anything and everything they want to in real time by sending push notifications to all phones that have Open event Android installed onto them. 

**Steps to reproduce:**
This above feature is achievable using **FCM**[also known as GCM) services by Google. This works as follows:

- The client app (the [Orga app](https://github.com/fossasia/open-event-orga-app)), will send notification data to the Orga server.

- The Orga server will send it to the FCM server. For this we need the following requirements for the Orgs server:-

- [ ] Able to communicate with your client.

- [ ] Able to send properly formatted requests to the GCM connection server.

- [ ] Able to handle requests and resend them using [exponential back-off](https://developers.google.com/api-client-library/java/google-http-java-client/backoff).

- [ ] Able to securely store the server key and client registration tokens.

- [ ] ~For XMPP, the server must be able to generate message IDs to uniquely identify each message it sends (GCM HTTP connection server generates message IDs and returns them in the response). XMPP message IDs should be unique per sender ID.~

- The FCM server will push all the data as push notifications to all client apps (i.e, to all the phones that have [Open event Android](https://github.com/fossasia/open-event-android) installed onto them.)

**Other information:**
This feature has to work on **real-time**. 

The FCM server to client-apps(Open event Android) part of it is handled by the FCM server itself. 
For communication between the Orga server and FCM server, we have to follow:

- ~XMPP, or~
- HTTP 
As far as I know, we will need XMPP, as it provides Upstream and downstream (device-to-cloud, cloud-to-device), unlike HTTP ( Downstream only, cloud-to-device )

The Google Docs for server side implementation for FCM can be found here: https://firebase.google.com/docs/cloud-messaging/server

**Future scope:**

FCM also allows communication with web apps, so this can be extended to Open Event web app in  future.

> _Edited by @niranjan94_

**Comment by niranjan94** [comment]
We will be using only HTTP. (Cloud-device). For upstream, the device is to use the Organizer Server HTTP API.

**Comment by niranjan94** [comment]
Scheduling this for Milestone 13 @mahikaw . The server is still not stable enough with the basics at this point.

**Comment by mahikaw** [comment]
Okay sure @niranjan94 I think we can then implement this feature in the Android repo by https://github.com/fossasia/open-event-orga-server/milestone/35 on priority.
