### ISSUE TITLE
Add support for a "pay what you want" model

### ISSUE THREAD

**Issue by kittykat** [fossasia/open-event-server#4213]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
When creating a new event, the ticket price needs to be specified.

**Expected behavior:**
Allow a user to enter a payment that they want to submit while providing some guidelines on recommended amounts.

**Steps to reproduce:**
1. Go to https://eventyay.com/events/create/
1. Enable "USE TICKETING SYSTEM"
1. Observe "Free ticket" and "Paid ticket" options.

**Other information:**
At this point, there should be an option to select "Pay what you want". This option should allow the event organiser to list a few suggestions which will be shown to the user (at the moment we so this with a slider from €0-€200 and an entry next to it which shows the amount). The suggestions can be listed either as markers on the slider or as a list below it.

**System information:** 
https://eventyay.com

**Comment by venkateshbellale** [comment]
###hi

so how to get started

**Comment by niranjan94** [comment]
Hi @venkateshbellale :) 

This issue isn't a priority at this point. Please check out the other [issues](https://github.com/fossasia/open-event-orga-server/issues) and pick one from them.

**Comment by mariobehling** [comment]
This has been implemented in the form of "donation" tickets.
