### ISSUE TITLE
Regression: clicking "Export CSV doesn't work anymore"

### ISSUE THREAD

**Issue by NinaNC** [fossasia/open-event-server#4382]
The issue was solved, but now it fails again

**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
When clicking CSV in "Export CSV", nothing seems to happen. When looking at the logs I see that it tries to reach an API and tries to perform the same tasks over and over again. It results in {state:FAILURE}

**Expected behavior:**
Downloading a CSV file.

**Steps to reproduce:**
Log in, go to Attendees, try to export the CSV.

**Other information:**
PDF export works.

**System information:** 

Using Chromium.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-legacy
