### ISSUE TITLE
Add support for multiple emails for a user

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-server#4436]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Users sometimes use work email and personal emails. If they get an invitation to an event to their work email, then they have to sign up potentially again.

**Expected behavior:**
Add support for multiple email for user like Github.

**Comment by souravsingh** [comment]
@geekyd @mariobehling I am interested in working on the issue.

**Comment by bhaveshAn** [comment]
@souravsingh Are you working on this issue? Please let me know.

**Comment by vipuldcoder** [comment]
I am interested in working on the issue.

**Comment by sumedh123** [comment]
@vipuldcoder Please proceed. I don't think there is progress on this one so you can take this up.

**Comment by vipuldcoder** [comment]
Thank You
