### ISSUE TITLE
Integrate Badgeyay

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/open-event-server#4475]
**I'm submitting a ...**
- [X] feature request

**Current behavior:**

Currently, badgeyay is a standalone website.
I would like to have a one-click solution from eventyay to generate badges.

**Expected behavior:**

Please add a button to the [open-event-orga-server](https://github.com/fossasia/open-event-orga-server) to generate a badge for the list of speakers.

**Steps to reproduce:**

1. I go to an example event.
1. I go to the edit page of the event
1. I view the list of speakers
1. I click on generate badges
1. I am redirected to the [badgeyay website](https://github.com/fossasia/badgeyay) in an other tab (fields are prefilled)
1. I can choose the png file (speaker is preselected)
1. I click on generate badges
1. I download the pdf file

(This is a proposed workflow. If it does not work, please propose another. for closing the issue one agreed workflow must stand)

Hints: 
- Please make yourself familiar with eventyay.
- This issue is crossposted: https://github.com/fossasia/badgeyay/issues/143

**This is a cooperation issue between projects. Please coordinate here: https://github.com/fossasia/badgeyay/issues/143**

**Comment by Kanav-7** [comment]
I would like to work on this issue.

**Comment by niccokunzmann** [comment]
@Kanav-7 Sure, please go ahead. Please coordinate on the other issue posted.

**Comment by mariobehling** [comment]
@niccokunzmann This comes a bit early as we are making a transfer to a separated system with front-end and backend. Therefore, this issue should only be tackled after the change has been made and other issues have been closed. Please delay that.

**Comment by bhaveshAn** [comment]
> This comes a bit early as we are making a transfer to a separated system with front-end and backend.

@mariobehling I think now the backend and frontend (in [Open-event-frontend](https://github.com/fossasia/open-event-frontend))are implemented separately. So can I work on this issue.

**Comment by mariobehling** [comment]
Out of scope currently.
