### ISSUE TITLE
Create some seed Data for Development

### ISSUE THREAD

**Issue by ananyo2012** [fossasia/open-event-server#4477]
**I'm submitting a ...
- [ ] bug report
- [ ] feature request
- [x] support request => According to [gitter discussion](https://gitter.im/fossasia/open-event-orga-server?at=59c37933cfeed2eb6534ad95)

**Current behavior:**
Presently there is no seed data for events, sessions, tickets etc. except the super admin. We have to manually create some data to test out the API. For newcomers It will be especially helpful if there is some test data to test the API

**Possible Solution**
We can write a python script to seed some data. Currently there is [populate_db.py](https://github.com/fossasia/open-event-orga-server/blob/nextgen/populate_db.py) that populates the database with some data for the super admin. We can add some method to add more data related to events, sessions, tickets etc and run that to create some test data.

**Comment by raju249** [comment]
@shubham-padia Is this issue available for working ?

**Comment by bhaveshAn** [comment]
@shubham-padia Can I take up this issue.

**Comment by iamareebjamal** [comment]
Closing this as there is no clear way a seed data can be created, eg, what fields should be used? The factories also don't reuse existing models but recreate relationships. If needed, will reopen
