### ISSUE TITLE
Export of Attendees as CSV not working on eventyay.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#4499]
If events have a larger crowd, the CSV export of the event does not work. Please fix as follows:
* Offer a button "Generate CSV"
* After the user hits the button show a progress icon
* When CSV is generated show a download button and store the CSV for a week
* On the download area show the date of the generated file
* Behind the file show "Re-generate" to create a newer version of the CSV

**Comment by rahuldecoded** [comment]
@mariobehling I would love to work in this. Can you please assign it to me.

**Comment by rahuldecoded** [comment]
@mariobehling I've been working on #4382 and I tried to fix it in #4501 Should I make more changes as stated by you in this issue?

**Comment by bhaveshAn** [comment]
@mariobehling @shubham-padia Can I take up this one.

**Comment by bhaveshAn** [comment]
It has been solved by the endpoint `/v1/exports/events/<string:event_identifier>/export/attendees/csv` : https://github.com/fossasia/open-event-server/blob/development/app/api/exports.py#LC179

Hence closing!
