### ISSUE TITLE
Download of attendees and orders as PDF and CSV not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#4516]
When trying to download the attendee or orders list either it takes very long or it does not work. Sometimes an error message "Bad Gateway" appears.

![screenshot from 2017-10-23 14-00-43](https://user-images.githubusercontent.com/1583873/31888069-e13e6afc-b7fa-11e7-8d22-e59b1cfe21f8.png)

**Comment by ananyo2012** [comment]
Is this similar to what happened in csv download? It works fine with fewer entries.

**Comment by SaptakS** [comment]
@ananyo2012 you ned to implement celery and take care of race case condition to queue the process because gunicorn will timeout after some time. So any download and export should be using celery. You can see the example for export of the entire event or importing of events for the same.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-legacy

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-legacy
