### ISSUE TITLE
Add support/end point for social-links application connect in settings

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4526]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

![image](https://user-images.githubusercontent.com/17252805/32121044-89dc5248-bb78-11e7-9dd0-b82ff829cf44.png)

**Comment by raju249** [comment]
@CosmicCoder96  Can you please elaborate more on this issue ?

**Comment by prateekj117** [comment]
@CosmicCoder96 @iamareebjamal Can you please elaborate this a bit more.

**Comment by iamareebjamal** [comment]
Implement backend endpoint for social connect. For e.g., I want to connect my Google account to the server so I can authenticate. 

Cannot be done till OAuth for these systems has not been implemented, so skip but is needed

**Comment by liveHarshit** [comment]
Is anyone working on it?

**Comment by shreyanshdwivedi** [comment]
@liveHarshit currently no one is working on it. As @iamareebjamal mentioned, it needs OAuth for implementation, which itself isn't implemented. So it is skipped for now

**Comment by prateekj117** [comment]
@iamareebjamal What services are we planning to integrate?

**Comment by iamareebjamal** [comment]
None

**Comment by mariobehling** [comment]
Out of scope according to updated plan.
