### ISSUE TITLE
Sessions API: Add missing 'Last Modified'

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-server#4530]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
![screen shot 2017-11-08 at 2 22 11 am](https://user-images.githubusercontent.com/12807846/32517233-cc9f5704-c42b-11e7-8a7a-18e9c65bc081.png)
Currently a field is missing in the API for displaying last modification date.

**Expected behavior:**
The API should include a field for modification/updates made to the session.

**Comment by Anonymous26** [comment]
i would like to work on this issue @geekyd

**Comment by ritikamotwani** [comment]
I would like to work on this issue.
