### ISSUE TITLE
Add API documentation for speakers for a session and speaker profiles for a user. 

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-server#4531]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
There is no documentation for [speakers for a session](https://open-event-api.herokuapp.com/#speakers-list-speakers-under-a-session) and [speaker profiles for a user](https://open-event-api.herokuapp.com/#speakers-list-speaker-profiles-for-a-user)
**Expected behavior:**
Add documentation

**Comment by shubham-padia** [comment]
Any updates here?

**Comment by raju249** [comment]
I am claiming this but need more info to know how API works.
One method is reading code, any other way @shubham-padia ?

**Comment by shubham-padia** [comment]
Checkout the blogs on blog.fossasia.org exposing how to add API documentation

**Comment by raju249** [comment]
Thanks @shubham-padia .
I was actually asking about how do I see the endpoint for the API ? the input needed for URI params

**Comment by poush** [comment]
You will need to check `app/api/__init__.py. All endpoints are there.

**Comment by raju249** [comment]
Sure @poush 
Thanks

**Comment by invinciblycool** [comment]
No @raju249 .
`/sessions/<int:id>/relationships/session-type` and `/speakers/<int:speaker_id>/user` are the correct routes.
Please check.

**Comment by raju249** [comment]
`/sessions/<int:id>/relationships/session-type` Should be `session-type` or `/sessions/<int:id>/relationships/speaker` ?
@invinciblycool

**Comment by invinciblycool** [comment]
Please check, I have edited the comment already before

**Comment by raju249** [comment]
Sure thing.
Taking those mentioned endpoints for documentation.
Thanks

**Comment by raju249** [comment]
Seems like the documentation is already available [here](https://github.com/fossasia/open-event-server/blob/development/docs/api/api_blueprint.apib#L11863)

I think for some reason its not shown on the web page. 
What you think ?

**Comment by invinciblycool** [comment]
I guess the issue is not what I expected. @raju249 You can work on other issues meanwhile I figure this out. Thanks!

**Comment by raju249** [comment]
Sure @invinciblycool 
I just saw that and reported here :sweat_smile:

**Comment by invinciblycool** [comment]
Actually after reading apiary docs, I realized that the request and response are needed for any request to be rendered by aglio. Opening a PR for the same.

**Comment by raju249** [comment]
Sure @invinciblycool 
happy that I was able to help :smile:
