### ISSUE TITLE
GET call to microlocation returning 404 response.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-server#4535]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Current:
Endpoint: https://open-event-api.herokuapp.com/v1/sessions/67/microlocation

Response: 
```json
{
    "errors": [
        {
            "status": 404,
            "title": "Object not found",
            "detail": "Object Not Found",
            "source": {
                "pointer": ""
            }
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}

```

**Comment by poush** [comment]
@sumedh123 the error output says 404 while you are saying 400.

**Comment by sumedh123** [comment]
@poush Sorry, my bad.

**Comment by invinciblycool** [comment]
Taking this up.

**Comment by invinciblycool** [comment]
@sumedh123 @poush The API endpoint works perfectly fine for me locally.
The endpoint returned a 404 for a non-existing session and returned the JSON for an existing session.
My request was as follows:

Endpoint  localhost:5000/v1/sessions/1/microlocation
Response
```json
{
    "data": {
        "relationships": {
            "event": {
                "links": {
                    "self": "/v1/microlocations/1/relationships/event",
                    "related": "/v1/microlocations/1/event"
                }
            },
            "sessions": {
                "links": {
                    "self": "/v1/microlocations/1/relationships/sessions",
                    "related": "/v1/microlocations/1/sessions"
                }
            }
        },
        "attributes": {
            "latitude": 45,
            "room": "room1",
            "name": "microlocation-name",
            "longitude": 45,
            "floor": 2
        },
        "type": "microlocation",
        "id": "1",
        "links": {
            "self": "/v1/microlocations/1"
        }
    },
    "jsonapi": {
        "version": "1.0"
    },
    "links": {
        "self": "/v1/microlocations/1"
    }
}
```
Am I missing something? I am unclear as to what is to be done.

**Comment by shubham-padia** [comment]
Unable to recreate the issue. Closing this thread due to inactivity. Please reopen if needed
