### ISSUE TITLE
Ticketing system switch

### ISSUE THREAD

**Issue by MostafaEbrahimi** [fossasia/open-event-server#4537]
I use docker for deploy development branch on my localhost windows system.when I clone project and deploy have missing ticketing system switch feature but in your demo it switch exists.
How to solve this problem ?!

**Comment by SaptakS** [comment]
@MostafaEbrahimi I think you might not have enabled the ticketing system in admin. To enable the ticket switch, you need to do the following steps: 
* go to Admin
* go to Modules
* turn on the switches for Ticketing and Payments
