### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-server#4539]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

Update the README.md file for the new Open Event API.
- Update the name of the repo in readme

**Comment by 0x48piraj** [comment]
_Have you read #3931, @geekyd ?_

> **I have revamped the `README.md` recently and this came to my mind, but this issue is still open! :blush:**
