### ISSUE TITLE
[Readme] Update branch policy in the readme file to the updated one

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-server#4543]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently the readme shows the previous branch policy that we had before separating of the legacy code and the API based code. 

**Expected behavior:**
Since the repositories have been separated and the branch policy has been changed, the readme needs to be updated.

**Comment by HimanshuAttri** [comment]
@SaptakS @mariobehling Can I take this issue? Since I am new to the organization, could you please help me with the information on current branch policies?

**Comment by poush** [comment]
@HimanshuAttri  Go ahead! See #4538 you will see the name of branches has been changed. You will changes names in branch policy according to this.

**Comment by shubham-padia** [comment]
@HimanshuAttri any updates?

**Comment by raju249** [comment]
@shubham-padia , @poush The referenced issue #4538 doesn't talk explicitly which branches are present currently in the repo.
Can you please clarify what exact changes are to be done ?
Thanks
