### ISSUE TITLE
Update installation/deployment instructions.

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-server#4544]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
Currently in all the installation/deployment instructions there are many instances where `open-event-orga-server` still persists which can create confusion while following the instructions.

**Expected behavior:**
`open-event-orga-server` needs to be replaced with `open-event-server`at many instances in installation/deployment docs.

**Steps to reproduce:**
Check out the documentation of different installations/deployments.
https://github.com/fossasia/open-event-server/tree/development/docs/installation and https://github.com/fossasia/open-event-server/tree/development/docs

**Comment by pandyamarut** [comment]
please give the path to the file for easy access.

**Comment by invinciblycool** [comment]
You might want to look [here](https://github.com/fossasia/open-event-api/tree/development/docs/installation)
All the installation/deployment docs can be found here.

**Comment by invinciblycool** [comment]
@SaptakS @niranjan94  if you could please add the appropriate labels so that it is easier for new contributors. Thanks.

**Comment by raju249** [comment]
Claiming this!

**Comment by raju249** [comment]
Changing all the occurrences of `open-event-orga-server` to open-event-server` .
