### ISSUE TITLE
index file serves a file from github repository

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4548]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Currently in the open event server when you request the root directory "/" it will make a request to github and then serve the HTML as response.
**Expected behavior:**

The program should be self-contained and not depend on internet request to desplay the index.html
**Steps to reproduce:**

Just try to run the server on a local enviroment without internet connection and it won't work. It won't display index.html
**Related code:**
`app/views/__init__.py line:85`
```
@home_routes.route('/')
def index():
    """
    Index route
    :return:
    """
    r = requests.get('https://raw.githubusercontent.com/fossasia/open-event-orga-server/gh-pages/api/v1/index.html')
    response = make_response(r.content)
    response.headers["Content-Type"] = "text/html"
    return response

```

**Comment by shubham-padia** [comment]
The project uses aglio(https://github.com/danielgtaylor/aglio) to render API docs. Anyone working on this, please propose how you intend to tackle this problem and then start on it.
Keep in my mind that the docs need to be generated only once during deployment, and they should be included in some directory like `dist/docs/api/v1` in the final build of the project that is deployed to the server.

**Comment by invinciblycool** [comment]
@shubham-padia Why not use the CLI of aglio(`aglio –theme-variables slate -i api_blueprint.apib -o output.html` as mentioned [here](https://blog.fossasia.org/rendering-open-event-servers-api-blueprint-document/) and use it to output the html once and then render it.
We could check if the html does not exist in a specific directory(say `dist/docs/api/v1`), then render it using the CLI or not otherwise.
