### ISSUE TITLE
flask reload

### ISSUE THREAD

**Issue by MostafaEbrahimi** [fossasia/open-event-server#4551]
How to config docker for reload flask app on changing source code?
(changing source code on local machine)

**Comment by MostafaEbrahimi** [comment]
may answer me ?!I need it as soon as possible ! :/

**Comment by niranjan94** [comment]
@MostafaEbrahimi please as your question at https://gitter.im/fossasia/open-event-orga-server 

Don't use GH issues for technical assistance. :)
