### ISSUE TITLE
Prepare a visualization for the database in documentation

### ISSUE THREAD

**Issue by abhishekvermasg** [fossasia/open-event-server#4554]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Other information:**
There is no database visualization for the database for this project, which is pertinent.

**Comment by abhishekvermasg** [comment]
I would like to work on this, if this seems like a viable option. @mariobehling @niranjan94 @shubham-padia

**Comment by shubham-padia** [comment]
@abhishekvermasg We have a database visualization on localhost:5000/admin, we are using flask-admin for it. Though we have many issue while editing data in flask admin, we use it for read only purposes for now. 
If you have any alternative in mind, it would be great if you can try it out where editing data and relationships works well in it.
Till then you can add info about the current flask admin in the documentation.

**Comment by rngadam** [comment]
Not sure if what is meant by visualization is ERD diagram, but it's easy to generate one in DBeaver:

![image](https://user-images.githubusercontent.com/538542/39411909-84e080ee-4c45-11e8-8b09-cb41e8f4060d.png)

**Comment by prateekj117** [comment]
@bhaveshAn @iamareebjamal Is this still required?

**Comment by iamareebjamal** [comment]
Low priority, skip
