### ISSUE TITLE
Make relation bw user and event independent of roles table

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-server#4560]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
For a relationship to exist between user and event, It is necessary right now that the `role` table has the default values of organizer, coorganizer, moderator etc roles pre-populated. 

When some changes are made to that table by mistake by the admins, the relationship between the user and event stops working 🤦

**Expected behavior:**

Make sure that the default values are present in the app and do not depend on the database. Information about the default roles can be found in the `populate_db.py` file at the root of the project. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `python --version`
```

**Comment by starlord1311** [comment]
i would like to work on this. can i? @shubham-padia

**Comment by shubham-padia** [comment]
@starlord1311 have you set up the server on your local machine?

**Comment by starlord1311** [comment]
@shubham-padia i am unable to. can you help?

**Comment by shubham-padia** [comment]
@starlord1311 please join it gitter channel for installation related queries :)

**Comment by pradeepgangwar** [comment]
@shubham-padia I would like to work on this.

**Comment by simsausaurabh** [comment]
@shubham-padia If no one is currently working on this issue, can I take this ?

**Comment by srv-twry** [comment]
@bhaveshAn I think you have already fixed this. Please confirm. If fixed, then please close this issue.

**Comment by bhaveshAn** [comment]
Currently, the permissions of events role has been accessible by `/v1/event-role-permissions`  so IMO this API solves the issue that
> When some changes are made to that table by mistake by the admins, the relationship between the user and event stops working 

If admin make changes in the permissions by mistake or intensionally (It means that Admin makes a PATCH request at `/v1/event-role-permissions/1` for organizers (say) ) then it will update the permissions and so reflected by function [_has_perm](https://github.com/fossasia/open-event-server/blob/development/app/models/user.py#LC240)
Hence closing. 
Feel free to reopen if https://github.com/fossasia/open-event-server/pull/4803 doesn't solves the issue.
