### ISSUE TITLE
Empty space, broken links, missing information

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/open-event-server#4562]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
- Plenty of Blank Lines 
![image](https://user-images.githubusercontent.com/14032427/34069292-10f09ae2-e274-11e7-89ca-ca309f371641.png)
![image](https://user-images.githubusercontent.com/14032427/34069313-ac6cff06-e274-11e7-83dd-2e902f66bd82.png)
- global.js not minified.
- no copy to clipboard button
![image](https://user-images.githubusercontent.com/14032427/34069320-ec500cda-e274-11e7-9e17-a451f454175e.png)
-science and tech placeholder missing
 [http://open-event-dev.herokuapp.com/static/placeholders/Science&Technology.jpg](http://open-event-dev.herokuapp.com/static/placeholders/Science&Technology.jpg)
- broken image links
![image](https://user-images.githubusercontent.com/14032427/34069342-aafb895c-e275-11e7-9ec5-dc46fc7d9135.png)
- location and connect with us missing
![image](https://user-images.githubusercontent.com/14032427/34069360-ed09e578-e275-11e7-8627-e1374abc18bc.png)
- no sitemap for search engine
![image](https://user-images.githubusercontent.com/14032427/34069402-8652ef5e-e276-11e7-81a4-c7b0682f8304.png)

**Expected behavior:**
- clean code
- a minified global.js for faster loading
- a copy to clipboard button to copy link
- fixed links
- added location and contact details
- sitemap for search engines

**Steps to reproduce:**
- remove lines 
- minify global.js
- add a copy to clip button
-added location and contact details
- add a sitemap for search engines

**Comment by simsausaurabh** [comment]
Are you working on this issue - @YashKumarVerma. If not, I would like to work on this issue.

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy
