### ISSUE TITLE
Hamburger

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/open-event-server#4566]
![screen shot 2017-12-20 at 12 27 03 am](https://user-images.githubusercontent.com/34275800/34173775-99e6c9b6-e51c-11e7-9a40-ba00ee9ef9b9.png)

![screen shot 2017-12-20 at 12 26 50 am](https://user-images.githubusercontent.com/34275800/34173777-9a51a8d0-e51c-11e7-9e37-4fb407082c4b.png)

There isn't a hamburger in the navbar the other links in the navbar just vanish where as if the hamburger is added all links will be available to the website user. It will increase the responsiveness of the website.

**Comment by samyakbvs** [comment]
The screenshots are given for the reviewers to see what I am talking about

**Comment by akshatnitd** [comment]
Check this (https://github.com/fossasia/open-event-server/blob/development/.github/ISSUE_TEMPLATE.md) for correct issue template
