### ISSUE TITLE
Data not translated(The links)

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/open-event-server#4567]
![screenshot 72](https://user-images.githubusercontent.com/24372680/34170007-4e4c5c12-e50f-11e7-8cd5-e19ff8b155f2.png)

**Comment by simsausaurabh** [comment]
Please use standard issue template for creating an issue.

**Comment by shubham-padia** [comment]
This depends on the available translated words on weblate. If there is no translation available, the words will appear the same. The translations are contributed by the community and there's nothing that can be done about this
