### ISSUE TITLE
Hamburger

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/open-event-server#4568]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request
- [x] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

The links in the navbar vanish after the window hits tablet size
**Expected behavior:**

All the links would be available to the user even after the window hits the tablet size
**Steps to reproduce:**

Introduce a hamburger 
![screen shot 2017-12-20 at 12 34 47 am](https://user-images.githubusercontent.com/34275800/34174055-9ae6decc-e51d-11e7-91a1-e83189d2d33e.png)
like this

**Comment by invinciblycool** [comment]
@samyakbvs This issue should be reported here https://github.com/fossasia/open-event-frontend

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy
