### ISSUE TITLE
Include name of contributors in "contributors list"

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/open-event-server#4569]
**I'm submitting a ...** 
- [X] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**

Recent contributors are not showing in contributor list of fossasia/open-event-server

**Expected behavior:**

Include the names of contributors in contributor list

**Steps to reproduce:**

I dont't have any steps for now

**Comment by bhaveshAn** [comment]
Can you please tell which names are not ot showing up in contributor list of fossasia/open-event-server

**Comment by shubham-padia** [comment]
@simsausaurabh Works as expected. Please reopen if the issue is found again. Thanks :smile:

**Comment by simsausaurabh** [comment]
@shubham-padia @bhaveshAn my name is not showing 'simsausaurabh'. Please clarify. :smile:
