### ISSUE TITLE
Bug in Event Search Page

### ISSUE THREAD

**Issue by ParthPratim** [fossasia/open-event-server#4570]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

The search utility does not sanitize user input due to which the script beginning on line number 1578 on page http://open-event-dev.herokuapp.com/explore/india/events/  crashes due to an Error : "unterminated string literal" and renders javascript on the page in bottom section (Images displaying the bug is attached) as well as the loading bar does not display any results neither does it disappear.

**Expected behavior:**

No matter what the input is the javascript should not be rendered and the page should either display no search results or sanitize the user input and then display related searches.

**Steps to reproduce:**

query payload : <script>alert("s")</script>
Test Link : http://open-event-dev.herokuapp.com/explore/india/events/?query=<script>alert("s")</script>

![screenshot from 2017-12-20 13 17 07](https://user-images.githubusercontent.com/30770796/34196428-1a61d782-e588-11e7-9927-f6e89a0c9846.png)

**Comment by bhaveshAn** [comment]
I would like to work on this issue.

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy
