### ISSUE TITLE
No Translation for 4 Languages mentioned in the Drop Down.

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/open-event-server#4571]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Translation of 4 Languages are not working

1. French
2. Polish
3. Russian
4. Thai

**Expected behavior:**
All the Mentioned Languages should work properly because those languages have been included in to the Languages drop down menu

**Steps to reproduce:**
Adding Translated Phrases for the Above mentioned Languages

**Other information:**
Some Screenshots related to the Issue
![screenshot 179](https://user-images.githubusercontent.com/16055010/34198506-a1b1adea-e590-11e7-9256-2187935ff43f.png)
![screenshot 180](https://user-images.githubusercontent.com/16055010/34198508-a1e412e4-e590-11e7-95d2-d8d7049b21c4.png)
![screenshot 181](https://user-images.githubusercontent.com/16055010/34198509-a21587ac-e590-11e7-944a-c4384e793135.png)
![screenshot 182](https://user-images.githubusercontent.com/16055010/34198511-a2467434-e590-11e7-81f9-a291b3393860.png)
![screenshot 184](https://user-images.githubusercontent.com/16055010/34198513-a27a6b9a-e590-11e7-8cb4-f2df8d70eeee.png)
![screenshot 186](https://user-images.githubusercontent.com/16055010/34198514-a2ab3da6-e590-11e7-9a81-51b75499d7ab.png)
![screenshot 187](https://user-images.githubusercontent.com/16055010/34198515-a2dda098-e590-11e7-973e-2fd9513ca1ae.png)
![screenshot 188](https://user-images.githubusercontent.com/16055010/34198516-a30ea224-e590-11e7-9dbb-ec3c0c7aa26e.png)

**System information:** 

```
Google Chrome in Windows 8.1
```

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy
