### ISSUE TITLE
Increase in Dynos

### ISSUE THREAD

**Issue by awesometushar000** [fossasia/open-event-server#4572]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Now it seems that the webapp http://open-event-api.herokuapp.com/ has less number of dyno, therefore it loads slowly.
**Expected behavior:**

Increase the number of dyno to get it loaded quickly when it hasn't been loaded for a long time.

As a GCI task: https://codein.withgoogle.com/dashboard/task-instances/5391513699745792/

**Comment by raju249** [comment]
Adding more dynos to heroku is not free. We can have atmost 2 dynos for free without credit/debit card info.
More information here -- > https://blog.heroku.com/new-dyno-types-public-beta

**Comment by shubham-padia** [comment]
invalid
