### ISSUE TITLE
Hindi Language Issue

### ISSUE THREAD

**Issue by awesometushar000** [fossasia/open-event-server#4573]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

There is no options of terms, conditions and policy after changing the language to Hindi.
![hindi](https://user-images.githubusercontent.com/24381770/34205436-5cde6272-e5a8-11e7-8c4e-83968c0fc78a.png)

**Expected behavior:**

There should be all options as like that of original English

**Steps to reproduce:**

Visit https://eventyay.com/ and change the language to Hindi.

As a GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5391513699745792/

**Comment by HarshKhatore** [comment]
This problem occurs not only with Hindi, but any other language except English. But, if you select English again from the drop-down, after some other language, it is displayed correctly.

**Comment by HarshKhatore** [comment]
My guess on this issue is, upon the change of the language, the server upon page refresh is not sending the **footer-menu** div back.

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy
