### ISSUE TITLE
reset-password end point should return 422 status, when non existing email address is provided

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4574]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

It returns a 404.
![image](https://user-images.githubusercontent.com/17252805/34255775-3376997e-e678-11e7-8f84-98efd0444f51.png)

**Expected behavior:**

It should return 422.

**Comment by ritikamotwani** [comment]
I would like to work on this issue
