### ISSUE TITLE
Server is not returning the errors using json-api compliant error class for password reset

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4576]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

It's returning a custom response using jsonfiy
**Expected behavior:**

It should make use of the classes defined in `api/helpers/errors.py`

**Comment by ritikamotwani** [comment]
I would like to work on this.
