### ISSUE TITLE
Use first() instead of one() for the queries

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4578]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

There are many apis which are using `one()` instead of `first()` for many of the queries.
Using `one()`
Raises `sqlalchemy.orm.exc.NoResultFound` if the query selects no rows. Raises `sqlalchemy.orm.exc.MultipleResultsFound` if multiple object identities are returned, or if multiple rows are returned for a query that does not return object identities.
Reference : http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.one
**Expected behavior:**

Using `first()`
Return the first result of this Query or None if the result doesn’t contain any row.
Reference : http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.first

**Steps to reproduce:**

**Related code:**

**Other information:**

**System information:** 

```
Your operating system
```
Ubuntu 16.04 LTS

```
output of `python --version`
```
Python 2.7.12

**Comment by vddesai1998** [comment]
Please assign this issue to me
