### ISSUE TITLE
Bug. Application error occuring when opening on Mac

### ISSUE THREAD

**Issue by arjunpandey2003** [fossasia/open-event-server#4580]
**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Problem in the logs of the owner of the application
**Expected behavior:**
There should be no application error when opening the app.

**Steps to reproduce:**
Use the heroku logs command to view the unified event stream and identify. 

**Other information:**
https://devcenter.heroku.com/articles/error-pages
https://stackoverflow.com/questions/37668480/node-js-heroku-app-application-error-trouble-with-logs

**System information:** 

<img width="1343" alt="screen shot 2017-12-28 at 2 20 08 pm" src="https://user-images.githubusercontent.com/25302509/34405898-de8bc894-ebdb-11e7-9d13-03fd6dffdce2.png">

```
Your operating system
```
Mac OS

**Comment by ParthS007** [comment]
@arjunpandey2003  Please see recent gitter channel chat, Dynos have exhausted. Application will be right back in few days. You can close this issue 👍

**Comment by arjunpandey2003** [comment]
@ParthS007 ok sure
