### ISSUE TITLE
I can submit proposal without logging in

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/open-event-server#4593]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
To submit a speaker proposal I have to login, but if I directly go to the url which becomes available when I login, I can submit details without logging in.

**Expected behavior:**
Proposal can be submitted only after logging in.

**Steps to reproduce:**
Go to http://open-event-dev.herokuapp.com/e/08fa700a/cfs/ without logging in.
You will see that if you click the submit proposal button a model pops up asking you to login/register.
![screenshot_20180107_183430](https://user-images.githubusercontent.com/8947010/34649652-6a7d4648-f3d9-11e7-84a3-dccfc599a129.png)

But when I go to http://open-event-dev.herokuapp.com/e/08fa700a/cfs/new_speaker/ without logging in, I can see the signup form!
![screenshot_20180107_183602](https://user-images.githubusercontent.com/8947010/34649666-a0d7d7bc-f3d9-11e7-8cd5-4367dc25a202.png)

**System information:** 

```
Your operating system: Kali Linux Rolling 2017.2
```

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-legacy

**Comment by abishekvashok** [comment]
@shubham-padia sorry for messing it up in the wrong repository
