### ISSUE TITLE
Add Python Version to Documentation

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-server#4599]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Presently, It is not clear to new contributors that which python verson is used in Open-event-server

**Expected behavior:**
Python version should be added.

**Other information:**
Open-event-server uses python 2.

**Comment by fr0der1c** [comment]
Would be nice to be my first PR :)

**Comment by ParthS007** [comment]
@fr0der1c  Please go ahead.
