### ISSUE TITLE
Generated reset password link is correct but not clickable

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4610]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/35488202-a4284b54-04aa-11e8-981a-f8bf29de8615.png)
The link appears as static text in the email.
**Expected behavior:**

The link should be clickable.

**Comment by Riyuzakii** [comment]
@CosmicCoder96 Can I help fix this issue?

**Comment by sumedh123** [comment]
@Riyuzakii Please go ahead.

**Comment by Riyuzakii** [comment]
@sumedh123 do you mind giving me some directions, I'm kind of a newbie?

**Comment by prshntsingh** [comment]
@CosmicCoder96 it has been working normally for me. Please check again
![screenshot from 2018-02-01 00-41-05](https://user-images.githubusercontent.com/19731697/35642411-0973550e-06e9-11e8-8190-1bebfc301ddf.png)

**Comment by CosmicCoder96** [comment]
@prshntsingh weird, I have two mails. One shows the link as a hyperlink, other doesn't. 
![image](https://user-images.githubusercontent.com/17252805/35720727-eeb4bc80-0814-11e8-8885-ac2414a1815f.png)

Both have been rendered differently. 
![image](https://user-images.githubusercontent.com/17252805/35720734-f7dbc3bc-0814-11e8-8b9f-2064c9e58f98.png)

**Comment by poush** [comment]
@sainiak009 Go ahead! Make sure you first able to reproduce it and then fix it.

**Comment by sainiak009** [comment]
@poush Reproduced and corrected it. Please review #4616
