### ISSUE TITLE
Add a test user with full rights to admin section 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#4611]
The test deployments should have a test user login with full credentials. Please ensure this test user is only working in the test deployments and not in the final master deployments.

Use: 
Password: openevent
Test Email: test@fossasia.org

**Comment by bhaveshAn** [comment]
Can I work on this issue.

**Comment by party98** [comment]
This functionality already seems to be present in the `create_db.py` script whicl also creates a `super_user` with full access to the admin section.

**Comment by bhaveshAn** [comment]
@mariobehling I have added a test user with following credentials as the admin of test deployment http://open-event-api-dev.herokuapp.com
Password: openevent
Test Email: test@fossasia.org

Hence closing this.
