### ISSUE TITLE
No bower.json file present

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-server#4615]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Following the setup instruction, after bower install, No bower file was present in the repo

**Expected behavior:**
I guess there should be one

**Comment by shubham-padia** [comment]
Bower has been removed as a dependency from the project, opened #4617 .
