### ISSUE TITLE
Remove all the steps involving bower from the docs

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-server#4617]
Do `git grep 'bower'` and find all the occurrences and remove the steps present at those occurences

**Comment by simsausaurabh** [comment]
@shubham-padia can I work on this issue?

**Comment by shubham-padia** [comment]
sure, go ahead

**Comment by simsausaurabh** [comment]
@shubham-padia since we are not following installation using bower, so shall I also remove commands from installation scripts too?

**Comment by invinciblycool** [comment]
Yes.
