### ISSUE TITLE
make "Where did you heard about our event?" choices configurable

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4619]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
choices for "Where did you heard about our event?" are hardcoded.

**Expected behavior:**
the current hardcoded choices for "Where did you heard about our event?" are not always useful. 
i'd like to populate the choices with a list of my own making, depending on where our event is publicized. or remove all choices and require a free-form field (like only allow the "other" choice).

**Comment by isunitha98selvan** [comment]
I would like to work on this.

**Comment by bhaveshAn** [comment]
Taking this one.

**Comment by bhaveshAn** [comment]
@eMBee Can you tell how to reproduce it

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
