### ISSUE TITLE
allow creating an event only with dates without times

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4620]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
when creating an event begin and end time values are required.

**Expected behavior:**
for some events time values are not fixed or not yet known at the time of publication. it should be possible to leave time fields empty instead of having to guess and possibly give wrong information that later is difficult to change.

**Comment by Masquerade0097** [comment]
@eMBee Can i work on it?

**Comment by Masquerade0097** [comment]
@iamareebjamal @shubham-padia Can i work on it ?

**Comment by Masquerade0097** [comment]
@iamareebjamal @shubham-padia Can i work on it ?

**Comment by Masquerade0097** [comment]
@iamareebjamal @shubham-padia Can i work on this ?

**Comment by Masquerade0097** [comment]
@SaptakS @niranjan94 Can i take this up ?

**Comment by poush** [comment]
@Masquerade0097 I am not sure if this finalised yet. IMHO it should be better to keep both required. An organiser can update data and timings anytime. We will not definitely want to publish event with no timings. Instead we can allow drafting the event without timings (if we don't yet). 

I will suggest you to look for other crucial bugs first.

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
