### ISSUE TITLE
allow city location without address

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4621]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
currently, when specifying a city, a detailed map is always shown.

**Expected behavior:**
when a city is specified without an address, then either no map should be shown or the map should be zoomed out so that no detailed location can me identified. some events don't have a specific location or the venue is not known yet (but the city is).

it should be possible to specify that an event is in a certain city without suggesting a specific location within that city.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `python --version`
```

**Comment by mishuvs** [comment]
@bhaveshAn is this issue still valid? Can I work?

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
