### ISSUE TITLE
cfs still closed when start is set to current time

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4622]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
by default the submission period starts at the current time. when entering a cfs in beijing for an event in the chinese timezone, then after publishing the event the cfs was still closed. possibly there is a misinterpretation of timezones somewhere. i set the start date to yesterday to make it work.

**Expected behavior:**
cfs should start as open.

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
