### ISSUE TITLE
can't set cfs deadline to midnight without confusing the user.

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4623]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
when setting the deadline for a cfs, currently i can choose a date and 23:30 as the latest time, or i have to choose the next day at 00:00. 
generally deadlines are expected to be at the end of a given day, not at 23:30, not at the beginning of the next day. people will read the date and think they still have time, or be surprised that the can't submit at 23:35.
it is possible (but not obvious) that the time can be set manually to 23:59, but that is only slightly better.

**Expected behavior:**
allow setting the deadline to 24:00 or 23:59:59 or leave out the time all together (which then is meant to be at midnight)

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
