### ISSUE TITLE
XSS vulnerability as reported on openbugbounty.org

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/open-event-server#4624]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

User details can be spoofed. I mean the cookie which is used for session authentication.

**Expected behavior:**

It should not happen

**Steps to reproduce:**

a reflected xss vulnerability and can steal the cookie of any logged-in user on eventyay.com
simple paylaod:  https://eventyay.com/explore/united-states/events/?query=786%3C!%27/*%22/*\%27/*\%22/*--%3E%3C/Script%3E%3CImage%20Srcset=K%20*/;%20Onerror=confirm`786`%20//%3E#

just go to this link through firefox and xss trigger there.

**Other information:**

Reported by sunderlal at: 
https://www.openbugbounty.org/reports/559453/

**Comment by abishekvashok** [comment]
Visit using Firefox.

**Comment by harsh-98** [comment]
I have made a PR regarding this issue [https://github.com/fossasia/open-event-legacy/pull/52](https://github.com/fossasia/open-event-legacy/pull/52)

**Comment by harsh-98** [comment]
@abishekvashok @mariobehling

**Comment by uds5501** [comment]
Moved over to the next version, no longer valid

**Comment by sundarrinsa** [comment]
Any swag will be awarded for reporting the issue.
