### ISSUE TITLE
timezones should be sorted by time, not by alphabetic location

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4625]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
when selecting a timezone for event times, the list is sorted by alphabetic city names. this is problematic when it is not known which city is the right one for my timezone. (i'd like to choose beijing, but that's not in the list, so then i have to look for shanghai or hong kong, or some other city in the right timezone).

**Expected behavior:**
when the timezones are sorted by time, then all possible cities for the same timezone are grouped together and i can easily select the most appropriate one.

**Comment by maxlorenz** [comment]
This is a frontend issue. The names are declared in `app/utils/dictionary/date-time.js` and can be sorted there. Should I fix the ordering in the frontend project or add a new route so that the time zones can be controlled here?

**Comment by shubham-padia** [comment]
@maxlorenz This should be handled in the frontend itself
@open-event-bot move to fossasia/open-event-frontend

**Comment by sk9331657** [comment]
@open-event-bot
