### ISSUE TITLE
urls in text fields do not work

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4627]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
text fields allow selecting text and setting a destination link, but when the texts are actually published there are no links in the text, and when editing again, the link is gone from the text field too.

**Expected behavior:**
either remove the link feature from the text field editor, or make the links work.

**Comment by bhaveshAn** [comment]
I think it is a frontend issue or of legacy repo
cc @niranjan94

**Comment by poush** [comment]
@open-event-bot move to fossasia/open-event-legacy
