### ISSUE TITLE
'External Event URL' field can't be renamed

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4628]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
the first title field in links and social media is read-only (and even when changed in the frontend, a changed title is ignored)
therefore the 'External Event URL' field is always present and can't be removed.

however, when leaving the field without a destination link then it is not shown on the published page, and instead a second link can be filled in achieving the desired effect of showing an external link with a custom title.

**Expected behavior:**
directly allow renaming the first field like the fields below, since there is no practical reason to keep a field called 'External Event URL' if in the end it can be made invisible anyways.

marking this as feature enhancement since a workaround exists.

**Comment by bhaveshAn** [comment]
@eMBee 
if the purpose here is to modify the external event url using patch then it is working properly for me using 
PATCH `localhost:5000/v1/events/<event_id>`

**Comment by schedutron** [comment]
@eMBee Yes, can you please retry patching the URL, and let us know the errors that occur?

**Comment by eMBee** [comment]
this about the url itself, but it is about the form field titled 'External Event URL'

in the eventgeneration there is an area for custom formfields where i can choose the title of the field and add in some data. i can add and delete fields, except for the field 'External Event URL' which can neither be renamed nor removed.

however, if left empty, the value of that field is not shown. therefore, there is no reason to force the existence of this field. it should be possible to rename it like all others.

btw:  this is actually a report against the legacy version at eventyay.com
when making my reports, i was not aware that there was a new version in place and there was no hint on eventyay.com where bugreports should go.

**Comment by bhaveshAn** [comment]
> btw: this is actually a report against the legacy version at eventyay.com
when making my reports, i was not aware that there was a new version in place and there was no hint on eventyay.com where bugreports should go.

@open-event-bot move to open-event-legacy

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
