### ISSUE TITLE
'Basic Details' shows up in yellow but can't see what's wrong

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4629]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
in the event overview the 'Basic Details' block is yellow, but when i edit the event i can't see what is missing.

**Expected behavior:**
mark the required fields that are not filled in, or make those fields not trigger the notice.

**Steps to reproduce:**
this might be specific to the event i created because maybe i didn't fill a field that everyone else usually fills, so please inspect https://eventyay.com/events/390/ to see the problem.

**Comment by poush** [comment]
@open-event-bot move to fossasia/open-event-legacy
