### ISSUE TITLE
editing event always forces the wizard

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4630]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
after creating an event by going through the wizard, any further edits of specific steps always force a move to the next step instead of going back to the overview. there is no way to save and jump back to the overview without going through all steps again.
 
**Expected behavior:**
once the wizard is completed, editing and then saving a step should go back to the overview instead of the next step again.

**Comment by bhaveshAn** [comment]
@niranjan94 @SaptakS I think it's a frontend issue ?

**Comment by niranjan94** [comment]
@eMBee could you tell us on which version of open-event you faced this issue ? Was this seen at https://eventyay.com ? If yes, then this issue should be posted to https://github.com/fossasia/open-event-legacy ; Else https://github.com/fossasia/open-event-frontend.

**Comment by eMBee** [comment]
yes, this is actually a report against the legacy version at eventyay.com
when making my reports, i was not aware that there was a new version in place and there was no hint on eventyay.com where bugreports should go.

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
