### ISSUE TITLE
typo "Where did you heard about our event?" should be "hear"

### ISSUE THREAD

**Issue by eMBee** [fossasia/open-event-server#4631]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
field is titled: "Where did you heard about our event?"

**Expected behavior:**
field should be titled "Where did you hear about our event?"
or possibly even: "How did you hear about our event?"

**Comment by realslimshanky** [comment]
Since it's an easy fix, I would like to work on it in order to understand how to setup and kickstart contribution to Open Event Server :relaxed:

**Comment by eMBee** [comment]
it's in the call for speakers form when editing an event.
for example: https://eventyay.com/events/390/edit/sessions-tracks-rooms/#call-for-speakers

**Comment by party98** [comment]
Hey, I would like to take this up.
