### ISSUE TITLE
Remove SERVER_NAME or add warning in docs

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4636]
The `SERVER_NAME` config in example env shadows the possible IP addresses a machine may take. For example, if the local IP is `10.0.3.2` the SERVER_NAME parameter being set to `localhost` will shadow this and 404 error will be shown instead.

This setting should either be removed or a warning should be added in the docs as it can be quite painful to pin point what the issue is

**Comment by ParthS007** [comment]
I am working on this .

**Comment by iamareebjamal** [comment]
Refer to #4663

**Comment by bhaveshAn** [comment]
Is this active now as I can access this app at `localhost:5000`

**Comment by iamareebjamal** [comment]
Are you using `SERVER_NAME` in env?

**Comment by iamareebjamal** [comment]
Also, this is solved in Flask 1.0 so no need to fix this. This will be solved when #4674 is merged

**Comment by srv-twry** [comment]
@iamareebjamal 
> Also, this is solved in Flask 1.0 so no need to fix this. This will be solved when #4674 is merged

I guess we can close this now.

**Comment by iamareebjamal** [comment]
This is not yet solved @Kreijstal @bhaveshAn @srv-twry as apparently by recent inability to run server locally

I think it should just be removed from `.env`

**Comment by bhaveshAn** [comment]
Yes, its required to be removed from `.env`

**Comment by srv-twry** [comment]
Yes, will remove it.
