### ISSUE TITLE
Unable to create feedback object through api endpoint

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-server#4637]
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Unable to create new feedback with my user id and event id

**Expected behavior:**
should be able to create new feedback with my event id

**Related code:**
error
```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "User: 7 doesn't match auth key",
            "status": 404,
            "source": {
                "parameter": "user_id"
            },
            "title": "Object not found"
        }
    ]
}
```

**Comment by AkshayCHD** [comment]
@iamareebjamal can you have a look at this please.

**Comment by iamareebjamal** [comment]
Please confirm that you are using https://open-event-api-dev.herokuapp.com

**Comment by AkshayCHD** [comment]
@iamareebjamal yes i used  https://open-event-api-dev.herokuapp.com
and sorry for the ambiguity, i have made changes in the description

**Comment by iamareebjamal** [comment]
A user himself cannot rate his event. So the error is wrong, but the behaviour is right. You can change the issue to throw proper error instead of showing 404

**Comment by AkshayCHD** [comment]
@iamareebjamal I tried to give feedback for an event with a different account but i am getting the same response.

**Comment by iamareebjamal** [comment]
OK, so the problem is that `is_user_itself` function compares current user ID with the provided ID and the user ID is int whereas provided ID is string, so the comparison fails. I'll send a PR to fix the issue

**Comment by AkshayCHD** [comment]
@iamareebjamal i am still unable to do this job, also if you have some time can you please have a look at my first draft of proposal for gsoc https://docs.google.com/document/d/1pkm8zEYxfGR809NOQNMwaMsbh5T4HSmrFcf-4nDNC_w/edit

**Comment by AkshayCHD** [comment]
@geekyd still i am unable to create feedback object through api endpoint, the same error error follows
