### ISSUE TITLE
Mismatched sub-dependency `html5lib`

### ISSUE THREAD

**Issue by realslimshanky** [fossasia/open-event-server#4644]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Problem is with the mismatched sub-dependency named `html5lib`.
Primary dependency to this project `bleach==1.5.0` uses [`html5lib [required: >=0.999,!=0.9999,<0.99999999,!=0.99999]`](https://github.com/mozilla/bleach/blob/0d06fa32a6bdc117ca396b56232a06c2e083fe73/setup.py#L20). Installing and locking would give an error as there's no version of html5lib which matches required criteria. By using pipenv to install and lock dependency following error will be shown.

```Could not find a version that matches html5lib!=0.9999,!=0.99999,<0.99999999,==1.0b10,>=0.999
Tried: 1.0-reupload, 0.2, 0.9, 0.10, 0.11, 0.11.1, 0.90, 0.95, 0.99, 0.999, 0.9999, 0.99999, 0.999999, 0.9999999, 0.99999999, 0.999999999, 0.999999999, 1.0b1, 1.0b2, 1.0b3, 1.0b5, 1.0b6, 1.0b7, 1.0b8, 1.0b9, 1.0b10, 1.0b10, 1.0.1, 1.0.1
````

On the other hand `xhtml2pdf==0.2.1` also uses [`html5lib [required: ==1.0b10]`](https://github.com/xhtml2pdf/xhtml2pdf/blob/940e8fad00925002c2a290b3cfe495049ce90fa4/requirements.txt#L3). And the version `1.0b10` is installed as subdependency which works perfectly.

In general case (without locking), `html5lib==1.0b10` is force installed for `bleach==1.5.0` which you might check by going through the dependency graph after installation.

**Expected behavior:**
Dependency locking is a very important feature and removing mismatched dependencies.
A version of `bleach` should be tested and used with the project which primarily requires available `html5lib` version. If we use `bleach==2.0`, it required [`html5lib>=0.99999999`](https://github.com/mozilla/bleach/blob/b8b8e4aa9b688fb00f41959e74d8054e461f6aaf/setup.py#L19) which will allow installation of `html5lib==1.0b10` gracefully as it fits the required criteria.

**Steps to reproduce:**
Install dependency with locking feature to reproduce this bug.

**Other information:**

Check out the Bleach release for [2.0](https://github.com/mozilla/bleach/commit/b8b8e4aa9b688fb00f41959e74d8054e461f6aaf), this can be used to resolve the issue.

**System information:** 

The bug will be same for every system.

```
Ubuntu 16.04 LTS
```

```
Python 2.7.12
```

**Comment by harsh-98** [comment]
@realslimshanky try  `pip install --upgrade bleach` or manually upgrade to bleach==1.4.3.
Also refer [this](https://github.com/ckan/ckan/issues/3257)

**Comment by realslimshanky** [comment]
@harsh-98 it works for `pip`, not `pipenv` which also supports lock feature.

**Comment by Kreijstal** [comment]
Instead of manually upgrading bleach, shouldn't we update the requirements archive?

**Comment by iamareebjamal** [comment]
bleach was upgraded to `>2.13` in #4674 

Please confirm so this can be closed

**Comment by iamareebjamal** [comment]
Fixed already
