### ISSUE TITLE
Locally generated image URLs don't take port into account

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4646]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

The URLs generated locally do not take port of the server into account. For instance, the sample event payload with image URL is converted to this format `http://localhost/static/media/events/1/large/eTNEbFJZOF/3827c2eb-5fcf-4ea3-ad46-bff1c10b69bf.jpg`

This is without the port number of the server and will create problems in consuming local APIs

**Expected behavior:**

The generated URLs should take the port of the server into account

**Steps to reproduce:**

Create an event with the example payload on locally running server

**Comment by realslimshanky** [comment]
I would like to work on this issue.

**Comment by sanudatta11** [comment]
I would like to take up this

**Comment by poush** [comment]
I think the simplest way would be to add `port` column in the settings table so that the url generator can directly use it from settings.

**Comment by Masquerade0097** [comment]
@iamareebjamal Can i work on this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by schedutron** [comment]
@Masquerade0097 Are you still working on this? If not, I'd like to pick this up :)

**Comment by Masquerade0097** [comment]
@schedutron Ya, please go on.
