### ISSUE TITLE
Installing packages in RHEL/CentOS

### ISSUE THREAD

**Issue by Progyan1997** [fossasia/open-event-server#4647]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Installation script for `Ubuntu` is available but not `RHEL/CentOS`

**Expected behavior:**

Both should be available.

**Steps to reproduce:**

* Run `scripts/install.sh` outside Ubuntu
* Fails to run `apt`

**Related code:**

```
# Install essential packages from Apt
apt-get update -y
# Python dev packages
apt-get install -y build-essential python python-dev
...
```

**Comment by SaptakS** [comment]
@Progyan1997 `scripts/install.sh` is used inside Vagrantfile for provisioning and in Vagrantfile, we have used an ubuntu box, hence the `install.sh` supports only ubuntu/debian commands and not RHEL/CentOS.

You can, however, update the local and generic documentation to include the steps which are different in CentOS/RHEL like OS.
