### ISSUE TITLE
Create a conference level chat system

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-server#4653]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Other information:**

One of the ideas as discussed with @eMBee at the conference, it would be really nice to have a chat system integrated into the event management at a conference level (or room level) so that the speakers and the attendees can communicate and share things. 

Might be a good thing to pick up once most of the other things are ready and deployed.

**Comment by mariobehling** [comment]
This is out scope.
