### ISSUE TITLE
No reference validation for attendee and ticket relationship

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4659]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Someone can add a reference to another event's ticket to an attendee on some other event

Event 155 has tickets 223 and 221

I can create an attendee with ticket 233 for event 255, where ticket 233 does not belong to the event 255

This causes serious referential integrity problems in mobile clients

**Expected behavior:**
Reference should be checked before persisting in database

**Steps to reproduce:**
```JSON
{
  "data": {
    "attributes": {
      "firstname": "Payer",
      "lastname": "Rich",
      "email": "payer.rich@example.com",
      "address": "address",
      "city": "example",
      "state": "example",
      "country": "IN",
      "is-checked_in": "false",
      "pdf-url": "http://example.com"
    },
    "type": "attendee",
    "relationships": {
      "event": { "data" : { "type" : "event", "id" : "{{event}}" } },
      "ticket": { "data" : { "type" : "ticket", "id" : "233" } }
    }
  }
}
```

**Comment by iamareebjamal** [comment]
@Masquerade0097 Can you please take it up

**Comment by Masquerade0097** [comment]
Yes.
