### ISSUE TITLE
Unknown error 500 on deleting feedback

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4660]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Unknown error when deleting feedback

**Expected behavior:**
Feedback should be deleted successfully

**Steps to reproduce:**
DELETE {{server}}/v1/feedbacks/46

**Comment by srv-twry** [comment]
@iamareebjamal @shubham-padia Can i take it ?

**Comment by iamareebjamal** [comment]
Please go ahead
