### ISSUE TITLE
Rebase singletons to lazy initialization for unit testing

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4667]
This is a refactor request, so this can be taken up once server is stable and all bugs are fixed.

> Explicit is better than implicit  

` - The Zen of Python, by Tim Peters`

RIght now, each `__init__.py` file contains a hefty amount of logic in it which gets executed when modules are initialized. This has a huge disadvantage though. Just by importing any file from inside a nested package, every line of code in every module, however unneeded is executed, and then each import in all of `__init__` is also executed. This results in behaviour that may not be desirable, such as:

- While testing locally via Python Shell, there is a huge performance drop as several unneeded things are initialized. For instance, by importing `from app.models.ticket import Ticket` app.`__init__`.py and models.`__init__`.py are executed which also executes each global variable initializer in the imports of these files for e.g., elastic search view connection which has no relation to the models
- No separation of concern. This is like a chain reaction where you want one dependency and you get everything instead. This also makes modularization of logic difficult. If I import a file for testing, and do not have redis, celery and other dependencies ready, it will fail, however it shouldn't because the class I am importing does not depend on these
- Impossible to unit test. Each function is inside app module and at least its `__init__` file gets executed when importing any function for testing, making it impossible to test in isolation. DB is initialized always, so you cannot unit test without a db, which is not unit testing at all, it is integration testing. This makes tests take a long time to execute, whereas unit tests should take as small time as possible and should not depend on invariants such as db on network. Also, currently, there are only db tests in the project, there should be unit tests for util functions and behaviours of other components as well.

This can be fixed by:
- only requiring module globals in `__init__`. Moving everything else in separate files where they can be imported if necessary
- Making globals initialization lazy even when moved to a separate file. For e.g. fetcher.py

```python
import os
import psycopg2

conn = psycopg2.connect('blah')

def do_it():
  item = conn.execute('select 1 from 1')
  return util_test(item)

def util_test(var):
  if (var + 1 < 3):
    return 2*8;
  else:
    return 3*6

```

Now, as it should be the logic of fetcher is all defined in `util_test` function, so I should not need a database to test it, however if I import fetcher, and don't have a db set up, this will fail. It can be fixed by limiting logic in a separate layer from database(as it should be), but this will require a lot of refactoring and global initialization will still be a problem. So instead, we can solve it via lazy initialization

```python
import os
import psycopg2

conn = None

def get_connection():
  if conn is None:
    conn = psycopg2.connect('blah')
  return conn

def do_it():
  item = get_connection().execute('select 1 from 1')
  return util_test(item)

def util_test(var):
  if (var + 1 < 3):
    return 2*8;
  else:
    return 3*6

```

Now, the functionality is isolated, conn is still initialized once,and this way, both memory and performance is saved via initlializing only what is required rather than always filling it with stuff almost none of the logic uses. This adds a bit of boilerplate code, but cleans up the access and makes unit testing a breeze

This can be taken up slowly, by trying to unit test each module and separating the file accordingly. Another solution is to shift static logic outside of app module where it does not depend on db and other stuff

https://www.reddit.com/r/Python/comments/1bbbwk/whats_your_opinion_on_what_to_include_in_init_py/

**Comment by iamareebjamal** [comment]
finally

**Comment by codedsun** [comment]
@iamareebjamal - This was wow 👍 Congo!
