### ISSUE TITLE
Error 500 on Create Ticket : Unique name

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4672]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
TIcket creation with same name causes error 500
```json
{
    "errors": [
        {
            "status": 500,
            "source": {
                "pointer": "/data"
            },
            "detail": "Object creation error",
            "title": "Unknown error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Expected behavior:**
There is a unique constraint on name and event id, so this should be checked before saving and shown to the user 

**Steps to reproduce:**
Try to create two tickets of the same name for the same event

**Comment by Masquerade0097** [comment]
@iamareebjamal Can i work on this ?

**Comment by mayank8318** [comment]
@iamareebjamal What should be the response?

**Comment by iamareebjamal** [comment]
Ticket <name> already exists

**Comment by Masquerade0097** [comment]
@iamareebjamal Can i work on this ?

**Comment by iamareebjamal** [comment]
Go ahead @Masquerade0097
