### ISSUE TITLE
Should "Last name" in create attendee api be required?

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#4676]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Docs say that the last name field in create an attendee is required but None is allowed in the API.

**Expected behavior:**
@iamareebjamal @SaptakS @niranjan94 @poush @shubham-padia What should be the expected behaviour here - required or not required?

**Steps to reproduce:**
Create an attendee with no last name field. It is successfully created.

**Comment by niranjan94** [comment]
Both first name and last should be required.

**Comment by party98** [comment]
Hey, i'd like to take this up.

**Comment by mayank8318** [comment]
@party98 I have solved it and am about to send in a PR. Maybe you could work on some other issue? ☺
