### ISSUE TITLE
Normalize social links in the database 

### ISSUE THREAD

**Issue by rngadam** [fossasia/open-event-server#4687]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report
- [ x feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Overview**

Social links should:

* be configurable for every entity level (speaker, event, user)
* be consistently validated
* only one row from actual social link stored in the database (instead of mostly NULL, unused columns)

**Current behavior:**

This is what the speaker table looks like:

![image](https://user-images.githubusercontent.com/538542/39411931-fa7a4b0a-4c45-11e8-9d2d-22318513ae20.png)

Every known supported properties is added as a separate column.

**Expected behavior:**

Database following normalization best practices. As an example, speaker information is:

![image](https://user-images.githubusercontent.com/538542/39411946-3d4b9f06-4c46-11e8-9420-508c05a8912b.png)

I would expect this to be modeled as a separate table with a N:N mapping to validate and enforce properties requested per event (as decided by the event creator). Perhaps also embedding regexps to validate proper inputs and describing optional flags.

**Steps to reproduce:**

Use https://dbeaver.jkiss.org/download/ -> connect to PostgreSQL oevent database -> click public schema -> ER diagram.

**Related code:**

Version 1 seems to allow arbitrary properties:

![image](https://user-images.githubusercontent.com/538542/39411920-c57ed164-4c45-11e8-9c4a-4d93dcf8efc0.png)

**Comment by mayank8318** [comment]
Yesterday's hangout call was really very informative (which I could not attend unfortunately as I was travelling). I saw the recording on youtube and watched a few videos on ERDs. Also, I have set up dbeaver. Could you please explain a little as to what the problem is, the various solutions that could be implemented and what should be the team's approach next? 
Thank you :)

**Comment by rngadam** [comment]
There's already a somewhat better normalization for social links related to the events:

![screen shot 2018-05-02 at 11 13 28 am](https://user-images.githubusercontent.com/538542/39503681-cfcd01c6-4df9-11e8-9b92-1fcc043cb851.png)

This is modeled in the ORM in this file: 

open-event-server/app/models/social_link.py

...as you can, instead of having an additional column in the main event table, we add a row in social_links.

This is better than adding a column, but can/should be improved further and applied consistently to link all entities that require a variable number of social links.

I wrote a quick example in PostgreSQL of how I would model this:

https://gist.github.com/rngadam/04e07c22285d7dfb84b54b370cb137b1

which looks like this:

![screen shot 2018-05-02 at 11 57 35 am](https://user-images.githubusercontent.com/538542/39504722-3d03213e-4e00-11e8-8deb-93c6a59f120c.png)

Note a couple differences in the design:

* use of uuid as primary key for primary entities (this make merging distributed databases easier with a universally unique identifier and gets around having to track incremental id for each column)
* naming of tables (entities) is always singular
* N:N tables between entities and social link
* Use of a regexp_validation (TODO: add a constraint/trigger to validate value against that regexp)
* Use of a configurable table to let event organizer setup desired social links (and whether they are optional or not)

**Comment by mayank8318** [comment]
@rngadam From what I understand, this approach is very flexible and customisable. For example, in the future, if we want to provide an option of hiding a social link, it can be easily added to the config table without directly affecting the relationship between an event (or speaker) and the social link. Please correct me if I am wrong :slightly_smiling_face:

**Comment by mayank8318** [comment]
Should I make new ORMs or modify the existing ones?
