### ISSUE TITLE
Migrate existing DB data to ensure a non-nullable last_name field for attendees

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-server#4688]
Follow up to #4682

> @shubham-padia: This might create problems when migrating the existing database as there maybe attendees without any last name. We need a migration to handle that. I'm not sure right now how we should go about that. Till we figure it out, we can make the field required in the API schema and let the db schema be as it was before. A follow-up issue can be made to handle change in the db schema.

**Comment by niranjan94** [comment]
@mayank8318 you could take this up

**Comment by mayank8318** [comment]
For empty last names, should I add a space character?
