### ISSUE TITLE
Unittests fail as unable to import 'current_app'

### ISSUE THREAD

**Issue by siddhant-curious** [fossasia/open-event-server#4696]
**I'm submitting a ...**  (check one with "x")
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
When attempting to run the tests as `python -m unittest discover tests/unittests/`, the tests fail with the following error. 

```
======================================================================
ERROR: api.validation.test_events (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: api.validation.test_events
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/siddhant/OpenSource/open-event-server/tests/unittests/api/validation/test_events.py", line 5, in <module>
    from app import current_app as app
  File "app/__init__.py", line 14, in <module>
    from app.settings import get_settings, get_setts
  File "app/settings/__init__.py", line 5, in <module>
    from app.models.ticket_fee import TicketFees
  File "app/models/ticket_fee.py", line 6, in <module>
    from utils.compat import u
  File "/Users/siddhant/OpenSource/open-event-server/tests/unittests/utils.py", line 3, in <module>
    from tests.unittests.setup_database import Setup
  File "tests/unittests/setup_database.py", line 6, in <module>
    from app import current_app as app, celery
ImportError: cannot import name current_app


----------------------------------------------------------------------
Ran 13 tests in 0.001s

FAILED (errors=13)
```

**Expected behavior:**
The tests should pass without any error. 

**Steps to reproduce:**
I followed the instructions on `Testing`at [README.md](https://github.com/fossasia/open-event-server/blob/development/README.md) 

Attempting to run `python -m unittest discover tests/unittests/` should reproduce the bug. 

**System information:** 

```
operating system: macOS High Sierra Version 10.13.14
```
```
output of `python --version` : Python 2.7.10 
```

**Comment by siddhant-curious** [comment]
@party98 nosetests fail as well, I'll create a separate issue for it. There seems to be a different failure issue than presented here.

**Comment by siddhant-curious** [comment]
@party98 kindly look into https://github.com/fossasia/open-event-server/issues/4709 for additional information.

**Comment by iamareebjamal** [comment]
This is because you ran the project on Python2. Thanks

There is an issue present some tests in local environment
