### ISSUE TITLE
Single Sign On Features - Integration with keycloak like servers

### ISSUE THREAD

**Issue by pandeybk** [fossasia/open-event-server#4697]
Is there any way we can integrate with keycloak like third party sso tool to manage users?

**Comment by pandeybk** [comment]
Linking parent issue #5115

**Comment by mariobehling** [comment]
Out of scope currently.

**Comment by rasos** [comment]
Yes, in order to set up a GDPR compliant service with SSO we would need to be able to connect to community or institutional supported oAuth providers such as fairlogin. Many of them are driven by keycloak, including many uiniversities.
