### ISSUE TITLE
Create_db always prompts for input

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4704]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Currently at create_db.py, it prompts in terminal for an e-mail address and a password, that all is fine, but currently there is no way to pass down variables from the terminal or from the enviroment so that it can decide beforehand which values to take from e-mail and password
**Expected behavior:**

I should be able to create databases from a script using predetermined values.
**Related code:**

```
insert any relevant code here else remove this section
```
https://github.com/fossasia/open-event-server/blob/e0a63f37e0ce7c7a39718f005a959f4194e6ada4/create_db.py#L30

**Comment by party98** [comment]
A condition can be added to check whether the shell session is interactive or not and use default values in case of non interactive session.

**Comment by party98** [comment]
The script in question is used at a couple of places, and is not limited to development environments. Therefore, the solution needs to be concrete. Furthermore, `config.py` is used as an input for setting the various variables within the project so I don't think that would be a "safe" place to add this data.
