### ISSUE TITLE
Rating field of feedback should be float

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-server#4708]
**I'm submitting a ...**  
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
The `rating` field of `feedback` is set to `String` 

**Expected behavior:**
`Rating` field should be `float`

<img width="634" alt="screen shot 2018-05-10 at 11 45 49 am" src="https://user-images.githubusercontent.com/16715499/39855731-b6a7ebe6-544a-11e8-8cf5-40e41ea9f0af.png">

**Comment by schedutron** [comment]
Will you be working on this issue? Or can I undertake it? Please let me know :)

**Comment by simarsingh24** [comment]
@schedutron please go ahead
