### ISSUE TITLE
Inconsistent data on Admin Statistics end points

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4710]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

The admin statistics end points return various stats about events, users etc.
Currently they are completely out of sync with the database.
For instance, the `admin/statisitics/events` returns 
![image](https://user-images.githubusercontent.com/17252805/39888957-1a5daf72-54b4-11e8-934c-1d77a9ab66b7.png)

Where as the actual event count when generically querying for events is 92:
![image](https://user-images.githubusercontent.com/17252805/39889011-44af3d9a-54b4-11e8-8fb8-c45b0cef175d.png)

**Expected behavior:**

The counts should be consistent.

**Comment by bhaveshAn** [comment]
I would to work on this issue.

**Comment by CosmicCoder96** [comment]
@bhaveshAn Yeah, that seems to be true, but I think there is still a mismatch because the admin dashboard shows around 716 events 
![image](https://user-images.githubusercontent.com/17252805/39907157-76db9476-5504-11e8-9408-fee67cf85a6d.png)
Where as according to the returned statistics by the end point total events are 
715 + 410 + 147
![image](https://user-images.githubusercontent.com/17252805/39907170-90e05d66-5504-11e8-8ad1-c892bd53c808.png)

**Comment by Kreijstal** [comment]
This was reverted by #5252, can you make the PR again?

**Comment by Kreijstal** [comment]
Actually, git was smarter than I thought.
