### ISSUE TITLE
POST returns in 500 during Access Code Creation [heroku deployment]

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4711]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/39889777-72496bde-54b6-11e8-8c51-e4b7a60f8798.png)

**Comment by bhaveshAn** [comment]
@CosmicCoder96 
POST `/v1/access-codes` works fine for me.
![screenshot from 2018-05-11 01-04-28](https://user-images.githubusercontent.com/22936570/39890134-835cc262-54b7-11e8-82bc-43e05d33d3af.png)

**Comment by CosmicCoder96** [comment]
@bhaveshAn That's local deployment, have you tested the deployed one?

**Comment by mayank8318** [comment]
@CosmicCoder96 I think this is happening on the master branch (from the screenshot) and works on the development branch  open-event-api-dev.herokuapp.com
