### ISSUE TITLE
Postman Collection of All Requests

### ISSUE THREAD

**Issue by party98** [fossasia/open-event-server#4712]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Expected behavior:**
As the project grows, it becomes difficult to document each request type. I suggest creating a postman collection with appropriate documentation and examples so that onboarding time for new developers is reduced and manual testing becomes easier.

**Comment by iamareebjamal** [comment]
[openevent.postman_collection.json.txt](https://github.com/fossasia/open-event-server/files/1995594/openevent.postman_collection.json.txt)

**Comment by iamareebjamal** [comment]
It's not complete yet though
