### ISSUE TITLE
Events not getting created through heroku server

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#4719]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

Current behavior:
On creating new event it show "Unexpected error occurred". This happens when using heroku deployment of open event server.

Expected behavior:
Event should get created.

**Comment by srv-twry** [comment]
Please use the dev server - https://open-event-api-dev.herokuapp.com/
It works for me.

**Comment by pradeepgangwar** [comment]
Yeah that worked! Thanks.
