### ISSUE TITLE
POST returns in 500 whenever someone tries to create a new User [heroku deployment]

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-server#4720]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Whenever I try to create a new User it results in an error with the error status as 500(Internal Server Error)
![image](https://user-images.githubusercontent.com/22127980/39960873-40ffba22-5648-11e8-8278-796e38cf025b.png)

**Expected behavior:**
A new user should be registered after the post request.

**Comment by srv-twry** [comment]
@ritikamotwani Can you please try and check if it fails on the dev server as well ? 
https://open-event-api-dev.herokuapp.com/
