### ISSUE TITLE
Add action detail in notifications of notifications API

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4726]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Currently following attributes/response are returned by the notifications api for a given notification
```js
"attributes": {
      "message": "example",
      "received-at": "2017-06-23T04:40:37.239724+00:00",
      "is-read": false,
      "title": "example"
    },
```
**Expected behavior:**

Ideal response should be 
```js
{
  title: 'Export of session ...',
  state: 'error',
  message: 'The following error occurred ...',
  primaryAction: {
	action: 'view',
    type: 'session',
 	id: 12344
  },
  receivedAt: '2018-05-14T04:58:06Z'
}
```

**Comment by mayank8318** [comment]
@CosmicCoder96 I would like to work on this. 
The current notifications model has action but doesn't have a type property.
```python
    id = db.Column(db.Integer, primary_key=True)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    user = db.relationship('User', backref='notifications', foreign_keys=[user_id])

    title = db.Column(db.String)
    message = db.Column(db.Text)
    action = db.Column(db.String)
    received_at = db.Column(db.DateTime(timezone=True))
    is_read = db.Column(db.Boolean)
```
Should it be added to this model? Also, as far as I understand it is dynamic since a session has an id but some other field might need something else. How should I go about adding this?

**Comment by CosmicCoder96** [comment]
@SaptakS @niranjan94 please guide on how to proceed.

**Comment by poush** [comment]
I have seen the model of Github Notification and Events API. We can take inspiration from both.

Based on the notifications API of github, we can go for something like
```
    {
        "id": "334643408",
        "unread": true,
        "reason": "subscribed",
        "updated_at": "2018-05-12T21:06:44Z",
        "last_read_at": null,
        "subject": {
            "title": "Improve UI of filter dialog",
            "url": "",
            "type": "Issue"
        },
            "private": false
    },
```

**Comment by mayank8318** [comment]
@poush Just to confirm, `primaryActions` will be in a separate table right?

**Comment by poush** [comment]
It depends upon what is the primary purpose of "primaryActions". It doesn't need to be exactly different entity, instead the current models can be directly related. For example, if there is some notification on your session, we can simply add related session inside `primaryAction` or `subject` (whatever we choose) using related schema in API.
If different entity is to be created then we need something like ActivityEvents or Log model which records the every actions performed by users. The the event handlers listing these activity events will fire notifications if required.

@fossasia/open-event-server-devs any thoughts or suggestions?
