### ISSUE TITLE
Locally generated URLs for events does not take port into account

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#4733]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
When using local server url for events consists of only localhost and port is missing which leads us to wrong url.

**Expected behavior:**
It should contain port number when using local deployment so that we do not have to manually enter the port to see events page.

**Comment by schedutron** [comment]
See #4646

**Comment by pradeepgangwar** [comment]
@schedutron but that is for images. Events url also have the same problem.
![screenshot_2018-05-15 aparoksha events open event](https://user-images.githubusercontent.com/21259802/40054517-b9487106-5862-11e8-803b-cfbcadaea086.png)

**Comment by bhaveshAn** [comment]
Working on it.

**Comment by pradeepgangwar** [comment]
@bhaveshAn Are u working on it? If not, I can try fixing this. :sweat_smile:

**Comment by iamareebjamal** [comment]
@bhaveshAn Are you working on this?

**Comment by bhaveshAn** [comment]
@pradeepgangwar You can work on it.

**Comment by srv-twry** [comment]
@pradeepgangwar Any updates ?

**Comment by pradeepgangwar** [comment]
@srv-twry Forgot this one. Got busy with other issues. You can try this if you want.

**Comment by srv-twry** [comment]
@pradeepgangwar This is not an issue in the server, URL is a computed property of the event model in the frontend.

It's computed in the frontend with this function:
``` JavaScript
url: computed('identifier', function() {
    return `${location.protocol}//${location.hostname}${this.get('router').urlFor('public', this.get('id'))}`;
  }),
```

**Comment by pradeepgangwar** [comment]
Ok, I didn't notice that. Thanks. Can you open an issue on front-end repo?

**Comment by srv-twry** [comment]
Yeah, sure. Please close this :)
