### ISSUE TITLE
Kubernetes still uses python2

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4734]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Kurbernetes run script uses python2 instead of python3
**Expected behavior:**

It should execute python3 instead of python

**Related code:**

https://github.com/fossasia/open-event-server/blob/224e679c65db9bbc877e84678ba38adfd07caab9/kubernetes/run.sh#L10

**Comment by srv-twry** [comment]
Taking this one.

**Comment by kushthedude** [comment]
@iamareebjamal Is kubernetes logs set up for the server now?

**Comment by iamareebjamal** [comment]
`Is kubernetes logs set up for the server now?`

Logs?

**Comment by prateekj117** [comment]
@srv-twry Can I take this up?

**Comment by mariobehling** [comment]
As currently are not focusing on Kubernetes, I am closing this.
