### ISSUE TITLE
Sessions should have feedback attributes

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#4736]
I'm submitting a __feature request__:

**Current behavior:**
Sessions do not have feedback attributes.

**Expected behavior:**
Sessions should have 3 key feedback attributes:

1. Rating (per user) - float
2. Feedback (per user) - string
3. Average rating (aggregate) - float

**Other information:**
I would like to implement these attributes.

**Comment by schedutron** [comment]
@iamareebjamal Should I go ahead and submit a PR adding the above attributes?

**Comment by iamareebjamal** [comment]
First let's handle the previous issue
