### ISSUE TITLE
Rating field of feedback should be integer

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#4743]
I'm submitting a __bug report__:

**Current behavior:**
The `rating` field of event feedback is of type `string`.
**Expected behavior:**
`rating` should be of type `integer`.

![image](https://user-images.githubusercontent.com/16715499/39855731-b6a7ebe6-544a-11e8-8cf5-40e41ea9f0af.png)

@poush Done.

**Comment by iamareebjamal** [comment]
Closing this in favor of #4708
