### ISSUE TITLE
Inconsistent requirements in requirements/common.txt

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-server#4748]
On upgrading there are some requirements that needs to be updated.

1. `librabbitmq` which is not available on PyPi for python 3 
2. `functools32` which is no longer required for Python 3
3. Pillow by default requires "ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting"
4. xhtml2pdf 0.2.2 has requirement html5lib>=1.0, but you'll have html5lib 0.9999999 which is incompatible.

Please check for linux systems as well.

**Comment by schedutron** [comment]
We can use [`pika`](http://pika.readthedocs.io/en/latest/intro.html) instead of `librabbitmq` for Python 3.

**Comment by poush** [comment]
See this https://stackoverflow.com/questions/41335873/is-it-possible-to-use-pika-instead-of-librabbitmq-with-celery

**Comment by Kreijstal** [comment]
>xhtml2pdf 0.2.2 has requirement html5lib>=1.0, but you'll have html5lib 0.9999999 which is incompatible.
This one is caused by bleach.

**Comment by schedutron** [comment]
@poush So it `pika` might be slower, but will it be just good enough for our purposes?

**Comment by iamareebjamal** [comment]
I thought I had corrected these in my PR. amqp instead, removed functools(couldn't find the use in project), updated PIL and xhtml2pdf

Will look at it

**Comment by iamareebjamal** [comment]
@poush I could install the new requirements without issue. I can't understand the context of the question?

**Comment by poush** [comment]
My bad 😅 my repo wasn't upto date.
