### ISSUE TITLE
Update heroku deployment instructions

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4754]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
The docs for deployment on Heroku are outdated and a few commands don't work. For eg. the last command ```heroku run migrate``` in the guide to create tables doesn't work. Infact there is no migrate command. 

**Expected behavior:**
The docs should be updated.

**Comment by mayank8318** [comment]
@srv-twry Try running the standard commands for database creation - https://devcenter.heroku.com/articles/getting-started-with-python#provision-a-database

**Comment by srv-twry** [comment]
Yes, I had solved it. I opened the issue so that I could update the docs :+1:
