### ISSUE TITLE
On creating a new event, list of all events doesn't get updated

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-server#4760]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

On creating a new event, list of all events doesn't get updated

**Expected behaviour:**

The newly created event should get added to the list of all events

**Steps to reproduce:**
Create a new event.
Use the API to get the list of all events.

**Comment by poush** [comment]
Are you checking events through logged account or browsing as guest ? because this could be due to unpublished events.

**Comment by nikit19** [comment]
I am checking events on postman by sending a get request to this endpoint https://open-event-api-dev.herokuapp.com/v1/events to see the list of all created events.It

**Comment by poush** [comment]
with auth token? ( if you didn't published event yet then you need it to see the event)

**Comment by bhaveshAn** [comment]
working fine locally for me ...

**Comment by srv-twry** [comment]
It's working fine locally for me too. @nikit19 Please use your own heroku deployment.

**Comment by nikit19** [comment]
https://open-event-api-dev.herokuapp.com
But any idea why it is not working here ?

**Comment by srv-twry** [comment]
Orga app uses the dev endpoint as well and it's working for it too. Please verify again :)

![videotogif_2018 05 23_13 54 15](https://user-images.githubusercontent.com/21277837/40412805-f3171a60-5e91-11e8-8d95-1bc94bf9f43d.gif)

**Comment by nikit19** [comment]
Yes it is working. Sorry for the confusion.
