### ISSUE TITLE
Modules API gives 404 at localhost

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4761]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

Currently, neither GET  nor PATCH is working in `/v1/modules`
**Expected behavior:**

It should work.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `python --version`
```
**Wanna work on this issue**

**Comment by Kreijstal** [comment]
This was reverted, so I reopened it.
