### ISSUE TITLE
Maximum order allowed to be more than the quantity of the Ticket

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4762]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
We can create a Ticket with Maximum order more than the quantity of the Ticket.

**Expected behavior:**
It shouldn't be allowed

**Steps to reproduce:**
Create a Ticket with max_order more than quantity of the ticket

![max_order_more than quantity](https://user-images.githubusercontent.com/21277837/40364522-2a4263de-5df0-11e8-9fe9-e90201c7b5ad.png)

Working on it.

@poush @niranjan94 Is this a bug or is it desirable to allow max_order to be more than the quantity of a ticket ?

**Comment by niranjan94** [comment]
@srv-twry valid bug. Please fix it. :)

**Comment by Kreijstal** [comment]
This was reverted because of failing, travis so reopening

**Comment by srv-twry** [comment]
@Kreijstal Are you going to open the PR for it or should I ?

**Comment by Kreijstal** [comment]
@srv-twry you can reopen the PR :+1:

**Comment by srv-twry** [comment]
@Kreijstal You haven't reverted this PR. You've only reverted #4761

**Comment by Kreijstal** [comment]
Ah, sorry! 
Great, then!
