### ISSUE TITLE
Travis Build failed

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4765]
**Describe the bug**
Currently, travis build is failing.

**To Reproduce**

**Expected behavior**

**Stacktrace**
If applicable, add stacktrace to help explain your problem.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

**Wanna work on it**

**Comment by Kreijstal** [comment]
Travis servers are having issues, that's all

**Comment by Kreijstal** [comment]
Well, apparently our build is actually failing now!

it appears to be here 
```
127.0.0.1 - - [22/May/2018 20:21:04] "PATCH /v1/auth/reset-password HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/May/2018 20:21:04] "PATCH /v1/auth/reset-password HTTP/1.1" 200 -
pass: PATCH /v1/auth/reset-password duration: 148ms
info: Displaying failed tests...
fail: GET /v1/modules?page%5bsize%5d=10&page%5bnumber%5d=2&sort=app-name&filter=%5B%5D duration: 69ms
fail: body: At '/data' Missing required property: data
body: At '/links' Missing required property: links
statusCode: Status code is not '200'
```

**Comment by bhaveshAn** [comment]
Will  fix it today.
