### ISSUE TITLE
Add tests to docker-compose/docker 

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4767]
**Describe the bug**
We didn't know docker-compose wasn't working because there was no travis tests for it

**To Reproduce**
see #4766

**Expected behavior**
Travis should execute tests to make sure docker compose works, execute docker-compose in travis and just test it.

**Additional context**

**Comment by iamareebjamal** [comment]
Although the motive is good, but this will increase build time drastically and dockerfile is not changed that much. This failure was due to breaking change of Python 2 to 3 which does not happen that often
