### ISSUE TITLE
Inconsistent Model and API docs for Access code.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4771]
**Describe the bug**
The defined model and the API docs differ for Access code.

##### API docs
Parameter | Description | Type | Required
-- | -- | -- | --
code | Access Code | string | -
access-url | URL of the access code | string | -
type | Amount or Percentage | string | -
is-active | If the access code is active | boolean | -
tickets-number | Tickets Number for Access Code | integer (>=0) | -
min-quantity | Minimum number of tickets for Access Code | integer (>=0) | -
max-quantity | Maximum number of tickets for Access Code | integer (>=0) | -
valid-from | Access Code valid from | ISO 8601 (tz-aware) | -
valid-till | Access Code valid till | ISO 8601 (tz-aware) | -
created-at | Access Code created at | ISO 8601 (tz-aware) | -
tickets | Event or Ticket | String | -
used-for | Access Code used for | String | -

##### Server
``` Python
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String)
    access_url = db.Column(db.String)
    is_active = db.Column(db.Boolean)
    tickets_number = db.Column(db.Integer)  # For event level access this holds the max. uses
    min_quantity = db.Column(db.Integer)
    max_quantity = db.Column(db.Integer)  # For event level access this holds the months for which it is valid
    valid_from = db.Column(db.DateTime(timezone=True), nullable=True)
    valid_till = db.Column(db.DateTime(timezone=True), nullable=True)
    event_id = db.Column(db.Integer, db.ForeignKey('events.id', ondelete='CASCADE'))
    event = db.relationship('Event', backref='access_codes', foreign_keys=[event_id])
    created_at = db.Column(db.DateTime(timezone=True))
    marketer_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    marketer = db.relationship('User', backref='access_codes_')

    used_for = db.Column(db.String)
```
1. ```type```: Mentioned in the API docs but absent in the model.
2. ```tickets``` is also absent in the model. Moreover it's use is not very clear.

**Expected behavior**
There shouldn't be differences.

**Comment by bhaveshAn** [comment]
Should I add it ?

**Comment by srv-twry** [comment]
you can add the tickets in the model but i am not sure about why we need ```type``` in the access_code. I think the docs for Access code were copied from Discount code and type which should have been deleted, wasn't. 
@poush @niranjan94 @SaptakS Why do we need a ```type```("amount" or "percentage") in access_code

**Comment by mayank8318** [comment]
@srv-twry Yes, your point is right

**Comment by bhaveshAn** [comment]
@srv-twry 
> you can add the tickets in the model 

Even that is not required 
> tickets is also absent in the model. Moreover it's use is not very clear.

Required as Access Code is having One to many relationship to Tickets. 
See this file : https://github.com/fossasia/open-event-server/blob/development/app/models/ticket.py#LC42

**Comment by schedutron** [comment]
`tickets` should be added in the model as their use is not ambiguous now.

**Comment by srv-twry** [comment]
@schedutron @bhaveshAn @mayank8318 What is ```tickets-number``` ? Any idea ?

**Comment by srv-twry** [comment]
> Use is Required as Access Code is having One to many relationship to Tickets.

Actually it's a many to many relationship(http://flask-sqlalchemy.pocoo.org/2.3/models/#many-to-many-relationships) but fair point.
