### ISSUE TITLE
Admin Access required for accessing Order endpoint

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-server#4777]
**Describe the bug**
Admin access is required for endpoints related to Order. 

**To Reproduce**
GET/POST request to Order endpoints.

**Expected behavior**
The organizer should be able to query the Order endpoints as it was before.

**Stacktrace**
`{
    "errors": [
        {
            "status": 403,
            "source": {
                "source": ""
            },
            "title": "Access Forbidden",
            "detail": "Admin Access Required"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}`

**Comment by srv-twry** [comment]
@Masquerade0097 Plan to work on it ?

**Comment by Masquerade0097** [comment]
@srv-twry Yes
