### ISSUE TITLE
Admin: Events: Sorting and pagination missing

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4780]
**Is your feature request related to a problem? Please describe.**
In the events tab of the admin section, version 1 has sorting and pagination options:
![events_sorting_state](https://user-images.githubusercontent.com/2054706/40532204-fdbdccac-5ffe-11e8-8281-36366d788a0e.png)
These are missing right now

**Describe the solution you'd like**
The api should provide sorting and pagination options like in version 1

**Comment by Kreijstal** [comment]
maybe pass every route through a decorator?

**Comment by Kreijstal** [comment]
I think this is implemented already on the server, but not on the frontend.

**Comment by niranjan94** [comment]
@maxlorenz API already provides these options.
