### ISSUE TITLE
Add Custom Speaker Registration form

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4781]
**Is your feature request related to a problem? Please describe.**

Addition of custom form filling for speaker details (Custom Speaker Registration form)

**Describe the solution you'd like**

Addition of model SpeakerForm for providing custom form of speaker registration.

**Describe alternatives you've considered**

**Additional context**

![screenshot from 2018-05-25 13-05-07](https://user-images.githubusercontent.com/22936570/40532252-79807110-601c-11e8-9a1e-cf0b447851df.png)
Organizer can add more attributes of Speaker. In route http://localhost:4200/events/<event_identifier>/edit/sessions-speakers

**Wanna work on this**

**Comment by bhaveshAn** [comment]
@niranjan94 @SaptakS @poush 
How can I make use of Custom Form model to add Custom fields in Speaker Form table or Should I make a new Model `SpeakerForm` with attrs
1. id
2. name (String)
3. type (String)
4. value (String)
??

**Comment by prateekj117** [comment]
@iamareebjamal I think we can close this, right? Because this is done now in #6435
