### ISSUE TITLE
Add Custom Session Registration form

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4782]
**Is your feature request related to a problem? Please describe.**

Addition of custom form filling for Session details (Custom Session Registration form)

**Describe the solution you'd like**

Addition of model SessionForm for providing custom form of session registration.

**Describe alternatives you've considered**

**Additional context**

![screenshot from 2018-05-25 13-05-07](https://user-images.githubusercontent.com/22936570/40532532-6138bbd4-601d-11e8-9334-22afb1397289.png)
Organizer can add more attributes of Session. In route http://localhost:4200/events/<event_identifier>/edit/sessions-speakers

**Comment by srv-twry** [comment]
@bhaveshAn Please delete the hints given in the issue template when opening issue. It makes the issue unnecessarily big.
For e.g. ```A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]``` can be deleted.

**Comment by iamareebjamal** [comment]
Solved already
