### ISSUE TITLE
Change bytes to str in all instances of "file.write"

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#4783]
**Describe the bug**
`file.write` causes an error in python 3.5 (Stack trace below)

**To Reproduce**
1. Set up the project with python 3.5 (preferably a virtual env)
1. Make the API call to start a zip task.

For more details refer to #4775 

**Expected behavior**
No error

**Stacktrace**
```sh
  File "/open-event-server/app/api/helpers/tasks.py", line 64, in export_event_task
    path = event_export_task_base(event_id, settings)
  File "/open-event-server/app/api/exports.py", line 69, in event_export_task_base
    path = export_event_json(event_id, settings)
  File "/open-event-server/app/api/helpers/export_helpers.py", line 209, in export_event_json
    fp.write(data_str)
TypeError: write() argument must be str, not bytes
```
**Additional details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version 3.5
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**
#4775

**Comment by srv-twry** [comment]
@mayank8318 Is this also a problem in Python 3.6 ? 
If not, then please use it since we are supposed to use 3.6
