### ISSUE TITLE
Admin: Events: State is missing

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4787]
**Is your feature request related to a problem? Please describe.**
In the events section on the admin page, the version 1 had a `state` column indicating the state of the event. This is not present in version 2. Compare:

v1 with state:
![events_sorting_state](https://user-images.githubusercontent.com/2054706/40542775-d311b252-6021-11e8-9535-8b1fa9f132a7.png)

v2 without state:
![v2_events](https://user-images.githubusercontent.com/2054706/40542776-d3334b74-6021-11e8-80ec-518ce3812c1c.png)

**Comment by srv-twry** [comment]
@maxlorenz It's a FE issue.

@open-event-bot move to fossasia/open-event-frontend
