### ISSUE TITLE
Admin: Events: Restore event: Event gone after delete, no restore options

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4789]
**Is your feature request related to a problem? Please describe.**
Events in version 2 must be restoreable. After deleting an event, it _is not visible_ in the `All Deleted` table and the action menu does not have an restore option (See `Actions` column in screen).

![v2_events_deleted](https://user-images.githubusercontent.com/2054706/40542909-74acbf08-6022-11e8-8df3-e603ce184217.png)

**Comment by schedutron** [comment]
Looking into it.

**Comment by srv-twry** [comment]
Soft deletion support has been added in the server. This is a FE issue.

**Comment by srv-twry** [comment]
@open-event-bot move to fossasia/open-event-frontend
