### ISSUE TITLE
Admin: Sales: Filter bar missing

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4790]
**Is your feature request related to a problem? Please describe.**
In v1, the project had a filter bar:
![v1_sales_filter_bar](https://user-images.githubusercontent.com/2054706/40543006-cd1e6f88-6022-11e8-9dc6-91e980f20e23.png)

This capability is missing in version 2. Hint: Needs frontend integration after the feature is implemented

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-frontend

**Comment by maxlorenz** [comment]
This also needs server capabilities, right? Should I reword that?
