### ISSUE TITLE
Admin: Sales: All but one tabs show demo data

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4791]
**Is your feature request related to a problem? Please describe.**
Except for `invoices`, all sales tabs display demo data. Please check if the correct endpoints exist. This is present in the tabs

- By Events
- By Organizer
- By Location
- By Marketer
- Discounted events
- Fees

Hint: frontend integration will be necessary

**Comment by maxlorenz** [comment]
Looking into int

**Comment by maxlorenz** [comment]
@bhaveshAn the backend work is done here, @Kreijstal has taken over for the frontend

**Comment by bhaveshAn** [comment]
Since backend is done hence closing this issue.

**Comment by maxlorenz** [comment]
@bhaveshAn the backend work is done here, @Kreijstal has taken over for the frontend
