### ISSUE TITLE
Admins: Sales: No sort/pagination options

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-server#4793]
**Is your feature request related to a problem? Please describe.**
The v1 version had sort options for the different columns and pagination. Please implement them for the different sales tabs. This depends on their implementation first in issue #4791. See one example:
v1:
![v1_sales_sorting](https://user-images.githubusercontent.com/2054706/40543299-0dbd6ab6-6024-11e8-9363-f2c5ddecf79f.png)

v2:
![v2_sales_sorting](https://user-images.githubusercontent.com/2054706/40543314-1de01a6a-6024-11e8-8dd8-68f71bf02742.png)

Needs frontend integration

**Comment by Kreijstal** [comment]
on the server side the pagination is already implemented by flask rest jsonapi

**Comment by YogeshSharma0201** [comment]
working on this
