### ISSUE TITLE
Events should also have average rating

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#4808]
**Is your feature request related to a problem? Please describe.**
Events should have an average rating attribute

**Describe the solution you'd like**
Will use Postgres aggregate clauses to compute the average, and perhaps some other tools for caching the average value, if need be.

**Additional context**
Discussed in #4728

I'd like to implement this.

**Comment by bhaveshAn** [comment]
@schedutron Working on it ? or may I do it.

**Comment by schedutron** [comment]
@bhaveshAn I'm working on it, but having a hard time mapping aggregates of one model to the field of another. I've discussed this with @srv-twry and he's given me some documentation to read. I'll soon open a WIP PR and if I'm unable to accomplish this, I'll hand over this issue to you soon 😄

By the way, another issue I'm having trouble with is #4744. You can take that up if you want. 👍
