### ISSUE TITLE
Add Event and Speaker Image Sizes at Admin dashboard

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4834]
**Is your feature request related to a problem? Please describe.**

Currently, there isn't any API for updating the Image Sizes for Event and Speaker.

**Describe the solution you'd like**

One Model Image Size having attributes of both Event Image Size and Speaker Image Size.
Schema and APIs separately for Event Image Size and Speaker Image Size.
Only accessible to admin for patch method.

**Describe alternatives you've considered**

**Additional context**

V1

![screenshot from 2018-06-01 18-33-09](https://user-images.githubusercontent.com/22936570/40878588-cfb6f7e4-66b0-11e8-9891-40563ec9266a.png)
![screenshot from 2018-06-01 18-33-00](https://user-images.githubusercontent.com/22936570/40878589-d0110f5e-66b0-11e8-9469-9608d6e95847.png)

**Wanna work on this issue**

**Comment by iamareebjamal** [comment]
I think introducing 12 sizes for every image is very strange for an API. Rather, there should be a URL model which lazily generates and serves images

<server>/image.png - max
<server>/[icon|92x92]/image.png - lazily generate and serve and thus cached for next request

This will have reactive approach and reduce unneeded redundancy of images being generated since an image may be accessed only once or even never

**Comment by bhaveshAn** [comment]
@iamareebjamal Please check if https://github.com/fossasia/open-event-server/pull/4836 aligns in some way with your opinion.

**Comment by iamareebjamal** [comment]
That's exactly what I'm voting against. All these nitty-gritty changes in sizes on the speculation and generation of so many images when they won't even be used is a waste of space and processing time

One of my biggest criticism of the current API structure is that APIs are made to provide sane defaults with least amount of data from and to the user. Hence proactively generating 8-10 image sizes(preconfigured or hard-coded) is catering for a very very specific use case and must not be the default.

Simply, the URL scheme of current API can be intercepted and image can be lazily generated, whichever sizes the admin has enabled or using default values.

This is just my opinion on the matter
