### ISSUE TITLE
Default values not being added to the SessionSchema

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4837]
**Describe the bug**

Despite of adding the "use_defaults" decorator, the "make_object" method isn't called for the Session schema and hence the default values aren't being set before schema validation. This is only the case with the Session schema. 
Other schema classes however work just fine.(checked on TicketSchema).

**To Reproduce**
1. Use postman to make a post request to create a session. Make sure you set `"state": null,`.
2. The default value specified in the schema is "draft" while in the model is "pending"(Another bug, resolve this also)
3. The server will return state as "pending" i.e. the default values specified in the schema won't be added. 

**Expected behavior**

Default values should be added.

**Comment by srv-twry** [comment]
@bhaveshAn Can you please remove the `has-PR` label ? I referenced it but it doesn't solve it.

**Comment by bhaveshAn** [comment]
this label is used to tell that someone has submitted the PR and fixed it or is fixing it in WIP. So I don't think to remove it till your PR is open.
