### ISSUE TITLE
Add the API Endpoints for Favourite Events of a User

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-server#4842]
**Is your feature request related to a problem? Please describe.**
The general app for Events will utilise a feature where Users will be able to to favourite an Event and there will be a section too where they can see their favourited events.

**Describe the solution you'd like**
Add the API Endpoints to Post favourite events and Get favourited events of a user

**Additional context**
Working on it : No

**Comment by bhavybarca** [comment]
@dreadpool2 i would like to work on it, can you provide the necessary requirements of the endpoint

**Comment by dreadpool2** [comment]
@bhavybarca Please go ahead if you want to work on it. The endpoints should be added to the user model I guess. The issue has been termed later by the mentor, so maybe you can work on it afterwards!

**Comment by bhaveshAn** [comment]
@mariobehling @dreadpool2 Please check if this feature is required in server or any open event component right now, so that we can proceed.

**Comment by simarsingh24** [comment]
Yes it is required right now we are locally storing favorites this way favorites are lost on changing devices
