### ISSUE TITLE
Access-Code: Access codes returns HTTP 422 when max and min quantity is equal

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4844]
**Describe the bug**

Access codes returns HTTP 422 when max and min quantity is equal

**To Reproduce**
Create an access code with equal max and min quantity.

**Expected behavior**

It should only return 422 when min qty is strictly greater than the max qty.

**Comment by mishuvs** [comment]
@srv-twry Can I take this one?

**Comment by srv-twry** [comment]
yes, go ahead.
