### ISSUE TITLE
Fix discount code

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4855]
**Describe the bug**

Discount code was having a weird bug that was making travis not work for the repositories. Interestingly it was working well before

**Expected behavior**

It should work just fine, without triggering a travis fail build

**Stacktrace**

See #4846 

**Additional context**

See #4854

**Comment by bhaveshAn** [comment]
Closing in relation to https://github.com/fossasia/open-event-server/issues/4846 and https://github.com/fossasia/open-event-server/pull/4854
