### ISSUE TITLE
Allow restricting check-in and auto-check-in for certain ticket types

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#4856]
**Is your feature request related to a problem? Please describe.**
The API should be able to restrict check in for all attendees holding certain ticket types

**Describe the solution you'd like**

There should be an attribute of for Ticket API called as 'is-check-in-restricted`, and 'auto-check-in-enabled'.

**Additional context**

Orga app issues: [#973](https://github.com/fossasia/open-event-orga-app/issues/973) [#974](https://github.com/fossasia/open-event-orga-app/issues/974)

**Comment by schedutron** [comment]
Are you working on this or can I work on this one?

**Comment by mishuvs** [comment]
Please go ahead.

**Comment by schedutron** [comment]
Besides adding the attributes mentioned above, should additional code for validating the check-in of attendees be implemented as well?

**Comment by iamareebjamal** [comment]
Yes @schedutron
