### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#4857]
**Describe the bug**

Pagination parameters are not working or are not being parsed. Are they implemented?

**To Reproduce**
1. Go to any API resource
2.  Try to use pagination parameters like page[number]
3. see error

**Expected behavior**

It should return the results but paginated
**Stacktrace**

```
{
  "errors": [
    {
      "status": 400,
      "source": {
        "parameter": "page%5bsize%5d"
      },
      "title": "Bad request",
      "detail": "Parse error"
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}
````

**Comment by ShubhamBansal1997** [comment]
@Kreijstal Would like to work on this.

**Comment by Kreijstal** [comment]
Okay basically it was external https://github.com/apiaryio/api-blueprint/issues/430
