### ISSUE TITLE
Populate DB for EventType and EventTopic as they were in v1

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4859]
**Is your feature request related to a problem? Please describe.**

Populate DB for EventType and EventTopic as they were in v1
**Describe the solution you'd like**

use populate_db.py to populate.
**Describe alternatives you've considered**

**Additional context**

**Wanna work on this issue**

**Comment by srv-twry** [comment]
@bhaveshAn I don't we want this to be the case. 
@pradeepgangwar has allowed the admin to add these topics and types in the admin section. Pre-populating them shouldn't be required. 

thoughts: @mayank8318 @schedutron @pradeepgangwar

**Comment by bhaveshAn** [comment]
It is required as we have to make it aligned to V1.
In V1 it is already done.
Follow up on the last Admin Section meeting. This is a requirement as said by @mariobehling 
We have to predefine all the Event Topics and Event Types as they were in V1. So that Admin should not manually add these every time when he go to production.
Makes sense?

> @pradeepgangwar has allowed the admin to add these topics and types in the admin section. Pre-populating them shouldn't be required.

That interface will be required to add more event types and topics. Which were not earlier in V1.

**Comment by srv-twry** [comment]
fair enough :+1:
