### ISSUE TITLE
API for Net Sales and Gross Sales

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-server#4873]
**Is your feature request related to a problem? Please describe.**
The API should provide net sales and gross sales for an event. Presently the orga app calculates gross sales for an event locally but for net sales, total expenditure is required which need to be provided by server.
EventBrite provides this functionality and as per discussion with @mariobehling this functionality is required by Orga app as well.

**Describe the solution you'd like**
Endpoint for providing Net sales and Gross sales.

**Describe alternatives you've considered**
Providing total expenditure, if providing total net sales isn't possible.

**Comment by Masquerade0097** [comment]
@SaptakS @niranjan94 @poush Please provide your opinion regarding this.

**Comment by maxlorenz** [comment]
Hi, as I am working on the admin sales routes right now, I have calculated some of the required functionality. Is the net sales amount just the sales after tax?

**Comment by Masquerade0097** [comment]
@maxlorenz According to [this](https://www.accountingtools.com/articles/what-is-the-difference-between-gross-sales-and-net-sales.html). Net Sales is -
Gross Sales (The grand total of all sale transactions reported in a period, without any deductions included within the figure ) minus the following three deductions:

1. Sales allowances. A reduction in the price paid by a customer, due to minor product defects. The seller grants a sales allowance after the buyer has purchased the items in question.

2. Sales discounts. An early payment discount, such as paying 2% less if the buyer pays within 10 days of the invoice date. The seller does not know which customers will take the discount at the time of sale, so the discount is typically applied upon the receipt of cash from customers.

3. Sales returns. A refund granted to customers if they return goods to the company (typically under a return merchandise authorization).

**Comment by maxlorenz** [comment]
Yes, will do! Thanks

**Comment by maxlorenz** [comment]
This is blocked until issue #4887 is merged as the fee calculation is done there

**Comment by maxlorenz** [comment]
Okay the route `/admin/sales/fees` contains the fields `payment-currency`, `fee-percentage`, `revenue` and `ticket-count` with `revenue = total of completed orders - fees`. Is that enough?

**Comment by Masquerade0097** [comment]
@maxlorenz Sorry for late reply, didn't see it. Just to be sure, the `total of completed orders` contains the total of orders after deducting any discount from discount codes, right ?
