### ISSUE TITLE
Request to tracks?include=sessions returns deleted sessions

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#4874]
**Describe the bug**
Currently on public route frontend sends query to tracks?include=sessions and in response it returns all the sessions including the one which were deleted.

**To Reproduce**
1. Create two sessions
2. Delete one of them.
3. Query for GET on tracks?include=sessions
4. It returns both the sessions including the one you deleted.

**Expected behavior**
Should not return deleted sessions.

**Comment by shubham-padia** [comment]
@srv-twry you might want to read up on https://blog.fossasia.org/handling-soft-and-hard-deletes-in-the-open-event-server-api/ and have a look at https://github.com/fossasia/flask-rest-jsonapi/tree/shubhamp-master?files=1 as we use a custom version of flask-rest-jsonapi

**Comment by srv-twry** [comment]
@pradeepgangwar This issue has been fixed. Can you please test it again. Make sure to install the requirements again i.e re run `pip install requirements/common.txt` so that it updates the library.

**Comment by pradeepgangwar** [comment]
Sure, let me check.

**Comment by pradeepgangwar** [comment]
@srv-twry This is working fine. Thanks! :+1:
