### ISSUE TITLE
API for Attendee Notes

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-server#4876]
**Is your feature request related to a problem? Please describe.**
EventBrite has options to add Attendee Notes by an organizer. One organizer can add more than one notes, if he may. 
Such functionalities should be present in Orga Server too so Orga App could implement these as well.

**Describe the solution you'd like**
API should be implemented for this feature.

**Describe alternatives you've considered**
 None.

**Additional context**
Please see the Eventbite Organizer app for more details.

**Comment by Masquerade0097** [comment]
@niranjan94 @SaptakS @poush @iamareebjamal Please provide your views regarding this.

**Comment by iamareebjamal** [comment]
Checkin History is already present

**Comment by Masquerade0097** [comment]
@iamareebjamal Okay, I've edited the issue to exclude checkin times.
