### ISSUE TITLE
Migration file for dashboard images has missing import

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#4900]
**Describe the bug**
The migration file for the recent dashboard images PR (#4836) has missing import.

**To Reproduce**
Upgrade your database after pulling from upstream development branch.

**Expected behavior**
Migration should be performed successfully.

**Stacktrace**
This is the error I got while upgrading the database:
```
File "/open-event-server/migrations/versions/dd7968d8d413_.py", line 19, in upgrade
    op.add_column('image_sizes', sa.Column('icon_size_quality', sa.Integer(), nullable=True))
NameError: name 'sa' is not defined
```

I will add the import line via a PR.

**Comment by srv-twry** [comment]
weird, how did it even get merged. Please fix it :)

**Comment by schedutron** [comment]
Yes, Travis had passed. How do we ensure things like this don't happen in the future and Travis automatically detects such problems?

**Comment by srv-twry** [comment]
No clue on how we can deal with this. We do have tests for checking multiple heads in the db but not sure how we can check this.

@iamareebjamal @niranjan94 Any way to ensure things like this don't go unnoticed ?

**Comment by iamareebjamal** [comment]
Maybe add a migrate command before tests?

**Comment by srv-twry** [comment]
``` Python
@hooks.before_all
def before_all(transaction):
    app = Flask(__name__)
    app.config.from_object('config.TestingConfig')
    db.init_app(app)
    Migrate(app, db)
    stash['app'] = app
    stash['db'] = db
```

**Comment by srv-twry** [comment]
Aren't we already doing it ? @iamareebjamal

**Comment by iamareebjamal** [comment]
Yeah, this won't work because for Travis, there is no existing schema, hence it will be always created from scratch. IMO there's no way of testing migration files unless we specifically step through each migration from the start which will be very time-consuming. But that's what we do in Java projects

**Comment by schedutron** [comment]
@iamareebjamal @srv-twry Can we just check from the previous migration head to the latest head instead of going all the way from start?

**Comment by srv-twry** [comment]
IMO for this to work you'll have to get the db to previous state first. Travis creates a new db for each test, so I can't understand how we can achieve this without going all the way from start.
