### ISSUE TITLE
Show debug error information on exception for development instance

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4903]
For development instance of application, especially on obscure errors like 500, debug stack trace information should be shown to the user in the response JSON

This will severely cut down the reliance of client developers on server developers and enable them to create issues with proper data

**Comment by schedutron** [comment]
How would we separate all the responses in the development branch from the master branch?

**Comment by iamareebjamal** [comment]
Not from the dev and master branch, but from the Development and Production Environment

**Comment by schedutron** [comment]
Will such separation require changes in the Travis file?

**Comment by iamareebjamal** [comment]
No, you run the app using one of the many environments like dev, staging, production and can change behaviour of the app by knowing which environment is being run

**Comment by srv-twry** [comment]
@iamareebjamal I think they are already propagated.
```
class DevelopmentConfig(Config):
    """
    The configuration for a development environment
    """

    DEVELOPMENT = True
    DEBUG = True
    CACHING = True
    PROPOGATE_ERROR = True

    # Test database performance
    SQLALCHEMY_RECORD_QUERIES = True
```
Also 
```
API_PROPOGATE_UNCAUGHT_EXCEPTIONS = env.bool('API_PROPOGATE_UNCAUGHT_EXCEPTIONS', default=True)
```
is true by default in all the configs.

**Comment by iamareebjamal** [comment]
Yes, but they are not displayed because they are caught beforehand and a JSON response like this is sent

```JSON
{
   "error": ...,
   "pointer": " "
}
```

Which isn't helpful. 

The default propagation would display an HTML page instead I guess. We don't need that

**Comment by schedutron** [comment]
How should we go about implementing traceback propagation to the clients?

**Comment by iamareebjamal** [comment]
Check how the status 500 is sent to the client, check there is the environment is debug and send the error trace by encoding into JSON

**Comment by sanudatta11** [comment]
1. How to check the env. What's the exact key value pair we are looking for.

**Comment by iamareebjamal** [comment]
`DEBUG`

**Comment by prateekj117** [comment]
@iamareebjamal I would like to work on it.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by shreyanshdwivedi** [comment]
@prateekj117 any update on this?

**Comment by prateekj117** [comment]
@shreyanshdwivedi No. You can take this up if you want.

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi It would be great if you could fix this asap! This is acting as a major issue because of the vague errors being logged.

**Comment by shreyanshdwivedi** [comment]
@mrsaicharan1 I'll try to fix this today. Meanwhile if anyone else finds a fix, please open a PR

**Comment by iamareebjamal** [comment]
I tested this, and seems that the heroku and test configs were just misconfigured, ProductionConfig was being used instead of DevelopmentConfig. Will verify and close this

**Comment by kushthedude** [comment]
> I tested this, and seems that the heroku and test configs were just misconfigured, ProductionConfig was being used instead of DevelopmentConfig. Will verify and close this

So the #6068 should be closed ?

**Comment by iamareebjamal** [comment]
Let me and other people verify that they are getting full stacktrace instead of obscure errors, then yes
