### ISSUE TITLE
Discount Code API does not has relationship to tickets

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#4905]
**Describe the bug**
Currently Discount code api does not has one to many relationship for tickets. Since one discount code can be applied to many tickets so there should be a relationship from discount code to tickets.

**Expected behavior**
- There should be a one to many relation between discount code and tickets.
- There is a **tickets** field in Discount code API which should be removed. It does not make any sense to have tickets as string with value either event or ticket.

**Parent issue**
#4940

**Comment by schedutron** [comment]
Are you working on it or can I take this one?

**Comment by pradeepgangwar** [comment]
@srv-twry There is one more field there which is **user-for**. IMO that is the field that defines its behaviour.
@schedutron you can work on this.

**Comment by pradeepgangwar** [comment]
@srv-twry @schedutron You can see the comments here which might be helpful.
https://github.com/fossasia/open-event-frontend/blob/d7822ae83c65bcafc89a10153a6a192d426b89b6/app/models/discount-code.js#L5-L36

**Comment by pradeepgangwar** [comment]
@srv-twry @schedutron You can see the comments here which might be helpful.
https://github.com/fossasia/open-event-frontend/blob/d7822ae83c65bcafc89a10153a6a192d426b89b6/app/models/discount-code.js#L5-L36

**Comment by srv-twry** [comment]
Thanks, understood :)
