### ISSUE TITLE
Attendees API should allow tagging checkin-times with device names

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#4907]
**Is your feature request related to a problem? Please describe.**
The EventBrite Organizer App has an option for device name, which is used to track sales and check-in. A similar feature is needed for Open Event.

**Describe the solution you'd like**
The Orga App doesn't support selling tickets, so only the checkin-times case shall be handled right now. 
The attendees API has a property called `checkin-times` which provides comma separated values. Another attribute `checkin-devices` can be used to provide csv for device names that was used to checked-in.

**Describe alternatives you've considered**
An array with two strings (csv for times and devices) could be passed in `checkin-times`.

**Additional context**
Open Event Orga App issue: [#1074](https://github.com/fossasia/open-event-orga-app/issues/1074)

**Comment by mishuvs** [comment]
@iamareebjamal @srv-twry @schedutron Please suggest the solution to be used.

**Comment by iamareebjamal** [comment]
This is to be implemented on server first

**Comment by schedutron** [comment]
So we need client devices to send their names through the Attendees endpoint?

**Comment by mishuvs** [comment]
Yes, and the field is probably optional - in case the organizers wants to track.

**Comment by mishuvs** [comment]
Orga devs expressed that csv might not be a good way. So I am trying for a better solution. Working on it.
