### ISSUE TITLE
The route admin/settings/images shows Internal Server Error

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-server#4912]
**Describe the bug**
In the frontend the route admin/settings/images shows 500 Internal Server Error and the stack trace for teh server shows 404.

**To Reproduce**
1. Go to admin/settings/images in frontend

**Expected behavior**
Should show the form for system images.

**Stacktrace**
![image](https://user-images.githubusercontent.com/22127980/41483550-27e72c54-70f7-11e8-82d3-53286db8e227.png)

![image](https://user-images.githubusercontent.com/22127980/41483560-30cc002e-70f7-11e8-8153-49c1db42d9fe.png)

**Additional details (please complete the following information):**
 - OS:Ubuntu

**Comment by bhaveshAn** [comment]
@ritikamotwani Can this be closed as just API integration of `v1/event-image-sizes` & `/v1/speaker-image-sizes` instead of `/v1/image-sizes` is required in frontend to get it working. Nothing missing from server ?

**Comment by srv-twry** [comment]
It doesn't seem to be a bug. Closing this one due to inactivity. @ritikamotwani Please reopen this if you disagree with this.
