### ISSUE TITLE
Add API for Message settings

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4914]
**Is your feature request related to a problem? Please describe.**

Currently, server have no feature of Message Settings API.
**Describe the solution you'd like**

Creating API for message setting that will allow only the admin to get and update the settings concerning this.
**Describe alternatives you've considered**

**Additional context**

**V1**
![screenshot from 2018-06-16 16-01-19](https://user-images.githubusercontent.com/22936570/41497955-88a046f2-717e-11e8-8d35-7197f3f89598.png)

**V2**
![screenshot from 2018-06-16 15-15-54](https://user-images.githubusercontent.com/22936570/41497726-b6ece7b4-7178-11e8-843e-201604192aaf.png)

**Comment by bhaveshAn** [comment]
Hi @maxlorenz 
System Messages is same as Message Settings Refer: Open Event Backlogs :)

**Comment by maxlorenz** [comment]
Great, assigned myself
