### ISSUE TITLE
Show System Roles and Events Role for a user

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#4919]
**Is your feature request related to a problem? Please describe.**

Currently, when we go to `/admin/users/all` route at frontend it is missing the System Role and Event role associated with a user.

**Describe the solution you'd like**

Modifying the API of users by adding Boolean attributes like 
`is_user_super_admin`
`is_user_admin`
`is_user_coorganizer`
`is_user_attendee`
`is_user_track_organizer`
`is_user_moderator`
etc

**Describe alternatives you've considered**

**Additional context**

![users tab roles](https://user-images.githubusercontent.com/22936570/41501401-5dadc986-71c1-11e8-9ebe-2b09656667bb.png)

@niranjan94 @SaptakS @iamareebjamal @poush 
Thoughts please can I go with this proposed approach ??

**Comment by SaptakS** [comment]
You can but you need to be very careful with permissions then. The permissions for GET list should be visible only to the admins and not everyone.

**Comment by bhaveshAn** [comment]
@SaptakS 

> The permissions for GET list should be visible only to the admins and not everyone.

GET Users List `/v1/users` is accessible to Admins only, already. 
https://github.com/fossasia/open-event-server/blob/development/app/api/users.py#LC69
