### ISSUE TITLE
HTTP 403 in GeneralStatistics even when the user is a coorganizer

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4932]
**Describe the bug**

The server returns HTTP 403 even when the user is a coorganizer. 

**To Reproduce**
1.Make a get request to the endpoint.

**Expected behavior**

It should send the general statistics.

**Comment by bhaveshAn** [comment]
Working fine for me 
![screenshot from 2018-06-18 16-58-13](https://user-images.githubusercontent.com/22936570/41533561-d419694c-7318-11e8-86bd-151474d18397.png)

**Comment by srv-twry** [comment]
Yeah, it's working for me too with POSTMAN. Got the error in the orga app. 
```
06-18 16:33:08.423 9952-11205/org.fossasia.eventyay D/OkHttp: <-- 403 FORBIDDEN https://open-event-api-dev.herokuapp.com/v1/events/5/general-statistics (547ms)
    Connection: keep-alive
    Server: gunicorn/19.8.1
    Date: Mon, 18 Jun 2018 11:03:08 GMT
    Content-Type: application/vnd.api+json
    Content-Length: 161
    Access-Control-Allow-Origin: *
    Via: 1.1 vegur
    {"errors": [{"status": 403, "source": {"source": ""}, "title": "Access Forbidden", "detail": "Co-organizer access is required."}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (161-byte body)
```

Definitely not an issue with the server. Closing this one.

**Comment by srv-twry** [comment]
Thanks bdw @bhaveshAn
