### ISSUE TITLE
Separate Discount code into EventDiscountCode and TicketDiscountCode

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-server#4937]
Right now the Discount code schema/model/endpoints they handle two types of Discount codes. 
1. The Event Discount code created by the admin and applied on the service charges.
2. The Ticket discount code created by the event organizer and applied on the ticket prices of that event. 

This is IMO not following separation of concerns and a source of a lot of bugs. It is extremely confusing to the developers specially the new ones. It is well explained in the dev handbook but I am not sure how many developers would go through the dev-handbook before contributing to the project. For the client side devs of frontend and android, it is even worse. 

Consider the two endpoints:
1. `/v1/events/{event_identifier}/discount-codes` - List of ticket discount codes under an event.
2. `/v1/events/{event_identifier}/discount-code` - Event discount code related with that event.

The difference between the two endpoints is a bare `s`. It seems highly confusing to me atleast if not others. 
I propose to separate them out into two endpoints. If there are lot of common fields between them we can always create a base class and let the two classes extend them in order to obey DRY. 
I am also not sure about the priority of this issue as to whether we should do it after successful feature parity with v1 and release or before that but I think we should definitely fix this one time or the other. 

Thoughts: @iamareebjamal @niranjan94 @SaptakS @poush @mayank8318 @schedutron @bhaveshAn

**Comment by sanudatta11** [comment]
Is it solved? I would like to look into it

**Comment by sanudatta11** [comment]
I think its fixed! I cannot seem to find the above routes! Can you guide me to the routes @srv-twry

**Comment by prateekj117** [comment]
@iamareebjamal Is it a priority. If yes, I would like to work on this.

**Comment by iamareebjamal** [comment]
Milestone is already added

**Comment by iamareebjamal** [comment]
Low priority

**Comment by prateekj117** [comment]
@iamareebjamal It was discussed in the weekly meeting to be done this week. So making a PR and opening a parent issue to check the functionality of Event and Ticket discount code so that we can start using the functionality in the frontend.
