### ISSUE TITLE
Initiate refund when order is deleted

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#4943]
**Is your feature request related to a problem? Please describe.**

When an accepted order is deleted, refund should be initiated.

**Additional context**

Parent issue: #4852

**Comment by srv-twry** [comment]
Yeah, there are a lot of things to consider before this. We have to check the legacy code too in order to see how it is implemented. It will be handled after I am done with the other issues.

**Comment by niranjan94** [comment]
Legacy code did not implement this. So, this will be a new feature. 

But a rough requirement is

- Organizer should have two options for orders
  - Cancel & refund (and ability to specify cancellation charge)
  - Cancel without refund
- Organizer should be able to turn on/off ticket cancellation functionality. There should also be an option for the organizer to specify the following
  - Until which date should cancellation be available
  - Should the cancellation be instantly processed and refund sent or should it wait for the organizer's approval. (And all the necessary API for that). 
  - Cancellation charges (percentage & conditions depending on date)

**Comment by kushthedude** [comment]
Closing it in favour of https://github.com/fossasia/open-event-frontend/issues/3157 , Will open new issue with necessary details regarding Refund
