### ISSUE TITLE
Store email of the Organizer

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-server#4952]
**Describe the bug**
Currently no email of the organiser is stored in the server(only paypal email is stored). It would be easier to contact the organizer if it was stored

**Comment by nikit19** [comment]
@mayank8318 that's the description of the organizer not the email

**Comment by mayank8318** [comment]
Email of the organizer is available in the User model

**Comment by srv-twry** [comment]
@nikit19 Use `event.organizers.email`. Every event has a relationship with the organizers. Use it.

**Comment by srv-twry** [comment]
Closing this one.
