### ISSUE TITLE
Modules end point is giving a 404. (Heroku)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#4969]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17252805/41921955-59ccd186-7964-11e8-9a3f-1b079a23d55f.png)

**Comment by bhaveshAn** [comment]
I guess heroku app requires manually running populate_db.py when there is updation in populate_db.py

**Locally**

![screenshot from 2018-06-26 20-52-19](https://user-images.githubusercontent.com/22936570/41922546-f73b4808-7982-11e8-8ca8-7b26a4b726e7.png)

**Heroku App**

![screenshot from 2018-06-26 20-52-40](https://user-images.githubusercontent.com/22936570/41922547-f86369cc-7982-11e8-918b-0c6995542167.png)

I am see same for `/v1/event-image-sizes` and `v1/speaker-image-sizes`

**Comment by Kreijstal** [comment]
Maybe the heroku is outdated?
