### ISSUE TITLE
Feature to send receipt to attendee via email

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-server#4988]
**Is your feature request related to a problem? Please describe.**
After an order is created there should be a feature to send the receipt of the order to the attendee. In the Eventbrite Organizers app, there is a feature to send a receipt of the order to the email of the attendee through a common email ```orders@eventbrite.com```.

**Screenshot**
![ezgif com-resize 27](https://user-images.githubusercontent.com/20684618/42098147-aa4bc84a-7bd7-11e8-85c4-b124c311ed17.gif)

**Willing to work on this issue**
No. Please anyone take this up.

**Comment by schedutron** [comment]
There is a function to send email to attendees after an order is completed:
https://github.com/fossasia/open-event-server/blob/1cd188b9df867945af354a1ad544017e16253c8d/app/api/orders.py#L125

Is this the feature you're looking for?

**Comment by srv-twry** [comment]
@schedutron That is sent once the order is completed. Only once. What he wants is some sort of feature so that the receipt/email can be sent again. (something like resending the verification email).

You can take it if you want.

**Comment by srv-twry** [comment]
@schedutron @mayank8318 @Kreijstal If anyone is short of issues then please take this one. It's a blocker in the orga app.
