### ISSUE TITLE
Do not send HTML from REST API

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-server#5009]
**Describe the bug**
HTML is being sent in response where plain text is expected, this should not be the case

When we open the about event section (which has links) in the app. Html formatted links are being present. This should not be the case. Screenshot below

![image](https://user-images.githubusercontent.com/28607714/42220234-fe5d3f74-7eeb-11e8-9c7c-8f3caf045a9b.png)

**Comment by schedutron** [comment]
Perhaps this issue is not related to the server, but I'm not sure. Thoughts @bhaveshAn @mayank8318 @srv-twry?

**Comment by srv-twry** [comment]
It is an issue in the server and @iamareebjamal suggested @dreadpool2 to create an issue in the server. I don't know how to fix this though. You'll have to figure it out if you want to work on it.

**Comment by schedutron** [comment]
Sorry, I didn't know about that 😅

**Comment by mayank8318** [comment]
I am not sure but is this the issue - 
```
    def __setattr__(self, name, value):
        if name == 'organizer_description' or name == 'description' or name == 'code_of_conduct':
            super(Event, self).__setattr__(name, clean_html(clean_up_string(value)))
        else:
            super(Event, self).__setattr__(name, value)
```

**Comment by schedutron** [comment]
@mayank8318 Maybe, need to test it. Do we need to separate usual text from links by adding placeholders and send a tuple, of text and a list of links, (which can be rebuilt at client) to fix this? @iamareebjamal

**Comment by iamareebjamal** [comment]
I don't think so, if this cannot be handled client side, we can have an optional query param `?urlize=true` or some better name to do this

**Comment by Kreijstal** [comment]
which URL is this?

**Comment by iamareebjamal** [comment]
events

**Comment by mayank8318** [comment]
Oh ok, we store it in the HTML format with all the tags because the FE uses a rich text editor for input. We just send it the raw format without cleaning the HTML. I agree with @iamareebjamal that there should be a query param for simple text-only form but I don't think that it should be the default option because we should maintain uniformity throughout our various apps. The event description should look same everywhere with bold text, italics, links etc -android app, webapp, FE. @dreadpool2 @iamareebjamal what are your thoughts on this? The app can parse this response, right? I am not sure but I guess the Open Event app does this.

**Comment by iamareebjamal** [comment]
HTML being stored in the database is a concern in itself. If a particular application uses rich content, then it may respect it on its own, like using markdown and parsing it before showing. Android has its own set of display protocols, using HTML won't be optimal. Also, allowing rich content is a serious decision which I don't think was taken by all developers, because we are just escaping the HTML. If rich content is allowed, I can make disruptive changes for other users on UI which comes under stored cross-site scripting. So are we even allowing rich content? Or just escaping HTML, if we are just escaping HTML, then links should not be converted to anchor tags.

**Comment by mayank8318** [comment]
In the editor we are allowing bold, italics underline. If I add a link this is how it is stored in the backend-
![screenshot from 2018-07-09 14-36-32](https://user-images.githubusercontent.com/22395998/42441360-9257f6e0-8385-11e8-8940-14b12ad17eee.png)

```
This should be in <strong>bold</strong>. This should in <em>italics</em>. This should be <u>underlined</u>. <ol><li>Point one</li><li>Point two</li></ol>&lt;a href="<a href="http://google.com" rel="nofollow" target="_blank">google.com</a>"&gt;link&lt;/a&gt;
```

**Comment by iamareebjamal** [comment]
In all honesty, my opinion is that allowing rich text by plain HTML is a huge undertaking and a security flaw. An equivalent of using eval in python or javascript on user code. Big companies like Facebook and MySpace have been hacked due to such ignorances.

**Comment by iamareebjamal** [comment]
How can we trust user input? It is the first rule of frontend engineering to never trust user input, and here we are taking HTML from user input and showing it back. This is a prime vector of stored XSS

https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Comment by mayank8318** [comment]
@iamareebjamal How should we handle this? Eventbrite allows such input - 
![screenshot from 2018-07-09 16-10-56](https://user-images.githubusercontent.com/22395998/42446122-caa949f6-8392-11e8-956c-3e4c1fab7dbc.png)

and it is displayed accordingly as a link
![screenshot from 2018-07-09 16-12-06](https://user-images.githubusercontent.com/22395998/42446144-e22fdd74-8392-11e8-9ce1-88ce7f3cee83.png)

**Comment by mayank8318** [comment]
I agree and understand that it is a major security flaw. We are giving control to the user. What is the best way of tackling this?

**Comment by iamareebjamal** [comment]
Eventbrite must also be allowing only a restricted set of HTML with aggressive cleansing of tags. Like I am sure tags like img and script and `onclick` attribute won't be supported. If HTML is supported, then it should be well documented that which HTML tags are supported and that it is required that client handles the HTML sent.

My suggestion would be to use restricted markdown instead

**Comment by iamareebjamal** [comment]
No, we need to escape it entirely

**Comment by mayank8318** [comment]
@iamareebjamal we are allowing only these tags ->
```python
def clean_html(html):
    if html is None:
        return None
    tags = [
        'b',
        'strong',
        'span',
        'p',
        'em',
        'i',
        'u',
        'center',
        'sup',
        'sub',
        'ul',
        'ol',
        'li',
        'strike'
    ]
    attrs = {
        '*': ['style']
    }
    styles = ['text-align', 'font-weight', 'text-decoration']
    cleaned = bleach.clean(html, tags=tags, attributes=attrs, styles=styles, strip=True)
    return bleach.linkify(cleaned, callbacks=[nofollow, target_blank], parse_email=True)
```

Links are formed because of the `linkify` function. We are also sanitizing the input in the frontend - 
```javascript
import Service from '@ember/service';
import sanitizeHtml from 'npm:sanitize-html';

export default Service.extend({

  sanitize: null,

  // Ensure any changes to the sanitizer rules are set in the rich text editor @ components/widgets/forms/rich-text-editor.js
  options: {
    allowedTags       : ['b', 'strong', 'i', 'em', 'u', 'ol', 'ul', 'li', 'a', 'p'],
    allowedAttributes : {
      'a': ['href', 'rel', 'target']
    },
    selfClosing           : ['br'],
    allowedSchemes        : ['http', 'https', 'ftp', 'mailto'],
    allowedSchemesByTag   : {},
    allowProtocolRelative : false,
    transformTags         : {
      'i' : 'em',
      'b' : 'strong',
      'a' : sanitizeHtml.simpleTransform('a', { rel: 'nofollow', target: '_blank' })
    }
  },

  purify(string) {
    return sanitizeHtml(string, this.options);
  },

  strip(string) {
    return sanitizeHtml(string, {
      allowedTags       : [],
      allowedAttributes : []
    });
  }
});
```

Can you give me an example of a dangerous input so that I can test if everything is working well?

**Comment by iamareebjamal** [comment]
If it is using bleach, then it's reasonably secure. I think links should be handled in frontend rather than converting in anchor tag on the server. This will solve all problems

**Comment by mayank8318** [comment]
@iamareebjamal So you mean that it should be removed from the list of allowed tags in the frontend? Also, `bleach.linkify()` will add the anchor tags anyways right?

**Comment by iamareebjamal** [comment]
I meant anchor tags shouldn't be added
