### ISSUE TITLE
Refund Policy not available

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-server#5010]
**Is your feature request related to a problem? Please describe.**
Refund policy should be available for every event (having ticketing functionalities)

**Comment by srv-twry** [comment]
Well it's simple. We don't have any as of now. We don't support refunds right now.

**Comment by srv-twry** [comment]
Alright, so right now what we can do is add it in every event with value "No refunds allowed" or equivalent. Later when we start supporting it, then we can allow the organizer to decide. Sounds good ?

**Comment by simarsingh24** [comment]
I think this should be best discussed with mentors

**Comment by nikit19** [comment]
@srv-twry Sounds good. Please update as soon as the refund policy is added

**Comment by srv-twry** [comment]
@nikit19 It's solved now.
