### ISSUE TITLE
Unable to re-create ticket after soft deletion

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#5026]
**Describe the bug**
After a ticket is deleted, creating a ticket with the same name for the same event gives a HTTP 500 error. So, if a ticket named "some-ticket-name" for event with id "1" is deleted, then creating a ticket for this event, with the same name gives the following error:

```
Object creation error: (psycopg2.IntegrityError) duplicate key value violates unique constraint "name_event_uc"
DETAIL:  Key (name, event_id)=(some-ticket-name, 1) already exists.
```

**To Reproduce**
Create a ticket for an event, delete it, and then create one with the same name.

**Expected behavior**
It should be possible for a ticket with the same name to be created. Maybe adding the `deleted_at` column to this composite key is the right solution.

If anyone wants to work on this issue, please go ahead.

**Comment by srv-twry** [comment]
Any ticket or other model is soft deleted so that the admin can easily restore it back when needed later. So if the admin later wants to restore that ticket then we will have two tickets with the same name. It shouldn't be possible to create a ticket with the same name IMO.

**Comment by schedutron** [comment]
Okay, so should this be closed or should we wait for mentors to comment?

**Comment by uds5501** [comment]
@iamareebjamal @CosmicCoder96 I think it has been recently fixed in FE using `destroyRecord`
