### ISSUE TITLE
Disallow updating the status of a cancelled order

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#5029]
**Describe the bug**

Disallow updating the status of a cancelled order since once the order is cancelled the tickets are unlocked. If in the future we try to uncancel it then we may not be sure that the tickets will be available or not, hence once the order is cancelled, then it shouldn't be allowed to invert it.

**Additional context**

Parent #4852

**Comment by Kreijstal** [comment]
you could also check if tickets are available or not.

**Comment by srv-twry** [comment]
Options:
1. We inform the event organizer that the order cancellation can't be reverted. 
2. We don't tell them anything during the cancellation and when they try to uncancel it then we check if the tickets are available or not. If available we uncancel it otherwise we tell them that "sorry, those tickets have been taken by someone else now".

I would go with option 1 here. v1 does it too. Plus the second option is really confusing and leads to uncertainity. I have never seen such behaviour anywhere.
