### ISSUE TITLE
Allow amount to be null in a free order

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-server#5031]
**Describe the bug**
Currently, the amount in the body of order has to be > 0 even for free tickets, which should not be the case

**To Reproduce**
1. Try creating an order for any free ticket
2. Keep amount in order body as 0 

**Expected behavior**
The amount should be allowed to be 0 for free tickets

**Comment by srv-twry** [comment]
If it is a free order, simply send amount as null.
Create a helper function `Utils.zeroToNull` in the android project which takes the number and returns null if the number is zero. Similar to `TextUtils.emptyToNull` which returns null for an empty string.

**Comment by simarsingh24** [comment]
@srv-twry please look at it
![image](https://user-images.githubusercontent.com/16715499/42360967-82c4beb2-8109-11e8-9fa0-93b658fa34d8.png)

**Comment by srv-twry** [comment]
Alright, I'll fix this null issue. Thanks for reporting!
