### ISSUE TITLE
Collect Attendee Information

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#5060]
**Is your feature request related to a problem? Please describe.**

A collect attendee information feature needs to be supported for each event such that the organizer can specify what data about an attendee needs to be collected.

**Describe the solution you'd like**

Events API should have a boolean attribute "collect-attendee-information".
And an API probably needs to be added for the frontend and app to be able to create order forms about what data needs to be collected.

**Additional context**

It needs to be like the way EventBrite has implemented it: [reference](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-collect-information-from-all-event-attendees)

**Comment by srv-twry** [comment]
@mishuvs Is it a requirement in the client applications ? If it is then you can work on it otherwise I would suggest first working on other areas which were already implemented in v1 but not yet in v2.

**Comment by srv-twry** [comment]
@starlord1311 I would say no because this is not an immediate requirement right now. Please look for label **Open for all** and take them up.

**Comment by mariobehling** [comment]
Overlapping with other issues.
