### ISSUE TITLE
Reset password API doesnt send token to email

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-server#5072]
**Describe the bug**
I am using POSTMAN and I am not receiving any email when I send a POST request to url `/v1/auth/change-password `to receive the token.
As per the API, I sent a body of
```
{
  "data": {
    "email": "sanyogghosh@gmail.com"
  }
}
```
and I even received a response
```
{
    "message": "Email Sent"
}
```
But I didn't receive any sort of email about the token.

**Comment by srv-twry** [comment]
Duplicate of #4910
