### ISSUE TITLE
Send attendees as a relationship in response to tickets API.

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#5098]
**Is your feature request related to a problem? Please describe.**
Currently attendees are not present in response of a tickets API.

**Describe the solution you'd like**
Add attendees to tickets API response.

Request I sent was `/v1/orders/{identifier}/tickets`

**Comment by srv-twry** [comment]
@pradeepgangwar You can use `v1/orders/{identifier/attendees` to get it.

**Comment by pradeepgangwar** [comment]
@srv-twry thanks. :+1:
