### ISSUE TITLE
HTTP 500 error in charges endpoint

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-server#5103]
**Describe the bug**
Every time I send my stripe token using the charges end point I am getting 500 internal server error

**To Reproduce**
Use the charges endpoint and add your stripe token in the request

**Expected behavior**
A success message or the appropriate error should be displayed
**Additional context**
![screenshot from 2018-07-15 17-03-25](https://user-images.githubusercontent.com/20878145/42733583-0890ce7a-8851-11e8-824d-c86f4cd24955.png)

**Comment by srv-twry** [comment]
Can't reproduce locally or on the heroku deployment.
![charge_500](https://user-images.githubusercontent.com/21277837/42736273-8aea6fb8-8881-11e8-9801-9e62d3422968.png)
