### ISSUE TITLE
Internal server error in charges endpoint

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-server#5111]
**Describe the bug**
Internal server error is encountered when I send my stripe token
**To Reproduce**
POST your stripe token in the charges endpoint you will always get an internal server error

**Expected behavior**
Success message or appropriate error message should be displayed

**Additional context**
![screenshot from 2018-07-16 14-24-52](https://user-images.githubusercontent.com/20878145/42750470-f70e6892-8904-11e8-8a03-7c8dc5948172.png)

**Comment by srv-twry** [comment]
@nikit19 It's not a programming error and will be solved when I add the stripe credentials in the heroku deployment. Issue: #5122
