### ISSUE TITLE
Add third party authentication

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#5115]
**Is your feature request related to a problem? Please describe.**

Authentication through third party providers should be integrated in the system.

Please create child issues and solve them.

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by srv-twry** [comment]
Hi @starlord1311, This is the parent issue which will have multiple sub-issues i.e. one for each provider. 
we have already implemented oauth for facebook. 
You can go ahead and do it for google. I'll quickly create a sub-issue for it and assign you :)

**Comment by srv-twry** [comment]
@starlord1311 i have created the issue. Please go ahead with it and ask questions on that issue if you need to.Note that you can always check the implementation for facebook oauth for reference.

**Comment by darthgera123** [comment]
do we want OAuth from github as well?

**Comment by mariobehling** [comment]
Out of scope currently.
