### ISSUE TITLE
Add completed orders to order-statistics endpoint

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#5134]
**Is your feature request related to a problem? Please describe.**
Currently order statistics endpoint does not return completed orders.

**Describe the solution you'd like**
It should return completed orders and also fix sales accordingly. sales should return order values calculated from completed orders only.

**Additional context**
Needed in FE.

**Comment by bhaveshAn** [comment]
Working on it

**Comment by pradeepgangwar** [comment]
@bhaveshAn please do this ASAP ... This is much needed on FE.
