### ISSUE TITLE
Export Speakers as PDF

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#5137]
**Is your feature request related to a problem? Please describe.**
Add an endpoint to export speakers as PDF

**Describe the solution you'd like**
Create a template and follow the steps used by other export endpoints.

**Describe alternatives you've considered**
\-

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by mayank8318** [comment]
@starlord1311 Are you clear of what is required and the implementation?

**Comment by starlord1311** [comment]
@mayank8318 can you explain what i am supposed to do?

**Comment by mayank8318** [comment]
@starlord1311 just look at other pdf export endpoints. You need to follow the same flow. Create an html template to display the list of speakers similar to orders for example. Also, a speaker can have multiple sessions, so you need to display all of those(you can take the export speakers as csv task as a hint). Feel free to ask if you have any queries :)

**Comment by starlord1311** [comment]
where are all the other pdf export endpoints?

**Comment by mayank8318** [comment]
https://github.com/fossasia/open-event-server/blob/development/app/api/exports.py
This has all the export tasks
