### ISSUE TITLE
Add user authentication with facebook_id

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#5167]
**Is your feature request related to a problem? Please describe.**
Add another option to authenticate via email + facebook_id. We need this because users registered via facebook do not have a password.

**Describe alternatives you've considered**
\-

**Comment by starlord1311** [comment]
can i take up this issue? @mayank8318

**Comment by mayank8318** [comment]
@starlord1311 Actually I have started working on this, maybe you can take up some other issue? :)
