### ISSUE TITLE
Add tickets pdf to order only after order is complete

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-server#5169]
**Describe the bug**
Currently tickets pdf contains dummy attendee names because pdf gets generated as soon as order is created.

**Expected behavior**
Pdf should be generated only after order status is complete.

**Comment by srv-twry** [comment]
@starlord1311 Umm, sorry but I have already solved this. This is a critical issue and we needed it immediately. You can try other issues :) Also check the channel once. https://gitter.im/fossasia/open-event-server
