### ISSUE TITLE
Twitter and Instagram Oauth 

### ISSUE THREAD

**Issue by starlord1311** [fossasia/open-event-server#5175]
**Describe the solution you'd like**

Similar to Fb and Google OAuth

**Would you like to solve it?**
yes

**Parent**
#5115

**Comment by srv-twry** [comment]
@starlord1311 I would suggest you to first finalise your active PRs. You already have 3 PRs opened but not merged. Get them merged and then claim other issues. No point opening PRs but not finalising it.

**Comment by starlord1311** [comment]
@srv-twry can you check out the google oauth pr i have made

**Comment by moulikcipherX** [comment]
@srv-twry can i take up this issue?

**Comment by darthgera123** [comment]
hhey is this issue still open? I have worked on google oauth before

**Comment by bhaveshAn** [comment]
@darthgera123 Sure! You can work

**Comment by darthgera123** [comment]
please assign it and guide me. thanks

**Comment by bhaveshAn** [comment]
@darthgera123 These are the helper classes. You need to use this to implement the authentication same as we tried to do for facebook in `app/api/auth.py`

**Comment by darthgera123** [comment]
Oh okay will do

**Comment by darthgera123** [comment]
so sorry i couldnt complete it so far. Ill make a pr in a day or two.

**Comment by sladyn98** [comment]
Is this issue still open? I have experience with Oauth

**Comment by bhaveshAn** [comment]
@sladyn98 Yes, it is. You can take.

**Comment by sladyn98** [comment]
I read the helper classes @bhaveshAn . Can you give me a bit more context on what exactly should be done and what are the exact requirements.Moreover how do i test it?

**Comment by prateekj117** [comment]
@bhaveshAn Seems like this issue is still open. Can I work on this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by Akhelesh** [comment]
Since there has been no progress on this issue for a long time I am taking up the issue. Currently working on it.

**Comment by prateekj117** [comment]
@Akhelesh I was just busy, working on this issue.

**Comment by Akhelesh** [comment]
Sorry I was unclear whether you were working on the issue or not. You can take up the issue

**Comment by shreyanshdwivedi** [comment]
@prateekj117 are you working on Instagram OAuth? If not, @mrsaicharan1 can do this as he is already working on Twitter OAuth.

**Comment by prateekj117** [comment]
@shreyanshdwivedi @mrsaicharan1 Yes, I am working on this issue, I got caught up in some other work, so sorry for being inactive for a couple of days.

**Comment by Rits1272** [comment]
Can I work on this issue?

**Comment by iamareebjamal** [comment]
Entire OAuth has to be implemented correctly so it is to be taken later on

**Comment by Rits1272** [comment]
Ok @iamareebjamal

**Comment by mariobehling** [comment]
Out of scope.
