### ISSUE TITLE
Add API for Session in accordance with List view for Frontend

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#5182]
**Is your feature request related to a problem? Please describe.**

Add API for Session in accordance with List view for Frontend

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Wanna work on this**

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by bhaveshAn** [comment]
I guess Sessions list view is the same as we have in general sessions list of an event
@srv-twry @mayank8318 @ritikamotwani @pradeepgangwar  Thoughts please
http://open-event-api-dev.herokuapp.com/v1/events/492/sessions

**Comment by bhaveshAn** [comment]
Already done
