### ISSUE TITLE
create paypal endpoint throwing server internal error

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-server#5218]
**Describe the bug**
making request to create paypal endpoint is throwing internal server error

**Endpoint**
`https://open-event-api-dev.herokuapp.com/v1/orders/fcf6d984-55f5-4f41-ace4-5f2cb213358e/create-paypal-payment`

Body
```
{ "data": { "attributes": { "return_url": "adf, "cancel_url": "adfl" }, "type": "paypal-payment" } }
```

Error Log
```
<html> <head> <title>Internal Server Error</title> </head> <body> <h1> <p>Internal Server Error</p> </h1> </body> </html>
```

**Comment by starlord1311** [comment]
can i take up this issue? @simarsingh24

**Comment by simarsingh24** [comment]
@starlord1311 yes please

**Comment by srv-twry** [comment]
@simarsingh24 Can you please test it again ? I've added the paypal keys to the heroku deployment.

**Comment by starlord1311** [comment]
@simarsingh24 should I do this?

**Comment by simarsingh24** [comment]
@starlord1311 @srv-twry please continue with this still throwing internal server error

**Comment by starlord1311** [comment]
@simarsingh24 can you tell me what i am supposed to do?

**Comment by simarsingh24** [comment]
@starlord1311 please discuss with @srv-twry why its throwing internal error also look at the documentation what response body it should send

**Comment by starlord1311** [comment]
@srv-twry can you tell me what to do?

**Comment by srv-twry** [comment]
I can't resolve this untill I get the credentials of the admin account created on the heroku deployment. I have already asked for it thrice on the channel. 

The problem is not in the code, it works locally and that's why we have been able to integrate it successfully in the frontend.

**Comment by CosmicCoder96** [comment]
Works now.
