### ISSUE TITLE
Populate the db with NotificationActions

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#5219]
**Is your feature request related to a problem? Please describe.**

After the addition of a new NotificationAction model, we must update the populate_db.py script to populate the db with the actions for notifications.

**Additional context**

Parent: #4843

**Comment by bhaveshAn** [comment]
@srv-twry  I think in the schema we can add validation of **Oneof ["view", "delete", "update", ...]** in attribute `action_type`
if the objective of populating db here is something else from what i understood then just LMK.

**Comment by srv-twry** [comment]
Yes, here it's different. I have created a new table in the database for notification actions. Now I want to populate the db with actions for each notification. 
Will make more sense when I open the PR.
