### ISSUE TITLE
Add Session Chat Room where Session Speakers and Attendees can chat about sessions

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#5230]
**Is your feature request related to a problem? Please describe.**

Add Session Chat Room where Session Speakers and Attendees can chat about sessions

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Parent Issue #4653 

**Wanna work on this**

**Comment by darthgera123** [comment]
is this issue already solved or i can help with it

**Comment by bhaveshAn** [comment]
This already have a PR https://github.com/fossasia/open-event-server/pull/5236

**Comment by Kreijstal** [comment]
out of scope
