### ISSUE TITLE
No check for verified account in event update endpoint

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#5235]
**Describe the bug**
Verified account check is not done while updating an event. So, any unverified user can publish the event in an update request.

**To Reproduce**
1. Go to create event in FE
2. Click on "Forward" in the first step.
3. Click on "Publish" in the second step.
4. The event is published successfully

**Expected behavior**
Unverified users should not be allowed to publish events at all.

**Additional details (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by starlord1311** [comment]
can i take up this issue? @mayank8318

**Comment by Kreijstal** [comment]
This was reverted by #5252, can you make the PR again?

**Comment by Kreijstal** [comment]
Actually, git was smarter than I thought.
