### ISSUE TITLE
Make field_identifiers for attendee custom form consistent with the model  

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-server#5243]
**Describe the bug**
Field identifier for the fields first-name and last-name are `firstName` and `lastName` respectively but the fields in the ticket_holder model are `firstname` and `lastname` respectively. Hence, there are complications while displaying the form in the frontend.

**Expected behavior**
This should be consistent with the fields in the concerned table.

**Comment by Kreijstal** [comment]
Actually, git was smarter than I thought.
