### ISSUE TITLE
Change data[user_id] to data[user] in POST event-chat-message

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#5249]
**Describe the bug**

Change data['user_id'] to data['user'] in POST event-chat-message

**To Reproduce**

**Expected behavior**

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

**Wanna work on this issue**

**Comment by Kreijstal** [comment]
out of scope
