### ISSUE TITLE
Unable to login through Google account.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/open-event-server#5251]
**Describe the bug**
Unable to login through Google account.
**To Reproduce**
1. Go to eventyay.com
2. Click on LOGIN
3. Click on Sign in with Google.

**Expected behavior**
Sign in with Google should work as expected.

**Screenshot**
![image](https://user-images.githubusercontent.com/25537606/43553032-c8534adc-960a-11e8-924c-3806b7e135fd.png)

**Comment by srv-twry** [comment]
eventyay.com deploys v1 right now. This repo is for the version 2.

**Comment by srv-twry** [comment]
@open-event-bot move to open-event-legacy

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy
