### ISSUE TITLE
HTTP 500 for updating event via identifier

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-server#5267]
**Describe the bug**

Internal server error occurs for patching an event via its identifier.

**To Reproduce**
1. Send a patch request to update an event
2. Use identifier instead of id to specify the event
3. See error

**Expected behavior**

Event should be updated successfully. If events shouldn't be modified via their identifier, a proper error should be sent.

**Screenshot**
<img width="1392" alt="screen shot 2018-08-05 at 4 14 53 am" src="https://user-images.githubusercontent.com/22810216/43681055-80697b5c-9866-11e8-9cd8-49ce5b78cd5d.png">

**Comment by srv-twry** [comment]
Your id in the request should be numeric only.

**Comment by schedutron** [comment]
Thanks, it works with the numeric id! But the request sender usually doesn't have any idea about the id.

**Comment by srv-twry** [comment]
> But the request sender usually doesn't have any idea about the id.

If they have the object, they'll always have the id.

**Comment by schedutron** [comment]
Okay, this can be closed then :)
