### ISSUE TITLE
Migration columns that are not matched

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#5268]
Here we decide whether we throw them away, convert them or do something with them, based on [this](https://pastebin.com/raw/nF8aEJ2X) file I did, I matched most of the columns that were just renamed and put these changes on a JSON, however. there are some columns that were deleted and new columns that were created, what do we do with these?

|       Old unmatched columns        |               New columns               |
|------------------------------------|-----------------------------------------|
| access_codes.tickets               | access_codes.deleted_at                 |
| access_codes.used_for              | custom_forms.deleted_at                 |
| custom_forms.speaker_form          | custom_forms.field_identifier           |
| discount_codes.tickets             | custom_forms.type                       |
| events.email                       | custom_forms.is_required                |
| events_version.email               | custom_forms.is_included                |
| notification.action                | custom_forms.is_fixed                   |
| orders.is_reminder_mail_sent       | custom_placeholders.large_image_url     |
| role_invite.declined               | custom_placeholders.icon_image_url      |
| session_version.start_time         | custom_placeholders.event_sub_topic_id  |
| session_version.end_time           | discount_codes.deleted_at               |
| settings.paypal_sandbox_username   | email_notifications.deleted_at          |
| settings.paypal_sandbox_password   | event_copyrights.deleted_at             |
| settings.paypal_sandbox_signature  | event_invoices.deleted_at               |
| settings.paypal_live_username      | event_invoices.invoice_pdf_url          |
| settings.paypal_live_signature     | events.has_organizer_info               |
| speaker.photo                      | events.refund_policy                    |
| speaker.thumbnail                  | events.order_expiry_time                |
| speaker.small                      | events.is_stripe_linked                 |
| speaker.icon                       | events_version.has_organizer_info       |
| speaker.featured                   | events_version.refund_policy            |
| sponsors.logo                      | events_version.order_expiry_time        |
| sponsors.sponsor_type              | events_version.is_stripe_linked         |
| stripe_authorizations.stripe_email | image_sizes.small_size_width_height     |
| ticket_holders.expertise           | image_sizes.small_size_quality          |
| ticket_holders.occupation          | image_sizes.thumbnail_size_width_height |
| ticket_holders.occupation_detail   | image_sizes.thumbnail_size_quality      |
| ticket_holders.recruitment         | image_sizes.icon_size_width_height      |
| ticket_holders.welcome_reception   | image_sizes.icon_size_quality           |
| ticket_holders.unesco_hackathon    | message_settings.sent_at                |
| tracks.track_image_url             | microlocations.deleted_at               |
| tracks.location                    | notifications.deleted_at                |
| user.signup_time                   | notifications.subject_id                |
| user_permissions.verified_user     | notifications.notification_topic        |
|                                    | orders.deleted_at                       |
|                                    | orders.cancel_note                      |
|                                    | orders.order_notes                      |
|                                    | orders.tickets_pdf_url                  |
|                                    | orders_tickets.deleted_at               |
|                                    | roles.deleted_at                        |
|                                    | role_invites.deleted_at                 |
|                                    | role_invites.role_name                  |
|                                    | role_invites.status                     |
|                                    | sessions.creator_id                     |
|                                    | sessions.last_modified_at               |
|                                    | sessions.send_email                     |
|                                    | session_types.deleted_at                |
|                                    | sessions_version.starts_at              |
|                                    | sessions_version.ends_at                |
|                                    | sessions_version.creator_id             |
|                                    | sessions_version.last_modified_at       |
|                                    | sessions_version.send_email             |
|                                    | settings.static_domain                  |
|                                    | settings.paypal_client                  |
|                                    | settings.paypal_secret                  |
|                                    | settings.paypal_sandbox_client          |
|                                    | settings.paypal_sandbox_secret          |
|                                    | settings.frontend_url                   |
|                                    | settings.cookie_policy                  |
|                                    | settings.cookie_policy_link             |
|                                    | social_links.deleted_at                 |
|                                    | social_links.identifier                 |
|                                    | speaker.deleted_at                      |
|                                    | speaker.photo_url                       |
|                                    | speaker.thumbnail_image_url             |
|                                    | speaker.small_image_url                 |
|                                    | speaker.icon_image_url                  |
|                                    | speaker.is_featured                     |
|                                    | sponsors.deleted_at                     |
|                                    | sponsors.logo_url                       |
|                                    | sponsors.type                           |
|                                    | stripe_authorizations.deleted_at        |
|                                    | stripe_authorizations.stripe_auth_code  |
|                                    | tax.deleted_at                          |
|                                    | tax.is_invoice_sent                     |
|                                    | tickets.deleted_at                      |
|                                    | tickets.is_checkin_restricted           |
|                                    | tickets.auto_checkin_enabled            |
|                                    | ticket_fees.country                     |
|                                    | ticket_holders.deleted_at               |
|                                    | ticket_holders.job_title                |
|                                    | ticket_holders.phone                    |
|                                    | ticket_holders.tax_business_info        |
|                                    | ticket_holders.billing_address          |
|                                    | ticket_holders.home_address             |
|                                    | ticket_holders.shipping_address         |
|                                    | ticket_holders.company                  |
|                                    | ticket_holders.work_address             |
|                                    | ticket_holders.work_phone               |
|                                    | ticket_holders.website                  |
|                                    | ticket_holders.blog                     |
|                                    | ticket_holders.twitter                  |
|                                    | ticket_holders.facebook                 |
|                                    | ticket_holders.github                   |
|                                    | ticket_holders.birth_date               |
|                                    | ticket_holders.pdf_url                  |
|                                    | ticket_holders.is_checked_out           |
|                                    | ticket_holders.checkin_times            |
|                                    | ticket_holders.checkout_times           |
|                                    | ticket_holders.attendee_notes           |
|                                    | ticket_holders.event_id                 |
|                                    | ticket_tag.deleted_at                   |
|                                    | tracks.deleted_at                       |
|                                    | users.facebook_id                       |
|                                    | users.facebook_login_hash               |
|                                    | users.first_name                        |
|                                    | users.last_name                         |
|                                    | users.details                           |
|                                    | users.contact                           |
|                                    | users.facebook_url                      |
|                                    | users.twitter_url                       |
|                                    | users.instagram_url                     |
|                                    | users.google_plus_url                   |
|                                    | users.original_image_url                |
|                                    | users.thumbnail_image_url               |
|                                    | users.small_image_url                   |
|                                    | users.icon_image_url                    |
|                                    | users.is_sales_admin                    |
|                                    | users.is_marketer                       |
|                                    | user_permissions.deleted_at             |
|                                    | user_system_role.event_id               |
|                                    | users_events_roles.deleted_at           |

**Comment by bhaveshAn** [comment]
@Kreijstal In follow up to this one. I have tried to move from v1 (code+migrations) to v2 (code+migrations).
https://pacific-island-48926.herokuapp.com/ is a heroku app which I initially made from v1 (fossasia/open-event-legacy#master) then I made a new branch pulled the (fossasia/open-event-server#development) resolved conflicts and pushed the code to this heroku app and that way it gave me v2 (v1 changed to v2) and works perfectly now acc to v2.
Only few things I faced were a multiple migrations head error due to `699b64daa444` & `e9d61dbd0cb8`
`python3 manage.py db merge 699b64daa444 e9d61dbd0cb8`
and "gender" attr was there in app/models/ticket_holder.py already which was included in a migration file of v2 `b4fdb245fccd`.
After resolving all these, These were the changes btw v1 & v2  **~900+ commits**
https://github.com/bhaveshAn/open-event-legacy/pull/1

So my point is will it be possible to do the same for production deployment too (app.eventyay.com). 
What if we pull the db of eventyay.com (if possible) and follow a process like what I did here. That way the data will already there in v1 db and  v1 db will be synchronized to v2. 
Your thoughts on this ???

**Comment by starlord1311** [comment]
@Kreijstal @bhaveshAn can i take up this issue?

**Comment by srv-twry** [comment]
@starlord1311 No. You're don't have enough experience of this project in order to tackle this.

**Comment by Kreijstal** [comment]
I mapped columns to columns manually, here is the json file I edited
https://pastebin.com/aW0VXqJ6

**Comment by CosmicCoder96** [comment]
Migration files do this automatically. Not sure what was going on here.
