### ISSUE TITLE
Disallow creating users with same email.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-server#5278]
**Is your feature request related to a problem? Please describe.**

Right now we can create users with the same email. If we soft-delete a user account and try to create an account with the same email again, the server allows creating it but sends HTTP 500 when doing so since it voilates the unique constraint in the db.

![image](https://user-images.githubusercontent.com/21277837/43689278-8f3072b2-9915-11e8-94c9-56fce267f5fc.png)

**Comment by mishuvs** [comment]
@srv-twry can I take this?

**Comment by srv-twry** [comment]
@mishuvs could you please do this quickly. Need this. Moreover it's a simple bug so shouldn't take long.
