### ISSUE TITLE
Internal Server Error due to migration problem

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-server#5280]
**Describe the bug**

Internal Server Error due to migration problem

**To Reproduce**

**Expected behavior**

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

![screenshot from 2018-08-06 01-54-57](https://user-images.githubusercontent.com/22936570/43689682-da2773f0-991b-11e8-9ef7-be9822537061.png)

**Comment by starlord1311** [comment]
@bhaveshAn can i take up this issue?
