### ISSUE TITLE
Add support for online event

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-server#5286]
**Is your feature request related to a problem? Please describe.**

Support for online event needs to be added, like in EventBrite

**Describe the solution you'd like**

A property `is_event_online` needs to be added, and checks for location need to be handled to allow publishing for online events

**Comment by bhaveshAn** [comment]
Currently do we want this or may be later ??

**Comment by mishuvs** [comment]
@bhaveshAn I think an online event is the same as an offline event except they don't have a location, for which we'll have to allow publishing without location. It's a small change I think, can we add it?
