### ISSUE TITLE
event_sub_topics is not initialized

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#5315]
In order to do the migration reliably we need event_sub_topics to be initialized just like event_topics are, what is important though is that it contains at least these values:
Comedy
City/Town
Dating
Volleyball
Yoga
Other
Avatar
Robotics
Logo
Food
Cultural
Craft
High Tech
Pop
Science
Medical
Education
Career
Baby
Startups &amp; Small Business
LGBT
Gaming
Easter
Top 40
EDM / Electronic
Educators
Social Media
Design
Auto
R&B
Medicine
Mobile
Anime/Comics
Mysticism and Occult
Classical
Air
Environment
Home & Garden
Beer
Fine Art
Reunion
Finance
Orchestra
Biotech
Non-partisan
Anime

**Comment by bhaveshAn** [comment]
Each event sub topic has a relation with event topic so please update the
above list alongwith it's event topic name.
