### ISSUE TITLE
Improve the testability of the project by adding unit tests

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-server#5320]
**Is your feature request related to a problem? Please describe.**

Right now the code coverage is very low and we should improve it by adding unit tests wherever possible.

**Comment by mohitsakhuja** [comment]
I want to work on this. Where should I start from i.e. which module(s) should I write tests for?

**Comment by srv-twry** [comment]
@mohitsakhuja You'll have to figure out yourself. Check if there is a module that is yet to be tested and write tests for it. If you don't find any then please inform so that I can close this issue.

**Comment by mohitsakhuja** [comment]
@srv-twry Okay, I'll go through the codebase more thoroughly.

**Comment by mrsaicharan1** [comment]
Do the tests require to be in a different file altogether? In addition, does adding tests to the auth helper methods come under this?

**Comment by srv-twry** [comment]
@mrsaicharan1 Hi, Yes we have a separate file for tests of each module. Adding any kind of unit tests comes under this.

**Comment by mrsaicharan1** [comment]
@srv-twry I've implemented a part of the test cases for payments. While I was doing this, I came across a parameter named `order_invoice` in `capture_payments` method located in the helpers file payments.py . I wasn't able to understand the object's structure exactly. Can you help me out here?

**Comment by srv-twry** [comment]
Hi @mrsaicharan1 , I had implemented it during my GSoC. The `order_invoice` parameter is just the order for which we are charging the payment. I could have named it `order` only, but `order_invoice` looked a little more appropriate. In fact in the docstring, I have explained it -> `:param order_invoice: Order to be charged for`.

**Comment by mrsaicharan1** [comment]
I wasn't able to find the doctoring in the code. Could you point me to the file it was implemented so that I can implement a test case for capturing payments?

**Comment by srv-twry** [comment]
https://github.com/fossasia/open-event-server/blob/e55d84117188d9e2df6eebe1362b6400f3fdb72c/app/api/helpers/payment.py#L86

**Comment by mrsaicharan1** [comment]
@srv-twry When I start running tests using *nosetests tests/all* , I get the error opev_test does not exist. Was the database supposed to be created while installation ?

**Comment by maze-runnar** [comment]
validations and helpers are done for unit test.
