### ISSUE TITLE
Remaining tables left to import

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#5347]
So I did the work of importing most of the tables, you can see the work I did here https://docs.google.com/document/d/1uN5wbkrxTPv5xmt1dbnvOMsBuC9oGWp9zWq5P0ZgNsM/edit

|           Column           |                                                           status                                                          |
|----------------------------|---------------------------------------------------------------------------------------------------------------------------|
| events                     | Imported ✔                                                                                                                |
| access_codes               | Imported ✔                                                                                                                |
| activities                 | Imported ✔                                                                                                                |
| association                | Imported ✔                                                                                                                |
| alembic_version            | No need to import                                                                                                         |
| custom_forms               | Not-Imported (field-identifier not null)  ❌                                                                               |
| custom_placeholders        | Imported ✔                                                                                                                |
| custom_sys_roles           | No need to import (populate already fills the data)                                                                       |
| discount_codes             | Imported ✔                                                                                                                |
| users                      | Imported ✔                                                                                                                |
| email_notifications        | Imported ✔                                                                                                                |
| event_copyrights           | Imported ✔                                                                                                                |
| event_invoices             | Imported ✔                                                                                                                |
| events_version             | Imported ✔                                                                                                                |
| export_jobs                | Imported ✔ (Should we really import this anyway?)                                                                         |
| image_sizes                | Imported ✔ (No need populate fills the data)                                                                              |
| import_jobs                | Imported ✔                                                                                                                |
| mails                      | Imported ✔                                                                                                                |
| microlocations             | Imported ✔                                                                                                                |
| message_settings           | No need to import (populate already fills the data)                                                                       |
| modules                    | Imported ✔                                                                                                                |
| notifications              | Imported ✔                                                                                                                |
| orders                     | Imported ✔                                                                                                                |
| tickets                    | Imported ✔                                                                                                                |
| orders_tickets             | Imported ✔                                                                                                                |
| pages                      | Imported ✔                                                                                                                |
| panel_permissions          | No need to import (populate already fills the data)                                                                       |
| permissions                | Not sure (not really sure if they should be Imported or not since the populate fills it with completely different data) ❌ |
| roles                      | No need to import (populate already fills the data)                                                                       |
| role_invites               | Not-Imported (role-name not null)  ❌                                                                                      |
| services                   | No need to import (populate already fills the data)                                                                       |
| tracks                     | Imported ✔                                                                                                                |
| session_types              | Imported ✔                                                                                                                |
| sessions                   | Imported ✔                                                                                                                |
| sessions_version           | Imported ✔                                                                                                                |
| settings                   | Imported ✔ (1 row could change)                                                                                           |
| social_links               | Imported ✔                                                                                                                |
| speaker                    | Imported ✔                                                                                                                |
| speaker_sessions           | Imported ✔                                                                                                                |
| speakers_sessions_version  | Imported ✔                                                                                                                |
| sponsors                   | Imported ✔                                                                                                                |
| tax                        | Imported ✔                                                                                                                |
| stripe_authorizations      | Imported ✔                                                                                                                |
| ticket_fees                | Imported ✔                                                                                                                |
| ticket_holders             | Imported ✔                                                                                                                |
| ticket_tag                 | Imported ✔                                                                                                                |
| user_permissions           |  No need to import (populate already fills the data)                                                                      |
| transaction                | Imported ✔                                                                                                                |
| user_system_role           | Imported ✔                                                                                                                |
| users_events_roles         | Imported ✔                                                                                                                |
| call_for_papers         | Imported ✔       |

Plus these tables which I don't know where to match
booked_ticket ❌, call_for_papers ❌, eventsusers ❌, image_config❌ , invites ❌, user_detail ❌, versions ❌

This is the import sql https://pastebin.com/uPGNNHXj

Does anyone know how to import these tables, or what to do with them?

**Comment by bhaveshAn** [comment]
@Kreijstal For the attrs where in models we have set nullable=False, may be you can set nullable=True but the schema should handle this like allow_none=False.
This way you will be able to add/modify the column using postgresql column completely and we are validating data concerning models using schemas in APIs ??

**Comment by Kreijstal** [comment]
That can be a solution, I think, then I would have to do a pull request and do it with the new database again

**Comment by prateekj117** [comment]
@bhaveshAn @iamareebjamal Is this issue still open? I would like to work on it.

**Comment by CosmicCoder96** [comment]
Migrations is how tables should be transferred. Done for the transfer.
