### ISSUE TITLE
Admin sales tab API is not on an json format the ember easily accepts

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-server#5359]
**Describe the bug**

 
If you go look on the admin sales, you will see that the admin sales are implement on the server yes, however, they're implemented on a deep data structure, and ember accepts a "flat" data structure, that means no objects inside other objects, and it's not in the same format that the ember implements it.

**Comment by niranjan94** [comment]
@Kreijstal this isn't an issue IMO. ember-data & models make more sense for resources. A route like sales, is more of statistics in the form of a nested-structured data. The FE can very well use the rest client and consume the json object.
