### ISSUE TITLE
Can't sign in with google

### ISSUE THREAD

**Issue by avsingh999** [fossasia/open-event-server#5362]
**Describe the bug**
When Click on Sign with google then it's showing this 
![signinerr](https://user-images.githubusercontent.com/25536022/44958556-7a817c80-aeff-11e8-811a-32daf4835002.PNG)

**Expected behavior**
when I click on Sign in with google+ must be sign in as it's with facebook

**Comment by vkartik97** [comment]
It's working now

**Comment by poush** [comment]
@avsingh999 Can you confirm if it is working?

**Comment by avsingh999** [comment]
@poush  @vkartik97  No it's not Working

**Comment by avsingh999** [comment]
@poush  also Showing error when we share a event via Google+

**Comment by avsingh999** [comment]
@poush There is also a problem when we share event  via Google+

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy

**Comment by Ishaan28malik** [comment]
is it still open ?

**Comment by yeshijinsel** [comment]
Wanna work on this issue

**Comment by niranjan94** [comment]
@Ishaan28malik yes. It is still open. Please proceed if interested.

**Comment by soumya-ranjan7** [comment]
@niranjan94 Can you assign me this issue?

**Comment by CosmicCoder96** [comment]
The issue needs to be fixed here, since Eventyay is running through the legacy codebase: https://github.com/fossasia/open-event-legacy/issues/67
