### ISSUE TITLE
Implement additional signups

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5363]
Please implement additional signups as follows for speakers and attendees:

* [ ] If you would like your information to be shared with potential recruiters, please check this box. By checking, you allow the Linux Foundation to share your information with potential recruiters. 

* [ ] By checking here, you opt-in to being listed in the event's online attendee directory. Some of your registration data will be made available to other event attendees in the directory (name, title, and company name only). 

* [ ] By checking here, you opt-in to receiving communications from the event's sponsors regarding their own news and messages (sent by The Linux Foundation; your contact information will not be shared).

* [ ] By checking here, you opt-in to receiving occasional communications from The Linux Foundation relating to our other open source projects, events, and services like training and certifications. If so, you can unsubscribe from email communications at any time using the email's Unsubscribe link. Please note that The Linux Foundation may contact you regarding events and other services you actually register for, even if you do not check this box or if you use a marketing email's Unsubscribe link.

**Comment by rajdeepbharati** [comment]
Can I work on this?

**Comment by uds5501** [comment]
@mrsaicharan1 Can I work on instagram/facebook Oauth?

**Comment by mrsaicharan1** [comment]
@uds5501 Facebook has already been integrated and @prateekj117 is working on instagram I suppose. Maybe you can work on Github OAuth?

**Comment by uds5501** [comment]
@mrsaicharan1 Alright, do I need to open a new issue for that?

**Comment by uds5501** [comment]
@mrsaicharan1 Alright, I am working on the Github OAuth and will refer to this issue only

**Comment by shreyanshdwivedi** [comment]
@uds5501 @prateekj117 I'm working on the frontend part of twitter OAuth - https://github.com/fossasia/open-event-frontend/issues/2140
If you want, I can implement the frontend of Github and Instagram OAuth too :)

**Comment by uds5501** [comment]
@shreyanshdwivedi That'd be great

**Comment by divyam-goel** [comment]
@mrsaicharan1 @uds5501 is there any other OAuth left to implement?

**Comment by uds5501** [comment]
I don't think that there are any notable third party oauths left for now

**Comment by kushthedude** [comment]
@mariobehling Is It up for grabs?
