### ISSUE TITLE
Password confirmation while creating tables in local installation 

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5364]
When I was installing the project locally, after running create_db.py, it didn't ask me to re-confirm the password, and password can easily be mistyped in the first time.  

So it would be better if we add password confirmation in that part.

**Comment by bhaveshAn** [comment]
Would you like to work on it?

**Comment by prateekj117** [comment]
Yes.

**Comment by poush** [comment]
Go ahead.
