### ISSUE TITLE
No verification email 

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-server#5379]
**Describe the bug**
No verification email is being sent 
**To Reproduce**
Sign up and you won't receive a verification mail

**Expected behavior**
You should receive a verification email

**Comment by sk9331657** [comment]
@nikit19  Actually email is also not delivered in the local setup of serve.

**Comment by sladyn98** [comment]
Can i be assigned this issue

**Comment by bhaveshAn** [comment]
Sure. Please fix it asap.

**Comment by bhaveshAn** [comment]
@sladyn98 Any update ?

**Comment by sladyn98** [comment]
Ya I'm working on it I cloned the repo and it should be done by midnight.

**Comment by nikit19** [comment]
@sladyn98 this is a high priority issue. Are you still working on it?

**Comment by sladyn98** [comment]
Yes I am

**Comment by sladyn98** [comment]
Where exactly is the function located?

**Comment by bhaveshAn** [comment]
Its here : https://github.com/fossasia/open-event-server/pull/5384/files
