### ISSUE TITLE
Login with google not working.

### ISSUE THREAD

**Issue by khansultan1** [fossasia/open-event-server#5380]
Trying to login with google but having some trouble can anyone  look around it. please find the screenshot for more.
![image](https://user-images.githubusercontent.com/6906715/45675945-31136d00-bb4e-11e8-8fb5-332c39427def.png)

**Comment by Ananthavijay** [comment]
@khansultan1 there is a similar issue already opened. Link - https://github.com/fossasia/open-event-server/issues/5362

**Comment by bhaveshAn** [comment]
@open-event-bot move to fossasia/open-event-legacy

**Comment by bhaveshAn** [comment]
Duplicate of https://github.com/fossasia/open-event-server/issues/5362 hence closing
