### ISSUE TITLE
Using Pipenv for Packaging

### ISSUE THREAD

**Issue by vkartik97** [fossasia/open-event-server#5391]
As an alternative to `virtualenv/venv` which is currently used in the project(requirements.txt), we can use pipenv also for easy installation. Also now `pipenv` is officially recommended python package and virtualization manager.
Please refer https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock

**Comment by iamareebjamal** [comment]
Sure. Great idea. Would you like to work on it?

**Comment by vkartik97** [comment]
Sure :+1:

**Comment by Ishaan28malik** [comment]
can i work on it ?

**Comment by Ishaan28malik** [comment]
can u brief out what is the issue?..

**Comment by Manas-kashyap** [comment]
Is this issue closed means someone worked on it and filed a pull request or not ?
