### ISSUE TITLE
Minor error in models/custom_form.py

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5399]
**Describe the bug**

In line 71 of models/custom_form.py, in place of `__table_args__ = (UniqueConstraint....)` it should be `__table_args__=(db.UniqueConstraint....)`

**To Reproduce**

**Expected behavior**

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

I'm working on this one.

**Comment by niranjan94** [comment]
Closing due to https://github.com/fossasia/open-event-server/pull/5400#issuecomment-427391978
