### ISSUE TITLE
Docstring typos in app/models/search/event.py, app/models/search/sync.py and app/views/elastic_search.py

### ISSUE THREAD

**Issue by satyasashi** [fossasia/open-event-server#5402]
**Describe the bug**
Python Documentation String must either be ''' Triple Single quotes ''' or """ Tripe Double quotes """. But it's like this --> " Docstring "
**To Reproduce**
1. Go to 'app/models/search/event.py'
2. Check  'Line number 8 & 22'
3. Go to 'app/views/elastic_search.py'
4. Check 'Line number 11'

**Expected behavior**
Triple-Double quotes or Triple-Single quotes.

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Comment by cursed4ever** [comment]
Issed PR No. #5405

**Comment by cursed4ever** [comment]
please asign
