### ISSUE TITLE
No favicon in open-event-server

### ISSUE THREAD

**Issue by sarnava1** [fossasia/open-event-server#5406]
**Describe the bug**

There is no favicon in the title bar of open-ebent-server
**To Reproduce**
1. Go to http://127.0.0.1:5000/

![nofaviconinopeneventserver](https://user-images.githubusercontent.com/25319565/46576217-6fc87480-c9e2-11e8-8386-708c7f616244.png)

**Expected behavior**
There should be a favicon in the title bar

**Comment by sarnava1** [comment]
@mariobehling @abishekvashok @iamareebjamal @bhaveshAn I want to work on this issue.

**Comment by iamareebjamal** [comment]
This is an API server, so it does not need a favicon

**Comment by sarnava1** [comment]
@iamareebjamal ok so I am closing this issue.
