### ISSUE TITLE
Error While deploying on docker

### ISSUE THREAD

**Issue by pandyamarut** [fossasia/open-event-server#5420]
While deploying on Docker. 
after some instructions When you give this command 
cmd-" docker-compose run web/bin/bash"
 There is Usual error (Shown below)-
ERROR: Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

**Comment by pandyamarut** [comment]
Like, It would be great if we have this solution in deploying guide via docker. 
Because this issue is faced by many ( Newcomers) so it will great help to them.

**Comment by iamareebjamal** [comment]
Fixed in #5408
