### ISSUE TITLE
cannot find module in create_db.py

### ISSUE THREAD

**Issue by pandyamarut** [fossasia/open-event-server#5421]
line 5 which is 
"from flask_migrate import stamp"
While executing this file it shows that there is no such module.

**Comment by satyasashi** [comment]
@pandyamarut Did you try checking in the shell "from flask_migrate import stamp" and it gives error? And did you check if "Flask-Migrate" is installed in your environment?

**Comment by pandyamarut** [comment]
@satyasashi i tried

**Comment by prabhupant** [comment]
@pandyamarut make sure you installed the requirements using python3 and also that you are using python3 to run the commands, as sometimes little typos play a major role :sweat_smile: . Otherwise, please post the complete error log here :)

**Comment by pandyamarut** [comment]
@bhaveshAn No.
