### ISSUE TITLE
Unable to goto next step in Create Event. Shows Content Security Policy Error.

### ISSUE THREAD

**Issue by satyasashi** [fossasia/open-event-server#5422]
**Describe the bug**
I have logged in, and tried Creating Event. At the end of the section 1, when published, It doesn't go to next section "Sponsors"

**To Reproduce**
1. Go to 'localhost:4200/create' enter the details
2. Click on 'Publish'
3. Look at the terminal
4. See the Error "Content Security Policy Violation" in Open-event-Frontend Terminal
5. See the Information in Open-event-server Terminal

**Expected behavior**

It should goto next section "Sponsors"

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

I have admin access.

**Error Images**
![content_sec_policy](https://user-images.githubusercontent.com/17382345/46881559-86028480-ce69-11e8-9bcd-8c131ec38dd6.png)

![server_publish](https://user-images.githubusercontent.com/17382345/46881658-cc57e380-ce69-11e8-85d1-3add956dde0c.png)

**Comment by CosmicCoder96** [comment]
@satyasashi You must have been trying to add an event image while creating it, it has been fixed now along with  #5423 . If it persists, please comment below, closing it for now.
