### ISSUE TITLE
Adding an event image while creating event leads to a timeout

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5423]
**Describe the bug**

On event creation wizard step 1, if an event image is added which corresponds to the `original-image-url` attribute of event model inside the server, the POST or PATCH request times out, and server doesn't generate any logs.

If this block of code is removed from `api/events.py`, the issue gets fixed, which means it has something to do with these helper functions.

```python
        if data.get('original_image_url') and data['original_image_url'] != event.original_image_url:
            try:
                uploaded_images = create_save_image_sizes(data['original_image_url'], 'event-image', event.id)
            except (urllib.error.HTTPError, urllib.error.URLError):
                raise UnprocessableEntity(
                    {'source': 'attributes/original-image-url'}, 'Invalid Image URL'
                )
            data['original_image_url'] = uploaded_images['original_image_url']
            data['large_image_url'] = uploaded_images['large_image_url']
            data['thumbnail_image_url'] = uploaded_images['thumbnail_image_url']
            data['icon_image_url'] = uploaded_images['icon_image_url']
```

**Comment by bhaveshAn** [comment]
There is a need to create a asynchronous celery task concerning this block.

**Comment by CosmicCoder96** [comment]
@bhaveshAn If you are willing to do it, it sounds good, please let me know ASAP, else I will be removing it for now, as it's a direct blocker to creating an event.
