### ISSUE TITLE
Post request to checkEmail returns opposite result

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5425]
**Describe the bug**

post request to checkEmail returns inverted results, i.e, if the user's email id is present, it returns false, and if absent, then it returns true

**To Reproduce**
1. open postman
2. make a post call to `/v1/users/checkEmail`
3. if the user is in the database, the response will be false, otherwise true

**Expected behavior**

the `result='False'` and `result= 'True'` statements are misplaced
![new post](https://user-images.githubusercontent.com/19776278/47063125-85fedd80-d1f7-11e8-9559-0d5a9ca0053c.png)

**Additional context**

Filing a PR for this one

**Comment by CosmicCoder96** [comment]
No, the responses are correct. If you read the lines above, you will notice that it asks if the email is available for use , if it exists in the database, it is not. Hence the response False is correct in this case and vice-versa.
