### ISSUE TITLE
OAuth2 authentication with google account fails (500)

### ISSUE THREAD

**Issue by 2DSharp** [fossasia/open-event-server#5429]
**Describe the bug**
While trying to create an event, and create an account with my gmail account, the process failed with an internal server error (500).

**To Reproduce**
1. Go to eventyay.com
2. Click on Create an event
3. Select Google+ for logging in.
4. Choose the account.
5. See the error.

**Expected behavior**
Should take me to the dashboard.

**Additional details (please complete the following information):**
 - OS: Ubuntu

**Comment by CosmicCoder96** [comment]
The issue needs to be fixed here, since Eventyay is running through the legacy codebase: fossasia/open-event-legacy#67
