### ISSUE TITLE
Error while running requirements.txt

### ISSUE THREAD

**Issue by cursed4ever** [fossasia/open-event-server#5448]
**Describe the bug**

One of the header files that is 'openssl/aes.h' could not be found when running requirements.txt using pip. I think this error is native to macOS, as apple dropped OpenSSL headers recently. 

**To Reproduce**
1. Run pip install -r requirements.txt
2. Everything installs as usual.
3. But finishes with throwing error that "<openSSL/aes.h> file could not be found"

**Additional details (please complete the following information):**
 - OS: MacOS Sierra
 - Python Version 3.7
 - Pip Version 18.1
 - Virtualenv Version 16.1

**Comment by cursed4ever** [comment]
For all those who are also facing this issue i have got a small hack. This is native to macOS High Sierra.
please see this link https://tutorials.technology/solved_errors/1-OSX-openssl_opensslv_h-file-not-found.html

**Comment by cursed4ever** [comment]
I think some one should add this to the documentation.

**Comment by war-turtle** [comment]
I want to do this task.
