### ISSUE TITLE
Action names are incomplete in Sessions API blueprints

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5451]
**Describe the bug**

Name of actions for `List Sessions under an Event`, `List Sessions under a Track`, `List Sessions under a Microlocation`, `List Sessions under a Session Type`, and `List Sessions under a Speaker` are all written as `List Sessions`

**Expected behavior**

Each should have a unique action name

**Screenshot**
![session](https://user-images.githubusercontent.com/19776278/48597289-16f5df80-e983-11e8-840d-206ff82ebbb2.png)

**Additonal Context**
I'm working on it!

**Comment by poush** [comment]
@prabhupant are you working on this? Let me know, I can assign you this.

**Comment by prabhupant** [comment]
@poush yeah i'm working on it :+1:
