### ISSUE TITLE
Docker Container Tasks

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5454]
These are tasks for improving container support for automatic deployment

When running docker-compose up, image is built on each change in requirements or other targets. Also, database user, name, and password are exposed directly. Using current docker-compose is not suitable for production as it is mainly used for quick development environment setup. However, there are several things that can be done to create a docker-compose-prod.yml which has production specific settings as an override.

- [x] Build and push docker image on each build with proper tags.
~~- [ ] Create a production version of docker compose file with option to configure secrets through files ignored in git~~
- [x] Improve current docker image by using multi-stage builds, removing redundant postgres initializer script, etc

# Docker Image
There will be semantic versioning of the project and development builds will be tagged with `development` and master builds will be tagged with `latest` along with the corresponding version. This will be used in the production compose file instead of building each time. This task can be broken into sub-tasks

**Comment by ajit2704** [comment]
@iamareebjamal  I would like to work on it

**Comment by iamareebjamal** [comment]
Which task, choose one.

**Comment by ajit2704** [comment]
I will go with first one.

**Comment by iamareebjamal** [comment]
Please create a new issue describing the first one and list this issue as its parent and you can start working on it

**Comment by iamareebjamal** [comment]
Image is already configured to be built on each push. Just need to configure tags correctly

**Comment by chetanyachopra** [comment]
hey hi @iamareebjamal i am up for 2nd task ie production ready docker-compose  should i start with making issue?

**Comment by iamareebjamal** [comment]
Yes, please go ahead

**Comment by iamareebjamal** [comment]
Second option not needed right now, so closing

It is recommended to copy the docker-compose file elsewhere and modifying it accordingly
