### ISSUE TITLE
Synchronous image download on event creation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5457]
**Describe the bug**
On creating an event, images are synchronously downloaded and resized which contributes to slow process of event creation. 
**To Reproduce**
1. Give original image URL to a large email and send a request to create and event

**Expected behavior**
Images should be downloaded and resized asynchronously

**Comment by iamareebjamal** [comment]
Implementation details are open for discussion as to which URLs to show while images are downloaded and clients will most probably eagerly fetch the data and cache it. So it should be a robust solution which does not enforce clients to refetch the event resource from server to get resized images

**Comment by CosmicCoder96** [comment]
This task was made a celery task to handle image resizing asynchronously.
