### ISSUE TITLE
Build and push docker image on each build with proper tags

### ISSUE THREAD

**Issue by ajit2704** [fossasia/open-event-server#5460]
There need improvement in docker image building with proper tags & updates of each  build. referring to first task of issue

-  #5454 Docker Container Tasks
**You working on it?**
yes

**Comment by iamareebjamal** [comment]
What;s the status?

**Comment by iamareebjamal** [comment]
This is already done, just tags need to be configured correctly

**Comment by iamareebjamal** [comment]
Already happening for a long time
