### ISSUE TITLE
Adding dredd tests for panel permission

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5467]
**Is your feature request related to a problem? Please describe.**

Add dredd tests for panel persmission
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I'm working on it!

**Comment by iamareebjamal** [comment]
@prabhupant Ideally, the case for issues with parent issue is to:

- Link the parent issue in child issue
- Only create child issues when the PR is read to be sent

Second point is necessary, or else the issue tracker will be flooded with child issues with no PR

**Comment by prabhupant** [comment]
@iamareebjamal ok. I am sending the PR right now
