### ISSUE TITLE
Completing tests for event role permissions

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5471]
**Is your feature request related to a problem? Please describe.**

completing the to-dos for writing event role permissions hooks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I'm working on it

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-server/blob/26f9734d0c13adc4a0fab108e13a666d2ee6233a/tests/hook_main.py#L2672
it is already done.
