### ISSUE TITLE
Settings don't refresh on PATCH

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5496]
**Describe the bug**
Settings are cached in memory and never again fetched from DB, even when they are patched. 

- Refresh settings on PATCH request

Secondly, if someone edits settings from DB, there is no way to refresh them. Call for discussion if this should be left that way. Cache should be expired after a period of time, or there should be an endpoint to explicitly refresh in memory settings

**Comment by iamareebjamal** [comment]
@poush @CosmicCoder96 What are your views on the second problem?

**Comment by mrsaicharan1** [comment]
Is this error still occurring? Would like to look into fixing this as this might be a priority in some cases.

**Comment by iamareebjamal** [comment]
I've fixed the bug. The issue is open to discuss the second point

**Comment by mrsaicharan1** [comment]
@iamareebjamal IMO, creating an endpoint would be much feasible as the user can click a button and get the updates instantaneously.

**Comment by mrsaicharan1** [comment]
Otherwise, he would have to wait for the cache cycle-time to finish.

**Comment by iamareebjamal** [comment]
This option does not concern the user. But yes, I agree there should be an endpoint for admins to refresh the settings

**Comment by divyam-goel** [comment]
I guess both the things should be there. Incase user makes an update but then forgets about refreshing the cached settings, it will automatically happen once the cache expires. Moreover, if the user wants the settings to immediately be reflected then he/she can simply hit the refresh button.

**Comment by Haider8** [comment]
@iamareebjamal can i work on adding a endpoint to refresh settings
