### ISSUE TITLE
Set up logging correctly

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5498]
Currently, logging is hardcoded in the app and never really used. Logging should be used almost on every action with proper label as:

- trace
- debug
- info
- warn
- error

Right now, logger is hardcoded to show ERROR only. This needs to be configurable through the command line. 

Also, I think default should be `INFO` or even `DEBUG` for the app itself and warn for other 3rd party libraries.

**Comment by makkoncept** [comment]
Hi @iamareebjamal, I would like to work on this issue. 
I am new to logging for a big code-base, so I have to do some research.  Can you please provide some useful links.

**Comment by prateekj117** [comment]
@makkoncept Sorry, but I am already working on this issue.

**Comment by prateekj117** [comment]
@makkoncept Feel free to take this issue.

**Comment by Divya063** [comment]
Can I work on this issue?

**Comment by uds5501** [comment]
@iamareebjamal Can multiple people work on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by uds5501** [comment]
@iamareebjamal Can I include logging.info in ical and pentbar exports?

**Comment by iamareebjamal** [comment]
Add logs in auth module. Signing In, Signing Up, Verification Token Generated, etc

**Comment by uds5501** [comment]
@iamareebjamal Okay.

**Comment by iamareebjamal** [comment]
One of you can add logging config of sentry. Create a sentry account and configure the app to send logging.warning and above to sentry and verify

**Comment by prateekj117** [comment]
@uds5501 I can work on the sentry part, you work on Auth. Cool?

**Comment by uds5501** [comment]
@prateekj117 Sounds good enough :+1:

**Comment by prateekj117** [comment]
@uds5501 Will be doing both.

**Comment by GeniusLearner** [comment]
I  am a newcomer and want to resolve this issue.

**Comment by prateekj117** [comment]
@GeniusLearner Go ahead.

**Comment by imrahul361** [comment]
can i try working on it?

**Comment by hkbiet** [comment]
Is it done ?

**Comment by EkanshMangal** [comment]
Hello Sir, Is any issue left?

**Comment by iamareebjamal** [comment]
There can 100s of issues open. So yes, many issues left. Please comment on only those which you think you can solve. Don't spam

**Comment by webmaster-sys** [comment]
any issue left?

**Comment by iamareebjamal** [comment]
Literally 136 issues left

**Comment by pradeeptrain9** [comment]
im new canu assign it to me

**Comment by tuchang** [comment]
Is it done? any tasks about it left?

**Comment by adityababar07** [comment]
iam on to it
