### ISSUE TITLE
Create Production specific dock-compose setup

### ISSUE THREAD

**Issue by chetanyachopra** [fossasia/open-event-server#5510]
create  docker-compose suitable for production environment and also there is need of hiding all secrets in a file that will be environment specific

**Approach**
will add all credentials  ie   `(username, passwords)` to `.env` that will be environment specific 

i think it will be the best approach feel free to share  better solution down here 

reffering to task in #5454 

- **working on it ?** 
yes

**Comment by iamareebjamal** [comment]
/remind me to review this in 2 days

**Comment by chetanyachopra** [comment]
resolved !!
