### ISSUE TITLE
Use ActivityPub to allow inter-operation with other free code events servers

### ISSUE THREAD

**Issue by strypey** [fossasia/open-event-server#5518]
There are a number of free code projects who aim to build a federated replacement for the event functionality of datafarms like FB and MeetUp. These include [Calendar-social](https://gitea.polonkai.eu/gergely/calendar-social/issues/122), [GetTogether](https://github.com/GetTogetherComm/GetTogether/issues/60), 
[Human Connection](https://github.com/Human-Connection/WebApp/issues/318), and [Mobilizon](https://framagit.org/framasoft/mobilizon). They are all either using, or considering using, the [ActivityPub](http://activitypub.rocks/) standard for federation between instances of their own software. With the right tweaking this will also allow federation with instances of each other's software too. My suggestion is that Open Event consider implementing support for AP, so it can inter-operate with these and other federated event apps.

Ideally, an events extension to AP will be specified as a result of this work, which other implementers can follow to inter-operate, without having to liaise with other projects. Such an extension could specify specific ways of using of existing protocols like CalDAV, and formats like iCal/ vCal, to build federated event apps on top of the AP base standard.

**Comment by mariobehling** [comment]
This is cool, but out of scope currently. In a perfect world would be great, if someone could take this up when such issues are opened. The team is still working on core features. Closing it therefore.

**Comment by aschrijver** [comment]
ActivityPub support would be quite interesting. If you ever plan to review this issue, then you can check this [ActivityPub Application Watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) to a good overview of what apps are (being) developed in the Fediverse landscape.
