### ISSUE TITLE
Email address verification mail is not being sent

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#5521]
**Describe the bug**
Did not receive any mail after new sign up.

Tried resending the mail using https://open-event-api-dev.herokuapp.com/v1/auth/resend-verification-email.
Still no mail was sent although the response was:
```
{
    "message": "Verification email resent"
} 
```

**To Reproduce**
Create a new account. No verification mail will be received.

**Expected behavior**
A verification mail should have been sent to the email address.

**Comment by iamareebjamal** [comment]
I tried it just now and got it

**Comment by iamareebjamal** [comment]
/remind me to close this in 1 day

**Comment by ShridharGoel** [comment]
Another user faced a similar issue https://github.com/fossasia/open-event-orga-app/pull/1447#issuecomment-455850568

**Comment by iamareebjamal** [comment]
You mentioned that this was eventyay server. It's dev server issue. eventyay.com is sending email correctly. Dev server indeed has an issue of not sending emails

**Comment by ShridharGoel** [comment]
@iamareebjamal Please remove the invalid label if this issue exists.

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Do you have access to the dev instance of server?

**Comment by iamareebjamal** [comment]
@CosmicCoder96 ping

**Comment by CosmicCoder96** [comment]
@iamareebjamal yes, I will register you as an admin.

**Comment by iamareebjamal** [comment]
Fixed
