### ISSUE TITLE
Update docs on Events end point to accomodate additional fields  for Front end's sidebar

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5529]
The frontend facilitates all the public aspects of an event through a side menu as shown below.
![image](https://user-images.githubusercontent.com/17252805/51509651-e2941900-1e34-11e9-9e09-cfcfccca1ef0.png)

However, it is desired to only show a menu item, if it's corresponding entries exist. For instance, display the item sessions, if sessions are present, display speakers if speakers are present.  Display schedule if the schedule is published etc.

To achieve this functionality the frontend has to make a call to the corresponding endpoint to check if sessions or speakers exist, but that results in sending 100s of network requests for data, user is probably not going to view anyway. 

Thus there needs to be an api endpoint or property values in the event schema itself, which tells if **sessions**,  **speakers** are present for a given event. Current production environment has revealed that querying sessions and speakers results in a significant overhead.

**Comment by CosmicCoder96** [comment]
@iamareebjamal What would be the correct approach to rectify this situation.

**Comment by iamareebjamal** [comment]
An event info endpoint which tells the status and information about what is present in the event in form of booleans

**Comment by apoorvkhare07** [comment]
Is this issue up for taking ? 
Would like to work on it.

**Comment by CosmicCoder96** [comment]
@apoorvkhare07 go ahead.

**Comment by CosmicCoder96** [comment]
@apoorvkhare07 I have added the fileds in https://github.com/fossasia/open-event-server/pull/5560
As a beginner's issue perhaps you can instead help with updating the docs corresponding to this change. I have modified the issue title.

**Comment by iamareebjamal** [comment]
@CosmicCoder96 This will slow down the list queries by a lot. This should be handled by a separate relationship to event

**Comment by CosmicCoder96** [comment]
@iamareebjamal okay, will make a new PR.

**Comment by prateekj117** [comment]
@iamareebjamal @CosmicCoder96 May I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by kushthedude** [comment]
@iamareebjamal @CosmicCoder96 As of present , Since when `Session and Speakers` and other data is not present and we need to query the DB to check for their presence , I have a simple approach for the following , As the `Bools` introduced by @CosmicCoder96 in the above PR, We can do the following, Whenever a speaker is confirmed , just toggle the value of the present `bool` and we can just check the following bool to make sure if the following tab needs to be displayed on the events sidebar or not .
What you guys think ?

**Comment by iamareebjamal** [comment]
I have implemented it in frontend already in an efficient way https://github.com/fossasia/open-event-frontend/pull/4848 https://github.com/fossasia/open-event-frontend/pull/5171
