### ISSUE TITLE
Adding sessions seed data for development 

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-server#5535]
**Parent Issue**
#4477 

**Is your feature request related to a problem? Please describe.**
According to the parent issue 4477, this aims to add seed data of sessions for development

**Describe the solution you'd like**

adding seed data for sessions

**Additional context**

i'm working on it

**Comment by iamareebjamal** [comment]
Closing this as there is no clear way a seed data can be created, eg, what fields should be used? The factories also don't reuse existing models but recreate relationships. If needed, will reopen
