### ISSUE TITLE
Billing Information: Add fields to the order-form

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5543]
**Describe the bug**

For solving issue https://github.com/fossasia/open-event-frontend/issues/1939 in the frontend, we need to add fields to order-form. Currently, the info is not getting saved in the model

**Expected behavior**

On submitting the form, info should be saved in database

**Additional Context**
I'm working on it

**Comment by mrsaicharan1** [comment]
I'll add the fields in the scheme asap.

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi What fields do you need to add exactly? I've added street address and changed the existing ones which had to be changed to optional and mandatory.

**Comment by mrsaicharan1** [comment]
I can see that the fields are added already in the ticket_holders form. I've changed some of the fields from mandatory to optional as per records.
