### ISSUE TITLE
Server: Implement Ticketing Process as in Eventyay Version 1

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5546]
In Eventyay V1 and Eventbrite users can get tickets without logging in. If they already enter their email and pay through a registered way (e.g. credit card, paypal), they don't have to login. New users will automatically receive an email after they buy a ticket. In that email is the account information. Existing users will have their ticket automatically added to their account even if they did not log in. 

Please research the process on Eventyay V1 and Eventbrite and change the process in Eventyay version 2 accordingly.

Corresponding frontend issue: #https://github.com/fossasia/open-event-frontend/issues/1994

**Comment by 16608770879** [comment]
leva起来

**Comment by YogeshSharma0201** [comment]
Working on this issue.
