### ISSUE TITLE
Add a new class of email for non logged in users placing an order.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5549]
In cases where non-registered users place an order, an account for them will be created automatically with a random system generated password. The welcome mail to them should be different from the one which is sent when they register using a password. This welcome mail should include a reset password link, with the instructions to the user.

Parent issue #5546

**Comment by nkkumawat** [comment]
hi, @CosmicCoder96 can I try this?

**Comment by CosmicCoder96** [comment]
@nkkumawat Sure, go ahead.

**Comment by CosmicCoder96** [comment]
@nkkumawat Any updates?
