### ISSUE TITLE
Uploaded Presentations still stored in Google Cloud instead of local system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5555]
The previously uploaded presentation slides are still stored in Google cloud instead of the local volume.

![screenshot from 2019-01-23 18-39-29](https://user-images.githubusercontent.com/1583873/51625740-3f2f2b00-1f3e-11e9-911a-38afc9f0ace7.png)

**Comment by uds5501** [comment]
Working on it

**Comment by prateekj117** [comment]
@mariobehling @iamareebjamal I would like to work on this issue.

**Comment by iamareebjamal** [comment]
This is a development issue. Not related to code AFAIK

**Comment by CosmicCoder96** [comment]
fixed now since all the data inside gcloud has been moved to storage.eventyay.com
