### ISSUE TITLE
sign in with google isn't working 

### ISSUE THREAD

**Issue by manisaiprasad** [fossasia/open-event-server#5562]
when you click on sign in with Google it just shows "We seem to be having some issues on our side."

**Additional details (please complete the following information):**
 - OS: MacOS

**Comment by prateekj117** [comment]
I would like to work on this issue.

**Comment by manisaiprasad** [comment]
even i would like to work on this issue

**Comment by prateekj117** [comment]
@manisaiprasad Ok, go ahead.

**Comment by ajitesh-30** [comment]
@manisaiprasad  Any updates on this issue as the problem still exists.

**Comment by prateekj117** [comment]
@iamareebjamal Can I take this up?

**Comment by iamareebjamal** [comment]
Not a priority right now
