### ISSUE TITLE
Co-organizer cannot add sessions/speakers and is not listed on dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5579]
The co-organizer isn't able to add session/speakers. It shows a loading icon eternally.

![screenshot from 2019-01-21 16-08-21](https://user-images.githubusercontent.com/1583873/51482466-cc378000-1d96-11e9-941c-1e341c1e4005.png)

https://r6---sn-i5heen7l.googlevideo.com/videoplayback?id=6602b1cd8654edc0&itag=18&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-i5heen7l&ms=nxu&mv=m&pl=23&sc=yes&ei=3t9FXOOeGYf41wKb7rWIAg&susc=ph&app=fife&mime=video/mp4&dur=12.051&lmt=1548082866954668&mt=1548083131&ip=77.183.28.142&ipbits=0&expire=1548090366&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,susc,app,mime,dur,lmt&signature=45C03F8508F45A8E5C9CB98C1209028D8FD44070E449036680C0C524B79E669B.77DDF327D82D8B205AB4FB8EEB8014C94177D5166E093280702637869802B096&key=us0

**Comment by uds5501** [comment]
@CosmicCoder96 @mariobehling @iamareebjamal  this issue can be closed. I can easily create sessions by co-organizer access and FWIW, here is a picture which shows Co-Organizers being listed as expected

![image](https://user-images.githubusercontent.com/21087061/54092765-1b248d80-43b6-11e9-9de4-524e4d5791bf.png)

**Comment by CosmicCoder96** [comment]
yeah it started working when I refactored the role invites API.
