### ISSUE TITLE
Email: New Session Proposal does not provide correct link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5581]
The proposal email does not provide correct link, e.g. it is: https://eventyay.com/events/598/sessions/5201

![screenshot from 2019-01-23 17-43-00](https://user-images.githubusercontent.com/1583873/51622223-700b6200-1f36-11e9-9d5f-a5fc76c63c16.png)

**Comment by uds5501** [comment]
Working on this
