### ISSUE TITLE
api/auth.py: Implement the OAuth login using the requests-oauthlib library

### ISSUE THREAD

**Issue by Akhelesh** [fossasia/open-event-server#5583]
**Describe the bug**
The current implementation of the auth.py module uses requests library to make calls to the API vendors. The project already has the requests-oauthlib dependency which is rarely used but is a better solution. This will help keep the code consistent among the different vendor requests.

**Expected Behaviour**
Use requests-oauthlib instead of requests library

**Additional context**
I am working on it.

**Comment by divyam-goel** [comment]
Can I work on this issue?
