### ISSUE TITLE
Implement Facebook OAuth using flask_dance

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5592]
Third party authentication using Facebook is already implemented. We should implement it using flask_dance as it is being for other OAuth providers as well.

**Additional context**
I am working on this issue

**Comment by divyam-goel** [comment]
@prateekj117 are you still working on this issue? If not, I'd be interested to work on it.

**Comment by prateekj117** [comment]
@divyam-goel Yaa, working on it.

**Comment by prateekj117** [comment]
@iamareebjamal I think we should close this.
