### ISSUE TITLE
Make speaker image visible

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5602]
**Describe the bug**
Speaker image is not visible on session page
**To Reproduce**
1. Go to 'Sessions' section for an event
2. See error

**Expected behavior**
Should show the image as a thumbnail rather than a full resolution image(URL should be in the model)

**Additional context**
Related to https://github.com/fossasia/open-event-frontend/issues/2027
Working on this

**Comment by Haider8** [comment]
@mrsaicharan1 since it's been 19 days, can i work on this issue now

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by CosmicCoder96** [comment]
No, this is not a valid issue, speaker image resizing was to be done as a celery task which was already completed in #5595 
The frontend should be able to access all the images now.
