### ISSUE TITLE
Ticket PDF: Security Issue, can be accessed by anyone

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5608]
The ticket PDF for events can be accessed by anyone who can find out the link, e.g. see https://api.eventyay.com/static/media/attendees/tickets/pdf/6ae42516-0a03-4436-b2a6-8a60f6a2b16d/QkJ0VHpPUX/ae067598-2896-4579-b4d9-8d5fa8a34e01.pdf

Expected should only be possible to open it from the actual account.

**Comment by mrsaicharan1** [comment]
Would like to work on this.

**Comment by mrsaicharan1** [comment]
I've closed the previous PR corresponding to this for clarity reasons. @CosmicCoder96 Will it be credible enough to check if the ticket holder is the same person who's accessing the link(writing conditionals in Jinja)?

**Comment by iamareebjamal** [comment]
No, the access needs to be controlled from API side.

**Comment by mrsaicharan1** [comment]
@iamareebjamal Alright.
