### ISSUE TITLE
Unable to login to the Admin Panel.

### ISSUE THREAD

**Issue by divyam-goel** [fossasia/open-event-server#5614]
**Description:**
When we try to login to admin panel, even if the credentials belong to super-admin, it returns "Credential incorrect"

**Steps to reproduce the behavior:**
1. Go to 127.0.0.1:5000/admin
2. Enter the admin credentials
3. Click on login button
4. See error "Credential incorrect"

**Expected Behaviour:**
It should login the user to the admin panel if credentials are correct and the user is an admin.

**Screenshots**
![error](https://user-images.githubusercontent.com/32808710/52912510-5d3b4180-32d8-11e9-93e6-86843c8f6fb4.png)

**Comment by mrsaicharan1** [comment]
Will work on this and fix it up.

**Comment by divyam-goel** [comment]
@mrsaicharan1  I wanted to work on this issue.

**Comment by mrsaicharan1** [comment]
Go ahead :)
