### ISSUE TITLE
Admin sales shows unexpected error occurred when orders are None

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5616]
**Describe the bug**

**To Reproduce**
1. Go to 'Admin sales section of admin panel'
2. See error

**Expected behavior**
Should show correct order info

**Screenshots**
![screenshot from 2019-02-18 10-50-16](https://user-images.githubusercontent.com/25197147/52933563-c7f08980-3379-11e9-9e69-054233a5bdd7.png)

**Stacktrace**

    'sales_total': sum([o.amount for o in orders if o.status == status]), TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Additional context**
Working on this.

**Comment by mrsaicharan1** [comment]
Would like to confirm if it's a local error or a site-wide error.

**Comment by uds5501** [comment]
@mrsaicharan1 I have created a fresh database and created no event so far. The Page is loading fine
![image](https://user-images.githubusercontent.com/21087061/52996232-f4240d00-3442-11e9-8edf-bf0e95d4a2dd.png)

**Comment by mrsaicharan1** [comment]
Hmm. Seems to be a local database entry error. Will close it in favour of this.
