### ISSUE TITLE
Add isBillingEnabled to order object

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5617]
**Is your feature request related to a problem? Please describe.**

In redesigning the order review page, we need to know is billing was enabled for that particular order or not
Currently there is no way to know this.

**Describe the solution you'd like**

Adding `isBillingEnabled` field to the `order` can allow us to get this info

**Additional context**

Working on it

**Comment by iamareebjamal** [comment]
Billing enabled for a particular order?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal yes. Please refer to discussion here - https://github.com/fossasia/open-event-frontend/issues/2047#issuecomment-464494518
