### ISSUE TITLE
Events list based on location.

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-server#5652]
**Is your feature request related to a problem? Please describe.**
I want to suggest user similar events in open-events-android app based on searchable location of the event he is currently viewing.

**Describe the solution you'd like**

I will pass event-identifier of the event user is currently viewing and want a list if events which include the searchable location of the event whose id is sent.

Something like this *event-topics/{id}/events?include=event-topic*, here events with event-topic which includes the event topic of passed event are returned.

**Comment by uds5501** [comment]
I would like to work on it post completion of #5651 , meanwhile if anyone wants to take it up, feel free to do so

**Comment by prateekj117** [comment]
@uds5501 I will work on it after Insta Oauth gets done.

**Comment by pnijhara** [comment]
Can I work on this issue.

**Comment by prateekj117** [comment]
@pnijhara Go ahead.

**Comment by mrsaicharan1** [comment]
I'd like to take this issue as it's been inactive for quite a long time.

**Comment by uds5501** [comment]
@mrsaicharan1 go ahead

**Comment by mrsaicharan1** [comment]
@angmas1 Just to make it a bit more perceivable, do you want it for a specific end-point or only event-topics? The aforementioned solution is a bit unclear.
Also, isn't this possible right now?
e.g Sending a GET request to `v1/event-types/1?includes=event.location`

**Comment by angmas1** [comment]
I found a work around for this so I don't need this anymore
