### ISSUE TITLE
Make discount/promotional code case-insensitive

### ISSUE THREAD

**Issue by dhsgisc** [fossasia/open-event-server#5653]
**Is your feature request related to a problem? Please describe.**

Users get invalid discount/promotional code error because it is currently case-sensitive.

**Describe the solution you'd like**

It will be a better user experience if we make the discount/promotional code case-insensitive.

**Describe alternatives you've considered**

**Additional context**

**Comment by shreyanshdwivedi** [comment]
@dhsgisc are you working on this? I would like to take this up

**Comment by dhsgisc** [comment]
pls be my guest mr @shreyanshdwivedi :)

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar I already made the changes on my local but couldn't make a PR due to my busy schedule.

**Comment by Anupam-dagar** [comment]
@shreyanshdwivedi is it okay if I keep my PR open? I missed out on the claim part here.

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar it's ok. Please take care for next time

**Comment by Anupam-dagar** [comment]
@shreyanshdwivedi  sure :tada:

**Comment by prateekj117** [comment]
@Anupam-dagar I see you closed the PR, are you still working on this issue?

**Comment by shreyanshdwivedi** [comment]
@prateekj117 I think I was already in the queue :)

**Comment by Anupam-dagar** [comment]
@shreyanshdwivedi @prateekj117 I am updating my PR. Please look for other issues. :smile:

**Comment by kushthedude** [comment]
@iamareebjamal @shreyanshdwivedi I think case sensitive discount code is perfect , Case Insensitivity reduces the security factor , and finally its a promotional code which should be case sensitive . Should close this i suggest

**Comment by prateekj117** [comment]
@shreyanshdwivedi Would be working on this issue.

**Comment by kushthedude** [comment]
Why do we even need insensitivity in discount codes? @iamareebjamal @shreyanshdwivedi

**Comment by iamareebjamal** [comment]
There are a lot of reasons. Mainly because we don't want someone to create codes like `summit19` and `suMMit19` and `SUMMit19` and `SUMMIT19` and have them behave differently

**Comment by kushthedude** [comment]
Code Sensitivity always provides an additional security factor on the codes . And as it is related to payments , Sensitivity should be given priority .

**Comment by iamareebjamal** [comment]
It provides annoyance and no security. Tomorrow someone will complain he/she got 50% off when it was written 75% off just because he didn't factor in case sensitivity. Or the discount code is not working altogether. Please back your claim with proof how it provides security?

**Comment by prateekj117** [comment]
@iamareebjamal May I work on this?

**Comment by iamareebjamal** [comment]
Go ahead
