### ISSUE TITLE
Register doesn't recognises 'string@string' as valid Email

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5660]
**Describe the bug**

Register user produces an unexpected error upon registering with email of type 'string@string'.

**To Reproduce:**
Steps to reproduce the behaviour:
1.)Go to'/Register'.
2.)Register with email of type 'string@string'
3.)See the error

**Expected behavior**
It should recognise it has an email as 'string@string' is a valid email format.

**Additional details (please complete the following information):**
 - OS: MacOS
 - Python Version: 3.7

**ScreenShot:**
<img width="1165" alt="screenshot 2019-03-05 at 1 25 42 pm" src="https://user-images.githubusercontent.com/44091822/53789440-5fdd9e00-3f4a-11e9-8b0b-f7558f337506.png">

**Comment by kushthedude** [comment]
@uds5501 i was trying to find where the rules of email are specified but i was not able to find as everywhere its just using email as an attribute. Any help?

**Comment by uds5501** [comment]
@kushthedude In the server, authorisation is being handled by `flask_login` and maybe this 422 error is from there only.

```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "status": "422",
            "title": "Validation error",
            "source": {
                "pointer": "/data/attributes/email"
            },
            "detail": "Not a valid email address."
        }
    ]
}
```
This is the error trace that I am getting and yeah, this is not being handled by the project so it must be `flask_login` . Kindly check the documentation for the same

**Comment by iamareebjamal** [comment]
This has surfaced recently. Even normal emails are denied

**Comment by kushthedude** [comment]
@iamareebjamal Can i work on it?

**Comment by iamareebjamal** [comment]
First work on normal email validation failure such as 'test@example.com'

**Comment by mrsaicharan1** [comment]
@kushthedude Still working on this? Would like to take it up if you're involved in other bugs.

**Comment by kushthedude** [comment]
I am still working for it😅

**Comment by angmas1** [comment]
Still not working, I think it's a major bug. Please resolve this on priority.

**Comment by shreyanshdwivedi** [comment]
@kushthedude are you working on this? Please resolve this asap or let other contributor try :)

**Comment by kushthedude** [comment]
@shreyanshdwivedi i completely forgot about it , if anyone wants to takeover please be my guest as i have not started doing anything on it

**Comment by shreyanshdwivedi** [comment]
Okay. I'm working on it then

**Comment by kushthedude** [comment]
Btw @shreyanshdwivedi i did some ground work about it and found that this error is gettin causes by flask_login and i am afraid should we modify the external dependancy or not ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude if this is the case, I think @iamareebjamal can decide it. However I'll once take a look at it to find out the reason for this error

**Comment by iamareebjamal** [comment]
Not needed then. Will see if a customer support request comes. Closing. Still comment if you find anything @shreyanshdwivedi

**Comment by kushthedude** [comment]
Should i closw the issue than @shreyanshdwivedi @iamareebjamal
