### ISSUE TITLE
Deleted events stays in cache until refreshed

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5662]
**Describe the bug**

-Whenever you delete an event,A tooltip appears showing event is deleted.
-Event stays in cache until the page is refreshed.
**To Reproduce**
1. Go to '/Events/Live'
2. Try to delete an event.
3. Refresh the page .

**Expected behavior**

When a event is deleted , The page should be refreshed to remove the event from the list.

**Additional details (please complete the following information):**
 - OS: MacOS
 - Python Version: 3.7

**Additional context**

![](https://im.ezgif.com/tmp/ezgif-1-973451cbe205.gif)

**Comment by iamareebjamal** [comment]
How is this a server issue?

**Comment by kushthedude** [comment]
Sir,Should I move it to frontend issue ?

**Comment by kushthedude** [comment]
Sorry @iamareebjamal ,Without giving a second look at issue i instantly opened it here , will keep in mind from here.
