### ISSUE TITLE
User can create events in past dates

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5663]
**Describe the bug**

I can create an event with the duration in the past which should be (obviously) not allowed.

**To Reproduce**
![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/21087061/53887524-7bc76980-4048-11e9-87d3-99127a603152.gif)

**Expected behavior**

It should throw UnprocessableEntry error if event's start-date is set before current date

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu 16.04 LTS
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Working on it

**Comment by iamareebjamal** [comment]
Low priority. You may work on it but there are higher priority tasks which need to be done

**Comment by uds5501** [comment]
@iamareebjamal Sure, I would start working on the high priority ones first and maybe finish this one later!

**Comment by Haider8** [comment]
@uds5501 can i try to fix this until then ?

**Comment by uds5501** [comment]
@Haider8  go ahead
