### ISSUE TITLE
Travis:Failing tests for resized images

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5665]
**Describe the bug**
Below tests are failing in `tests_files`
     ERROR: Method to test create image sizes
     ERROR: Method to test create resized images
`urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Expected behavior**
Tests should pass

**Comment by mrsaicharan1** [comment]
![screenshot from 2019-03-07 14-52-28](https://user-images.githubusercontent.com/25197147/53952980-424e3700-40f8-11e9-94d0-b55f7f8f1e6f.png)
![screenshot from 2019-03-07 14-52-35](https://user-images.githubusercontent.com/25197147/53952983-437f6400-40f8-11e9-84c5-5b99c2aac332.png)

**Comment by iamareebjamal** [comment]
Since which PR did it start failing?

**Comment by mrsaicharan1** [comment]
#5658 I believe.

**Comment by iamareebjamal** [comment]
Doesn't make sense, tests passed on that PR. If that was the case they would have failed

**Comment by iamareebjamal** [comment]
Also, nothing related to authorization changed there

**Comment by mrsaicharan1** [comment]
My bad, I'll check what's causing this.

**Comment by mrsaicharan1** [comment]
@iamareebjamal Is it something wrong with the link(urllib isn't able to access) or is it something else?

**Comment by mrsaicharan1** [comment]
https://travis-ci.org/fossasia/open-event-server/builds/501947056?utm_source=github_status&utm_medium=notification

**Comment by mrsaicharan1** [comment]
Please correct me if I'm wrong,Travis started failing from that PR. But I dont' see why the test was failing. Will try testing it with another link
