### ISSUE TITLE
Facebook Login shows error in next.eventyay website

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5667]
![auth-issue](https://user-images.githubusercontent.com/31065687/54029183-90813a00-41cd-11e9-8540-8935372723ca.png)

**Comment by prateekj117** [comment]
Link related to issue - https://stackoverflow.com/questions/37001004/facebook-login-message-url-blocked-this-redirect-failed-because-the-redirect

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Who has access to the Facebook app settings?

**Comment by kushthedude** [comment]
Currently, the *FB Oauth* has been commented out as specified in https://github.com/fossasia/open-event-frontend/issues/2509

**Comment by mariobehling** [comment]
Out of scope currently.
