### ISSUE TITLE
Facebook Login doesn't work

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5668]
**Describe the bug**
When testing the website locally using API server also running locally, clicking on Facebook Login does not trigger anything. It doesn't show any pop-up or any error in logs or on the website.

**Expected behavior**
It should show a pop-up to ask permission for using our Facebook's info.

**Additional context**
Working on it.

**Comment by mrsaicharan1** [comment]
This is not an issue I believe. You need to set the OAuth keys for this to work.

**Comment by prateekj117** [comment]
@mrsaicharan1 Did that already. Plus, even if someone does not do that, the button shouldn't be unresponsive, it should have shown some error.

**Comment by iamareebjamal** [comment]
This should be in frontend

**Comment by prateekj117** [comment]
@iamareebjamal I think here we can discuss the implementation for the OAuth problem of Facebook. I have also opened an issue on the frontend regarding the same. 
https://github.com/fossasia/open-event-frontend/issues/2298

**Comment by iamareebjamal** [comment]
Ok. @mrsaicharan1 Can you please mention other people who were implementing other OAuth providers so that we can discuss?

**Comment by mrsaicharan1** [comment]
@uds5501 We can discuss regarding the Oauth issue here.

**Comment by kushthedude** [comment]
@mrsaicharan1 I would like to participate in workaround needed for the Oauth reconfiguration.
