### ISSUE TITLE
ubuntu failed to perforom step 4 of basic installation in docs 

### ISSUE THREAD

**Issue by Nightrider0098** [fossasia/open-event-server#5672]
after creating database and closing postgresql next step 'cp .env.example .env ' is giving error 
cp: cannot stat '.env.example': No such file or directory

**Comment by mrsaicharan1** [comment]
Please check this once again.  Might be a file path error on your system.

**Comment by iamareebjamal** [comment]
You're not in the correct directory. I'm closing the issue because it's not actually an issue but continue the discussion to get it resolved on your end
