### ISSUE TITLE
Super Admin is unverified user

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5675]
**Describe the bug**

Admin/Users shows the super admin to be unverified

**Expected behavior**

It should simply be verified!

![image](https://user-images.githubusercontent.com/21087061/54092850-4eb3e780-43b7-11e9-968d-d94040fe563b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Open for all!

**Comment by AnkurIngale** [comment]
I'll like to work on it.

**Comment by prabhupant** [comment]
@uds5501 This happens only when the super admin changes its email id. I don't think this is an issue as this ensures that the new email id entered is authentic by sending it a confirmation link. Views @CosmicCoder96 ?

**Comment by kushthedude** [comment]
@uds5501 This is not a issue as @prabhupant told this only happens when the super user has changed his **Email ID** 
<img width="757" alt="Screenshot 2019-03-25 at 3 37 29 AM" src="https://user-images.githubusercontent.com/44091822/54886573-5db69180-4eaf-11e9-8ad8-e91bc4d3e431.png">

**Comment by uds5501** [comment]
@kushthedude I have seen this behaviour in few more instances rather than just email changes.infact, any time when I have seen this behaviour take place, my admin email was untouched :) so I am still investigating this

**Comment by kushthedude** [comment]
@uds5501 This can be closed , I cant reproduce it now
