### ISSUE TITLE
Ticketing not enabled error message

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5684]
**Describe the bug**
Ticketing not enabled error message comes when an unverified user tries to register an event or someone tries to register the event without giving a location.

**Expected behavior**
Error Message should be more clear and helpful to the user.

**Additional context**
Working on it.

**Comment by mrsaicharan1** [comment]
What is the expected Error Message here?

**Comment by prateekj117** [comment]
@mrsaicharan1 Error message should give the detail why ticketing is not enables, like "User is unverified" or "You need to specify the location of the event", etc.
