### ISSUE TITLE
Link in email verification

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5685]
**Describe the bug**
The link for the email verification sent to the user starts with eventyay rather than next.eventyay and this has to be changed manually when accessing the link to verify the user.

**Additional context**
Working on it

**Comment by iamareebjamal** [comment]
Development configuration issue. @CosmicCoder96 can you please change the frontend URL in the admin settings?

**Comment by CosmicCoder96** [comment]
@iamareebjamal done.
