### ISSUE TITLE
Fix bug in start and end date

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-server#5694]
**Describe the bug**

Currently a user can choose the start/end date to be before the current date.
**To Reproduce**
1. Go to 'Create Event'
2. Click on 'Session & Speakers'
3. Scroll down to 'Call for speakers'

**Expected behavior**

User should not be able to select the start/end date before the current date.
**Screenshots**

![Screenshot 2019-03-15 at 6 35 42 PM](https://user-images.githubusercontent.com/31013104/54428794-29c1ca80-4751-11e9-9969-383817213a6c.png)

**Additional context**

I'm working on it.

**Comment by kushthedude** [comment]
@harsh-jindal Can i solve it if you have not made significant progress on it?

**Comment by iamareebjamal** [comment]
These are minor issues guys. Focus on bugs which prevent the system from being usable. These are not even bugs, these are enhancements

**Comment by kushthedude** [comment]
@iamareebjamal No problem!

**Comment by bhawesh96** [comment]
@harsh-jindal Looks like this issue can be closed here

**Comment by iamareebjamal** [comment]
Let it he open. Just focus on bugs

**Comment by kushthedude** [comment]
@bhawesh96 let the issue be open so that it can be worked upon later.

**Comment by uds5501** [comment]
@iamareebjamal Looks like this has been taken care of in #5686
