### ISSUE TITLE
Payment currency missing in admin sales api

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5697]
**Describe the bug**

`payment_currency` is missing in `discounted` and `events` of `admin_sales`. 

**Expected behavior**

`payment_currency` must be returned too

**Additional context**

Related to https://github.com/fossasia/open-event-frontend/issues/2316
Working on it

**Comment by iamareebjamal** [comment]
Why can't the payment currency of event be used?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal the data available at `/admin/sales` doesn't include event info. It only has the details returned by this api.
![Screenshot from 2019-03-20 17-13-27](https://user-images.githubusercontent.com/25428397/54681952-9f53df00-4b33-11e9-8216-6ef9ae337ee8.png)
