### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5711]
Need to update these dependencies on priority:

- marshmallow = ">=2.15.1"
- requests = ">=2.20.0"

**Comment by prateekj117** [comment]
@iamareebjamal Can I work on this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by pnijhara** [comment]
@iamareebjamal @prateekj117 Can I work on this issue?

**Comment by prateekj117** [comment]
@pnijhara Go ahead.
