### ISSUE TITLE
Logs are not being printed

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5722]
**Describe the bug**
Logs are not printed in the console

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@iamareebjamal In the pull request of setting up logging correctly, I set the level of app logs to be WARN. Logs were really helping out during development as they were telling which files are being executed and which endpoints are being accessed, so I think we should change it. Your views on this?

**Comment by iamareebjamal** [comment]
I don't think it's about the log level. It's just that flask request logger is missing from the dictconfig. Also, set default level to INFO

**Comment by prateekj117** [comment]
@iamareebjamal Running python manage.py db heads gives:
`Raven is not configured (logging is disabled). Please see the documentation for more information.
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "sync_events_elasticsearch" to job store "default"
Added job "cron_rebuild_events_elasticsearch" to job store "default"
Added job "send_after_event_mail" to job store "default"
Added job "send_event_fee_notification" to job store "default"
Added job "send_event_fee_notification_followup" to job store "default"
Scheduler started
6e5c574cbfb8 (head)
`

**Comment by kushthedude** [comment]
@prateekj117 Is it up for grabs?

**Comment by iamareebjamal** [comment]
PR is now reverted so this is working fine now
