### ISSUE TITLE
deletedAt for user is a readonly column and can not be changed 

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-server#5734]
**Describe the bug**
The admin should be able to restore the deleted users. So changing the value of deleted user from a date to null should be possible (only for an admin).

**Additional context**
Up for grabs

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 can I work on this?

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi go ahead.
