### ISSUE TITLE
Error when clicking forward on editing the created event.

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5737]
**Describe the bug**
After creating the event, when you edit the event again, you get a "Copyright error" or sometimes a "tax not found error".

**Expected behavior**

Event creator should be able to edit the event without any errors.

**Additional context**

Working on it.

**Comment by uds5501** [comment]
@prateekj117 this is a partially occuring error. not consistent at all.

**Comment by prateekj117** [comment]
@uds5501 Yaa, noticed that. But it seems like it was occuring due to event-copyright and event-tax only. So it might be the same issue. Will confirm that.

**Comment by kushthedude** [comment]
Cant reproduce , Any specific steps for it @prateekj117

**Comment by prateekj117** [comment]
@kushthedude If you are not sure if the error is reproducible or not, don't close the issue. Though I think the `tax not found` and `event-copyright` not found error don't exist anymore. @uds5501 Are you facing these issues?

**Comment by uds5501** [comment]
@prateekj117 it was recently resolved by @CosmicCoder96 in the frontend PR, don't worry

**Comment by kushthedude** [comment]
@prateekj117 I think this error could be due to some outdated dependancies , As of now the following issue is not reported , if you are still facing it Please tell the pattern or steps involved
