### ISSUE TITLE
translations download link for frontend 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5744]
**Describe the bug**

The translations download link needs to be stored 
**Linked to**
[PR](https://github.com/fossasia/open-event-frontend/pull/2445)
**Additional info**
Working on it

**Comment by mrsaicharan1** [comment]
@iamareebjamal Regarding the storage of the link for translations downloads on the frontend, could you please tell me which model should I be storing it at?

**Comment by iamareebjamal** [comment]
Why can't it be created on the fly?

**Comment by mrsaicharan1** [comment]
Alirght, so when should `url_for('download_translations')` be sent to the front-end ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by mrsaicharan1** [comment]
I just had one more doubt, when should it be sent while accessing the route?

**Comment by iamareebjamal** [comment]
I don't understand

**Comment by mrsaicharan1** [comment]
The link for downloading .po messages, at what point should it be sent if we are creating it on the fly?

**Comment by iamareebjamal** [comment]
Why can't it be created on frontend?

**Comment by mrsaicharan1** [comment]
https://github.com/fossasia/open-event-frontend/pull/2445

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Will better understand the backend flow here

**Comment by mrsaicharan1** [comment]
I guess it was supposed to be stored in one of the models or create a new model for admin. @CosmicCoder96 Your views?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Can you clarify if the link generated to download the zip file is dynamic and generated each time or is it a static link? If it's dynamic then you need to provide an endpoint to trigger the download on FE, if it's static it can be hardcoded on FE.

**Comment by mrsaicharan1** [comment]
the link isn't dynamic as I've kept the translations download logic under a static route `'/admin/content/translations/all`

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 
if it's a route then you can just do `this.get('loader').load('/admin/content/translations/all')` on the frontend using the `loader` service. Loader service automatically pre-fixes the rest of the API URL.
