### ISSUE TITLE
Error 404 should be returned when a normal user tries url "/admin"

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5758]
**Describe the bug**
Error Code 403 is returned which does give the idea of url of admin panel.

**Expected behavior**
Error Code 404 should be returned.

**Additional context**
Working on it.

**Comment by Anupam-dagar** [comment]
@prateekj117 Looking by the error code `403` is `Forbidden`, I guess it's correct only unless we want to explicitly hide the admin url.
