### ISSUE TITLE
Handling unauthenticated user orders for pre-registered users

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5760]
Currently, Orders API requires a JWT token in order to create an order. For users whose email address is not registered -- the frontend creates a new user and sends him the ticket along with a password reset link -- just like the legacy system.

However, pre-existing users are prompted to enter their password. The goal is to give even the pre-registered users the ability to place an order without logging in. The order appears in their account when they log in at a later stage.

@iamareebjamal Looking for feedback from you -- what would be the way to go on the server?

**Comment by iamareebjamal** [comment]
So, let's say I am unauthenticated. And I go to buy a ticket, enter my email which is already registered. And complete the payment, it should be added to my account without me entering the password.

Am I understanding it correctly?

In the end, if the ticket buyer's email is already registered, we place the order without the requirement of authentication?

**Comment by CosmicCoder96** [comment]
@iamareebjamal Yes, precisely.

**Comment by iamareebjamal** [comment]
- Have to make Order Endpoint open for unauthenticated user.
- Check if the email being used in order is registered
  - If not, "creates a new user and sends him the ticket along with a password reset link -- just like the legacy system."
  - If registered, use that and save the order under that user's name

I believe this will solve the issue.

Problems with this approach - I can buy tickets for you. Even if I have to pay, or I just buy free tickets using your email ID in ordering process, this is bad. Is this acceptable or we should add a verification for that, which obviously complicates the process

**Comment by CosmicCoder96** [comment]
@iamareebjamal Oddly enough Eventbrite allowed me to do that. I used incognito and just gave my pre-registered email while not logged in. This is weird --anyone can place orders for a registered account. Someone can purchase 100s of free tickets if we do this on Open Event.
I had a discussion with @mariobehling regarding this some time back. One possible solution is to allow a buyer to enter a pre-registered email and place order without authenticating only if the order is paid. For a free order, the user has to register. As someone would unlikely to pay for a fake order and it won't happen. 
@mariobehling Can you confirm which approach should we go ahead with.

**Comment by kushthedude** [comment]
> So, let's say I am unauthenticated. And I go to buy a ticket, enter my email which is already registered. And complete the payment, it should be added to my account without me entering the password.
> 
> Am I understanding it correctly?
> 
> In the end, if the ticket buyer's email is already registered, we place the order without the requirement of authentication?

@CosmicCoder96 If we implement this, Chances of spam may get high and mistake too, Let's say a user enters the Email of a preexisting user and he buys a paid ticket considering that he will get them but the person whose email he entered by mistake gets the ticket.
Another approach to this problem I have thought is that, if a preexisting user places an order there should be some sort of OAuth or Some kind of two-factor authentication. @iamareebjamal Your views?

**Comment by CosmicCoder96** [comment]
@kushthedude The point of the issue is to not make user authenticate before buying tickets to ease the buying process. And you are talking about two-factor authentication, that's more authentication. Eventbrite is a commercially successful platform which is able to manage this. Ease of purchasing increases the likelihood of a sale being made. We will make an additional field to confirm the email before allowing to place the order. If a user enters the wrong email twice, it's not in the scope of our discussion.

**Comment by kushthedude** [comment]
@CosmicCoder96 I see that its more practical approach but still we need to think about free tickets as you said. Else I think it's fine.
