### ISSUE TITLE
Super Users being created are non-verified

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5762]
**Describe the bug**

When a super user is being created by the following sequence, it is being created as unverified user.

**To Reproduce**
1. Keep a user Logged in
2. Stop the server
3. Make new user by `create_db.py`
4. Start the server
5. See the error

**Expected behavior**

The user being created should be verified.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Looking into it

**Comment by kushthedude** [comment]
@uds5501 But just asking if there is no need to create another superuser when you already have one so, Is this issue significant? 😕

**Comment by iamareebjamal** [comment]
Yes, there should be ability to add multiple super users

**Comment by kushthedude** [comment]
@iamareebjamal I tried to create a new superuser and now I cant access `admin\users\` and server log shows this : -
![image](https://user-images.githubusercontent.com/44091822/55869051-5c6db000-5ba3-11e9-95e1-474a18374fae.png)

**Comment by iamareebjamal** [comment]
data is not a dict, it's a list

**Comment by kushthedude** [comment]
<img width="1440" alt="Screenshot 2019-06-05 at 4 50 00 PM" src="https://user-images.githubusercontent.com/44091822/58952670-fae84d00-87b1-11e9-9fe3-38c5d6b91bdf.png">
@uds5501 Just created a super admin , Can you check again please ?

**Comment by kushthedude** [comment]
@uds5501 Please check , If it still persists on your local will re-open .
