### ISSUE TITLE
Translations zip file deletion(Celery task) not working

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5766]
**Describe the bug**
Translations donwloads as a zip file are generated properly but the deletion of the file as a celery task fails due to error given in the screenshot.

Reference: https://github.com/fossasia/open-event-frontend/pull/2445
![55771111-47b4ed80-5ab9-11e9-8fbe-d24649d19bc5](https://user-images.githubusercontent.com/25197147/55782349-b601ac00-5ac9-11e9-87c0-3228e9419a39.png)

**To Reproduce**
1. Go to 'Admin' Section
2. Click on 'Content tab'
3. Click on 'Download .po files'

**Expected behavior**
The deletion needs to happen properly. Adding to this, if we remove/comment the delete_translations code, the download works smoothly but the file must be removed as it shouldn't reside on the server at all.

**Additional context**
Working on it.

**Comment by mrsaicharan1** [comment]
@iamareebjamal @CosmicCoder96 I've tried using `delete_translation.delay(path_to_zip)`  and was able to proceed with the normal download. Do we need to have a countdown for this?

**Comment by iamareebjamal** [comment]
Yes, or else the file will be deleted before the download is complete

**Comment by mrsaicharan1** [comment]
@iamareebjamal When I use `apply_async` for the celery task, the above error occurs. What might be the problem?

**Comment by iamareebjamal** [comment]
There should be an assignment somewhere near

**Comment by mrsaicharan1** [comment]
@iamareebjamal @CosmicCoder96 The assignment error was occurring because apply_async was returning `celery.result.AsyncResult` whihc needed to be stored somehwere. Pushing a PR now as it is now fixed.
