### ISSUE TITLE
Make wrong current password error message more informative.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-server#5768]
**Describe the bug**

Currently when the user tries to change the password and enters a wrong current password, user is notified `Wrong Password`. While this is correct in terms of current password but in frontend it can be confusing for the user to know which password was wrong. Making it more informative will be helpful for the user.

**To Reproduce**
1. Go to '/settings/password'
2. Enter wrong current password and new passwords
3. Click on save

**Expected behavior**

A more informative error message `Wrong Password. Please enter correct current password.` should be shown to the user.

**Additional context**

I am working on it.

**Comment by iamareebjamal** [comment]
Ideally these things should be handled on client side only. Based on error codes. Maybe they don't want to show the same message in frontend and mobile. @CosmicCoder96  Your thoughts?
