### ISSUE TITLE
Documentation: Add documentation for translations download zip endpoint

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5772]

**Comment by kushthedude** [comment]
Working on it.

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update?

**Comment by kushthedude** [comment]
Will be pushing tonight

**Comment by shreyanshdwivedi** [comment]
@kushthedude if you haven't worked upon it, I think you should let me take it over. It's already 6 days since you claimed it. I'll be opening a PR tonight

**Comment by kushthedude** [comment]
Cool take it

**Comment by kushthedude** [comment]
@shreyanshdwivedi May i retake if you havent made changes on your local

**Comment by shreyanshdwivedi** [comment]
@kushthedude I'm taking help from @mrsaicharan1 as we both are unable to export events. I'll let you know if I am unable to proceed

**Comment by shreyanshdwivedi** [comment]
@mrsaicharan1 @uds5501 @kushthedude I am unable to export events on my local. If you are able to export events can you please post the screenshots of network request and response section?

**Comment by kushthedude** [comment]
Same for me @shreyanshdwivedi

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Can you do this? I'll help you out with the documentation.

**Comment by vardaan-raj** [comment]
Hello!, can I contribute to this and if so can you tell me a bit about this and what is it that you specifically want
