### ISSUE TITLE
Documentation: Update users docs

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5773]
A field called `was_registered_with_order` was added, documentation has not been updated.

**Comment by prateekj117** [comment]
@CosmicCoder96 I would like to take this up.

**Comment by kushthedude** [comment]
@CosmicCoder96 There should `good first issue` tag with this too I think

**Comment by shreyanshdwivedi** [comment]
@prateekj117 are you working on it?

**Comment by prateekj117** [comment]
@shreyanshdwivedi Ya, you take up #5774

**Comment by shreyanshdwivedi** [comment]
@prateekj117 if you are busy with something else, please let me know. I would like to take this up :)

**Comment by prateekj117** [comment]
@shreyanshdwivedi No, I will work on this.

**Comment by shreyanshdwivedi** [comment]
@prateekj117 it's already 6 days since you claimed the issue. It is just a documentation update. Please open a PR by tonight or let others do it :)

**Comment by iamareebjamal** [comment]
@shreyanshdwivedi Please go ahead with this
