### ISSUE TITLE
Documentation: Update orders API docs

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5774]
Information Fields regarding billing was added to orders API. Documentation has not been updated.

**Comment by prateekj117** [comment]
@CosmicCoder96 Would like to work on this.

**Comment by shreyanshdwivedi** [comment]
@prateekj117 I see you've already claimed #5773 
Can I work on this till you solve that issue?

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi proceed, @prateekj117 can work on #5773 meanwhile
