### ISSUE TITLE
Documentation: Update docs with new role-invite end points

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5775]
Some miscellaneous routes were added regarding role-invites and to accept them. Docs need to be updated.

**Comment by kushthedude** [comment]
Would like to take it up.

**Comment by CosmicCoder96** [comment]
@kushthedude One issue at a time. First get #5772 merged, allow other developers to work on issues parallelly.

**Comment by kushthedude** [comment]
No problem 😅

**Comment by uds5501** [comment]
@CosmicCoder96 Shall I have a go?

**Comment by CosmicCoder96** [comment]
Yes

**Comment by uds5501** [comment]
@CosmicCoder96 Just a quick doubt,  I need to change the `api_blueprint.apib` file, right? :sweat_smile: ea

**Comment by CosmicCoder96** [comment]
Yes.

**Comment by shreyanshdwivedi** [comment]
@uds5501 are you working on it? If you are busy with any other issue, can I take it over?

**Comment by uds5501** [comment]
@shreyanshdwivedi I am working on it have prepared the changes on the local. I will push the PR by tonight!

**Comment by Tlazypanda** [comment]
@CosmicCoder96 Can I work on this issue?

**Comment by kushthedude** [comment]
Go Ahead @Tlazypanda
