### ISSUE TITLE
Change the session status from pending to rejected if the event has passed.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-server#5777]
**Describe the bug**

Currently if the user's session is in pending state till the event has happened, it still shows pending after the event has passed. A better label will be rejected since the user's session wasn't accepted till the event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my sessions after event has passed'
2. Click on 'an older session'
3. See error

**Expected behaviour**

Pending label should be Rejected.

**Additional context**

I am working on this issue.

**Comment by uds5501** [comment]
@Anupam-dagar Can I take over? I have half of the work down, if you allow I shall push it by tomorrow.

**Comment by Anupam-dagar** [comment]
@uds5501 Sure.
