### ISSUE TITLE
Un-Authenticated request for Event Feedback List

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-server#5782]
**Is your feature request related to a problem? Please describe.**
https://api.eventyay.com/v1/events/1/feedbacks?sort=rating&filter=%5B%5D
the request is only allowed for logged in user I guess it shouldn't be right?

**Describe the solution you'd like**
Remove the authentication from event feedback list as each and every user should be able to see the ratings and comments from other users

**Comment by mrsaicharan1** [comment]
@aggarwalpulkit596 Would like to work on this.
