### ISSUE TITLE
Generate ticket PDFs on the go

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5784]
Currently, tickets PDFs are generated when an order is completed and stored in a directory.
This adds the overhead of storage and the complexity of moving them around when storage changes, and we need to manipulate strings hardcoded in the tickets URL field. This will happen often, considering we are in the development phase. 

Legacy system generated PDFs on the fly, is it feasible to do it in our current architecture? Kind of like we do with translation zip files. Also, it will automatically implement security checks as only the users with required privileges will be able to access the endpoint which generates PDFs. I am not sure when and why were tickets implemented as static files which need to be stored.

@iamareebjamal your views and feedback?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 I'd be interested in implementing this for the tickets as I've already worked on the translations downloads as a zip file. This would be an improved way as we shouldn't be serving the tickets from a static folder.

**Comment by uds5501** [comment]
@mrsaicharan1 how are you planning to implement this? It surely helps in solving the security issue attached to it!

**Comment by mrsaicharan1** [comment]
@uds5501 The best way to go about this is to implement the access control over a flask route.  The access-control check would be checking if the user is authorized to access the ticket by comparing the logged-in user and the ticket-holder. TO geenrate the PDFs dynamically, we could use a python package called `pdfkit` which acts as a wrapper to generate PDFs from Jinja Templates dynamically.

**Comment by iamareebjamal** [comment]
We are already generating PDFs, so no new logic for that should be necessary. Rest can be done as explained by @mrsaicharan1

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @iamareebjamal I'll go ahead with the implementation right away as this seems like a high priority issue regarding security and how the PDFs are served.

**Comment by uds5501** [comment]
@mrsaicharan1 that sounds good.

**Comment by mrsaicharan1** [comment]
@iamareebjamal Just another question. The storage overhead for the tickets as static files will still be prevalent. Would it be ok to schedule the deletion of ticket pdfs as a celery task(we could schedule it for after 10 mins. of ticket access) similar to the translations zip downloads? In this way, we wouldn't be needing to store the files on the server. I also believe that we shouldn't be serving static files from the server. Please correct me If I'm wrong.

**Comment by iamareebjamal** [comment]
I don't think they should be deleted. I mean, if we run out of storage, we'll just delete the entire folder but just go ahead with generating and saving. It'll save us time to just show the saved ticket. However, if generating and serving saved ticket have very little time difference between the 2, then yes, we may delete the file
