### ISSUE TITLE
Logs not being printed in case of error in DB layer

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5787]
Status 500 on from server but nothing is printed in logs

**Comment by mrsaicharan1** [comment]
I would like to take this up.

**Comment by mrsaicharan1** [comment]
@iamareebjamal Is logging the only problem now?

**Comment by iamareebjamal** [comment]
Try to diagnose why it may be happening, because there are no logs so can't do anything on production

**Comment by CosmicCoder96** [comment]
@iamareebjamal Counter needs to be reset in the database for the user's table, it's an object creation error.

**Comment by mrsaicharan1** [comment]
Maybe rebuilding the database would help?

**Comment by CosmicCoder96** [comment]
Fixed.

**Comment by CosmicCoder96** [comment]
@iamareebjamal It is weird though that I obtained the logs through postgres container, this should have been logged in the opev-web container as well.

**Comment by iamareebjamal** [comment]
No, unfortunately, Postgres does not restore the sequence on restore. https://wiki.postgresql.org/wiki/Fixing_Sequences

Although, we still need to diagnose why log wasn't printed

**Comment by iamareebjamal** [comment]
Working
