### ISSUE TITLE
Ticket Flow Refactoring

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5788]
**Describe the bug**
The tickets are currently served as static files without any access-control check which exposes it to everyone who possesses the link to the tickets. In addition, the ticket needs to served from a route which has a security check equipped with it.

**To Reproduce**
1. Go to 'https://api.eventyay.com/static/media/attendees/tickets/pdf/6ae42516-0a03-4436-b2a6-8a60f6a2b16d/QkJ0VHpPUX/ae067598-2896-4579-b4d9-8d5fa8a34e01.pdf'
2. We observe that anyone who possess the link can access it. This is a major security issue.

**Expected behavior**
Must check if the ticket holder is the same the currently authenticated user. Also, shoulds provide informative JOSN API: comliant error messages.

**Additional context**
Working on it.

**Comment by iamareebjamal** [comment]
How is it different from #5608 ?

**Comment by mrsaicharan1** [comment]
Duplicate isseu. Closing.
