### ISSUE TITLE
Unable to Submit Feedback

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-server#5793]
**Describe the bug**
Unable to make a request on this end point
https://api.eventyay.com/v1/feedbacks
Body
{
  "data": {
    "relationships": {
      "event": {
        "links": {
          "self": "/v1/feedbacks/771/relationships/event",
          "related": "/v1/feedbacks/771/event"
        }
      }
    },
    "attributes": {
      "rating": "4",
      "deleted-at": null,
      "comment": "Awesome event"
    },
    "type": "feedback",
    "id": 1,
    "links": {
      "self": "/v1/feedbacks/771"
    }
  },
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/v1/feedbacks/771"
  }
}

Response
{
    "errors": [
        {
            "status": 422,
            "source": {
                "pointer": "/data/relationships/user"
            },
            "title": "Unprocessable Entity",
            "detail": "A valid relationship with user resource is required"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 another issue for you although i'm not sure if it's a issue or not

**Comment by mrsaicharan1** [comment]
Yeah! Will take this up and try to find out what's causing this!

**Comment by mrsaicharan1** [comment]
@aggarwalpulkit596 Is this due to a GET request?

**Comment by aggarwalpulkit596** [comment]
Body
{
"data": {
"relationships": {
"event": {
"links": {
"self": "/v1/feedbacks/771/relationships/event",
"related": "/v1/feedbacks/771/event"
}
}
},
"attributes": {
"rating": "4",
"deleted-at": null,
"comment": "Awesome event"
},
"type": "feedback",
"id": 1,
"links": {
"self": "/v1/feedbacks/771"
}
},
"jsonapi": {
"version": "1.0"
},
"links": {
"self": "/v1/feedbacks/771"
}
}
this is body

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 this is exactly same as https://open-event-api-dev.herokuapp.com/#feedback-feedback-collection-post

**Comment by mrsaicharan1** [comment]
@aggarwalpulkit596 
I'm able to submit it locally and getting the same valid response as mentioned on the API server blueprint. Might be because you're making the request on the legacy API site. Will close this issue. If there's any other blocking issues, please do notify :)

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 i tried this from postman but still wasn't able to do it

**Comment by mrsaicharan1** [comment]
![Screenshot from 2019-04-14 13-16-23](https://user-images.githubusercontent.com/25197147/56089891-95659780-5eb7-11e9-8f78-a763a43f3830.png)
Just check if you have your headers set right.

**Comment by aggarwalpulkit596** [comment]
![Screenshot 2019-04-14 at 1 19 11 PM](https://user-images.githubusercontent.com/29139786/56089911-ec6b6c80-5eb7-11e9-93ce-ef21cfacedc9.png)
@mrsaicharan1

**Comment by mrsaicharan1** [comment]
`{
  "data": {
    "type": "feedback",
    "relationships": {
      "event": {
        "data": {
          "type": "event",
          "id": "1"
        }
      },
      "user": {
        "data": {
          "type": "user",
          "id": "1"
        }
      }
    },
    "attributes": {
      "rating": "4",
      "comment": "Awesome event."
    }
  }
}`

**Comment by mrsaicharan1** [comment]
Could you show me the body?

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 just checking with the above body request

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 yup it's working closing this
