### ISSUE TITLE
Notify user when he enters same old password as new password

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5794]
**Is your feature request related to a problem? Please describe.**

When a user changes his old password, Notify the user that he has entered the same old password as new password

**Describe the solution you'd like**

Notify user he has entered the same old password as new password

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/56079180-7c54dc00-5e0e-11e9-9a75-613a46b3ccc5.png)

**Comment by shreyanshdwivedi** [comment]
@kushthedude are you working on it?

**Comment by kushthedude** [comment]
@shreyanshdwivedi Just make the API reject the same old password , else will be handled in https://github.com/fossasia/open-event-frontend/issues/2636

**Comment by shreyanshdwivedi** [comment]
@kushthedude can I proceed?

**Comment by kushthedude** [comment]
Sure
