### ISSUE TITLE
Integrate PayPal Braintree  for ticket purchasing

### ISSUE THREAD

**Issue by RotBolt** [fossasia/open-event-server#5796]
**Is your feature request related to a problem? Please describe.**
Yes , This is blocking issue for [Open-event-android](https://github.com/fossasia/open-event-android/issues/1607)

**Describe the solution you'd like**
Currently PayPal Rest SDK is being used but
BrainTree is recommended way for doing the paypal payments .It also provide seamless Integration with android clients. 

**Would you like to work on this issue**
Yes

**Comment by iamareebjamal** [comment]
Design issue to be discussed here. How will clients know which payment options are available and which SDK to show?

Stripe, Braintree, both or other?

Need more probable issues to think before implementation
