### ISSUE TITLE
Integrate Firebase Python Admin SDK (FCM )for push notifications

### ISSUE THREAD

**Issue by RotBolt** [fossasia/open-event-server#5797]
**Is your feature request related to a problem? Please describe.**
EventBrite provides push notifications to clients for upcoming events and update of events .
Open-event-android does not have any push notifications unlike Event-Brite 
Related Issue : https://github.com/fossasia/open-event-android/issues/1608

**Describe the solution you'd like**
FCM will provide the ability to generate push notifications for subscribed clients

**Would you like to work on this issue**
Yes

**Comment by iamareebjamal** [comment]
The integration will be optionally integrated and implemented in many phases and is open for all, as it is not trivial to add

**Comment by theLimitBreaker** [comment]
Currently I thought Push Notifications for
- Update of event to clients
  - Speaker add/delete/update
  - Event time update
  - Event Location update
  - Event cancelled
  - Session/Track update/delete/add

- New Upcoming events to clients from subscribed organizers (require #5798 to be implemented according to my  knowledge)

**Comment by iamareebjamal** [comment]
All of the above updates can be grouped in `event_update` push. Once received, the client will fetch the new info about the event. For fine-grained details, we'll just pass the parameter of what's changed in the event. The level of detail like add/update/delete is not required

**Comment by theLimitBreaker** [comment]
that's what I meant actually for code and actual push  . Sorry I explained it in verbose manner .

**Comment by mariobehling** [comment]
Firebase is out of scope of this project.
