### ISSUE TITLE
Implement Organisers API

### ISSUE THREAD

**Issue by RotBolt** [fossasia/open-event-server#5798]
**Is your feature request related to a problem? Please describe.**
Yes , EventBrite gives option to search for organisers
Related to feature : https://github.com/fossasia/open-event-android/issues/1611

<img src="https://user-images.githubusercontent.com/24780524/56091016-ef218e00-5ec6-11e9-82bd-34c975490ff3.jpeg" width=360>

**Describe the solution you'd like**
I would make Orgainsers API , which would give single point of access to get orgaisers details (Also according to demographics)

**Would you like to work on this issue**
Yes

**Comment by uds5501** [comment]
@theLimitBreaker Are you working on it?

**Comment by theLimitBreaker** [comment]
Yes I will be

**Comment by iamareebjamal** [comment]
This can already be implemented using /users endpoint AFAIK

Please confirm

**Comment by theLimitBreaker** [comment]
Currently organisers come with events api like other attributes. I am talking about separate organisers api 
`/organisers/{Location}` 

for `/users` in response I get `organiser-events`, `track-organisers-event` etc . No organisers

**Comment by iamareebjamal** [comment]
You can use filter API for that

**Comment by theLimitBreaker** [comment]
so  I call `/events` with filter for organisers to filter out the organisers in all the events . It can give me the data to show to client side .

But having different api would be clean. Further Organisers API would also help for https://github.com/fossasia/open-event-android/issues/1608

**Comment by iamareebjamal** [comment]
> This can already be implemented using /users endpoint AFAIK

**Comment by theLimitBreaker** [comment]
OK . But when Users subscribe to Organisers for updates , I need to make some changes in the method for user api . If am going to work with with /users api . Would that be fine ? @iamareebjamal

**Comment by iamareebjamal** [comment]
Subscription is out of scope for now. Maybe we'll do if all blocking issues have been solved

**Comment by theLimitBreaker** [comment]
Well This issue I raised mainly for that . For subscribing to organisers and all organisers related thing .
