### ISSUE TITLE
Place Order API not working

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-server#5804]
**Describe the bug**
on hitting `orders?include=event,attendees&fields[event]=id&fields[attendees]=id` endPoint , `HTTP 422 UNPROCESSABLE ENTITY`

### Update 
When Some fields in Body being sent null (Like amount or order-example) this error code is generated . This is the response

```
{
    "errors": [
        {
            "detail": "Field may not be null.",
            "source": {
                "pointer": "/data/attributes/amount"
            },
            "status": "422",
            "title": "Validation error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by mrsaicharan1** [comment]
@theLimitBreaker I'll try to fix this blocking issue.

**Comment by iamareebjamal** [comment]
Yes, amount should not be null, but if it is not sent to the server, it should automatically be taken as 0
