### ISSUE TITLE
docs(api) : repetition in documentation

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5808]
**Describe the bug**

We are repeating ourselves a lot. We should be keeping the documentation DRY and use types.

https://blog.apimatic.io/common-mistakes-developers-make-in-their-api-blueprint-files-4b3b8c61306b

**To Reproduce**
1. Go to `docs/api/api_blueprint.apib`
2. See error

**Expected behavior**

We should be using types to avoid repeatition

**Additional context**

Working on it

**Comment by sumit-158** [comment]
I wanna work on this issue!

**Comment by mariobehling** [comment]
Documentation has changed a lot over time and we need to approach this in team meetings rather than on the tracker here. Therefore closing it.
