### ISSUE TITLE
No check for CFS and Ticket end date

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5809]
**Describe the bug**

Currently, the CFS end date and ticket end date can be more than the event end date. Proper error must be raised on such cases

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Create Event`
2. Create an event with a ticket having end date greater than the event end date
3. Open CFS with end date more than the event end date

**Expected behaviour**

Proper check must be implemented

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Mozilla Firefox

**Additional context**

Working on it

**Comment by uds5501** [comment]
@iamareebjamal this has been taken care of in #5801

**Comment by shreyanshdwivedi** [comment]
Closed via https://github.com/fossasia/open-event-server/pull/5801
