### ISSUE TITLE
Un-Authenticated request for Event FAQ List 

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-server#5810]
Is your feature request related to a problem? Please describe.
https://api.eventyay.com/v1/events/1/faqs
the request is only allowed for logged in user I guess it shouldn't be right?

Describe the solution you'd like
Remove the authentication from event faq list as each and every user should be able to see the faq's related to the event

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1

**Comment by mrsaicharan1** [comment]
Will take a look into it
