### ISSUE TITLE
Co-organizer access required error on leaving sponsor step

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5811]
**Describe the bug**

If I make an event using non-admin user, it can't leave sponsor form or go away from session form using previous and forward buttons .

**To Reproduce**
1. Create an event using non-admin user
2. try to move forward from sponsor step
3. See error

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21087061/56264750-15cd0800-6105-11e9-94dc-89ec79f0fe3f.gif)

**Expected behavior**

It should've moved forward without any error

**Stacktrace**

```cmd

INFO:werkzeug:127.0.0.1 - - [17/Apr/2019 11:33:47] "OPTIONS /v1/events/00784287 HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2019 11:33:47] "PATCH /v1/events/00784287 HTTP/1.1" 403 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2019 11:33:47] "PATCH /v1/events/00784287 HTTP/1.1" 403 -

```
**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Working on it

**Comment by uds5501** [comment]
@iamareebjamal @mrsaicharan1 
I digged deep in this and the reason came out behind this error was :
When our event identifiers are strings, this method works out all right, but in the cases where the event identifier goes out to be all integer, that's where this method breaks.

In this particular case, the event identifier that it was assigned is `00784287` but the identifier being passed around in requests is `784287(integer)` and is not being typecasted during permission checks.

so, how do I prevent this from happening?

**Comment by iamareebjamal** [comment]
Explicitly convert identifiers to string

**Comment by kushthedude** [comment]
@uds5501 Can you please check it once again? Since on event yay none of us is an admin, And still our event creation was going smooth

**Comment by uds5501** [comment]
@kushthedude kindly follow the discussion in the closed PR, you'll understand where the error is messing up
