### ISSUE TITLE
A mail to signup being sent up for an existing user on role invite

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5815]
**Describe the bug**

Currently, if I invite a user for an event role, be it existing user or non existing, they both are sent the same mail for signing up. Which shouldn't happen for existing user.

**To Reproduce**
1 Invite an existing user
2. See the email
3. See error

**Expected behavior**

For an existing user, the email sent should've been of login instead.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu 16.04
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Up for grabs

**Comment by prateekj117** [comment]
@uds5501 Can I take this up?

**Comment by uds5501** [comment]
@prateekj117 Sure!
