### ISSUE TITLE
Implement checks on deleting an event

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5822]
**Is your feature request related to a problem? Please describe.**

Deleting of an event should be prevent by an API if any order has been placed for the event, in order to avoid fraud. Please refer to https://github.com/fossasia/open-event-server/issues/5805#issuecomment-483576022

**Describe the solution you'd like**

Implement checks on deleting event. An event shouldn't be deleted if it has any order associated with it.

**Additional context**

Working on it.

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @mrsaicharan1 @uds5501 I wanted to discuss few things before proceeding. I'm planning to do this - If any order is associated with an event, APIs must restrict its deletion. Once the event passes, we must wait for a span of few days before enabling the deletion of the event because it may happen that the event organiser didn't show up at the venue or no event was there at the venue. So a minimum span of few days must be there before allowing the event organiser to delete the event. Your views

**Comment by mrsaicharan1** [comment]
The part about the API blocking the deletion of an event with an order associated is fine I guess. But I'm a little skeptical about the deletion after the event has passed. But I don't think you should allow deletion of past events. The organizer might never show up/conduct the event.

**Comment by iamareebjamal** [comment]
Right, for now, just implement check for Order thing, we'll tackle other things later

**Comment by iamareebjamal** [comment]
Disable delete for any event with any order for now, we'll refine these checks later.

Then allow deletes only when all the events from account have been deleted
