### ISSUE TITLE
HTTP connection hangs and flooding of "Booting worker with pid" from openv-web container 

### ISSUE THREAD

**Issue by yitzikc** [fossasia/open-event-server#5827]
I'm trying to run the server with docker-compose, following the instructions in aws.md and docker.md. Even though all the docker containers are up and port 8080 is supposed to be exposed, attempts to connect to it hang forever.
I see this behaviour both in an EC2 running Ubuntu and with Docker 2.0.0.3 on MacOS/X 10.14. I've raised the debug level on my OS/X docker setup to "debug" by editing the "--log-level" values in container_start.sh, and I see that Gunicorn keeps respawning worker threads. Every few seconds I see a message:

`opev-web    | [2019-04-21 13:58:49 +0000] [3168] [INFO] Booting worker with pid: 3168
opev-web    | [2019-04-21 13:58:50 +0000] [3175] [INFO] Booting worker with pid: 3175`

How can I debug this further? I haven't found any log files inside the opev-web  container.
Also, I'd appreciate confirmation that this issue is reproducible, or conversely that the same version runs properly on other people's setup

**Additional context**
* Docker on an Ubuntu 18.04 EC2 of size t2.medium, and Docker desktop 2.0.0.3  on MacOS/X 10.14.
* Version: master latest - a93777582f8f1083908bbfa51ddc19e56521fd57

**Comment by iamareebjamal** [comment]
Can you try stopping the elasticsearch container? It takes a lot of resources.

```
docker stop opev-elastic-search
```

Also, can you share the output of this command?

```
docker ps
```

**Comment by yitzikc** [comment]
Thanks for the quick reply! I've edited docker-compose.yml to run without Elasticsearch, and I still see the same behaviour. The output from docker ps is below. I'm pasting below my edited docker-compose.yml.


`
 docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
439814d29ea2        open-event-server_web      "sh scripts/containe…"   23 seconds ago      Up 21 seconds       0.0.0.0:8080->8080/tcp   opev-web
1afc51a8c07b        open-event-server_celery   "sh scripts/containe…"   23 seconds ago      Up 21 seconds       8080/tcp                 opev-celery
0ad93f479711        postgres:10-alpine         "docker-entrypoint.s…"   24 seconds ago      Up 22 seconds       5432/tcp                 opev-postgres
05d5080aa0ae        redis:3-alpine             "docker-entrypoint.s…"   24 seconds ago      Up 22 seconds       6379/tcp                 opev-redis`


`
version: '3.5'

x-environment-vars: &environment-vars
  DATABASE_URL: postgresql://open_event_user:opev_pass@postgres:5432/open_event
  ELASTICSEARCH_HOST: elastic:9200
  REDIS_URL: redis://redis:6379/0
  ADMIN_EMAIL: "@{ADMIN_EMAIL}"
  ADMIN_PASSWORD: "@{ADMIN_PASSWORD}"

x-defaults: &defaults
  build: .
  restart: unless-stopped
  environment:
    <<: *environment-vars
  depends_on:
    - postgres
    - redis
  #  - elastic
  links:
    - postgres:postgres
    - redis:redis
   # - elastic:elastic
  volumes:
    - ./static:/data/app/static

services:

  postgres:
    image: postgres:10-alpine
    container_name: opev-postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: open_event_user
      POSTGRES_PASSWORD: opev_pass
      POSTGRES_DB: open_event

  redis:
    image: redis:3-alpine
    container_name: opev-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - rd:/var/lib/redis/data

  # elastic:
  #   image: elasticsearch:5.6.12-alpine
  #   container_name: opev-elastic-search
  #   restart: unless-stopped
  #   environment:
  #       - discovery.type=single-node
  #   volumes:
  #       - es:/usr/share/elasticsearch/data
  #   ports:
  #       - 9200:9200
  #       - 9300:9300

  web:
    <<: *defaults
    container_name: opev-web
    ports:
      - 8080:8080

  celery:
    <<: *defaults
    container_name: opev-celery
    environment:
      <<: *environment-vars
      DEPLOYMENT: celery
      C_FORCE_ROOT: "true"

volumes:
    pg:
    rd:
    es:
`

**Comment by yitzikc** [comment]
my edited docker-compose.yml - including it inline since Github doesn't support uploading YAML files.

```version: '3.5'

x-environment-vars: &environment-vars
  DATABASE_URL: postgresql://open_event_user:opev_pass@postgres:5432/open_event
  ELASTICSEARCH_HOST: elastic:9200
  REDIS_URL: redis://redis:6379/0
  ADMIN_EMAIL: "@{ADMIN_EMAIL}"
  ADMIN_PASSWORD: "@{ADMIN_PASSWORD}"

x-defaults: &defaults
  build: .
  restart: unless-stopped
  environment:
    <<: *environment-vars
  depends_on:
    - postgres
    - redis
  #  - elastic
  links:
    - postgres:postgres
    - redis:redis
   # - elastic:elastic
  volumes:
    - ./static:/data/app/static

services:

  postgres:
    image: postgres:10-alpine
    container_name: opev-postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: open_event_user
      POSTGRES_PASSWORD: opev_pass
      POSTGRES_DB: open_event

  redis:
    image: redis:3-alpine
    container_name: opev-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - rd:/var/lib/redis/data

  # elastic:
  #   image: elasticsearch:5.6.12-alpine
  #   container_name: opev-elastic-search
  #   restart: unless-stopped
  #   environment:
  #       - discovery.type=single-node
  #   volumes:
  #       - es:/usr/share/elasticsearch/data
  #   ports:
  #       - 9200:9200
  #       - 9300:9300

  web:
    <<: *defaults
    container_name: opev-web
    ports:
      - 8080:8080

  celery:
    <<: *defaults
    container_name: opev-celery
    environment:
      <<: *environment-vars
      DEPLOYMENT: celery
      C_FORCE_ROOT: "true"

volumes:
    pg:
    rd:
    es:
```

**Comment by iamareebjamal** [comment]
This issue is not reproducible for me, but I would like to help you out in figuring out what's the problem. Can you check the output of `curl -L localhost:8080`?

**Comment by yitzikc** [comment]
Nothing, it just hangs. I'll try it later on Linux with strace and see if I get any more insight. How would you suggest debugging this, and see what's troubling Gunicorn and causing those endless worker re-spawns?

**Comment by iamareebjamal** [comment]
I think it will be due to less memory perhaps, but the server runs fine in even 1 GB RAM setting.

**Comment by yitzikc** [comment]
I was able to work around the problem by adding ` --preload` to the Gunicorn command-line in `scripts/container_start.sh`. I haven't been able to get much insight into the underlying root cause, but I can offer my fix this as a pull request if desired. I'd be glad to help determine the root cause if you have any requests (e.g. run code from branches that have extra logging etc.).

**Comment by iamareebjamal** [comment]
Thanks @yitzikc. We'd really appreciate your PR. Thank you for trying to determine the root cause, can you test the latest commit from development? 

However, I am not sure if it will make any difference since the problem seems to be arising from gunicorn and not the server code, but it doesn't hurt to try

Thanks again

**Comment by yitzikc** [comment]
I've also managed to reproduce the bug on my dev workstation (Docker Desktop 2.0.0.3 on OS/X 10.14) with the development branch (commit `5c5e3cb9a6647fe05f426d39381e6988338c6964`). The same workaround also resolves it.
_A wild guess_: something that should be specified as an environment variable is specified as a shell variable instead, hence it doesn't survive forks. Your test environment might set it as an environment variable elsewhere, thus hiding the problem.
