### ISSUE TITLE
Depenendency Upgrades

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5828]
The following dependencies have to be upgraded

- urllib3 = ">=1.24.2"
- SQLAlchemy = ">=1.3.0"
- Jinja2 = ">=2.10.1"
- marshmallow = ">=2.15.1"

**Comment by prateekj117** [comment]
@iamareebjamal May I work on it?

**Comment by iamareebjamal** [comment]
Go ahead
