### ISSUE TITLE
Integrate and verify new sentry SDK

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5837]
Update sentry SDK and verify it works

**Comment by uds5501** [comment]
@iamareebjamal Looking into it

**Comment by uds5501** [comment]
@iamareebjamal We are currently using `raven[flask]` to include sentry sdk, shall I update that dependency itself?

**Comment by iamareebjamal** [comment]
Yes

**Comment by uds5501** [comment]
@iamareebjamal I was looking at raven documentation and it says that it's being phased out for `sentry-python` . Should we update our repository to sentry-python implementation or just use the legacy `raven` one?

**Comment by iamareebjamal** [comment]
That's the point of the issue
