### ISSUE TITLE
Export: Event export API and Zip not working "Network Error"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#5848]
Trying to access the API through export page and downloading the zip results in "Network Error" e.g. at https://next.eventyay.com/events/45da88b7/export

**Comment by uds5501** [comment]
@mariobehling can't recreate the network issue, the zip file downloads perfectly

**Comment by iamareebjamal** [comment]
Because localhost:4200 is running on your PC

**Comment by uds5501** [comment]
@iamareebjamal okay, looking into it then

**Comment by CosmicCoder96** [comment]
It works now.
