### ISSUE TITLE
Update Dockerfile and other configs to support Python 3.7

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#5854]
No reason to not use latest version

**Comment by ashwani99** [comment]
May I take this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by amansheaven** [comment]
Looks like this issue isn't being done by the interested member. Willing to pick this up, Can I?

**Comment by iamareebjamal** [comment]
Sorry, this has already been fixed in #6490
