### ISSUE TITLE
Delete User Favorite By EventId

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-server#5857]
**Is your feature request related to a problem? Please describe.**
Current Implementation of user-favorite-events allows deletion of events by using the id given by the server.
**Describe the solution you'd like**
There should be an option to delete the event using eventId rather the user-favorite-event id

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 Can you take a look

**Comment by mrsaicharan1** [comment]
Yeah! Will solve this.

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 any update on this ?

**Comment by mrsaicharan1** [comment]
@aggarwalpulkit596 Sorry for the delay on this. Will get up to speed with this today.

**Comment by mrsaicharan1** [comment]
DELETE methods are automatically integrated when JSON API endpoints are created. What is the query you're having a problem with right now? You can directly delete the event using event_id.

**Comment by mrsaicharan1** [comment]
http://127.0.0.1:5000/#events-event-details-delete

**Comment by iamareebjamal** [comment]
We're talking about deleting favorite, not the event

**Comment by aggarwalpulkit596** [comment]
Any Update @mrsaicharan1  on this

**Comment by aggarwalpulkit596** [comment]
This is a major roadblock for the app we need this ASAP @iamareebjamal correct?

**Comment by mrsaicharan1** [comment]
There are some priority issues which are blocking the system from
functioning properly right now. I've been involved in the discussions and
the necessary things required for them.
Will try to do this as soon as I'm finished with those. You can keep a tab
on the issue tracker and the gitter channels as to what we've been talking
about :) .However, in the meantime, anyone else is welcome to take this.

**Comment by iamareebjamal** [comment]
@prateekj117 Can you take this up?

**Comment by prateekj117** [comment]
@iamareebjamal Sure. On it. 👍

**Comment by prateekj117** [comment]
So one solution here is to pass body in the Request, but @iamareebjamal told that Delete method doesn't work with body. So one solution is to make a new endpoint. Or is there any other solution? @uds5501 @mrsaicharan1 @shreyanshdwivedi

**Comment by mrsaicharan1** [comment]
You'll need to make a new API endpoint using flask_reset_json_api to create
and update this. The delete function will be integrated automatically.

**Comment by iamareebjamal** [comment]
There'll be no need of create as it won't be different from the previous endpoint and delete function won't be integrated automatically since you're not deleting the resource by its ID. you are deleting it by event's ID

**Comment by prateekj117** [comment]
@iamareebjamal Without creating a new endpoint, how would we know if the client passed an id or an event_id to delete the favorite.

**Comment by iamareebjamal** [comment]
You can create a new endpoint, but there'll be no create or update and delete will not be integrated automatically. You'll have to write custom delete function

**Comment by prateekj117** [comment]
@iamareebjamal So a new endpoint with a custom delete function, right?

**Comment by iamareebjamal** [comment]
No
