### ISSUE TITLE
Update API docs for Omise payment Gateway fields

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#5864]
New fields have been introduced in the event and settings models. API docs need to be updated to reflect those changes

Parent issue: #5823

**Comment by kushthedude** [comment]
@CosmicCoder96 Can i take it ?

**Comment by CosmicCoder96** [comment]
@kushthedude yes please proceed.

**Comment by uds5501** [comment]
@CosmicCoder96 Taking this one due to inactivity
