### ISSUE TITLE
Typo in the notification invitation message

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-server#5872]
**Describe the bug**

Currently, one user gets the notification-<b>You've been invited to be `a` attendee at TEST EVENT2.</b> But for attendees and for organizer, it should be changed to-<b> You've been invited to be `an` attendee at TEST EVENT2.</b> according to standards.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'notification panel.'
2. Scroll down.
4. See error.

**Expected behaviour**

 Typo needs to be fixed for the case of attendees and organizer.

**Screenshots**

![Screenshot 2019-04-20 17:21:55](https://user-images.githubusercontent.com/35539313/56456935-02ce6800-6391-11e9-907b-d8bd1f7895c2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version71.0398

**Additional context**

Working on it.

**Comment by kushthedude** [comment]
@mohitm15 Are you on it or should i overtake ?

**Comment by mohitm15** [comment]
On it @kushthedude

**Comment by kushthedude** [comment]
Its been 20 days

**Comment by mohitm15** [comment]
Encountered a bug..so gets delayed

**Comment by uds5501** [comment]
@CosmicCoder96 @iamareebjamal Can we put a beginner friendly issue tag on this? I guess it will be great issue for new comers

**Comment by kushthedude** [comment]
> @CosmicCoder96 @iamareebjamal Can we put a beginner friendly issue tag on this? I guess it will be great issue for new comers

👍

**Comment by QuietDilletante** [comment]
Hi there, I have experience with Python, but have never made a PR, or worked with OS. Could I give this a try? I might have a few stupid questions, but it seems like something I could manage.

**Comment by uds5501** [comment]
@QuietDilletante sure, go ahead!

**Comment by QuietDilletante** [comment]
Great, I'll let you know if I have issues.

**Comment by shreyanshdwivedi** [comment]
@QuietDilletante any update?

**Comment by muznahaftab** [comment]
@prateekj117 May I work on this?

**Comment by prateekj117** [comment]
@muznahaftab Go ahead.

**Comment by smcri** [comment]
Can I work on this issue?

**Comment by kushthedude** [comment]
@smcri Go ahead
