### ISSUE TITLE
Implementing Checks on Number of Discounted and Access Code Tickets

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5876]
Parent Issue - : #5874 

**Additional Information**

Implement a Server Side Check on Number of Discounted `Tickets/Access Tickets` User enters

Working On It

**Comment by mrsaicharan1** [comment]
Duplicate of #5865. Please close.

**Comment by mrsaicharan1** [comment]
@kushthedude Also, please try to check if this has **already been implemented/an issue has been opened** for this already. There is a method which has been implemented to check this and we need to take a closer look at it. This is the main reason why the tests were failing for #5786

**Comment by kushthedude** [comment]
@mrsaicharan1 didnt look close before opening , will take care
