### ISSUE TITLE
Generate Order Invoice properly(akin to Tickets)

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5878]
**Describe the bug**
The order invoice which is currently being generated is a screenshot of the page. Instead of this, we need to replace this with a generation of a proper PDF, similar to how the tickets are generated.

**To Reproduce**
1. Go to any event ticket
2. Click on Order Invoice

**Expected behavior**
A page should be printed with proper fields, rather than a screenshot.

**Additional context**
Working on this.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 What are the fields which we exactly need to include?

**Comment by CosmicCoder96** [comment]
As of now, the ones we have _tried_ to incorporate on the frontend. See the current invoice structure, also all the billing info.
