### ISSUE TITLE
Transfer the ownership of your events to another organizer.

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5890]
**Is your feature request related to a problem? Please describe.**

We are implementing feature to provide ability to a user to delete his/her account. If the user is associated with any event, he/she must be given choice to transfer the events to other organizers associated with the event. (Just like in GitHub)

**Describe the solution you'd like**

Something similar to `Github's Danger Zone` 
![danger](https://user-images.githubusercontent.com/25428397/57812116-ba387d80-7789-11e9-9efd-211751859832.png)

**Additional context**

Frontend issue: https://github.com/fossasia/open-event-frontend/issues/3012

**Comment by uds5501** [comment]
@shreyanshdwivedi Okay, I will finalise the endpoint over here, and help you with the frontend part.

**Comment by mariobehling** [comment]
This also means we should have the main organizer role to be renamed to "event owner". So, the one who creates an event is the "owner".
