### ISSUE TITLE
Make Order Invoice similar to EventBrite

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5891]
**Describe the bug**
Parent Issue:
https://github.com/fossasia/open-event-server/issues/5878

**Expected behavior**
The current order invoice needs to be generated as a proper PDF with the details specified here:
https://github.com/fossasia/open-event-server/pull/5886#issuecomment-492976538

_**While calculating the tax, the percentage and the amount must be shown**_

**Additional context**
Will work on this as soon as https://github.com/fossasia/open-event-server/pulls/5886 is merged.

**Comment by kushthedude** [comment]
@mrsaicharan1 , Our invoice is very different and very depreciated in terms of `EventBrite` , Can you have a look
<img width="651" alt="VAT_invoice_example_PDF" src="https://user-images.githubusercontent.com/44091822/59174361-ac9acb80-8b6e-11e9-9f50-fa68908ccbcb.png">
