### ISSUE TITLE
Credentials Exposed to non-admin users

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5923]
**Describe the bug**
Sensitive data is currently being exposed to non-admin users which is a major vulnerability
issue and needs to be fixed on priority.
Postgres configs, admin credentials, configs on the production server etc are made visible to non-admin users.

**Expected behavior**
This should only be accessible by the admin

**Additional context**
Working on this.

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 How? can you add more details

**Comment by iamareebjamal** [comment]
@CosmicCoder96 I discussed with him on gitter. Sending same info to you. Not a good idea sharing this in publuc
