### ISSUE TITLE
Timestamp saved in Database is not correct

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5943]
**Describe the bug**
Timestamp saved in `created_at` column of users field is not correct.

![Screenshot from 2019-05-21 20-40-02](https://user-images.githubusercontent.com/31065687/58108228-13306780-7c09-11e9-8494-7f8cfffbfaed.png)

Here, all five users were created at different times.

**Expected behavior**
Timestamp should be correct.

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@iamareebjamal I noticed that same time saves in case of subsequent requests. Any idea why? Though the package used for saving default time shows the correct time when printing the value in some other file in the same request.

**Comment by iamareebjamal** [comment]
Time is saved in UTC. What is wrong?

**Comment by prateekj117** [comment]
It saves the same time even when they are created at different times.

**Comment by iamareebjamal** [comment]
How much separation was there between the requests

**Comment by prateekj117** [comment]
@iamareebjamal Around 10-15 seconds.

**Comment by iamareebjamal** [comment]
Debug why

**Comment by prateekj117** [comment]
@iamareebjamal On it.
