### ISSUE TITLE
New Endpoint for Most used Event-Locations

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5945]
Server issue of [fossasia/open-event-frontend#2970](https://github.com/fossasia/open-event-frontend/issues/2970)

**Comment by prateekj117** [comment]
@iamareebjamal I see the event-locations table has some already saved Locations. So should I instead use the locations from the events table itself? As I think event-locations table is not being updated when creating a new event, or am I wrong?

**Comment by iamareebjamal** [comment]
Only location name would be saved in the event table AFAIK. What's stored in event-location table?

**Comment by prateekj117** [comment]
@iamareebjamal Some country names, which are hard-coded I guess.

**Comment by iamareebjamal** [comment]
Then use the locations in event table

**Comment by prateekj117** [comment]
@iamareebjamal Closing this one.
