### ISSUE TITLE
Add a new field rating in session schema

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5950]
Parent issue - https://github.com/fossasia/open-event-frontend/issues/2959

Add a new field `rating` in `session schema`.

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @CosmicCoder96 @mrsaicharan1 I wanted to discuss few things before implementing it. 
So, do we need to implement rating a session by admin/organizers via `feedback` schema or just update the rating on submission without having any feedback object?
If we are planning on saving a feedback object, we'll have to add a `average_rating` field rather than `rating` in sessions schema.

**Comment by iamareebjamal** [comment]
Why the field `average_rating`? `average_rating` can be calculated from the saved objects in DB

**Comment by shreyanshdwivedi** [comment]
I found a similar implementation for event schema in which we are having an `average_rating` field which will be indeed calculated calculated via saved objects.
I think the whole idea was to reduce computation at the time of loading bcoz if we'll calculate rating at the time of loading, it'll be a overhead calculation which can be reduced by using an averag_rating field.

**Comment by iamareebjamal** [comment]
When is `average_rating` calculated? Is it in schema only or in model as well. If it is in model then it will almost certainly be inconsistent

**Comment by shreyanshdwivedi** [comment]
It's only in schema @iamareebjamal

https://github.com/fossasia/open-event-server/blob/e261d23d802cedd180424551c01c2ec8fd6c33e1/app/api/schema/events.py#L123

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I dig deeper into this and found out that the event model and session model both are associated with a property `average_rating` something like this -
```py
    def get_average_rating(self):
        avg = db.session.query(func.avg(Feedback.rating)).filter_by(session_id=self.id).scalar()
        if avg is not None:
            avg = round(avg, 2)
        return avg

    @property
    def average_rating(self):
        return self.get_average_rating()
```
Also, both event and session schema has field `average_rating` too. Like you said earlier that if this field is present in both schema and models, then it'll lead to delay in fetching results. So, is this fine or do we need to remove it from models?

**Comment by iamareebjamal** [comment]
No, it's not a field in model, it's a method. This is fine. Implement it in same way
