### ISSUE TITLE
Error while editing event

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5955]
**Describe the bug**
While editing an event, an unusual error pops up:
`EventCopyright 1:Not Found`

**To Reproduce**
1. Go to 'One of your created events'
2. Edit any attribute
3. See error

**Expected behavior**
The edited changes must be saved.

**Stacktrace**

`INFO:werkzeug:127.0.0.1 - - [25/May/2019 13:32:43] "GET /v1/events/1/event-copyright HTTP/1.1" 404 -`

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Comment by kushthedude** [comment]
@mrsaicharan1 I was able to edit `Existing Events` ,Please check it once again

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Can you guys reproduce it ?

**Comment by Anupam-dagar** [comment]
@mrsaicharan1 i can confirm this, although I don't know the proper reason for it and how it occurs, but it has happened to me many times.

**Comment by mrsaicharan1** [comment]
Yeah, it's mostly due to the server validation errors. Have to check which
ones specifically

**Comment by prateekj117** [comment]
@mrsaicharan1 @Anupam-dagar Used to happen with me as well a lot, event-taxes also showed this problem, though I don't face it anymore.

**Comment by kushthedude** [comment]
The issue has been closed because all the validations have been removed for now , if anyone experience it again , please reopen it
