### ISSUE TITLE
FallBack to SMTP when SendGrid Fails/Exceeds Quota

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5958]
**Describe the feature request**
We need a feature in the system where the SMTP protocol must be used when SendGrid's quota exceeds/ fails to work. 
This is essential as whenever someone orders a ticket, they expect the tickets/invoice to reach them via mail. A backup service like this would be useful.

**Additional context**
Working on it.

**Comment by iamareebjamal** [comment]
A simpler version should be implemented first. An email sender object that provides an interface like `send_email` so that we can just use it. And internally it checks the configuration and uses sendgrid or SMTP according to config present. Then it can be enhanced to add the fallback usage

**Comment by mrsaicharan1** [comment]
Oh, okay ! @iamareebjamal , just to clarify, we have two separate tasks written out, `send_email_task` for Sendgrid and ` send_mail_via_smtp_task` for SMTP. Do you mean that we just need one method which checks for the internal config and sends it according to the enabled protocol?

**Comment by iamareebjamal** [comment]
Correct
