### ISSUE TITLE
Integration of AliPay Payment Gateway

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5959]
**Describe the feature**
Integration of _AliPay_ to extend the payment gateway options in China. Stripe Sources will be used for the integration of this.
This will be followed by a frontend PR pertaining to AliPay Enabling, Keys, payment buttons etc.
This is a parent issue which will be followed by sub tasks :

1: Create a Source object
2: Have the customer complete authorization
3: Charge the Source(*Pending*->*Charged*)
4: Confirm that the charge has succeeded

**Additional context**
Working on this.

**Comment by shreyanshdwivedi** [comment]
@mrsaicharan1 if you need any help on front-end PR, I can help you out. Please let me know

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Yeah, will notify you as soon as I'm done with the main workflow of the backend and I have any doubts with the frontend!

**Comment by prateekj117** [comment]
@mrsaicharan1 I can help with server sub-tasks. Let me know what you have in mind and what things you would be working on.

**Comment by kushthedude** [comment]
@mrsaicharan1 no need for this , Omise provides alipay , I and @uds5501 had a discussion about the various strategies omise provided and alipay is one of them and is working fine with omise

**Comment by mrsaicharan1** [comment]
Stripe has already been integrated and this works well with stripe sources.
No need of integrating with Omise.

**Comment by kushthedude** [comment]
You sure , there are some local wallets supported by omise which were our main meed for open tech summit thailand ?

**Comment by mrsaicharan1** [comment]
Omise is the most popular payment gateway in Thailand. On the other hand,
AliPay can be integrated either ways but this was the idea proposed in my
GSoC proposal. This works well for Sofort Pay as well. This is the main
reason why I’m using Stripe sources. Please check the documentation
pertaining to this.

**Comment by mrsaicharan1** [comment]
Does Omise work for Sofort Pay? @kushthedude

**Comment by kushthedude** [comment]
AFAIK safart is widely used in western states , omise might not be
supporting safart as of now

**Comment by mrsaicharan1** [comment]
Yeah, so that’s the clear justification i’m trying to point you towards
here. Stripe supports a huge basket of gateways through sources and I plan
to integrate these two gateways, as soon as I’m done testing Omise with
@uds5501
