### ISSUE TITLE
Hour after Minus - Hour is 00 again

### ISSUE THREAD

**Issue by kokoye2007** [fossasia/open-event-server#5963]
**Describe the bug**
HH:MM is not working

**To Reproduce**
in event time
1. HH choose
2. MM choose
3. HH is 00 again

**Comment by kushthedude** [comment]
@iamareebjamal the following issue is of FE and already the work has been started on it , It can be closed .

**Comment by iamareebjamal** [comment]
Please mention the issue number

**Comment by kushthedude** [comment]
See https://github.com/fossasia/open-event-frontend/issues/2077 and https://github.com/fossasia/open-event-frontend/issues/2366

**Comment by iamareebjamal** [comment]
Duplicate of above issues. Hence, closing

**Comment by kushthedude** [comment]
@iamareebjamal Since the following is a FE issue ,Closing it henceforth
