### ISSUE TITLE
Organizer should be able to download tickets of attendees

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#5968]
Organizers should have access to download tickets of attendees of their own events.

**Comment by mrsaicharan1** [comment]
@ShridharGoel The recent ticketing refactor made it point to a different link. Will fix this.

**Comment by mrsaicharan1** [comment]
@ShridharGoel This issue is not present locally.
<img width="957" alt="Screenshot 2019-05-29 at 10 00 41 AM" src="https://user-images.githubusercontent.com/25197147/58567785-98fb7680-81f8-11e9-9c26-ce5450c241b7.png">

**Comment by ShridharGoel** [comment]
Just checked, the URL for new attendees is having `generated` instead of `static/media` but still the link is not working. Did you try to open the link?

**Comment by mrsaicharan1** [comment]
Will check

**Comment by mrsaicharan1** [comment]
@ShridharGoel You can't access the tickets directly. The request going to that link must have certain authorisation headers to access it. This was a security refactor on the server to prevent access to the unauthorized personnel.

**Comment by ShridharGoel** [comment]
@mrsaicharan1 Yes I'm providing JWT authorization token in the Headers.

**Comment by ShridharGoel** [comment]
The link is being fetched properly. It's just that it's not opening.

**Comment by mrsaicharan1** [comment]
Yeah, I go that. But the mechanism the server is in such a way that a `current_user` proxy must be present. What is the exact error ?

**Comment by ShridharGoel** [comment]
@mrsaicharan1 This is displayed:

![Error screenshot](https://user-images.githubusercontent.com/35566748/58573866-4653a600-825c-11e9-9fff-85873ebe388c.png)

**Comment by mrsaicharan1** [comment]
```
try:
            order = Order.query.filter_by(identifier=order_identifier).first()
            user_id = order.user.id
        except NoResultFound:
            return NotFoundError({'source': ''}, 'This ticket is not associated with any order').respond()
```

**Comment by mrsaicharan1** [comment]
@ShridharGoel So basically, either the order_identifier which you are passing is wrong or the order isn't going through and isn't saved on the db.

**Comment by iamareebjamal** [comment]
@ShridharGoel Please post the URL here

**Comment by ShridharGoel** [comment]
> @ShridharGoel Please post the URL here

https://open-event-api-dev.herokuapp.com/generated/tickets/attendees/tickets/pdf/3697e440-c43e-405b-8af3-d16de4386cb0/cjN6Q2pwNS/3697e440-c43e-405b-8af3-d16de4386cb0.pdf

**Comment by ShridharGoel** [comment]
> I'm able to obtain the tickets through the frontend

Please send link of that PDF

**Comment by iamareebjamal** [comment]
@mrsaicharan1 Please check if you can dowwnload the PDF

**Comment by mrsaicharan1** [comment]
I can download from the front-end

**Comment by iamareebjamal** [comment]
@mrsaicharan1 I'm talking about the link shared here

**Comment by mrsaicharan1** [comment]
It's the same link I believe

**Comment by mrsaicharan1** [comment]
NO, @iamareebjamal .

**Comment by ShridharGoel** [comment]
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTkxNTgyMTQsImlhdCI6MTU1OTA3MTgxNCwibmJmIjoxNTU5MDcxODE0LCJpZGVudGl0eSI6NH0.ekLj24ie4a_RDPCVurL1dpsCSpjRQJzbtoGTYgsbt_U

**Comment by mrsaicharan1** [comment]
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTkxNTgyMTQsImlhdCI6MTU1OTA3MTgxNCwibmJmIjoxNTU5MDcxODE0LCJpZGVudGl0eSI6NH0.ekLj24ie4a_RDPCVurL1dpsCSpjRQJzbtoGTYgsbt_U

Yeah, 404 not found.

**Comment by iamareebjamal** [comment]
So this issue is valid then

**Comment by ShridharGoel** [comment]
How is it related to the JWT token? Shouldn't the link to download be working anyways?

**Comment by iamareebjamal** [comment]
No, I shouldn't be able to download your ticket

**Comment by mrsaicharan1** [comment]
> @ShridharGoel You can't access the tickets directly. The request going to that link must have certain authorisation headers attached to access it. This was a security refactor on the server to prevent access to the unauthorized personnel.

This ^ @ShridharGoel

**Comment by ShridharGoel** [comment]
> No, I shouldn't be able to download your ticket

But organizers can download the tickets of the attendees of their event, right?

**Comment by mrsaicharan1** [comment]
> > No, I shouldn't be able to download your ticket
> 
> But organizers can download the tickets of the attendees of their event, right?

I think a new endpoint is required for that where they can download individual/all tickets.

**Comment by ShridharGoel** [comment]
> > > No, I shouldn't be able to download your ticket
> > 
> > 
> > But organizers can download the tickets of the attendees of their event, right?
> 
> I think a new endpoint is required for that where they can download individual/all tickets.

Actually, the links of the PDFs of attendees are being provided to the organizer in the Orga App. Due to the recent security changes, this functionality might have changed because of which the links can no longer be accessed by the organizers. Although, in the present case, I'm not able to download my own tickets too using the Attendee App.

**Comment by iamareebjamal** [comment]
@ShridharGoel That's because attendee app has not implemented the security changes.

@mrsaicharan1 No need for new endpoint, just change the added check that allows organizer to download the ticket as well

**Comment by mrsaicharan1** [comment]
@ShridharGoel So the main problem here is, you're not able to download your own ticket right
?

**Comment by ShridharGoel** [comment]
@mrsaicharan1 I am able to download my own ticket from the frontend, but not from the attendee app. That might be because the attendee app has not implemented the security changes as @iamareebjamal mentioned above.

The change required is that the organizers should be able to download the tickets of the attendees of their events as well.

**Comment by mrsaicharan1** [comment]
Alright.

**Comment by mrsaicharan1** [comment]
Just change the issue link and will work on this.

**Comment by ShridharGoel** [comment]
Updated.
