### ISSUE TITLE
Unverified accounts can place orders

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#5970]
**Describe the bug**
Unverified accounts can place orders.

**Expected behavior**
Only verified accounts should be allowed to place orders.

**Comment by shreyanshdwivedi** [comment]
@ShridharGoel we are even allowing guest users to place the order who can just enter their email and place an order. So why should only be verified users allowed to place an order?

**Comment by kushthedude** [comment]
@ShridharGoel Please see #5760 , A discussion is going for the order flow , So the following can be close

**Comment by ShridharGoel** [comment]
Okay, if that's intentional then it's fine. 

But in a past issue this has been addressed as a 'huge security flaw' 
https://github.com/fossasia/open-event-frontend/issues/1616
