### ISSUE TITLE
Error in link provided in new session proposal email

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#5976]
**Describe the bug**
The link contains an extra `/` after `https://fossasia.github.io/open-event-frontend/`

![New session proposal wrong link](https://user-images.githubusercontent.com/35566748/58651381-c8ac9a80-832e-11e9-98ba-6fe533ee5950.png)

**Comment by mrsaicharan1** [comment]
@iamareebjamal What is the exact frontend url in production?

**Comment by iamareebjamal** [comment]
Doesn't matter, make_frontend_url should handle it. I have written tests for it. Check why it happened
