### ISSUE TITLE
Wrong Twitter URL Redirection

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5978]
#### Description :- 

* Twitter URL added for `Speaker` is getting an additional `EventYay` attribute which is Useless . 

* Due to this `Speaker Twitter URL` is getting redirected to wrong URL . 

#### To Check :- 

* Go To [This Event](https://eventyay.com/e/433e7b16/speakers)
* Click On Speaker.
* Check the `Twitter Redirected URL`.
 
*Example* : `https://eventyay.com/e/433e7b16/twitter.com/kushthedude`

**Comment by uds5501** [comment]
@kushthedude Will have a look into it

**Comment by kushthedude** [comment]
@uds5501 Thanks for checking , IDK what was the error before , Just changed the URL and everything seemed working fine .
