### ISSUE TITLE
Typo in the mail being sent after event ends

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#5985]
**Describe the bug**
Typo in the mail being sent after the event ends.

![Screenshot from 2019-06-03 02-29-20](https://user-images.githubusercontent.com/31065687/58767363-a5d8eb00-85a7-11e9-8742-94bca64884f9.png)

**Additional context**
Free for anyone to take up.

**Comment by kushthedude** [comment]
@iamareebjamal We should label it Good First Issue

**Comment by ram-nad** [comment]
I am taking up this issue
