### ISSUE TITLE
test_multiple_heads is not raising the expected error

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#5988]
**Describe the bug**

On having multiple heads, the travis build fails with error -
```
error: Hooks handler process 'dredd-hooks-python ./tests/hook_main.py' exited with status: 1
warn: Hook handling timed out.
error: Hooks handler process 'dredd-hooks-python ./tests/hook_main.py' exited with status: 1
info: Backend server process exited
The command "dredd" failed and exited with 1 during .
```
It should raise error as expected in - https://github.com/fossasia/open-event-server/blob/development/scripts/test_multiple_heads.sh

**Expected behavior**

Expected error should be raised - `Error: Multiple Migration Heads`

**Additional context**

On it

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal  I think this issue is non-existent now. I just got error for this travis failure - https://travis-ci.org/fossasia/open-event-server/builds/547072348?utm_source=github_status&utm_medium=notification

Error: `Error: Multiple heads are present; please specify a single target revision`

**Comment by iamareebjamal** [comment]
Sometimes it fails correctly, sometimes it doesn't

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal what should be done then? I'm unable to reproduce it for now

**Comment by iamareebjamal** [comment]
Increase the milestone

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I don't have access. 😅
Please do so

**Comment by shreyanshdwivedi** [comment]
It is not reproducible till now. Encountered correct error message twice this week

**Comment by iamareebjamal** [comment]
https://travis-ci.org/fossasia/open-event-server/builds/553157177?utm_source=github_status&utm_medium=notification

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I saw correct error message in this travis failure -
`info: Hooks handler stderr: ERROR [root] Error: Multiple heads are present; please specify a single target revision`

**Comment by iamareebjamal** [comment]
That's not the point of the script. That's flask failure, unrelated to script. The script is meant to stop the build ASAP as it encounters multiple heads and not continue dredd tests and others

**Comment by kushthedude** [comment]
https://travis-ci.org/fossasia/open-event-server/builds/553303214?utm_source=github_status&utm_medium=notification 
Occurred here too

**Comment by iamareebjamal** [comment]
Nope. That's failure during installing dredd
