### ISSUE TITLE
Wrong error throwing during sign up

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#5989]
**Describe the bug**
For short length of the password, the error is `HTTP 422`, It should be `HTTP 400`.

**Comment by shreyanshdwivedi** [comment]
Checking it now

**Comment by shreyanshdwivedi** [comment]
@liveHarshit @iamareebjamal currently we don't have any exception with status `HTTP 422`. The exceptions present currently can be viewed in `app/api/helpers/exceptions.py`
Do we need to introduce new exception for using it only at one place?

**Comment by iamareebjamal** [comment]
We need 400 Bad Request, not 422

Also, server already throws a lot of 400 errors, just the name and mechanism of throwing might be different

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Still on this?

**Comment by iamareebjamal** [comment]
I'm sorry, I thought 422 was conflict. Unprocessable Entity is correct

**Comment by shreyanshdwivedi** [comment]
So we don't need to have Bad Request Exception? This issue is to be closed ? @iamareebjamal
