### ISSUE TITLE
Ability to add donation support

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#5991]
**Describe the feature**
Our system requires the option of adding NGO events. When an event is categorised as an NGO event, it should have the feature of selling **only free** tickets. It should also have the option where people can donate funds to the fundraising event. 

This is a **parent** issue. It can be divided into sub-parts:
1. Integration of a working donation system
2. Adding NGO events/Open Source events
3. Adding the feature of recurring donations(_Monthly, Yearly etc..._)

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@mrsaicharan1 Can I work on the server side implementation of this?

**Comment by mrsaicharan1** [comment]
> @mrsaicharan1 Can I work on the server side implementation of this?

@prateekj117 I was planning to work on this myself, as discussed in the latest meeting. Will notify if I need help :)

**Comment by prateekj117** [comment]
@mrsaicharan1 As @mariobehling said that the term `is_ngo` is misleading, should we change the field name in the models as well?

**Comment by mrsaicharan1** [comment]
@prateekj117 yes, Please remove this

**Comment by prateekj117** [comment]
@iamareebjamal What should we rename it to?

**Comment by iamareebjamal** [comment]
Ask your peers

**Comment by prateekj117** [comment]
@mrsaicharan1 @uds5501 @shreyanshdwivedi What should I rename it to?

**Comment by mrsaicharan1** [comment]
@prateekj117 It's better to remove the fields as they are not required. We already have donation fields for events. At first, we needed NGo so that we could represent them separately as Open Source/ngo events. But, we just need donation support. So yeah, it'd be better to remove these fields now.
