### ISSUE TITLE
The ticket_fees documentation needs to be updated

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5994]
The ticket fees api docs have no mention of country variable and the post request needs to be updated accordingly for travis build of #5657 to pass

**Additional context**

Working on it

**Comment by Samwisebuze** [comment]
@uds5501 Has this issue been resolved? If not I can look into updating the doc.

**Comment by uds5501** [comment]
Go ahead @Samwisebuze

**Comment by EkanshMangal** [comment]
@uds5501 Sir, If this issue is still open, Can I look at it?

**Comment by iamareebjamal** [comment]
If an issue is green, it is open. If it is red, it is close

**Comment by mariobehling** [comment]
Solved during order rewrite.
