### ISSUE TITLE
Fetching featured speakers, accepted sessions, public call for speaker by default

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-server#5998]
**Describe the bug**
By default, the server should only return featured speakers, accepted sessions, public speakers call when client-side make GET requests. Currently, it also returns pending sessions or private call for speaker.

**Additional context**
Discussed in: https://github.com/fossasia/open-event-android/pull/1902 (comment)

**Comment by iamareebjamal** [comment]
Except featured speakers, everything should be done as @anhanh11001 stated

**Comment by mrsaicharan1** [comment]
@anhanh11001 I'd like to take this.

**Comment by mrsaicharan1** [comment]
@anhanh11001 Which endpoint are you talking about?

**Comment by iamareebjamal** [comment]
@mrsaicharan1 every endpoint which returns sessions or call for speakers

**Comment by prateekj117** [comment]
@iamareebjamal Would like to take this up.

**Comment by CosmicCoder96** [comment]
@iamareebjamal how would pending and other sessions will be retrieved after this?

**Comment by prateekj117** [comment]
@CosmicCoder96 By id. For cases like the one stated by @shreyanshdwivedi on Gitter, we can check the role of retriever and return session list accordingly.

**Comment by CosmicCoder96** [comment]
Whar do you mean by `id`? `Id` of what?

**Comment by iamareebjamal** [comment]
Only admin and event owner will be able to see the pending sessions, that too after passing a query parameter, not by default

**Comment by CosmicCoder96** [comment]
@prateekj117 To clarify, as of this moment, none of the pages which are not public, work on the frontend, including admin sessions, all, live, past, draft are broken and 

> Only admin and event owner/organizer will be able to see the pending sessions,

`Will` implies even server-side refactor was not in the PR? The frontend is completely crippled.

**Comment by iamareebjamal** [comment]
Revert the PR then
