### ISSUE TITLE
Review Wiki documentation and move content to /docs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6005]
Some docs have been posted to the wiki instead of the /docs repo. Please review the documentation in the wiki and what to keep. Move what is still relevant to /docs, please: https://github.com/fossasia/open-event-server/wiki

**Comment by meprogemur** [comment]
I'm working on this. Can you provide me a little more insight on the problem?

**Comment by meprogemur** [comment]
@mariobehling
