### ISSUE TITLE
Implementation of a payment reminder mechanism for organisers(invoice)

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6021]
**Describe the feature**
**Parent issue**
Event organizers should be reminded to pay the invoice to the eventyay platform. This can further be extended to limit certain features of the platform such as limiting access to specific areas of the it.
These reminders can be sent through mail or by pushing notifications to their dashboard.
The exact implementation can be discussed.
The frequency of mails/notifications, the specific message sent etc. can be modified by the admin.

**Additional context**
Working on it

Reference:
https://www.eventbrite.com/support/articles/en_US/Troubleshooting/understanding-eventbrite-fee-invoices?lg=en_US

**Comment by mrsaicharan1** [comment]
@mariobehling Is this the right in which we can proceed or am I missing something? Would be great if you could clarify.

**Comment by mariobehling** [comment]
Already resolved. Thanks.
