### ISSUE TITLE
Same Discount Code is not able to be applied for two different events

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6027]
**Describe the bug**

Currently if you create two same discount codes for two events , You will see it is invalid for one of the event

**To Reproduce**

- Create Discount Code X for Event A
- Create Discount Code X for Event B
- Apply X to B 
- See Error

**Expected behavior**

Same Discount Should be able to apply

#### Screenshot

<img width="1440" alt="Screenshot 2019-06-07 at 5 49 25 PM" src="https://user-images.githubusercontent.com/44091822/59103489-a3caaf80-894c-11e9-81a8-757cc6e7f3b3.png">

**Comment by prateekj117** [comment]
@uds5501 In case you are busy, can I take this one up.

**Comment by uds5501** [comment]
@prateekj117 please feel free to do so, ask @kushthedude to assign you this issue

**Comment by prateekj117** [comment]
@uds5501 @kushthedude I am not able to face this issue, instead of going request to 'discount-code', the request goes to 'access-code', which makes me wonder what's the difference between them. The issue does not exist if there are two same 'access-codes' for different events.

**Comment by prateekj117** [comment]
@iamareebjamal Your views on this?

**Comment by prateekj117** [comment]
@uds5501 @iamareebjamal @mrsaicharan1 Here the problem is, we query discount code only by its name, and event_id is not passed in params.
So there is no way to query it using event. What should be the way to go about it?

**Comment by iamareebjamal** [comment]
Paste the query here

**Comment by prateekj117** [comment]
@iamareebjamal 
`discount = db.session.query(DiscountCode).filter_by(code=kwargs.get('code'), deleted_at=None).first()`

**Comment by iamareebjamal** [comment]
>  we query discount code only by its name, and event_id is not passed in params.

The query browser is making

**Comment by prateekj117** [comment]
@iamareebjamal I checked the kwargs, event_id is not being passed from frontend as well.

**Comment by kushthedude** [comment]
> The query browser is making

?

**Comment by iamareebjamal** [comment]
@prateekj117 That's why I asked, what query is coming from frontend?

**Comment by prateekj117** [comment]
@iamareebjamal 
![Screenshot from 2019-07-14 00-22-52](https://user-images.githubusercontent.com/31065687/61175469-a19fe480-a5cd-11e9-8909-849162095017.png)

**Comment by iamareebjamal** [comment]
Change the access code accessor to /event/<id>/access-code/<access-code-id> as it should have been

Change to be done in both server and client.

This is a high priority change. So don't take a lot of time please
