### ISSUE TITLE
Deleted speakers are visible in sessions

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-server#6028]
**Describe the bug**
Deleted speakers are visible in sessions

**Expected behaviour**
Deleted speakers should not be visible in sessions

**Screenshots**
![speaker1](https://user-images.githubusercontent.com/19900978/56160500-f343cd80-5fe4-11e9-9f30-74ab52041b92.gif)

**Additional context**
I am working on it

**Comment by prateekj117** [comment]
@iamareebjamal On it.
