### ISSUE TITLE
Limit the number of emails an account can sent out in a given timeframe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6033]
One account yesterday tried a password reset requesting a reset 1000 times.

Please implement a threshhold for account resets and propose a threshhold for other emails in a certain time frame. Open relevant issues for this.

A threshhold for an account reset email should be 3 times per hour. After that the user should receive a message: "You have reached the threshhold for this action. Please try again in one hour."

**Comment by shreyanshdwivedi** [comment]
I'll be working on this

**Comment by mariobehling** [comment]
Thank you. It is related to this frontend issue: https://github.com/fossasia/open-event-frontend/issues/3128

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi https://github.com/fossasia/open-event-server/issues/6034

**Comment by niranjan94** [comment]
Also, we need rate limiting on all of the API endpoints to prevent misuse. @shreyanshdwivedi please create an issue for it with the solution.
