### ISSUE TITLE
Don't allow unverified users to place free orders

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6034]
Unverified users shouldn't be allowed to place free orders, paid orders are okay.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 is this PR not fixing this issue? https://github.com/fossasia/open-event-server/pull/6008

**Comment by kushthedude** [comment]
@shreyanshdwivedi Thats what i was saying , We should be restricting free orders rather than free tickets .

**Comment by shreyanshdwivedi** [comment]
Okay then. I'll work on it and fix it asap 
Should I revert https://github.com/fossasia/open-event-server/pull/6008 in my upcoming PR for free order?

**Comment by kushthedude** [comment]
@shreyanshdwivedi That would work , Try to inculcate both the changes in same PR if possible

**Comment by shreyanshdwivedi** [comment]
@kushthedude can you please take care of this please? I'm involved in other issues

**Comment by kushthedude** [comment]
@shreyanshdwivedi Sure will take a look at it , Just a doubt what about an order with 100% discount do we need check on it too?

**Comment by kushthedude** [comment]
> Okay then. I'll work on it and fix it asap
> Should I revert #6008 in my upcoming PR for free order?
> @kushthedude @CosmicCoder96 @iamareebjamal

@iamareebjamal @niranjan94

**Comment by prateekj117** [comment]
@kushthedude Taking this due to inactivity.

**Comment by kushthedude** [comment]
@prateekj117 Sure, Please go ahead , Some Points :
- Revert the Old PR , Once yours is ready.
- Take care the zero amount is not created due to some discount code.
