### ISSUE TITLE
Populate event locations with most frequent locations routinely

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6054]
Parent issue https://github.com/fossasia/open-event-frontend/issues/2970

Event locations endpoint should return the most popular locations for events, and be updated regularly.

**Comment by prateekj117** [comment]
@CosmicCoder96 I will take this one. Closed the old one  (https://github.com/fossasia/open-event-server/pull/5982). Will open a new one by tonight.

**Comment by prateekj117** [comment]
Also, this is a duplicate of https://github.com/fossasia/open-event-server/issues/5945

**Comment by CosmicCoder96** [comment]
@prateekj117 
![image](https://user-images.githubusercontent.com/17252805/59602883-8363d780-913a-11e9-9b5d-41c5c82af4c6.png)
That means I am working on this.

**Comment by prateekj117** [comment]
@CosmicCoder96 Wanted to work on it. No issue. 😅

**Comment by CosmicCoder96** [comment]
Yeah, I figured but had already started working on it :) after self
assigning.
