### ISSUE TITLE
Implementation Of Refund Functionality and Event Policy

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6065]
Addition of new feature available to organiser: `Refund Policy`
A rough idea of the plan : 
- A Toggle while creation of event : 
    - Organizer should have two options for orders :
        - Cancel & refund (and ability to specify cancellation charge)
        - Cancel without refund
        - Organizer should be able to turn on/off ticket cancellation functionality.
- Option to specify the following fields : 
    - Date until we can request a refund
    - How to avail refund, Way of refund and should it require `Organiser Permissions`
    - Cancellation charges on the basis of `Time and Date` when refund is issued after placing of order.

**Comment by mariobehling** [comment]
Thanks, we have defined a simpler approach to refunds in the frontend. Therefore closing this.
