### ISSUE TITLE
Error raised on reset password if user is not registered

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6069]
Raising an error on password reset if the user is not registered is like gifting hackers a list of users present in the database.

Instead, regardless of user being present in the system, it should return 

"If your email was registered with us, you'll get an email with reset link shortly"

**Comment by shreyanshdwivedi** [comment]
Will work on it

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can I take this as you will be handling order workflow?

**Comment by shreyanshdwivedi** [comment]
@kushthedude order workflow is being handled by @uds5501 and @mrsaicharan1 as he had a similar PR few days ago. I'll open a PR in few hours

**Comment by kushthedude** [comment]
Cool
