### ISSUE TITLE
Refactor workflow for pending orders

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#6072]
**Is your feature request related to a problem? Please describe.**

Currently, a user who orders pending ticket gets 3 days time to complete payment. Till then the ticket is reserved.

**Describe the solution you'd like**

As discussed with @mariobehling, we should implement these two points - 
 - provide 30 minute time to user to pay for pending tickets. If payment is not done in 30 minutes, update the status of ticket to `expired`
 - If ticket expires due to the above stated reason, send an email and notification to the user stating something like - "Do you want to order this ticket still? You can order through this link within 24 hours ( if ticket is available )"

**Comment by shreyanshdwivedi** [comment]
As I've completed all of my WIP PRs, I'll start working on it

**Comment by kushthedude** [comment]
> As I've completed all of my WIP PRs, I'll start working on it

Can you please also open an issue to show `Deleted Orders` in `Admin Panel`

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Please notify if you need any help here :)

**Comment by uds5501** [comment]
@shreyanshdwivedi 

> * If ticket expires due to the above stated reason, send an email and notification to the user stating something like - "Do you want to order this ticket still? You can order through this link within 24 hours ( if ticket is available )"

I can help with this, my last PR handled this only so I think I can implement this one. Let me know if you require any help

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi I'll try to do the 30mins expiry part.

**Comment by shreyanshdwivedi** [comment]
@uds5501 @mrsaicharan1 go ahead :)
