### ISSUE TITLE
Add relationship of tickets (price range) in Events

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#6094]
Reference issue: https://github.com/fossasia/open-event-android/issues/1990

**Comment by prateekj117** [comment]
@liveHarshit On it.

**Comment by iamareebjamal** [comment]
Relationship will be added, not attribute

**Comment by liveHarshit** [comment]
Solved

**Comment by iamareebjamal** [comment]
How?

**Comment by liveHarshit** [comment]
> How?

Already there-
![image](https://user-images.githubusercontent.com/27783786/60676025-73b6f380-9e9b-11e9-8250-3c0f6ed65910.png)

**Comment by iamareebjamal** [comment]
Umm, you'll load all tickets to find min and max count?

**Comment by liveHarshit** [comment]
> Umm, you'll load all tickets to find min and max count?

I've created a class with price and Id but I'm getting zero price for all tickets: PR https://github.com/fossasia/open-event-attendee-android/pull/2066

**Comment by anhanh11001** [comment]
@liveHarshit I'm reopening this as I think I can take this issue up, then we would have a better solution in Android

**Comment by shreyanshdwivedi** [comment]
@anhanh11001 any update?
