### ISSUE TITLE
Notifications are not updating

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#6104]
Updating notification is not working: https://api.eventyay.com/#notifications-notification-detail-patch , It is giving same notification without updating in response. (I have tried to change value for is-read = true )

Reference PR (discussion): https://github.com/fossasia/open-event-android/pull/1998

**Comment by uds5501** [comment]
@liveHarshit I tried updating notifications in my local server and they seem to be working fine. The front-end notification updates are working fine too!

**Comment by iamareebjamal** [comment]
@uds5501 Please paste the payload and URL you used to update the notification state from unread to read

**Comment by uds5501** [comment]
Payload : 

```
{
  "data": {
    "attributes": {
      "is-read": "false"
    },
    "type": "notification",
    "id": "68"
  }
}

```

URL : `http://127.0.0.1:5000/v1/notifications/68`
I tested this locally and it worked.

**Comment by liveHarshit** [comment]
I'm getting following response after updating notification 
```
Updated notification 15
D/OkHttp: <-- 200 OK https://open-event-api-dev.herokuapp.com/v1/notifications/13 (1951ms)
D/OkHttp: Connection: keep-alive
    Server: gunicorn/19.9.0
    Date: Fri, 28 Jun 2019 04:35:40 GMT
    Content-Type: application/vnd.api+json
    Content-Length: 664
D/OkHttp: Etag: 36587bd0ffc8e966e00f42b3463e0c2b6bdb5a77
    Access-Control-Allow-Origin: *
    Via: 1.1 vegur
D/OkHttp: {"data": {"type": "notification", "attributes": {"is-read": false, "received-at": "2019-06-27T17:26:23.002052+00:00", "title": "Your order invoice and tickets (O1561656381-13)", "deleted-at": null, "message": "Your order has been processed successfully."}, "id": "13", "relationships": {"notification-actions": {"links": {"self": "/v1/notifications/13/relationships/actions", "related": "/v1/notifications/13/notification-actions"}}, "user": {"links": {"self": "/v1/notifications/13/relationships/user", "related": "/v1/notifications/13/user"}}}, "links": {"self": "/v1/notifications/13"}}, "links": {"self": "/v1/notifications/13"}, "jsonapi": {"version": "1.0"}}
```
With
```java
@PATCH("notifications/{notification_id}")
    fun updateNotification(
        @Path("notification_id") notificationId: Int,
        @Body notification: Notification
    ): Single<Notification>
```

Here 
Body `notification.isRead` is true.

And the notification class - 
```java
@Type("notification")
@JsonNaming(PropertyNamingStrategy.KebabCaseStrategy::class)
@Entity
data class Notification(
    @Id(IntegerIdHandler::class)
    @NonNull
    @PrimaryKey
    val id: Int,
    val message: String? = null,
    val receivedAt: String? = null,
    var isRead: Boolean = false,
    val title: String? = null,
    val deletedAt: String? = null
)
```

**Comment by uds5501** [comment]
@liveHarshit I am not really good at understanding this format .
```
@PATCH("notifications/{notification_id}")
    fun updateNotification(
        @Path("notification_id") notificationId: Int,
        @Body notification: Notification
    ): Single<Notification>
```

but does it mean that `isRead` = `is-read` in the current context?

**Comment by liveHarshit** [comment]
> but does it mean that `isRead` = `is-read` in the current context?

yes

**Comment by uds5501** [comment]
> ```java
>     var isRead: Boolean = false,
> ```
@liveHarshit 
Wait. Doesn't this mean that you are passing `is-read=false` in your attributes? (If the response you sent was for this request itself) 
Can you please check if making it `true` to the same object changes it's `is-read` status

**Comment by liveHarshit** [comment]
> > ```java
> >     var isRead: Boolean = false,
> > ```
> 
> @liveHarshit
> Wait. Doesn't this mean that you are passing `is-read=false` in your attributes? (If the response you sent was for this request itself)
> Can you please check if making it `true` to the same object changes it's `is-read` status

I have tried with creating a new object and pass it, same results - 
```java
val newNotification  = Notification(
                id = notification.id,
                message = notification.message,
                receivedAt = notification.receivedAt,
                isRead = true,
                title = notification.title,
                deletedAt = notification.deletedAt
            )
            compositeDisposable += notificationService.updateNotification(newNotification)
```

**Comment by iamareebjamal** [comment]
@liveHarshit Open Chrome DevTools through stetho and see what is going to the server rather than guessing

**Comment by liveHarshit** [comment]
@iamareebjamal Found the problem. It is taking `isRead` to `read` instead of `is-read` in Body.
![image](https://user-images.githubusercontent.com/27783786/60323365-7dbe8b00-999f-11e9-854c-ea921501a953.png)

**Comment by liveHarshit** [comment]
It should not happen with the ResourceConverter

**Comment by iamareebjamal** [comment]
Configure the Jackson settings correctly and it should work. Closing this issue
