### ISSUE TITLE
Design Event Invoice Template 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6123]
**Is your feature request related to a problem? Please describe.**
Currently there is no template for event invoice. Please design one so that it can be rendered.
**Describe the solution you'd like**
Something similar to this, a basic design would do for now. No need of DRAFT in the back now. We can integrate it later.

<img width="569" alt="Screenshot 2019-06-29 at 6 36 37 PM" src="https://user-images.githubusercontent.com/25197147/60384563-f5261480-9a9c-11e9-8892-eb1fc41aa71f.png">

Here is the list of sub-issues:

- Add Basic Layout
- Add Billing Addresses (To and From)
- Add Info regarding Eventyay service fees 
- Add table for ticket sales and Gross Revenue(Total Revenue) and Net Revenue(Revenue after slashing eventyay fees)

**Additional context**
Please assign yourselves and start working on it.

**Comment by kushthedude** [comment]
@mrsaicharan1 I think, Breaking every part of the invoice to different sub-issue will be better for reviewing and checking workflow.
If anyone wants to start work on it, Please open a sub-issue and proceed step-by-step.

**Comment by shreyanshdwivedi** [comment]
@mrsaicharan1 it would be great if you can make an outline having details of sub-issues so that we can start working by taking up a sub-issue

**Comment by mrsaicharan1** [comment]
Sure, @shreyanshdwivedi .
Here is the list of sub-issues:

- Add Billing Addresses (To and From)
- Add Info regarding Eventyay service fees 
- Add table for ticket sales and Gross Revenue(Total Revenue) and Net Revenue(Revenue after slashing eventyay fees)

**Comment by kushthedude** [comment]
@mrsaicharan1 Please an Basic Design outlet as another sub issue with
eventyay logo on top

**Comment by mrsaicharan1** [comment]
@kushthedude Please check the issue. I've already added it.

**Comment by uds5501** [comment]
@mrsaicharan1 as far as the billing address is concerned, we can proceed after the merge of #6103. Correct?

**Comment by mrsaicharan1** [comment]
Yup. The basic layout would be the best thing to go about first.

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Can you design the basic layout for this? Would be great if someone could design the basic layout for this as this would serve as a crucial factor to save those PDFs and make them accessible to the organizer.

**Comment by shreyanshdwivedi** [comment]
Sure. Will open a sub-issue and start working on it

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Could you start off with the basic layout? Would be helpful to test the event invoice functionality as a whole :)

**Comment by kushthedude** [comment]
@shreyanshdwivedi If you are busy, May I take care of it ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude yeah please go ahead. I'm working on other bugs currently

**Comment by kushthedude** [comment]
Cool
