### ISSUE TITLE
Handle discount code logic on db level

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#6126]
The discount code calculation should be done on database level queries.

Refer : https://github.com/fossasia/open-event-server/pull/6055#pullrequestreview-256064847

**Comment by Rits1272** [comment]
Hey everyone, Can I work on this issue?

**Comment by prateekj117** [comment]
@Rits1272 Go ahead.

**Comment by Rits1272** [comment]
Ok @prateekj117 !

**Comment by Rits1272** [comment]
Hello @prateekj117! I am a new contributor here trying to understand the codebase and solve this issue.
Can you please help me out by confirming that in the db level queries we need to enhance the code by converting the pythonic code to postgresql queries using psycopg2 python library inside the function?

**Comment by iamareebjamal** [comment]
We don't need to convert to SQL queries, we want to use SQLAlchemy

**Comment by Rits1272** [comment]
@iamareebjamal So we need to write code in the models so we can fetch old holders from a method rather than calculating inside the function? Am I going the right way?

**Comment by iamareebjamal** [comment]
`from a method rather than calculating inside the function`

I don't get it. What'd be the difference between method and function if it's going to do stuff in Python

**Comment by Rits1272** [comment]
Oh sorry I does not mean that. I was saying that do we need to write a field in the models for the old_holders?

**Comment by iamareebjamal** [comment]
No

**Comment by Rits1272** [comment]
Hello again @iamareebjamal ! From a past few days I have been trying really hard to solve this issue. But I am stuck. Can you please give me a guideline or some steps to solve the issue?

**Comment by iamareebjamal** [comment]
It's not a beginner friendly issue, you can try to solve other issues

**Comment by Rits1272** [comment]
Okay sure.

**Comment by iamareebjamal** [comment]
Solved by reimplementation. Will rivisit when discount codes are reimplemented
