### ISSUE TITLE
Make billing information mandatory for paid orders

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6137]

**Comment by kushthedude** [comment]
@CosmicCoder96 Wont this be handled in FE Validations ?

**Comment by iamareebjamal** [comment]
@kushthedude Handling anything on frontend is equivalent to handing a blank cheque with your signature to a thief and hoping he won't cash it. Seems like you missed my message a month back in the gitter channel about frontend validations === useless validations
