### ISSUE TITLE
Schedule Order Expiry with APschedudler instead of celery

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6143]
**Is your feature request related to a problem? Please describe.**

Currently, order expiry is a celery task and it becomes very tedious to debug info related to it as the server runs successfully in spite of an error related to it(because celery may/may not be running). APScheduler guarantees that it's scheduling the task. If the server is running, APS is also running & it stays synchronised with server. Both of them are in resonance.  This helps in a refined way to debug and removes the interdependence of celery. 

**Additional context**
Working on it.

**Comment by mrsaicharan1** [comment]
Order expiry is actually tied to an APS task itself. I guess this is not persistent. Closing it therefore.

**Comment by iamareebjamal** [comment]
> I guess this is not persistent.

?

**Comment by mrsaicharan1** [comment]
Order expiry is an APScheduler task. That's what I meant to say. But do you think we need this for other tasks such as sending emails and downloading images?

**Comment by iamareebjamal** [comment]
No, just confused about what is not persistent? Does the task of expiry not persist on server restart for APS Scheduler?

**Comment by mrsaicharan1** [comment]
@iamareebjamal I haven't confirmed that part. I will check it out.
