### ISSUE TITLE
Deleted Event Restoration fails

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6147]
```
{"errors": [{"status": 422, "source": {"pointer": "/data/attributes/starts-at"}, "title": "Unprocessable Entity", "detail": "starts-at should be after current date-time"}], "jsonapi": {"version": "1.0"}}
```

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 this check was implemented on event schema to avoid any event to have invalid dates.
What exactly do we need to fix this issue? As the check is on the schema, we cannot simply remove it for a few cases and apply it for other cases.

**Comment by uds5501** [comment]
@shreyanshdwivedi How about we ignore the test for deleted events?

**Comment by shreyanshdwivedi** [comment]
@uds5501 actually when the event is restored, a PATCH request is sent which updates the deleted-at to null again and so when these values are passed to schema, we cannot know if the event was deleted or not.
One thing we can do is update the event start and end time to current time while restoration.
Should I follow this approach? @iamareebjamal @uds5501

**Comment by iamareebjamal** [comment]
Why can't we just only check dates if event is being created/ or dates are being updated

**Comment by shreyanshdwivedi** [comment]
Actually the check is on schema and it is validated automatically for any update. @iamareebjamal

**Comment by iamareebjamal** [comment]
So there is no way to see if the entity is being created or updated?

**Comment by shreyanshdwivedi** [comment]
I haven't found a way to know if the event is being created or updated.
The data which is being passed to `validate_date` while restoration-
```
{
'schedule_published_on': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=tzutc()), 
'starts_at': datetime.datetime(2019, 6, 16, 18, 30, tzinfo=tzutc()), 
'is_featured': False, 'state': 'published', 
'is_map_shown': True, 
'is_sessions_speakers_enabled': False, 
'can_pay_by_stripe': False, 
'longitude': 0.0, 
'coorganizers': [], 
'privacy': 'public', 
'location_name': 'A', 
'can_pay_by_omise': False, 
'is_sponsors_enabled': False, 
'is_event_online': False, 
'can_pay_by_cheque': False,
'track_organizers': [], 
'moderators': [], 
'organizers': [], 
'is_tax_enabled': False, 
'has_owner_info': False, 
'owner': '1', 
'name': 'A', 
'can_pay_by_alipay': False, 
'payment_currency': 'USD', 
'show_remaining_tickets': False, 
'is_ticketing_enabled': False, 
'registrars': [], 
'can_pay_onsite': False, 
'is_donation_enabled': False, 
'description': '', 'timezone': 'Asia/Kolkata', 
'latitude': 0.0, 
'can_pay_by_paypal': False, 
'ends_at': datetime.datetime(2019, 6, 20, 18, 30, tzinfo=tzutc()), 
'can_pay_by_bank': False, 'is_ticket_form_enabled': True
}
```
I didn't find any relevant key to know if the event is created or updated.

**Comment by CosmicCoder96** [comment]
> I didn't find any relevant key to know if the event is created or
updated.
Before update, after update , before create, after create hooks? What do
you mean?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I meant that the schema check which is implemented, it has no way to know if the event is being created or updated. It works automatically and we don't call it explicitly.

**Comment by iamareebjamal** [comment]
Then please delete the schema check and add programmatic check
