### ISSUE TITLE
User with organizer or coorganizer role can delete other roles too

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#6152]
**Describe the bug**

Currently, a user with coorganizer access to an event can delete other organizers/coorganizers/owners too. But the user should be allowed to delete users with roles smaller than the user itself.

**Expected behavior**

User should be able to delete another user (having a role in the event), only if the user 

**Additional context**

On it

**Comment by ShridharGoel** [comment]
> But the user should be allowed to delete users with roles smaller than the user itself.

In my opinion, either only owner should have the access to create/delete roles or only owner and organizers should have that access, with organizers being allowed to create/delete roles except that of owner.

**Comment by shreyanshdwivedi** [comment]
So, only users with organizer access can create events. The only problem lies with the delete function. Creating a PR for it
