### ISSUE TITLE
No hard delete for feedback

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#6153]
**Describe the bug**

Currently there is hard delete for feedback. When a user sets his/her rating to 0 again, the feedback of the user should be removed completely from the db.
This issue needs to be solved to merge https://github.com/fossasia/open-event-frontend/pull/3198

**Expected behavior**

When the user clears his/her rating (i.e. sets it to 0 again), the feedback must be removed.

**Additional context**

On it

**Comment by iamareebjamal** [comment]
Don't understand why is there a need of hard delete?

**Comment by shreyanshdwivedi** [comment]
Actually currently when user sets its rating to 0 again, I destroyed the record on frontend by - `feedback.destroyRecord()` but it is only setting rhe deleted_at to 0.
The feedback is still in db and messes up with avg rating and number of ratings

**Comment by iamareebjamal** [comment]
Then fix the queries of average rating and number of ratings

**Comment by shreyanshdwivedi** [comment]
One more case - suppose user again rates the session, then their will be similar entries in db - same user, same session. Even if I fix the queries for avg rating and number of ratings, these similar entries will exist. 
Also, we soft delete event, user etc so that they can be restored later but I don't think any such purpose is required in case of feedback. That's why I thought of hard delete.
However, final call is obv yours, should I proceed with updating queries?

**Comment by iamareebjamal** [comment]
OK, go ahead with hard delete
