### ISSUE TITLE
Accounts: Profile Picture not getting updated

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6171]
**Describe the bug**

Profile Picture not getting updated

**To Reproduce**

- Try to change your `Profile Image` in `Accounts`

**Expected behavior**

Should be done without any issue.

**Stacktrace**

```py
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/Users/kush/open-event-server/app/api/uploads.py", line 15, in upload_image
    extension = '.{}'.format(image.split(";")[0].split("/")[1])
IndexError: list index out of range
```

**Comment by prateekj117** [comment]
Not facing this issue. @uds5501 @mrsaicharan1 @shreyanshdwivedi Are you able to reproduce it locally?

**Comment by prateekj117** [comment]
Ok, turns out I am not able to update profile picture from `non-null` to `null`

**Comment by mrsaicharan1** [comment]
@kushthedude @prateekj117 Works fine in all cases.

**Comment by prateekj117** [comment]
@mrsaicharan1 Have you tried with open-event-frontend? Change avatar from `non-null` to `null`.

**Comment by mrsaicharan1** [comment]
Yes

**Comment by kushthedude** [comment]
Will check again and not ,will close the issue

**Comment by mrsaicharan1** [comment]
So, I've checked again. This is happening by chance. Sometimes it's happening, sometimes it isn't so let's keep it open.

**Comment by kushthedude** [comment]
Was the stacktrace same @mrsaicharan1 ?

**Comment by kushthedude** [comment]
> So, I've checked again. This is happening by chance. Sometimes it's happening, sometimes it isn't so let's keep it open.

@mrsaicharan1, It's occurring at every place where we are using the Image Upload tool, and
```py
File "/Users/kush/open-event-server/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/Users/kush/open-event-server/app/api/uploads.py", line 15, in upload_image
    extension = '.{}'.format(image.split(";")[0].split("/")[1])
IndexError: list index out of range
```
with this stacktrace, Were you able to reproduce it ?

**Comment by uds5501** [comment]
@kushthedude Please tell me a few things about this issue -

- Was the celery on and working during this report?
- What are the types of images which shows this error (extensions)

Also is there anything particular which comes up during this issue?

**Comment by kushthedude** [comment]
Celery was on during it

**Comment by kushthedude** [comment]
Some index error was there in upload.py

**Comment by iamareebjamal** [comment]
Paste the output of image variable - image

**Comment by shreyanshdwivedi** [comment]
@kushthedude can you check if this is still reproducible?

**Comment by uds5501** [comment]
Working now
