### ISSUE TITLE
Wrong links of images when fetching user details in development instance

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6174]
**Describe the bug**

GET `/v1/users/{user_id}`

Response contains wrong URLs of images, starting with `http://localhost/static/media/users/`.

Issue exists only for the development instance. Correct links are received for the production instance.

**Expected behavior**

Links should start with `https://open-event-api-dev.herokuapp.com/static/media/users/`.

**Comment by shreyanshdwivedi** [comment]
@ShridharGoel where is this data you are fetching from?

**Comment by ShridharGoel** [comment]
@shreyanshdwivedi Are you taking about the endpoint? I've already mentioned it in the issue.

**Comment by shreyanshdwivedi** [comment]
@ShridharGoel not endpoint. Actually what is the url of server which you're fetching it from? Just wanted to check once where problem could reside

**Comment by iamareebjamal** [comment]
open-event-api-dev.herokuapp.com

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi I'll take a deeper look into this.

**Comment by uds5501** [comment]
Fixed by @CosmicCoder96
