### ISSUE TITLE
Owner unable send  any role invite

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6179]
403: Organizer access is required.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I just sent successful role invite. Can you please give more info like what was the role u are inviting?
```js
attributes | {…}
created-at | 2019-07-11T21:50:50.333Z
email | test@gmail.com
hash | null
role-name | organizer
status | pending
relationships | {…}
event | {…}
data | {…}
id | 25
type | event
role | {…}
data | {…}
id | 1
type | role
type | role-invite
```

**Comment by CosmicCoder96** [comment]
The database had given the owner role to someone other than the creator of the event for nextcloud event. Not sure if it's a trend and migrations were wrong, or if they were indeed created by someone, else. Have manually updated the production Db user event roles table for now.

**Comment by CosmicCoder96** [comment]
Actually letting it remain open, need to check for some other events which were created on legacy server, and imported here.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 are we good to close this issue?

**Comment by CosmicCoder96** [comment]
Yes, invites seem to be working now.
