### ISSUE TITLE
Docs: Update order expiry time Admin Only tag

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#6185]
![image](https://user-images.githubusercontent.com/27783786/61132155-6c659a80-a4d8-11e9-9ef9-dd61e681c69e.png)

https://github.com/fossasia/open-event-attendee-android/pull/2104#discussion_r302898824

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by shreyanshdwivedi** [comment]
@liveHarshit I can retrieve `order-expiry-time` even without login
This is the code -
```
if 'Authorization' in request.headers:
            _jwt_required(app.config['JWT_DEFAULT_REALM'])

            if current_user.is_admin or current_user.is_super_admin:
                self.schema = SettingSchemaAdmin
            else:
                self.schema = SettingSchemaNonAdmin
        else:
            self.schema = SettingSchemaPublic
```
And `SettingSchemaPublic` has `order_expiry_time`.
If you go to your browser and hit url - `http://localhost:5000/v1/settings` then alo you can view `order-expiry-time` in the response (keep server up and running).
I think you're not using dev branch. Please take a look and let me know if you still face any difficulty.

**Comment by liveHarshit** [comment]
@shreyanshdwivedi Yes I'm also able to get through the browser, will check again the implementation in Android. Now the docs need to be update. :+1:

**Comment by shreyanshdwivedi** [comment]
Will update the docs :)

**Comment by kushthedude** [comment]
> Will update the docs :)

Why does the client need to see expiry-time?

**Comment by iamareebjamal** [comment]
To show to the user

**Comment by sameshl** [comment]
@iamareebjamal I want to take this up but I don't exactly understand what I have to do here. Should i change `Yes` to `No` in the tab?

**Comment by kushthedude** [comment]
@sameshl Feel free to solve the issue.

**Comment by sameshl** [comment]
@kushthedude I have to only change the tab value from `Yes` to `No` right?

**Comment by kushthedude** [comment]
Yes ,I think so
