### ISSUE TITLE
Lowercase email migration not being called

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6187]
For some reason, migration 7bb5891a9f2e_lowercase_email.py is not being called on new db creations, that is why the citext extension wasn't created and devs were encountering errors

This would most probably be due to some merge conflict and erroneous linking to previous migration. In this way, multiple migrations may have been knocked out of the chain.

This was called on production DB, so we need to think of a way to reintroduce orphan migrations without breaking the production DB

**Comment by prateekj117** [comment]
@uds5501 Why was this closed?

**Comment by prateekj117** [comment]
Output of 'python3 manage.py db history'

![Screenshot from 2019-08-19 22-28-16](https://user-images.githubusercontent.com/31065687/63284280-ce33d400-c2d0-11e9-9f3b-a5b032cda9c4.png)

**Comment by iamareebjamal** [comment]
Create a new project and run migrations and see

**Comment by prateekj117** [comment]
@iamareebjamal Oh ya.

**Comment by prateekj117** [comment]
Created a new database.

![Screenshot from 2019-08-21 22-02-18](https://user-images.githubusercontent.com/31065687/63450329-65c72d00-c45f-11e9-8cda-daf7b12c7fc4.png)

**Comment by iamareebjamal** [comment]
Strange. Closing
