### ISSUE TITLE
Add Foreign keys to Invoice model

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6195]
**Is your feature request related to a problem? Please describe.**
Currently, Event Invoice does not link to an order. This should be linked as it would  help in the integration of invoice payments with the order workflow

**Additional context**
Working on it.

**Comment by iamareebjamal** [comment]
Now that I think of it, this will require change in every query where Order is used and in relationship as well. This will be a no go. Please create a new table for it and add order as foreign key, which will both save the work and not break existing code

Reverting the PR

**Comment by mrsaicharan1** [comment]
@iamareebjamal Yes, I was dubious about this because of this. Event Invoice table is already present so I'll just use it.

**Comment by mrsaicharan1** [comment]
@iamareebjamal Just a question. The orders would still have to be recorded onto the Order model right?
Wouldn't it interfere in every query where Order is used(as this order is payment for event invoice)?

**Comment by iamareebjamal** [comment]
Why will order be inserted? It'll already be there in the table, right?
