### ISSUE TITLE
Nextcloud session throws a 500 error on visiting

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6212]
Nextcloud session throws a 500 error on visiting

https://eventyay.com/events/70d8ad61/sessions/5344

**Comment by uds5501** [comment]
@CosmicCoder96 stack trace?

**Comment by CosmicCoder96** [comment]
Fixed in the production DB. Between the releases, before validations were reinstated, an invalid github URL for a speaker was present.
