### ISSUE TITLE
Event Export: Download Link points to localhost on production

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6213]
After `Event Export` is done, The download link points to `localhost:`.

![image](https://user-images.githubusercontent.com/44091822/61503875-ef19b880-a9f6-11e9-9142-c526a6af0291.png)

**Comment by mrsaicharan1** [comment]
Will fix this

**Comment by kushthedude** [comment]
@mrsaicharan1 Is the issue you created is its replica?

**Comment by mrsaicharan1** [comment]
This is a bit different than the other one

**Comment by kushthedude** [comment]
So this means the recent PR don't solves this.

**Comment by mrsaicharan1** [comment]
It does.

**Comment by prateekj117** [comment]
@mrsaicharan1 The problem is with the received download link in the Email as well.
