### ISSUE TITLE
empty_string() needs a rewrite

### ISSUE THREAD

**Issue by cclauss** [fossasia/open-event-server#6221]
**Describe the bug**

https://github.com/fossasia/open-event-server/blob/development/app/api/helpers/utilities.py#L28-L34 is exceedingly convoluted, does `__type(x)__` compares contrary to PEP8, and contains several logic errors.  A code review of this function would be a worthwhile effort.  Some `__doctests__` would really be helpful here.

**To Reproduce**

**Expected behavior**

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

**Comment by iamareebjamal** [comment]
Yup. it was created when Python 2 to 3 migration/compatibility was needed

**Comment by iamareebjamal** [comment]
There are unit tests. The behaviour is flaky though. None should return True, it is returning False

https://github.com/fossasia/open-event-server/blob/ff408e557f6ff12e37e72a5201d110d589ce50e3/tests/all/integration/api/helpers/test_utilities.py#L32

**Comment by cclauss** [comment]
Perhaps add a few more tests for clarity:
```python
self.assertTrue(string_empty('  '))  # <space><space>
self.assertTrue(string_empty(' ' * 20))  # <space> * 20
self.assertFalse(string_empty(0))  # an int
self.assertFalse(string_empty(0.0))  # a float
self.assertFalse(string_empty([]))  # a list
self.assertFalse(string_empty(False))  # a bool
```

**Comment by cclauss** [comment]
self.assertTrue(string_empty('\t  \n'))  # <tab><space><return

**Comment by cclauss** [comment]
Does this codebase still support Python 2 or not?

**Comment by cclauss** [comment]
From README.md it looks like legacy Python can be dropped so:
```python
def string_empty(value: str) -> bool:
    if isinstance(value, str):
        return not value.strip()
    return False
```

**Comment by iamareebjamal** [comment]
```python
def string_empty(value: str) -> bool:
    return isinstance(value, str) and not value.strip()
```
