### ISSUE TITLE
URL in ticket confirmation mail is hardcoded to eventyay.com

### ISSUE THREAD

**Issue by yitzikc** [fossasia/open-event-server#6232]
The ticket-purchased and ticket-cancelled message templates have the phrase '.Login to manage your orders at https://eventyay.com' hardcoded. 

**Affected Version**
Backend 1.3.0
Frontend 1.1.0

**To Reproduce**
* Set the frontend URL in system settings to something other than eventyay.com
* Have a ticket purchase / cancel message sent to you.

**Expected behaviour**
The messages should include the frontend URL specified in system settings.

**Comment by mrsaicharan1** [comment]
Will fix this right away

**Comment by iamareebjamal** [comment]
Please search all instances of eventyay.com and replace
