### ISSUE TITLE
User can publish past events

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6244]
**Describe the bug**
Past draft events can be published

**To Reproduce**
Create a draft event with today's date. Publish it tomorrow.

**Expected behavior**
Publishing past draft events should fail

**Comment by shreyanshdwivedi** [comment]
So if the draft is created within 24 hours, then only it should be publishable?

**Comment by iamareebjamal** [comment]
No, if my draft says it event starts on a past date, it should not be publishable. I thought this was already handled in the date verifications

**Comment by shreyanshdwivedi** [comment]
Okay. The date check is updated to check only if event date is changed. It was necessary for few checks. 
I'll add condition for this transition to check date.

**Comment by iamareebjamal** [comment]
It should be able to create a draft event with past date but not publish. I think this will also make it easier to restore events. So when you restore event, if it has past date, make it a draft
