### ISSUE TITLE
Implementation of PayTM Payment Gateway

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6247]
**Feature Description & Workflow**
Integration of PayTM payment gateway is required to boost sales in India. The workflow would be in the following way

1. When an order is placed, we generate the checksumhash on the server-side.
2. to obtain the txn token, a call is to be made to the `Initiate Transaction API` with the checksum & parameters.
3. We fetch the available Payment Options from the `Fetch Payment Option API`.
4. User selects a payment option as Pay using PayTM
5. User enters mobile number linked to PayTM. Calls `Send OTP API` & `Validate OTP API`.
6. Call the `Transaction Status API` to verify the transaction response **[essential]**
7. Redirect the user to the appropriate order page in accordance with the response

**Comment by iamareebjamal** [comment]
Please implement the endpoint in a way it is also usable on Android

**Comment by mrsaicharan1** [comment]
> Please implement the endpoint in a way it is also usable on Android

Yeah, will take care.

**Comment by kushthedude** [comment]
@mrsaicharan1 Please tell me if you need any help with FE or Server for the implementation as you are working on other bugs and feature too.
