### ISSUE TITLE
Use event identifier instead of event id, in the URLs to fetch discount codes

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6250]
@iamareebjamal Regarding the recent refactors in discount codes, we have to provide the event id, can we instead switch it to using an identifier instead of the id? As that is what all public event related routes use to refer to it, and also identifiers are the primary key for the FE while dealing with the event.

**Comment by iamareebjamal** [comment]
Support both. Event IDs are the primary keys in both DB and mobile
