### ISSUE TITLE
Redundant code in CustomFormDetail

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6252]
**Describe the bug**
In the `before_get_object`, we are checking for event_id, while we have no Url which is trying to get custom form using the event_id. Just one plain simple custom-forms/<int:id>.

**Additional context**
On it.

**Comment by smdp2000** [comment]
@prateekj117 i would like to work on this issue

**Comment by prateekj117** [comment]
@smdp2000 Go ahead.

**Comment by uds5501** [comment]
Not of priority rn
