### ISSUE TITLE
Server checks for ticket prices are missing

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6280]
**Describe the bug**
Server checks are required for ticket prices. This would also allow decimal values greater than zero to pass through [similar to eventbrite]

**Additional context**
Corresponding FE PR which requires these checks : https://github.com/fossasia/open-event-frontend/pull/3341

**Comment by ashutosh1919** [comment]
@mrsaicharan1 Please see my closed branch which passes all the integration tests and change accordingly.
