### ISSUE TITLE
API for order creation with attendee info using a single endpoint

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#6320]
**Is your feature request related to a problem? Please describe.**
Parent Issue - https://github.com/fossasia/open-event-server/issues/6302
API for order creation with attendee info using a single endpoint. It should not be needed to hit 30 endpoints to create an order

**Additional context**

On it

**Comment by iamareebjamal** [comment]
The first part would be to take in ticket info and quantity with optional discount code and return calculated price info with tax, discount code, access code calculation. Please create a sub-issue on it and first work on this

**Comment by shreyanshdwivedi** [comment]
Ok. On it

**Comment by prateekj117** [comment]
@iamareebjamal Next step?

**Comment by iamareebjamal** [comment]
Design API to create an order. Will take same input as the price calculation API, along with attendee information as well and will create an order
