### ISSUE TITLE
Add paytm variables to event model

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-server#6340]
**Is your feature request related to a problem? Please describe.**

Parent issue - https://github.com/fossasia/open-event-server/issues/6247
As we are moving forward with paytm now, we should have variables to ask organizer about their info if they want to link paytm to their event as a payment gateway

**Describe the solution you'd like**

I'll add new fields required for paytm to event model

**Additional context**

On it

**Comment by Abhi-khandelwal** [comment]
Hey @shreyanshdwivedi , I would like to work on this issue.

**Comment by shreyanshdwivedi** [comment]
@Abhi-khandelwal actually we are having discussions about this feature since a week ago and I've already made changes locally.
 I think you should start with some beginner friendly issues.
