### ISSUE TITLE
Implement routes for initiating transactions with PayTM

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6341]
**Feature Description**
Sub issue #6247 
This is the first stage in the payment workflow where a request with appropriate headers is sent to the transaction API to obtain txn token.
We'll be using this txn token to further proceed with the processing of payments.

**Comment by thesmallstar** [comment]
Can I work on this?

**Comment by mrsaicharan1** [comment]
This is already being worked upon. Please take another issue :)
