### ISSUE TITLE
Stripe client ID disappears automagically

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6347]
Stripe client ID disappears from the setting table from DB automatically after some time. Most likely when a new PR is merged and the deployment is made on heroku

Happened thrice by now.
Live secret and publishable key also vanish :tada: but test keys remain.

This is a very neat trick, but we need to get this resolved

**Comment by CosmicCoder96** [comment]
@iamareebjamal 
culprit 😈 : https://github.com/fossasia/open-event-server/blob/735dac3f8bb00f63659e5ecd1f7f2322f9cfcac9/populate_db.py#L90

Should we remove them from there or add config vars for heroku?

**Comment by iamareebjamal** [comment]
Thought so. 

Remove this code. As there will always be a conflict on whether to pick value from DB or environment variable. Since we are preferring the frontend UI, it should not be picked up from environment variable
