### ISSUE TITLE
Attendee pdf URL is not working

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#6364]
Fixes https://github.com/fossasia/open-event-attendee-android/issues/2273

https://open-event-api-dev.herokuapp.com/generated/tickets/orders/tickets/pdf/6cbaf31d-7d10-4b8d-b22c-5be61209ad1d/MnNBVEJ1Q1/6cbaf31d-7d10-4b8d-b22c-5be61209ad1d.pdf

![image](https://user-images.githubusercontent.com/27783786/63048465-40cd3a00-bef4-11e9-8554-056c5156316b.png)

![image](https://user-images.githubusercontent.com/27783786/63048430-2b581000-bef4-11e9-871b-1bbd0fea4f6e.png)

**Comment by prateekj117** [comment]
@liveHarshit Looking into it.

**Comment by prateekj117** [comment]
@iamareebjamal The url generated has the correct path. I think it's because flask does not simply serve static files with path url specified. Am I right?

**Comment by iamareebjamal** [comment]
That statement makes no sense to me. See how it is being shown on frontend and specify here

@mrsaicharan1 Please take a look

**Comment by mrsaicharan1** [comment]
@iamareebjamal I will take a look at what’s wrong

**Comment by prateekj117** [comment]
@iamareebjamal so say I want to serve a pdf whose path url is: `(root project directory)/abc/abc.pdf`.
So if we start the server, and go to `localhost:5000/abc/abc.pdf`, will we get that pdf on browser? If not, I think the pdf rendering is working that way. It has the directory path url after `localhost:5000`

**Comment by mrsaicharan1** [comment]
@prateekj117 The files would be served over a route which handles security & other aspects. Check `app/api/helpers/auth.py`

**Comment by mariobehling** [comment]
Implementation has changed. Therefore closing this.
