### ISSUE TITLE
Generated event invoices have a default state of 'pending'

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#6368]
**Describe the bug**

Any new event invoice being generated have a default state of `pending` which shouldn't be the case.

![Screenshot from 2019-08-16 17-30-12](https://user-images.githubusercontent.com/21087061/63166368-d3ccb800-c04b-11e9-833d-a17c8da3d8c0.png)

**Expected behavior**

The default state should be of `due`

**Comment by kushthedude** [comment]
@uds5501 How are event invoiced getting generated? On what basis ?
