### ISSUE TITLE
Increase dredd timeout

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6372]
dredd has been timing out a lot lately. Increase the timeouts

Also, dredd 4.0 is ancient. It hasn't been updated since dredd tests were added in the repo. Use latest one

**Comment by kushthedude** [comment]
@iamareebjamal For the second part, Is there anything rather than updating Dredd in `.yml` ?

**Comment by iamareebjamal** [comment]
Yes, you'll have to fix any deprecations
