### ISSUE TITLE
Add cache for npm

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6374]
There is no cache for npm in Travis

Also, avoid global installation and use npx instead

**Comment by moulikcipherX** [comment]
Anyone is working on this issue?

**Comment by iamareebjamal** [comment]
No

**Comment by asha15** [comment]
@iamareebjamal Shall i try this?

**Comment by iamareebjamal** [comment]
Hi, I forgot to update this, but all npm commands have shifted to circle CI with caching enabled, so this issue is invalid. There are other issues open, please find one.
