### ISSUE TITLE
Make API documentation compatible with latest dredd

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6377]
2 tests are failing on latest dredd. https://travis-ci.org/fossasia/open-event-server/builds/572997848?utm_source=github_status&utm_medium=notification

Fix them

Also, remove the warnings about API documentation

**Comment by integral-rip** [comment]
hey, can i work on it

**Comment by iamareebjamal** [comment]
Not worth it as some of the warnings are deliberate
