### ISSUE TITLE
Separate dredd and test tasks and add stages

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6379]
Dredd takes 18 minutes to run and then tests run in 4 minutes. Both have no connection and running them parallelly will reduce the build time.

4 minutes of reduction is not the biggest feature though. More importantly, we'll have better understanding of what fails (dredd or tests) instead of having dredd time out or fail without nosetests running

Another stage will be introduced which will run once both tasks have passed

**Comment by aryan2305** [comment]
Hi, I would like to work on this issue. This will be my first pull request here. Can you help me with where to start?

**Comment by iamareebjamal** [comment]
Read the travis docs about stages and reconfigure the config in .travis.yml

**Comment by iamareebjamal** [comment]
Done
