### ISSUE TITLE
Anyone can edit details of other users

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6381]
**Describe the bug**
`PATCH` request to edit details of any user on production instance gets executed successfully which is a serious security issue.

While on the dev instance, `Access Forbidden` error is thrown, which is the correct behaviour.

**Comment by ShridharGoel** [comment]
@iamareebjamal @CosmicCoder96

**Comment by mrsaicharan1** [comment]
I’ll fix this

**Comment by prateekj117** [comment]
@mrsaicharan1 May I take this one up?

**Comment by prateekj117** [comment]
Looking into it.

**Comment by mrsaicharan1** [comment]
@prateekj117 if this issue isn’t present on the Dev server(which will
eventually be merged into master), is this still valid?

**Comment by ShridharGoel** [comment]
Dev server does not mean the dev branch, it means the debug instance of the
server being used for testing purposes.

**Comment by prateekj117** [comment]
@ShridharGoel Which is in sync with the current commits, right? I think it's not valid in that case @mrsaicharan1 .

**Comment by ShridharGoel** [comment]
Okay, in that case we should wait for @iamareebjamal to confirm whether it's valid or not.

**Comment by iamareebjamal** [comment]
I mean find why it is happening at least. What if it only happens due to ProductionConfig.

Go back in commit history and find the faulty commit and then we can close it

**Comment by prateekj117** [comment]
@iamareebjamal On it.

**Comment by iamareebjamal** [comment]
Closing since no investigation carried on
