### ISSUE TITLE
Add placeholder for FE version in Release Drafter

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6388]
Add a placeholder for FE version in Release Drafter configuration as done in FE

**Comment by sameshl** [comment]
@kushthedude I would love to work on this. Can you elaborate a bit on the issue

**Comment by kushthedude** [comment]
@sameshl See this https://github.com/fossasia/open-event-frontend/commit/ba2c6c3b0fe48d9e4466ec5af5133a38ec1dec79

**Comment by akshat0047** [comment]
I would like to implement this small fix @kushthedude

**Comment by divyanshutewari17** [comment]
I would love to work on this. Can you please elaborate the issue?

**Comment by mariobehling** [comment]
Closing this as there has been some work in this area already been done.
