### ISSUE TITLE
Rename association table to a proper name

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6389]
There's a table called association

Can anyone guess what it is used for?

That's right. Linking ticket tags and tickets. So obvious...

**Comment by GeniusLearner** [comment]
@iamareebjamal I am a newcomer and I want to take this issue.

**Comment by kushthedude** [comment]
Go on

**Comment by GeniusLearner** [comment]
Hi, @kushthedude could you help me with this.
I am new to the community and open source.

**Comment by prateekj117** [comment]
@iamareebjamal On it.
