### ISSUE TITLE
All URLs of event are on localhost

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6392]
Pentabarf, iCal, xCal URLs are all on localhost

https://open-event-api-dev.herokuapp.com/v1/events/7

**Comment by ashwani99** [comment]
@iamareebjamal Can I take this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by ashwani99** [comment]
@iamareebjamal Can you please help me reproduce the error in local? I have tried creating new events but they all are having `i_cal`, `x_cal` values to be `null`
