### ISSUE TITLE
Wrong number of speakers

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6393]
**Describe the bug**
https://eventyay.com/e/c0e175a3
Event has only 1 speaker but number of confirmed speakers is being shown as 5 on both frontend and Android.

![Number of speakers issue](https://user-images.githubusercontent.com/35566748/63229484-42616f80-c21e-11e9-88d8-8e6c6434a02d.png)

**Comment by shreyanshdwivedi** [comment]
Will check

**Comment by shreyanshdwivedi** [comment]
@ShridharGoel is the speaker associated with 5 confirmed sessions?

**Comment by ShridharGoel** [comment]
No, 3 confirmed sessions.

**Comment by shreyanshdwivedi** [comment]
@ShridharGoel  I checked the db and relationships. I think I know the probable cause. Can you tell me if you have deleted sessions that were assigned to the speaker earlier? If yes, how many sessions were there?

**Comment by ShridharGoel** [comment]
Yes I think I had deleted sessions when I was making changes to the schedule, though I don't remember how many. But there were no changes in the number of speakers.

**Comment by shreyanshdwivedi** [comment]
Ok. @iamareebjamal @ShridharGoel  the error here is we have tables `sessions`, `speakers` and `sessions_speakers_links` in the db. The table `sessions_speakers_links` is used to establish relationship between speakers and sessions and also to retrieve speaker count. But when a session is deleted it is not reflected in this table and so deleted session and speakers are being counted too.

**Comment by iamareebjamal** [comment]
> and also to retrieve speaker count

Why?

>  it is not reflected in this table and so deleted session and speakers are being counted too.

It doesn't need to be reflected. Deleted speakers should be filtered out

**Comment by soumya-ranjan7** [comment]
@shreyanshdwivedi Can I take up this issue?

**Comment by shreyanshdwivedi** [comment]
@soumya-ranjan7 I'll suggest you to try out some beginner friendly issues first to get the understanding of codebase.
