### ISSUE TITLE
Wrong error and pointer for unverified user

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-server#6394]
Reference: https://github.com/fossasia/open-event-attendee-android/pull/2287#discussion_r314992174

![image](https://user-images.githubusercontent.com/27783786/63244440-027ca580-c27b-11e9-8f69-552c0596d74d.png)
![image](https://user-images.githubusercontent.com/27783786/63244456-0c9ea400-c27b-11e9-985e-154010904a27.png)

**Comment by shreyanshdwivedi** [comment]
So you need error `Please verify your account to order free tickets`? And pointer?

**Comment by liveHarshit** [comment]
> So you need error `Please verify your account to order free tickets`? And pointer?

@iamareebjamal

**Comment by iamareebjamal** [comment]
user should be pointer. UNAUTHORIZED should be the error

**Comment by liveHarshit** [comment]
> user should be pointer. UNAUTHORIZED should be the error

Shouldn't it be unverified?

**Comment by shreyanshdwivedi** [comment]
I think the error earlier was fine - 'Unverified user cannot buy free tickets'. @liveHarshit?

**Comment by iamareebjamal** [comment]
There is no UNVERIFIED HTTP status code https://httpstatuses.com/401

However, I was wrong, it should be 403 FORBIDDEN

HTTP spec should be changed. 401 UNAUTHORIZED should be UNAUTHENTICATED and 403 FORBIDDEN should be UNAUTHORIZED

**Comment by liveHarshit** [comment]
> I think the error earlier was fine - 'Unverified user cannot buy free tickets'. @liveHarshit?

It's detail, see the error title.
