### ISSUE TITLE
Return list of completed attendees instead of all

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-server#6396]
**Describe the bug**
While fetching the list of attendees using the endpoint `events/{id}/attendees` all attendees are returned while only completed attendees should be returned.

**Comment by kushthedude** [comment]
@ShridharGoel What do you mean by completed attendee ?

**Comment by ShridharGoel** [comment]
@kushthedude Check out the attendees page of any event of yours on the frontend. There you will see the various categories. Completed attendee basically means an attendee with a completed order.

**Comment by kushthedude** [comment]
All attendees should be returned, and for completed we can apply sort filters.
@iamareebjamal ?

**Comment by ShridharGoel** [comment]
@kushthedude Check this: https://gitter.im/fossasia/open-event-organizer-android?at=5d5aa53353490e334d21dcd4

**Comment by kushthedude** [comment]
> @kushthedude Check this: https://gitter.im/fossasia/open-event-organizer-android?at=5d5aa53353490e334d21dcd4

What about the attendee with offline tickets @ShridharGoel , They have status of placed.

**Comment by iamareebjamal** [comment]
@kushthedude Server should only return valid values by default without filtering. If more are required, they are be queried explicitly

**Comment by prateekj117** [comment]
@iamareebjamal Working on this.

**Comment by akshat0047** [comment]
I would like to take up this issue @iamareebjamal @prateekj117

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by akshat0047** [comment]
While solving the issue I've realized there is no documentation for the urls below(I checked them with find too):

- /events/{int:event_id}/attendees
- /events/{event_identifier}/attendees
- /users/{user_id}/attendees
- /tickets/{ticket_id}/attendees

But we have them in routes and all of them are working and described as routes 
![Screenshot_2019-11-13_01-13-07](https://user-images.githubusercontent.com/32462195/68705791-b8266e80-05b4-11ea-9335-8f957f7535b7.png)


Is this done with purpose or may I create an issue regarding this.
@iamareebjamal

**Comment by iamareebjamal** [comment]
Documentation as in API docs?

**Comment by akshat0047** [comment]
ok adding an issue.

**Comment by utkarsh2787** [comment]
i am a newbie...can i get the chance and assistance on how to contribute

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-server/pull/6594#issuecomment-738728679
