### ISSUE TITLE
Tickets not generated for all attendees in a 4 ticket order

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6419]
> We have booked 4 tickets for the upcoming conference in September (see 
attachment for invoice), however we encounter some small issues. May we 
please ask you help us out?

We have the following issues:

·3 of the 4 persons (except for ****) received an email, however 
the link to the ticket is not working (‘Not found’ error)

·The download of the tickets via the main page (where the tickets were 
bought) gives only 1 ticket for ****

**Comment by mrsaicharan1** [comment]
@iamareebjamal Instead of creating 4 different tickets(PDFs) for one order and sending them separately, wouldn't it be better to merge the info related to the attendees in one ticket which could be sent to the attendees on that order?

**Comment by iamareebjamal** [comment]
Yes, sounds better. But, then you can't have separate tickets for separate people making scanning difficult in my opinion

**Comment by mrsaicharan1** [comment]
We'd also need to refactor the generation of the QR code in such a way that it pulls the info about every attendee on that order, similar to other ticketing sites.

**Comment by iamareebjamal** [comment]
No, that is opposite of what we want. We want different QR for each person so it is easy to track individual attendee on organizer app

Also, we never make backward incompatible changes when dealing with mobile clients unless absolutely needed and critical. You'll make this change and it'll break every organizer app in the world

**Comment by mariobehling** [comment]
Seems to be working now.
