### ISSUE TITLE
Event on public page fails to open

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6423]
On eventyay.com, 
https://eventyay.com/e/78230603

This event is listed in the public page, but server cannot fetch it using it's identifier as the identifier is missing alphabets and thus is interpreted as an ID.

Ideal behavior: identifiers should always have letters in them.

Is the rationale correct @iamareebjamal

**Comment by CosmicCoder96** [comment]
As a temporary solution manually changing ID now.

**Comment by iamareebjamal** [comment]
Yes, it is correct

**Comment by prateekj117** [comment]
@iamareebjamal On it.
