### ISSUE TITLE
Admin: Add gMap keys fields in settings

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6424]
Please See https://github.com/fossasia/open-event-frontend/issues/3484

**Comment by prateekj117** [comment]
@kushthedude Will be taking a look into it.

**Comment by kushthedude** [comment]
@prateekj117 Please take a look at FE once, since its a external dependancy, I dont think we can extract the key in our FE config

**Comment by akshat0047** [comment]
I think this issue too needs to be closed as we're shifting away from google maps fossasia/open-event-frontend#3484

@prateekj117
