### ISSUE TITLE
Enhance csv ticket export

### ISSUE THREAD

**Issue by jospoortvliet** [fossasia/open-event-server#6426]
In the ticket view is a nice export button. I'd like to have it expanded to all relevant info, including address data, nr and details of ticket holders, payment details etc. This is useful for further processing and tracking of attendees & payments!

In our case, we send invoices manually and we track the state in a spreadsheet.

**Comment by amansheaven** [comment]
So by that you mean you want a enhanced api that could deliver event details in a .xls sheet?? The one you were able to procure was from 
`GET  /v1/events/{event_identifier}/export/orders/csv ` 
on open event server. It's not such a big feature but i would love to work on this once this get tagged by any contributor :)

If you need some more data sqeezed it maybe we can give that to you with a special API that just gives overview of the event, please mention the same if needed.

**Comment by mariobehling** [comment]
Thank you. Most information of custom forms etc. has already been added to the CSV. Remaining is to add payment method and billing information which we will track through this issue here https://github.com/fossasia/open-event-server/issues/8009
