### ISSUE TITLE
Add fields regarding `Billing Info` on choice of Attendee or Organiser

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6444]
Parent Issue https://github.com/fossasia/open-event-frontend/issues/3518

Changes to be done:
- Addition of field `is_billing_info_enabled_by_organiser`
- Addition of field `is_billing_info_filled_by_attendee`

**Comment by iamareebjamal** [comment]
Why is this field needed? `is_billing_info_filled_by_attendee`

**Comment by kushthedude** [comment]
> Why is this field needed? `is_billing_info_filled_by_attendee`

To check if an attendee is willing to fill billing information or not, If filled, To store the info and use the following boolean to display it in order details too.

**Comment by iamareebjamal** [comment]
If the attendee is willing to enter the information, he/she will enter it. What will this field accomplish?

**Comment by kushthedude** [comment]
The idea is to give a checkbox if attendee wants to enter he will tick it

**Comment by iamareebjamal** [comment]
The checkbox is purely frontend component just to show/hide the form. It has no relevance in context of server or DB
