### ISSUE TITLE
Correct API docs of update orders

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6451]
**Describe the bug**
The `PATCH` request for orders API docs shows identifier instead of the id as the value of `id` in body of the request, which actually shows an error when used. 

**Expected behavior**
API docs should have id there to prevent confusion and error for someone simply following the documentation.

**Additional context**
Feel free to take this up.

**Comment by sameshl** [comment]
@prateekj117 I would love to take it up. Working on it right away!

**Comment by prateekj117** [comment]
@sameshl Go ahead.

**Comment by Tlazypanda** [comment]
@prateekj117 can I work on this issue?

**Comment by prateekj117** [comment]
@Tlazypanda There is already a PR opened, but as it is stale, I will close that one. You go ahead with a new one.

**Comment by Tlazypanda** [comment]
@prateekj117 have opened a pr for the same.Kindly look into it.
