### ISSUE TITLE
Migrate Classes from Python 2->3

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-server#6452]
**Describe the feature**
Some classes which are currently defined throughout the codebase are pertinent to Python2. Python3 Styled syntax is required.

**Comment by iamareebjamal** [comment]
I don't understand what's the difference

https://github.com/fossasia/open-event-server/blob/development/app/api/activities.py

Seems like Python3 to me.

Maybe change schemas and models to dataclasses? 

https://docs.python.org/3/library/dataclasses.html

**Comment by mrsaicharan1** [comment]
`app/api/helpers/payment.py`
The representation of Classes in this file and many other places are written as `class PaymentsManager(object):` which is Python2.
You don't need to subclass the object in Python3.  Classes are defined like this
`class PaymentsManager:`

https://realpython.com/python3-object-oriented-programming/

**Comment by sameshl** [comment]
I would love to take this up @mrsaicharan1

**Comment by mrsaicharan1** [comment]
> I would love to take this up @mrsaicharan1. Working on it right away!

@sameshl Please check the assignees before claiming an issue.

**Comment by sameshl** [comment]
@mrsaicharan1 I didn't look at that. My bad
