### ISSUE TITLE
Make comment optional in feedback 

### ISSUE THREAD

**Issue by ranjsa** [fossasia/open-event-server#6459]
**Is your feature request related to a problem? Please describe.**
Writing comment should be optional in feedback , but right now it does not accept feedback without writing comment . 
![screen2](https://user-images.githubusercontent.com/43692789/65375714-3867dc00-dcb6-11e9-9e63-c7b5b6f88011.png)

**Describe the solution you'd like**
I want to change the code in server to accept empty comment with just rating . 
**Additional context**
I am working on it.

**Comment by kushthedude** [comment]
The following is the issue from `Client Side`, On the server, the comment is already optional, As we are also using `Feedbacks` in the web client.
