### ISSUE TITLE
Allow getting tickets without logging in

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-server#6461]
**Is your feature request related to a problem? Please describe.**
It's with reference to the issue created in Open Event attendee project. [Issue #1869](https://github.com/fossasia/open-event-attendee-android/issues/1869)

**Describe the solution you'd like**
Allowing users to allow buying tickets without logging in. Currently, there's an issue from server side to implement it. A user has to be authenticated while fetching custom forms. So please remove the check for authentication in case of custom forms.

**Comment by kushthedude** [comment]
@iamareebjamal For the guest orders, We are following when the user creates the `Order` after entering his `Email ID`, We mail him the `password reset link` and make his account. So I think there is no issue from the server-side. As the following is also followed in `Event Brite`. Hence I think its a vague issue.

**Comment by iamareebjamal** [comment]
How will the user create order when custom form is only allowed to be seen by authenticated user?

**Comment by kushthedude** [comment]
> How will the user create order when custom form is only allowed to be seen by authenticated user?

If thats the case, Than the following must be the issue on `Web Client` too ?

**Comment by iamareebjamal** [comment]
How are they working. What is the flow exactly. AFAIK it does not match that of eventbrite

**Comment by tronku** [comment]
Any updates on the issue?

**Comment by iamareebjamal** [comment]
@kushthedude What's the workflow?

**Comment by kushthedude** [comment]
This is:
- User enters his email and if the email is not associated with any previous user, his account is created using following: 
```js
async createNewUserViaEmail(email) {
      this.set('isLoading', true);
      let newUser = this.store.createRecord('user', {
        email,
        'password'               : (Math.random() * 10).toString(16),
        'wasRegisteredWithOrder' : true
      });
```
- After this User is logged in to his account and also an email with password reset link is sent to him.

**Comment by iamareebjamal** [comment]
@tronku Please follow the same workflow for now. We'll be adding no authentication for free orders later on
