### ISSUE TITLE
Add server version and an API to show it

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6470]
- [x] README shows wrong release information, update it to correct release
- [ ] Add an API which shows the current version of the server.

**Comment by jatinAroraGit** [comment]
Hi there,
I would like to work on this issue.
Can you please assign it to me ?
Thanks.

**Comment by iamareebjamal** [comment]
You can start working on it

**Comment by lladhibhutall** [comment]
@iamareebjamal @prateekj117 
Would like like to take this issue! is the server version stored somewhere?

**Comment by prateekj117** [comment]
@lladhibhutall Go ahead. I don't think there is. @iamareebjamal Correct me if I am wrong.

**Comment by iamareebjamal** [comment]
No, it needs to be added as a constant in the project

**Comment by lladhibhutall** [comment]
Will create a new file in the root of the project named server_version.py which will have the endpoint returning the current version.

**Comment by iamareebjamal** [comment]
Create the file in app folder
