### ISSUE TITLE
Add name of the user who has submitted feedback with comment and rating 

### ISSUE THREAD

**Issue by ranjsa** [fossasia/open-event-server#6472]
**Is your feature request related to a problem? Please describe.**

Right now we are only getting comment and rating in the feedback submitted by a user , So we cant see who has actually posted the feedback . 
![WhatsApp Image 2019-09-29 at 8 21 48 AM](https://user-images.githubusercontent.com/43692789/65825288-d2212180-e292-11e9-9624-a179deaa5c8e.jpeg)

**Describe the solution you'd like**

Add name of the user  with rating and comment . in the feedback response .
```
{
  "meta": {
    "count": 1
  },
  "data": [
    {
      "relationships": {
        "event": {
          "links": {
            "self": "/v1/feedbacks/1/relationships/event",
            "related": "/v1/feedbacks/1/event"
          }
        },
        "user": {
          "links": {
            "self": "/v1/feedbacks/1/relationships/user",
            "related": "/v1/feedbacks/1/user"
          }
        }
      },
      "attributes": {
        "rating": "4",
        "deleted-at": null,
        "comment": "Awesome event"
      },
      "type": "feedback",
      "id": 1,
      "links": {
        "self": "/v1/feedbacks/1"
      }
    }
  ],
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/v1/events/1/feedbacks"
  }
}
``` 

**Additional context**
https://github.com/fossasia/open-event-attendee-android/pull/2366
I am working on it .

**Comment by akshat0047** [comment]
I would like to work on this issue @prateekj117 @iamareebjamal

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by akshat0047** [comment]
Referring to #6522 according to which user name is not to be implemented as an attribute, I went through the complete flask rest JSON API docs, we have to get the name using user relationship. But how can I proceed, I explored resource linkage, include=model. Do I need to query in resource manager? @iamareebjamal @prateekj117

**Comment by iamareebjamal** [comment]
You need to just link the user as a relationship. See any schema like event or speaker

**Comment by akshat0047** [comment]
> You need to just link the user as a relationship. See any schema like event or speaker

[Code](https://pasteboard.co/ICY8SWK.png)
I see it already linked in the file, the only change that can be made is to change the schema to UserSchemaPublic

**Comment by iamareebjamal** [comment]
You need to dynamically update the schema depending on the kind of user requesting the resource - admin or normal

**Comment by akshat0047** [comment]
ok

**Comment by akshat0047** [comment]
Actually, I can fix it with a lambda function like [this](https://pasteboard.co/ICZjqvj.png) but I see a check already defined in User Resource Manager for a detail view [this](https://pasteboard.co/ICZk8Jr.png). On testing API by clicking on the related link under relationships even if I hardcode it UserSchemaPublic, the before get validators again change it to UserSchema according to the check defined in the User. Also, the user name is served in both the schema, I think its already solved or should I implement this double-check lambda function

**Comment by akshat0047** [comment]
Please let me know if what I figured out is correct and this issue is invalid, else I will research more towards solution @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes, the issue is invalid
