### ISSUE TITLE
Monthly invoice mails are erroring out

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6486]
When deploying 1.6.2 last night, I noticed there are several errors in celery and APS and basically, no invoice email was sent most probably.

I could not copy logs as I was in middle of deployment. 

Write tests for the invoice mail generation and debug what could go wrong

**Comment by prateekj117** [comment]
@iamareebjamal On it.

**Comment by mrsaicharan1** [comment]
I'll take this up. I've also found out what happened here.
Because there was no ticket fee set up on the admin system, the emails started erroring out. 

```
  File "/Users/saicharan/Desktop/open-event-server/app/api/helpers/scheduled_jobs.py", line 253, in send_monthly_event_invoice
    db.session.query(TicketFees).filter_by(currency=currency).one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3332, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```
Will fix this up and add the test
