### ISSUE TITLE
Cron job for marking event invoices due is wrong

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6494]
PR https://github.com/fossasia/open-event-server/pull/6166 is wrong. The query fails in every case

https://github.com/fossasia/open-event-server/blob/bc45c1d267b924b556d36855f29c1dd96e901209/app/api/helpers/scheduled_jobs.py#L164-L174

This line is not valid SQLAlchemy syntax:

https://github.com/fossasia/open-event-server/blob/bc45c1d267b924b556d36855f29c1dd96e901209/app/api/helpers/scheduled_jobs.py#L169

`Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with EventInvoice.event has an attribute 'ends_at'`

It should be `db.session.query(EventInvoice).join(Event).filter(EventInvoice.status == 'upcoming', Event.ends_at >= datetime.datetime.now()).all()`

Each run of this task is failing

Fix it and write tests to ensure it is working

**Comment by arpit551** [comment]
@iamareebjamal I would like to take this one if no one is working on it.

**Comment by iamareebjamal** [comment]
Go ahead. This is high priority issue so please try to submit a PR within few days

**Comment by arpit551** [comment]
@iamareebjamal are there any tests written for scheduled jobs?

**Comment by iamareebjamal** [comment]
For some of them, it might be written, I'm not sure

**Comment by mrsaicharan1** [comment]
@arpit551 If you're pre-occupied elsewhere, I'll go ahead & fix this.

**Comment by iamareebjamal** [comment]
@mrsaicharan1 Please go ahead, this is high priority
