### ISSUE TITLE
Move APScheduler tasks and crons to celery

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6496]
100s of APscheduler tasks are failing with WORKER timeouts and throwing errors like `error with status PGRES_TUPLES_OK and no message from the libpq`

This happens due to connection sharing not working across processes. 

I thought APscheduler would be good enough for most things and celery was an overkill, but for python, due to its GIL, it's better to not use forking and use completely decoupled worker like celery.

Hence, move APscheduler tasks and crons to celery and use celery beat for cron

**Comment by himanshupathak21061998** [comment]
Hello, @iamareebjamal I want to solve this issue.
So, I have to do something like this https://stackoverflow.com/questions/1990531/how-can-i-schedule-a-task-to-execute-at-a-specific-time-using-celery
For all the tasks present here https://github.com/fossasia/open-event-server/blob/04ec741536c6974627b51edcc280ab078db84f44/app/__init__.py#L262

**Comment by iamareebjamal** [comment]
Not getting errors now after some refactoring, so not an issue for now
