### ISSUE TITLE
Run docker container as non root user

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6505]
Currently, the app and celery run as root in docker containers 

They should be run as normal users

**Comment by lladhibhutall** [comment]
@iamareebjamal This seems interesting, would like to take it.

**Comment by prateekj117** [comment]
@lladhibhutall Go ahead.

**Comment by pravarag** [comment]
@lladhibhutall are you working on it? otherwise I can take it.

**Comment by lladhibhutall** [comment]
@pravarag Yes still working on it.

**Comment by ashwani99** [comment]
Working on this

**Comment by codedsun** [comment]
@iamareebjamal What shall be the name of the user? in this command

`USER <your_user_name>`

**Comment by iamareebjamal** [comment]
open_event_user
