### ISSUE TITLE
dataclasses dependency not found

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6509]
**Describe the bug**
In PR #6466, dataclasses module was not added in requirements.txt 

**Additional context**
On it.

**Comment by mrsaicharan1** [comment]
Dataclasses come built-in with Python 3.7

**Comment by prateekj117** [comment]
@iamareebjamal @mrsaicharan1 Didn't know we are using 3.7 now. My bad. Closing this.
