### ISSUE TITLE
ICalExporter not working

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6511]
https://github.com/fossasia/open-event-server/blob/97e94f2ce14d20341253822b5456c93bef590c71/app/api/helpers/ICalExporter.py#L48-L53

There is no email attribute on event object.

Fix the method and write tests

**Comment by mrsaicharan1** [comment]
@iamareebjamal We have tests for ical exports. Will fix this method.

**Comment by iamareebjamal** [comment]
Yes, but we don't have tests which fail for this case which is equal to having no tests

**Comment by mrsaicharan1** [comment]
@iamareebjamal What kind of a privacy scenario are we considering here when it comes to using `speaker.email` ?

**Comment by iamareebjamal** [comment]
I don't know, maybe it's discussed on the PR in which it was implemented

**Comment by roshnet** [comment]
@iamareebjamal Based on my limited understanding of this issue, I need to ask how can an email be related to an event? Are we referring to the email of the organizer instead?

**Comment by iamareebjamal** [comment]
Yes, @roshnet, it's supposed to be the email of owner/organizer.
