### ISSUE TITLE
Event chip filter not working properly

### ISSUE THREAD

**Issue by tronku** [fossasia/open-event-server#6517]
**Describe the bug**
In the Events tab of the Attendee app, when a particular tag or chip of an event is clicked, it navigates to a search screen which shows results depending upon the chip. The issue is that the search gives results only if the first chip is selected not the other ones. On debugging, I noticed that everything is properly working on app side but no result is recorded from the backend side.

**To Reproduce**
1. Go to the Events tab.
2. Click on the first chip of any event.
3. The Search screen will open and will give the results.
4. Now, go back and select another chip.
5. The Search screen will open but will give no results.

**Expected behavior**
There should be at least one event in the results on all the chips.

**Additional details (please complete the following information):**
 - OS: Ubuntu

**Screenshot**
![ezgif-3-4bc813093069](https://user-images.githubusercontent.com/31654207/66405242-79c2f000-ea07-11e9-8e21-48372605cc8a.gif)

**Comment by kushthedude** [comment]
Shouldn't this be an issue on the client-side ?

**Comment by tronku** [comment]
I have checked on client-side. The app is sending the request to the server but no data is provided in the results. Please check it at server-side once too.

**Comment by iamareebjamal** [comment]
Please paste the URL generated

**Comment by lladhibhutall** [comment]
What is the status of the issue? Would like to take it if its a server side problem. @tronku  @prateekj117 @iamareebjamal

**Comment by iamareebjamal** [comment]
@tronku Please paste the API URL

**Comment by tronku** [comment]
https://open-event-api-dev.herokuapp.com/v1/events?include=event-sub-topic,event-topic,event-type&sort=name&filter={filter data}
here's the URL

**Comment by tronku** [comment]
filter data depends on some conditions like free event, speaker sessions and location. 
Here's an example - 
"and":[{
           "name":"location-name",
           "op":"ilike",
           "val":"%kolkata%"
        }, {
           "name":"name",
           "op":"ilike",
           "val":"%%"
        }, {
           "name":"event-type",
           "op":"has",
           "val": {
           "name":"name",
           "op":"eq",
           "val":"Auto, Boat & Air"
           }
        }, {
           "name":"ends-at",
           "op":"ge",
           "val":"%2019-10-17T14:42%"
        }
        ]
    }]

**Comment by iamareebjamal** [comment]
I understand, but you need to form an issue like this:

>
	Reproduction Steps:
	
	1. Visit the URL - <complete_url>
	2. Notice the events have these tags - party
	3. Now, visit this URL which filters events on basis of party - <complete_url>
	
	Expected:
	I expect it to give 3 events
	
	Actual:
	No events are returned

This is the easiest way for anyone working on the issue to confirm the bug, work on it and verify it has been fixed after solving it.

**Comment by iamareebjamal** [comment]
People working on server will not be able to go through the app and see where and what is wrong, it needs to be reported in context of the API, not the app

**Comment by tronku** [comment]
Okay, I got it. I will edit the issue description.

**Comment by iamareebjamal** [comment]
No, not a problem

**Comment by iamareebjamal** [comment]
`{"name":"ends-at","op":"ge","val":"%2019-10-17T15:01%"}`

This should be 
`{"name":"ends-at","op":"ge","val":"2019-10-17T15:01"}`

I'm not even sure why it was working before

**Comment by tronku** [comment]
So, is it working now?

**Comment by iamareebjamal** [comment]
You tell

**Comment by tronku** [comment]
but the same thing works with the first chip and % is added in every condition
this works -
https://open-event-api-dev.herokuapp.com/v1/events?include=event-sub-topic,event-topic,event-type&sort=name&filter=%5B%7B%0A%20%20%20%22and%22%3A%5B%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22location-name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ilike%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%25kolkata%25%22%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ilike%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%25%25%22%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22event-type%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22has%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22eq%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22Attraction%22%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22ends-at%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ge%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%252019-10-17T18%3A08%25%22%0A%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D%5D&page%5Bnumber%5D=1&page%5Bsize%5D=5

this doesn't -
https://open-event-api-dev.herokuapp.com/v1/events?include=event-sub-topic,event-topic,event-type&sort=name&filter=%5B%7B%0A%20%20%20%22and%22%3A%5B%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22location-name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ilike%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%25kolkata%25%22%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ilike%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%25%25%22%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22event-type%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22has%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22name%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22eq%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22Auto%2C%20Boat%20%26%20Air%22%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%22name%22%3A%22ends-at%22%2C%0A%20%20%20%20%20%20%20%22op%22%3A%22ge%22%2C%0A%20%20%20%20%20%20%20%22val%22%3A%22%252019-10-17T18%3A10%25%22%0A%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D%5D&page%5Bnumber%5D=1&page%5Bsize%5D=5

**Comment by iamareebjamal** [comment]
Thank you, finally you have given something to work with, excellent. Let's see

1. Works
```
[{
   "and":[{
       "name":"location-name",
       "op":"ilike",
       "val":"%kolkata%"
    }, {
       "name":"name",
       "op":"ilike",
       "val":"%%"
    }, {
       "name":"event-type",
       "op":"has",
       "val": {
       "name":"name",
       "op":"eq",
       "val":"Attraction"
       }
    }, {
       "name":"ends-at",
       "op":"ge",
       "val":"%2019-10-17T18:08%"
    }
    ]
}]&page[number]=1&page[size]=5
```

2. Doesn't work

```
[{
   "and":[{
       "name":"location-name",
       "op":"ilike",
       "val":"%kolkata%"
    }, {
       "name":"name",
       "op":"ilike",
       "val":"%%"
    }, {
       "name":"event-type",
       "op":"has",
       "val": {
       "name":"name",
       "op":"eq",
       "val":"Auto, Boat & Air"
       }
    }, {
       "name":"ends-at",
       "op":"ge",
       "val":"%2019-10-17T18:10%"
    }
    ]
}]&page[number]=1&page[size]=5
```

Now, we know the issue, and can work on it. Before, no one even knew what was wrong

**Comment by iamareebjamal** [comment]
It doesn't work because `Auto, Boat & Air` event type does not exist

These are all the event types:

```
+--------------+------+------------------------------+-----------------------------+
|   deleted_at |   id | name                         | slug                        |
|--------------+------+------------------------------+-----------------------------|
|       <null> |    1 | Camp, Treat & Retreat        | camp-treat-retreat          |
|       <null> |    2 | Dinner or Gala               | dinner-or-gala              |
|       <null> |    3 | Other                        | other                       |
|       <null> |    4 | Concert or Performance       | concert-or-performance      |
|       <null> |    5 | Conference                   | conference                  |
|       <null> |    6 | Seminar or Talk              | seminar-or-talk             |
|       <null> |    7 | Convention                   | convention                  |
|       <null> |    8 | Festival or Fair             | festival-or-fair            |
|       <null> |    9 | Tour                         | tour                        |
|       <null> |   10 | Screening                    | screening                   |
|       <null> |   11 | Game or Competition          | game-or-competition         |
|       <null> |   12 | Party or Social Gathering    | party-or-social-gathering   |
|       <null> |   13 | Race or Endurance Event      | race-or-endurance-event     |
|       <null> |   14 | Meeting or Networking Event  | meeting-or-networking-event |
|       <null> |   15 | Attraction                   | attraction                  |
|       <null> |   16 | Class, Training, or Workshop | class-training-or-workshop  |
|       <null> |   17 | Appearance or Signing        | appearance-or-signing       |
|       <null> |   18 | Tournament                   | tournament                  |
|       <null> |   19 | Rally                        | rally                       |
+--------------+------+------------------------------+-----------------------------+
```

**Comment by tronku** [comment]
So, I think these filters shouldn't be provided in the app also.
