### ISSUE TITLE
Update docs to python 3.7

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6520]
**Describe the bug**
As most systems still have installed python 3.6, we should update our documentation to make virtual env of python 3.7 by default.

@iamareebjamal As I was testing out the system (for Dev Sprint) on some other laptops, unless specified python3.7 in commands, everything starts with python 3.6, as that's the default for python3 in most systems for now. So for ease of installment of system, we should just specify commands with python 3.7

**Additional context**
Working on it.

**Comment by iamareebjamal** [comment]
Just specifying python3.7 won't work. You need to install it using pyenv

**Comment by prateekj117** [comment]
@iamareebjamal It worked. Just need to install python 3.7, and it's dev tools using apt, and specify virtualenv python version to be 3.7 while creating the virtualenv. Something like: `virtualenv -p python3.7 venv`.

**Comment by prateekj117** [comment]
And due to `And when a new virtualenv is created using a particular python version, all commands resolve to that python version only`, everything will work fine after that.

**Comment by prateekj117** [comment]
Still says python3.6 https://github.com/fossasia/open-event-server#components

**Comment by chiral-carbon** [comment]
@prateekj117 shall I make the doc change?
