### ISSUE TITLE
default value of ticket_include is false in system

### ISSUE THREAD

**Issue by akshat0047** [fossasia/open-event-server#6525]
**Describe the bug**
ticket_include is set to 'false' by default which complicates setting up a new event for testers in the development

**To Reproduce**
1. Go to createdb.py file
2. Set the default value to true

**Expected behavior**
A tester should directly be able to create event while testing without enabling it manually in the database

**Additional context**
I am taking up this issue

**Comment by kushthedude** [comment]
What is the complexity you got? Also, he can enable the following through the FE.

**Comment by kushthedude** [comment]
The current workflow is better AFAIK.
cc: @iamareebjamal

**Comment by prateekj117** [comment]
@kushthedude Unless and until other mentors agree on something regarding anything which requires maintainers access, please don't perform that action. Almost every mentor here is half of the time correcting you instead of the person solving the issue. 

@akshat0047 Rather than having default value as true, @iamareebjamal suggested updating the docs with this information that the tester needs to update the `include_ticket` in modules table in order to use ticketing in the system.

**Comment by kushthedude** [comment]
I think you missed the cc.

**Comment by prateekj117** [comment]
@kushthedude I think you again missed the key points. `please don't perform that action`.

**Comment by kushthedude** [comment]
Please tell me mentor except @iamareebjamal correcting me, rather you have
been corrected more than me. Correct your knowledge before correcting me
@prateekj17

**Comment by kushthedude** [comment]
I noted a lot more than your key points.

**Comment by prateekj117** [comment]
@kushthedude Go through the issues and PR's once, and you will know. You again missed the key point of the conversation, this is not adding anything productive to the issue.

**Comment by iamareebjamal** [comment]
Let's keep things civil. Let's not close issues without discussion, and keep the snaps to ourselves. Both of you should evaluate what you say before commenting here.

**Comment by iamareebjamal** [comment]
> Please tell me mentor except @iamareebjamal correcting me

Ignoring the part about correcting anyone, I don't think there is any active maintainer here except me, and the repo seems like a battleground lately. Before writing a comment, both of you should paste it somewhere and look at it, and think if it is an issue board of an open-source project where you're going to write that, or some facebook/reddit flame war.

**Comment by akshat0047** [comment]
Ok, I will create a PR updating the same in docs. @prateekj117 @iamareebjamal

**Comment by iamareebjamal** [comment]
A nice enhancement will be to add a manage script to enable modules from command line

`python manage.py module enable ticketing`

**Comment by akshat0047** [comment]
ok, on it. @iamareebjamal
