### ISSUE TITLE
Add CircleCI Badge

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6527]
cc: @iamareebjamal

**Comment by kushthedude** [comment]
@iamareebjamal Since `CircleCI` Badge URL is available to only `Maintainers`.If you may post the badge URL, It can be a `Good First Issue`. Else you may add it.

**Comment by iamareebjamal** [comment]
https://shields.io/category/build

**Comment by kushthedude** [comment]
Actually I was saying for the following badge which circleCI only shows to repo maintainers.
<img width="133" alt="Screenshot 2019-10-16 at 4 09 56 AM" src="https://user-images.githubusercontent.com/44091822/66875125-d8213d00-efca-11e9-8e66-7ba8323afaf6.png">

**Comment by iamareebjamal** [comment]
We should follow same badge style as other badges in the repo

**Comment by kushthedude** [comment]
:+1:
