### ISSUE TITLE
[Docs]: Grammatical mistake in documentation for local installation

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#6552]
**Describe the bug**

A grammatical mistake in the documentation for the [local installation](https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md) of the project.

**To Reproduce**
1. Go to 'https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md#using-pipenv'
2. Scroll down to 'Step 2'
4. See error, `Go the directory where your postgres file is stored`

**Expected behavior**

`Go to the directory where your Postgres file is stored`

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

Want to work on this

**Comment by iamareebjamal** [comment]
p->P is not a grammatical mistake. Besides, postgres is not wrong

**Comment by iamareebjamal** [comment]
OK, `to` is missing

**Comment by Samiksha99** [comment]
I would like to work on this issue

**Comment by Haider8** [comment]
@Samiksha99 Sure, go ahead.

**Comment by NNRepos** [comment]
Since this hasn't been done in a while, I'll do it instead. I think it would've been wiser to approve @snitin315's commit by the way.

**Comment by prateekj117** [comment]
@NNRepos It's a documentation issue and not an urgent one. And it's important for a newcomer to know how things should go so that no two developers work on the same issue. Though it has been a few days and there has been no PR from @Samiksha99, you can go ahead with this issue.
