### ISSUE TITLE
The image in readme broken

### ISSUE THREAD

**Issue by Swap76** [fossasia/open-event-server#6556]
**Describe the bug**
The image in readme is broken

**To Reproduce**
1. Go to Readme.md
3. Scroll down to Installation 
4. See the broken image

**Additional context**
<img width="682" alt="Screenshot 2019-10-28 at 8 07 39 AM" src="https://user-images.githubusercontent.com/37082605/67647965-2be03e80-f95a-11e9-908d-999ccc5282a9.png">

**Comment by Swap76** [comment]
I will love to work on this as first issue on fossasia :-)

**Comment by iamareebjamal** [comment]
The screenshot itself is broken

**Comment by Swap76** [comment]
<img width="1062" alt="Screenshot 2019-10-28 at 1 29 14 PM" src="https://user-images.githubusercontent.com/37082605/67661333-f69e1580-f986-11e9-92ec-60b255bb2897.png">
@iamareebjamal Updated the Screen Shot

**Comment by kushthedude** [comment]
The docker svg is broken, You need to find a nice svg replacement . You may work on it.

**Comment by Swap76** [comment]
@kushthedude Thanks, Assign it to me

**Comment by Swap76** [comment]
@iamareebjamal Thanks for the info will send PR
