### ISSUE TITLE
Discount Code Orders possible even though number of discounted tickets exhausted

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6569]
Organizers have the option to limit discount tickets. Even though the number is exhausted users can still get discounted tickets. This should not be possible.

Replicate: Go to event dashboard, click on "Tickets" choose "Discount" on the left sidebar and create a discount code. Use this discount code and try to buy tickets after you ordered the number of max. discount tickets. It will still work.

![Screenshot from 2019-11-03 19-08-13](https://user-images.githubusercontent.com/1583873/68089855-7a676e80-fe6d-11e9-85aa-b1b22e64d66a.png)

**Comment by kushthedude** [comment]
I will take a look at it.

**Comment by Rits1272** [comment]
Can I work on this issue?

**Comment by prateekj117** [comment]
Hey @Rits1272, great to see you want to contribute here. This is a high priority issue. You can look into some other issues for now.

@kushthedude Update?

**Comment by Rits1272** [comment]
Sure @prateekj117.I will look into some other issue.

**Comment by prateekj117** [comment]
@kushthedude Progress on this?

**Comment by kushthedude** [comment]
Not much, you may take it up, was occupied with ci and routing issue. You
may take up if you want.

**Comment by prateekj117** [comment]
@mariobehling @iamareebjamal Taking this one up.

**Comment by kushthedude** [comment]
@prateekj117 Did you get time to debug ?

**Comment by prateekj117** [comment]
@kushthedude Yup. The logic is kind of complex so I and @iamareebjamal decided to look after these issues directly in the new Orders API.

**Comment by kushthedude** [comment]
What about the new release than?
If there is any hotfix for this currently @iamareebjamal . As order api may
take some time.

**Comment by kushthedude** [comment]
@iamareebjamal

**Comment by iamareebjamal** [comment]
Yes, once 1-2 PRs are finalized, we'll make a release

**Comment by codedsun** [comment]
Taking this up 👍

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/issues/6569#issuecomment-554768218

**Comment by kushthedude** [comment]
> #6569 (comment)

Should we still wait for the new API or find a way to fix it for now? @iamareebjamal

**Comment by iamareebjamal** [comment]
No, take this up
