### ISSUE TITLE
Fix: Attendee endpoint serving none values for non-required fields

### ISSUE THREAD

**Issue by akshat0047** [fossasia/open-event-server#6586]
**Describe the bug**
On rendering attendee information on frontend there are fields with labels but no value we need to fix it by serving only not null value to front end

**To Reproduce**
1. Create an Event on Frontend and add tickets
2. Make attendee form with mixed, required and non required values
3. Buy few tickets with mixed information and check attendees under tickets tab of manage events
4. You will see labels with blank values

[Frontend Screenshot](https://pasteboard.co/ID0lgBN.png)

**Expected behavior**
Labels with blank values should not exist, if a field is blank do not serve it through api
We may fix it by:
- Adding a default value to non required-fields

**Additional context**
For more refer to [this PR](https://github.com/fossasia/open-event-frontend/pull/3567) and [this issue](https://github.com/fossasia/open-event-frontend/issues/3406)

Working on it

**Comment by akshat0047** [comment]
@iamareebjamal @prateekj117 I think setting a default value will be a better solution with "Not Specified" ?

**Comment by iamareebjamal** [comment]
Default value should be saved when saving in DB, not when returning in the API

**Comment by iamareebjamal** [comment]
Not sure what's the use case, but if there is in future, we can easily handle it in frontend instead
