### ISSUE TITLE
Add missing end-points to the API docs

### ISSUE THREAD

**Issue by akshat0047** [fossasia/open-event-server#6591]
There are four end-points missing from the API docs though they are working and well defined in the API   

- /events/{int:event_id}/attendees
- /events/{event_identifier}/attendees
- /users/{user_id}/attendees
- /tickets/{ticket_id}/attendees

**Describe the solution you'd like**
Add documentation for the same under the attendees tab

Working on It

**Comment by akshat0047** [comment]
This issue is on hold due to #6594

**Comment by iamareebjamal** [comment]
It shouldn't be on hold. Both are unrelated
