### ISSUE TITLE
Add end-point for attendees list in context to Admin

### ISSUE THREAD

**Issue by akshat0047** [fossasia/open-event-server#6595]
**Is your feature request related to a problem? Please describe.**
At present the attendees endpoint is returning all of them irrespective of their status, we need users to fetch attendees with completed/placed status and admin to fetch attendees with completed/placed/pending status. 

**Describe the solution you'd like**
We may implement the same by:
- adding a route for admin
- adding a handler in resource manager
- add an admin tab in API docs with its first end-point

**Describe alternatives you've considered**
Open for alternatives @prateekj117 @iamareebjamal 

Please refer to #6594 

Working on this

**Comment by b-thebest** [comment]
Can I work on this issue?
