### ISSUE TITLE
Run container using CLI arguments instead of environment variables

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6598]
Currently, the container is started using an environment variable to decide if server or celery instance will be run. It makes it difficult to modify the image for quick edits when running. 

https://github.com/fossasia/open-event-server/blob/b3a8c3305ec232f3a0a6b30c5961ca5a43e26df5/scripts/container_start.sh#L2-L9
https://github.com/fossasia/open-event-server/blob/b3a8c3305ec232f3a0a6b30c5961ca5a43e26df5/scripts/container_start.sh#L21-L23

Instead it should be run via CLI arguments. Like

`./container_start.sh run api` or `./container_start.sh run celery`

**Comment by codedsun** [comment]
taking this up
