### ISSUE TITLE
Fix: Unable to fetch user details of an attendee

### ISSUE THREAD

**Issue by akshat0047** [fossasia/open-event-server#6600]
**Describe the bug**
The endpoint /attendees/{attendee_id}/user is not working niether it is documented

**To Reproduce**
1. Ping /attendees/{attendee_id}/user
2. Error => AttributeError: 'NoneType' object has no attribute 'is_admin'

**Expected behavior**
Should return UserSchemaPublic or UserSchema based on user access

**Additional details (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.7.5
 - `HEAD` Commit hash: b3a8c3305ec232f3a0a6b30c5961ca5a43e26df5

**Additional context**
Discovered this while working for #6584 , expecting a similar solution

[Working on this]

**Comment by iamareebjamal** [comment]
Low priority as it is most probably not used by any client right now

**Comment by mariobehling** [comment]
As it does not seem to be needed for our current feature set, I am closing this.
