### ISSUE TITLE
Refactor code for custom endpoints.

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6606]
**Describe the bug**
Custom endpoints should be shifted to a different folder so as to solve the problem of circular dependency in case of Limiter functionality.  And also for a better design and follow single responsibility principle.

**Additional context**
On it.

**Comment by codedsun** [comment]
@iamareebjamal @prateekj117  - the custom endpoints refers to the endpoints like this

https://github.com/fossasia/open-event-server/blob/b69df88f6d802aefd046865ed0ef0e41f5c00797/app/api/attendees.py#L31

So, we have to move this to the custom folder with filename `attendee.py` and just make this work.

Am I correct?
