### ISSUE TITLE
New account creation with same email is allowed

### ISSUE THREAD

**Issue by sharmaaditya570191** [fossasia/open-event-server#6608]
**Describe the bug**
The system currently allows to create 2 accounts with same email id.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Register page.
2. Create new account with same registered email id.

**Expected behaviour**
2 accounts with same email id should not be allowed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
I want to work on this.

**Comment by kushthedude** [comment]
> This is not a frontend issue

I am not able to reproduce nor on local neither production !

**Comment by iamareebjamal** [comment]
Yes, as expected, thus wanting more info from the user about the claims

**Comment by sharmaaditya570191** [comment]
Hi @prateekj117 . There is a checker on the server side for this. What about checking this on the client side?  It would make the process fast.

**Comment by kushthedude** [comment]
No check needed for client

**Comment by sharmaaditya570191** [comment]
I meant checking if user already exists just after user is done typing the email.

**Comment by kushthedude** [comment]
We have more severe issues and bugs to fix before this. Also this is not a
bug but an enhancement.

**Comment by sharmaaditya570191** [comment]
Hi @kushthedude . Can I open a new issue for the same in open-event-server with `enhancement` label?

**Comment by iamareebjamal** [comment]
No
