### ISSUE TITLE
Image resizing is not working

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6618]
https://github.com/fossasia/open-event-server/blob/9bb9f68305c261713ee486f3840ebcf55dc70d23/app/api/helpers/files.py#L80

urlib is throwing 403 Forbidden error for almost all images. 

Please use requests and verify image resizing works. Also, create a management command which finds all events which have no resized images and resizes them

**Comment by iamareebjamal** [comment]
@codedsun Can you please take this up?

**Comment by codedsun** [comment]
Taking this up

**Comment by codedsun** [comment]
@iamareebjamal I learnt that this task creates resized image and stored in static folder. How do i test that for 403 error via which api `upload image?` Please guide me how should I proceed?

As when I am hitting through the frontend and selecting the image like event background, event logo it works fine.

**Comment by iamareebjamal** [comment]
Send this as original image URL in Postman - https://storage.eventyay.com/eventyay.com/events/758/background/Vk0zSTdyZX/1517e947-29df-4a3c-9580-373db3ba9ba9.png

Also, working fine means the image is resized and all image URLs are correctly set. Is that happening?

For management command, no

**Comment by codedsun** [comment]
@iamareebjamal 

![image](https://user-images.githubusercontent.com/20026440/69666656-9c41c300-10b2-11ea-8871-edccba04100e.png)

They are null

**Comment by codedsun** [comment]
@iamareebjamal When the event is created the files.py function is run. What is expected that large_image_url, thumbnail_image_url - should be created with a valid url? Am I right?

**Comment by iamareebjamal** [comment]
Yes

**Comment by codedsun** [comment]
@iamareebjamal Okay I will debug it tomorrow.

**Comment by iamareebjamal** [comment]
Status? PATCH endpoint is not as important. That is atleast working with its limitation. This is completely broken

**Comment by codedsun** [comment]
@iamareebjamal Sorry I missed that due to health issues. I am resuming and working on it now.

**Comment by codedsun** [comment]
@iamareebjamal I am finding a way to check that celery worker is running or not on my machine also how do I turn on logs for celery.. I see that function is called, but I m debugging more about it.

**Comment by iamareebjamal** [comment]
celery won't run if you've not run it. It's simple

**Comment by iamareebjamal** [comment]
Did you follow the instructions and run celery? https://github.com/fossasia/open-event-server/blob/development/docs/installation/basic.md

**Comment by codedsun** [comment]
Yeah, while running `celery worker -A app.celery`

I am having error
```
[2019-12-05 17:39:30,349: WARNING/ForkPoolWorker-3] HEAD http://localhost:9200/event [status:N/A request:0.004s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:
```

**Comment by iamareebjamal** [comment]
ENABLE_ELASTICSEARCH=False in your .env

**Comment by codedsun** [comment]
@iamareebjamal For the locally saved images on the server it's working fine for me.i.e. From frontend I tried to upload the images, they are getting resized and stored in the events table. 

Now as per the requirement, that creating an event by using a postman request with imageurl of not a locally saved file, it's throwing 403 error. I am debugging it now.

**Comment by iamareebjamal** [comment]
No need to debug. The cause and solution both are written in the issue itself

**Comment by codedsun** [comment]
@iamareebjamal Lol, what should I do then?

**Comment by iamareebjamal** [comment]
Follow what's written in the issue

**Comment by codedsun** [comment]
>Also, create a management command which finds all events which have no resized images and resizes them?

How do we write a management command, please guide me? 
Also, What should be done for 403 error?

**Comment by iamareebjamal** [comment]
> urlib is throwing 403 Forbidden error for almost all images. 
> 
> Please use requests and verify image resizing works.

I have literally pasted what I wrote in the issue

**Comment by codedsun** [comment]
>No need to debug. The cause and solution both are written in the issue itself

What's the solution here? I need to fix 403 error of urllib

>urlib is throwing 403 Forbidden error for almost all images.

It's throwing for the files which are not saved locally on the server, do I need to fix this for the images which are from the source other than local machine or test for which are locally saved on the server?

**Comment by iamareebjamal** [comment]
> Please use requests and verify image resizing works.

**Comment by codedsun** [comment]
That hyperlink made a ton of difference for a beginner like me. I thought request as a hitting api.

>Please use requests and verify image resizing works.

For this you meant to replace using urllib and use requests instead to open the file and then perform the resizing. Am I correct here?

**Comment by iamareebjamal** [comment]
Yes

**Comment by codedsun** [comment]
@iamareebjamal If that hyperlink would have been present, it wouldn't have taken a day. Thanks :)

**Comment by iamareebjamal** [comment]
```
AttributeError("module 'requests.exceptions' has no attribute 'URLError'")
```

You didn't test the exceptions @codedsun Please fix ASAP

**Comment by codedsun** [comment]
@iamareebjamal No nopes, it was not replaced to Invalid URL

**Comment by codedsun** [comment]
@iamareebjamal https://github.com/fossasia/open-event-server/pull/6648

**Comment by iamareebjamal** [comment]
```
Task resize.event.images[947ebb58-7870-49b5-8488-fc82b2000077] raised unexpected: ObjectNotFound({'parameter': 'event_id'}, 'Event: 1014 not found')
```

Resize task is using safe_query which means it removes deleted events when querying. Thus, it throws an error when you try to resize images of deleted events. It's an internal module and hence shouldn't use safe_query. See if there is any way to trigger resize event or speaker through API. If there's not, then change safe_query to normal query

**Comment by codedsun** [comment]
@iamareebjamal Will check and reply.

**Comment by codedsun** [comment]
For Events image resizing and speaker image reisizing
The task is only triggered when we patch an event/speaker image or the first time event/speaker is created using POST request.

**Comment by codedsun** [comment]
Also, guide me for this sir. Thanks
