### ISSUE TITLE
PATCH endpoint is broken

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6619]
The point of PATCH endpoint is to only update selected fields of the the resource. Right now, the PATCH endpoint resets all fields except the ones sent to it. This should be fixed on priority

Take the current saved instance of the object and patch only the fields sent from the client

**Comment by codedsun** [comment]
I am taking this up.

**Comment by iamareebjamal** [comment]
Please take #6618 It's more important

**Comment by codedsun** [comment]
@iamareebjamal Cool, thanks. Taking that up

**Comment by samyakbvs** [comment]
Can I take this up?

**Comment by iamareebjamal** [comment]
Already taken and not beginner friendly

**Comment by codedsun** [comment]
@iamareebjamal I will take this issue now, Do i have to send seperate PR for every end point ?

Also,
>The point of PATCH endpoint is to only update selected fields of the the resource. Right now, the PATCH endpoint resets all fields except the ones sent to it. 

Then how the patch request are working currently? are they working or not?

**Comment by iamareebjamal** [comment]
> Do i have to send seperate PR for every end point ?

You have to fix the patching mechanism. If it were to be done for each endpoint, I might have as well asked to rewrite the entire app because it would be useless

> Then how the patch request are working currently? are they working or not?

It's mentioned in the issue how they are working right now

**Comment by codedsun** [comment]
@iamareebjamal  I ran a patch request for modules, it's working fine and is setting the values which I passed.

> Right now, the PATCH endpoint resets all fields except the ones sent to it. 

But it sets correctly. For which endpoint should I reproduce this error?

**Comment by iamareebjamal** [comment]
event

**Comment by codedsun** [comment]
@iamareebjamal Resuming the work on this high priority issue.

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Priority%3A+URGENT%22

**Comment by Tlazypanda** [comment]
@iamareebjamal I tried to reproduce this issue on events patch but seems to be working fine :sweat_smile:

**Comment by iamareebjamal** [comment]
OK
