### ISSUE TITLE
After-Event Mail: Separate Email Template of Speaker and Owner/Organizer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6620]
There is an after-event message, that should not go to the speaker and organizer at the same time, which can be viewed at https://eventyay.com/admin/messages/list .

![Screenshot from 2019-09-16 10-59-01](https://user-images.githubusercontent.com/1583873/64946703-c20d4900-d873-11e9-9e2d-e07f22fefc0c.png)

Instead there should be
a) a message to the owner and organizers
b) a message to the speaker
These message should be differently and don't include upcoming events.

1. Please implement a message to the "Owner, Organizer"
Subject: {eventname} is over. Thank you for using Eventyay!
Email: Hi {email}, you event {eventname] is over. Thank you for using the Eventyay platform for your event. We hope you enjoyed it. 

2. Implement a message only for accepted speakers
Subject: {eventname} is over. Thank you for participating!
Email: Hi {email},thank you for participating in our {eventname]. We hope you enjoyed it and keep in touch.

**Comment by codedsun** [comment]
I am taking this up!

**Comment by Bhavik-Ardeshna** [comment]
@iamareebjamal  Hey I need to work in which file plz help me I started checking all files ?

**Comment by Bhavik-Ardeshna** [comment]
Means I need to change the message ??
