### ISSUE TITLE
Cannot create ticket with name "Business Ticket" if former ticket with name "Business Ticket" was deleted

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6621]
Cannot create ticket with name "Business Ticket" if former ticket with name "Business Ticket" was deleted. Error message appears.

**Comment by iamareebjamal** [comment]
```
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "name_event_uc"
DETAIL:  Key (name, event_id)=(Business Ticket, 1170) already exists.

[SQL: UPDATE tickets SET name=%(name)s WHERE tickets.id = %(tickets_id)s]
[parameters: {'name': 'Business Ticket', 'tickets_id': 1265}]
```

Append `-deleted` to the ticket name when deleting. Similar to what we did in user email field

**Comment by kushthedude** [comment]
@iamareebjamal Shouldn't the ticket be deleted when we click remove ?

**Comment by kushthedude** [comment]
Why the id is still stored ?

**Comment by codedsun** [comment]
@kushthedude I think there should be a log for everything in the database, so soft deletion method followed for deletion of tickets.

**Comment by iamareebjamal** [comment]
Tickets may be related to orders, so first of all, any ticket with placed order should not be able to be deleted, but this is another issue. Secondly, people make mistakes, and regarding events, tickets, and orders are the most important things related to an event in an event management system, so no, they shouldn't be deleted.

**Comment by codedsun** [comment]
@iamareebjamal For this issue the name of ticket shall be changed in`beforedeleteobject` method ? and also the permission has to be checked or not?

**Comment by iamareebjamal** [comment]
If it can be done in the same PR reliably, then great

**Comment by codedsun** [comment]
@iamareebjamal I am stuck on beforedeleteibject method, I can't figure how to update the schema before the deletion, do i have to perform a db session transaction here or you can give me a example where it's done.

**Comment by iamareebjamal** [comment]
` I can't figure how to update the schema before the deletion`

Why do you want to do that?

**Comment by codedsun** [comment]
> `I can't figure how to update the schema before the deletion`
> 
> Why do you want to do that?


>Append -deleted to the ticket name when deleting. Similar to what we did in user email field

@iamareebjamal

**Comment by kushthedude** [comment]
@codedsun Please stick to one issue at a time.

**Comment by iamareebjamal** [comment]
@kushthedude At least he's sending PRs to urgent issues within a day

**Comment by iamareebjamal** [comment]
@codedsun It's not called updating the schema. It's updating DB, and see how it's done when deleting a user

**Comment by codedsun** [comment]
@kushthedude - I love learning here and also this issue is not very major
one..I am working on it side by side..also as I am new to django, I will
take time to figure things out here.

Also, I am free all day and night, what else shall I do..

If you can want you can take this up. :)

**Comment by kushthedude** [comment]
Its great to hear from you, anyways I will be unavailable next week due to
end semester exams :( , Go ahead with the issues.
