### ISSUE TITLE
Tickets can be created with end date greater than event end date

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#6646]
**Describe the bug**
Tickets can be created with end date greater than event end date.

**Expected behavior**
There should be a server-side check to check that this doesn't happen

**Additional context**
- [x]  Taking this up

**Comment by codedsun** [comment]
@prateekj117 @iamareebjamal I can also create ticket before start of event, can this happend? If not I will also add this check to this PR.

**Comment by iamareebjamal** [comment]
So, ticket sales should only start after the start of event? 

"I want to buy tickets to the movie"
"Sorry sir, the movie has started"
"OK, so when will the next show tickets be available?"
"After the movie starts after 3 hours"
After 3 hours:
"I want to buy tickets to the movie"
"Sorry sir, the movie has started"
