### ISSUE TITLE
Ticket Ordering Confirmation Email Directs to dead link at  "api.eventyay.com.."

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6654]
After a user receives an email, the user receives a confirmation email comes with a broken link.

In the test the email link is http://url4008.eventyay.com/wf/click?upn=jq3Y4iMptY{somehash}
It forwards to https://api.eventyay.com/generated/tickets/orders/tickets/pdf/c9e893{somehash} with a broken link.

EXPECTED: The link in the email should direct to the same link as on the downloads page in the user account as below.

![Screenshot from 2019-12-06 18-28-24](https://user-images.githubusercontent.com/1583873/70342946-5b863e80-1856-11ea-9e88-312a9b4ac3d8.png)

**Comment by codedsun** [comment]
@iamareebjamal Taking this up

**Comment by codedsun** [comment]
@iamareebjamal How do i reproduce this issue, the values in db says that it's working fine


Snapshot of Mails table in db message

`Hi, this is a confirmation mail of your tickets for the event Eventyay Testing<br/>Your order has been processed successfully.<br/> <a href='http://127.0.0.1:5000/generated/tickets/orders/tickets/pdf/4216b933-b714-47cf-ac2b-054b9f1dcfc4/S000UkdqUE/4216b933-b714-47cf-ac2b-054b9f1dcfc4.pdf'>Click here</a> to view/download your ticket.<br><br><em>Looking forward to seeing you at the event.`

**Comment by iamareebjamal** [comment]
Solved months ago by disabling link tracker
