### ISSUE TITLE
Add created_at, modified_at in ticket holders

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6655]
Currently, ticket holders/attendees have no information when they were created and when they were modified. At these to the model

**Comment by codedsun** [comment]
Taking this up!

**Comment by NickSneo** [comment]
want to take this up

**Comment by iamareebjamal** [comment]
@NickSneo This is a high priority issue, not good for beginners, as we need this mered fast. And anyway, it is already taken up

**Comment by NickSneo** [comment]
@iamareebjamal okay, no problem!!!
