### ISSUE TITLE
Add error handler for status 429 

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6659]
Status 429 Too many requests has no error handler, and hence it returns HTML instead of JSON

https://flask-limiter.readthedocs.io/en/stable/#custom-rate-limit-exceeded-responses

**Comment by NickSneo** [comment]
I am new to open source and would ike to start with this one, please assign it to me

**Comment by codedsun** [comment]
@NickSneo No need for assign, you can work and send the PR

**Comment by NickSneo** [comment]
okay thanks

**Comment by Rits1272** [comment]
Can I work on this?
