### ISSUE TITLE
Delete ticket holders after order_expiry_time + created_at if they don't have order_id

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6661]
Sometimes, some dummy ticket holders get created with no order_id, it'll take time to create new order API, hence for now, after every `order_expiry_time`, a function should run which will delete all ticket holders with no order_id which have `created_at + order_expiry_time < now`

**Comment by codedsun** [comment]
@iamareebjamal Do i have to write a job for that?

**Comment by iamareebjamal** [comment]
It's in the settings
