### ISSUE TITLE
Make ticket_id and event_id not null in TicketHolder

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6669]
Self explanatory

**Comment by ashwani99** [comment]
Working on this

**Comment by ektaarora3501** [comment]
hey ! is the issue resolved ? If not can I work on it ?

**Comment by sakshamb2113** [comment]
Hi @iamareebjamal  i am a newbie. Can i work on this issue ?

**Comment by prateekj117** [comment]
@sakshamb2113 Go ahead.

**Comment by iamareebjamal** [comment]
Yes

**Comment by deadoralive023** [comment]
is this issue still open?

**Comment by iamareebjamal** [comment]
Looks like that to me
![image](https://user-images.githubusercontent.com/3874064/81781084-35577f80-9515-11ea-944f-96b01988e9f2.png)

**Comment by deadoralive023** [comment]
This is my first time trying to contribute to an  open source, so please let me know can I take this issue if its still open

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/issues/6669#issuecomment-627788095

**Comment by faraz16iqbal** [comment]
Working on this issue if it's still open!

**Comment by satyasai7** [comment]
Can i work ?

**Comment by deadoralive023** [comment]
Yes you can

**Comment by b-thebest** [comment]
Can I work on this issue?

**Comment by deadoralive023** [comment]
Yes you can

**Comment by b-thebest** [comment]
This is gonna be my first contribution, Can you please navigate me to the file or location where I need to do the change

**Comment by iamareebjamal** [comment]
First you need to understand the project. Unfortunately, we can't spoonfeed you the steps

**Comment by b-thebest** [comment]
Sure, I will check it out. Thank you
