### ISSUE TITLE
Session CSV Export: Missing fields and Incorrect Columns

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6695]
Exporting session/speaker information does not show all collected columns. Specifically the information on session length is missing, but also a lot of other info collected.

Furthermore <SessionType 'Talks'> shows up on rows. Expected is just: Talks

![Screenshot from 2019-12-24 06-09-29](https://user-images.githubusercontent.com/1583873/71394935-0c8d2700-2614-11ea-9936-04b3f56c1335.png)

**Comment by codedsun** [comment]
taking this up.
