### ISSUE TITLE
Unable to create file migrations/versions

### ISSUE THREAD

**Issue by Aju100** [fossasia/open-event-server#6702]
**Describe the bug**
Upon trying to clone the repository. It shows these errors.

`
C:\Users\Aju\Desktop>git clone https://github.com/Aju100/open-event-server.git
Cloning into 'open-event-server'...
remote: Enumerating objects: 60676, done.
remote: Total 60676 (delta 0), reused 0 (delta 0), pack-reused 60676
Receiving objects: 100% (60676/60676), 46.96 MiB | 626.00 KiB/s, done.
Resolving deltas: 100% (42934/42934), done.
error: unable to create file migrations/versions/rev-2019-08-03-05:18:10-4925dd5fd720_add_user_token_blacklist_time_table.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-07-01:11:29-f5c3a4fd23fb_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-09-19:41:03-246b5b6123af_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-10-00:08:43-9d5753192ac9_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-13-13:24:45-d252c86d0200_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-13-14:38:26-1bdf23be63bd_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-13-16:07:52-cd3beca1951a_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-17-16:59:44-90d62fe3b5e3_change_pending_invoices.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-17-20:46:39-9172ceb350b8_duplicate_ticket_tag.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-08-24-20:32:00-ebfe89366d48_.py: Invalid argument
error: unable to create file migrations/versions/rev-2019-09-02-09:34:18-7c32ba647a18_.py: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**To Reproduce**
1. Go to cmd in windows
2. Clone the repository
3 See error and warnings

**Additional details (please complete the following information):**
 - OS: Windows 10  Home Edition
 - Python Version :3,7

**Comment by iamareebjamal** [comment]
Please use linux. Windows has arcane file name restrictions

**Comment by Aju100** [comment]
@iamareebjamal  sure.
