### ISSUE TITLE
User warning to run create_db.py

### ISSUE THREAD

**Issue by Aju100** [fossasia/open-event-server#6709]
**Describe the bug**

**To Reproduce**
1. Go to 'generic installation'
2. Follow the instructions
3. Run python3 create_db.py
`UserWarning: Could not any envfile.
  warnings.warn('Could not any envfile.')
`DATABASE_URL` either not exported or empty
`

**Additional details (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version [`3.7']

**Comment by codedsun** [comment]
Read the  instruction file.

`cp .env.example .env` you didn't performed this step

**Comment by Aju100** [comment]
@codedsun  I have perform it.

**Comment by Aju100** [comment]
@codedsun 
`UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
`
How to remove such warning.

**Comment by iamareebjamal** [comment]
git pull upstream development
