### ISSUE TITLE
Urgent: Stripe is not working

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6716]
Stripe is not working because server is not recognising Pending Orders.

```py
{
    "errors": [
        {
            "status": 409,
            "source": {
                "parameter": "id"
            },
            "title": "Conflict",
            "detail": "You cannot charge payments on a cancelled, expired or completed order"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```
<img width="1353" alt="Screenshot 2020-01-03 at 9 50 52 AM" src="https://user-images.githubusercontent.com/44091822/71707176-8d1b0700-2e0e-11ea-938a-6b7ebebc2d63.png">

Refers https://github.com/fossasia/open-event-frontend/issues/3712

**Comment by iamareebjamal** [comment]
Duplicate of #6703?

**Comment by kushthedude** [comment]
Might be, Not sure

**Comment by kushthedude** [comment]
> Duplicate of #6703?

It can not be as #6703 was caused due to https://github.com/fossasia/open-event-server/pull/6693  and this patch is not release in production rn.

**Comment by kushthedude** [comment]
@iamareebjamal When will the server release be made ?

**Comment by iamareebjamal** [comment]
How was it solved when the patch fixed was not released in production?

**Comment by kushthedude** [comment]
The following screenshot was of my local, and it was solved after the PR
was merged. However the issue of production may be different then it.

**Comment by iamareebjamal** [comment]
Is there even as issue in producion?

**Comment by kushthedude** [comment]
https://github.com/fossasia/open-event-frontend/issues/3712#issuecomment-570410932

**Comment by kushthedude** [comment]
I cross verified on my local and this was the issue I was facing. I did not check on eventyay.

**Comment by iamareebjamal** [comment]
Then that issue is unrelated to this
