### ISSUE TITLE
Speaker images not being resized correctly

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6724]
thumbnail width height is set to 150px but still the image generated is of 500px

https://eventyay.com/e/423d0650/sessions/s/all

Also, if I upload an image of 320x320 px and resize width is set to 500px. It upscales the image to 500px. If the image dimension is less than target dimension, return the original image URL as is

**Comment by iamareebjamal** [comment]
@codedsun Can you please take a look

**Comment by codedsun** [comment]
@iamareebjamal - The db values are different from what you mentioned here

>thumbnail width height is set to 150px but still the image generated is of 500px

https://github.com/fossasia/open-event-server/blob/e758cfc1dc812bd0d867beed0a65f24886634158/populate_db.py#L98-L103

**Comment by iamareebjamal** [comment]
The admin panel shows different values. It means it is not tied to the admin settings - https://eventyay.com/admin/settings/images

And similarly, these are not stored in DB as well. There are only 2 types in DB. event and profile. And admin settings shows profile one as `Profile/Speaker images`

**Comment by iamareebjamal** [comment]
https://api.eventyay.com/v1/speaker-image-sizes

Shows 150

**Comment by codedsun** [comment]
@iamareebjamal  - Okay, will check for the case of 150. Thanks

**Comment by codedsun** [comment]
@iamareebjamal - the flow is working fine. I try to upload 2 images for speakers
1. with dimension 
724 × 1024

the dimension of thumbnail image is - 150*212
![image](https://user-images.githubusercontent.com/20026440/71784835-15232b80-301e-11ea-81ba-ad93c2571ba3.png)


2. with dimension
900*750

the thumbnail image dimension - 150*125

![image](https://user-images.githubusercontent.com/20026440/71784846-31bf6380-301e-11ea-95de-1b9c18f443d2.png)


What else can reproduce me this issue.?

**Comment by codedsun** [comment]
For this

>Also, if I upload an image of 320x320 px and resize width is set to 500px. It upscales the image to 500px. If the image dimension is less than target dimension, return the original image URL as is

I shall then set the thumbnail_url to originial_image_url u meant?

**Comment by iamareebjamal** [comment]
Not working in production. I resized them using the manage.py method you created. Thumbnail images are of 150px

**Comment by codedsun** [comment]
@iamareebjamal - Let me check out this on master branch then.

**Comment by iamareebjamal** [comment]
Try the manage.py command

**Comment by codedsun** [comment]
The method is not working you meant? Okay will chck

**Comment by codedsun** [comment]
@iamareebjamal - Resized using manage.py command also, same result. the manage.py command also uses the same celery task which is used while uploading speaker image. Both are working fine for me in dev. What else should I try to reproduce this issue?

**Comment by codedsun** [comment]
@iamareebjamal  - Ping

**Comment by iamareebjamal** [comment]
Will check why it didn't work in production

**Comment by codedsun** [comment]
@iamareebjamal - One possibly would be when the values were not found, then only the else condition will execute which takes `thumbnail_width_height=500`

https://github.com/fossasia/open-event-server/blob/95357f2460246d3b2cd534e111f2a024aa068e70/app/api/helpers/files.py#L130-L140

**Comment by iamareebjamal** [comment]
What is `image_sizes_type`? It should be profile

**Comment by codedsun** [comment]
@iamareebjamal - But the task runs with type `speaker-image`

**Comment by iamareebjamal** [comment]
That's wrong. In production, the type is profile, the same is used in the admin settings - https://api.eventyay.com/v1/speaker-image-sizes

See the type. Check on your local. What's the type

**Comment by codedsun** [comment]
@iamareebjamal - The celery task also uses the same key `speaker-image`. The createdb file also creates the same and on my local also shows the same. 

![image](https://user-images.githubusercontent.com/20026440/71892990-66dbcb00-3170-11ea-9835-bb01dcd1d836.png)

The api running on production says type `profile` . That's strange

**Comment by iamareebjamal** [comment]
It's not strange. The API just fetches the row with ID 2 regardless of type. I know it's stupid. I already opened the reimplementation issue for image resizing 1-2 months back.

For now, try to figure what should be used, profile or speaker-profile. Check where profile is being used

**Comment by codedsun** [comment]
@iamareebjamal - yes this is the issue, I shall take that up after 1-2 issues.

https://github.com/fossasia/open-event-server/issues/6641

> The API just fetches the row with ID 2 regardless of type. I know it's stupid

Also, This should be fixed then.

> For now, try to figure what should be used, profile or speaker-profile. Check where profile is being used

It's `speaker-image` not ~speaker-profile~. I will get back to you

**Comment by iamareebjamal** [comment]
It's pretty normal. profile was being used previously. When speaker image split from it, nobody bothered to create a migration. It's kind of tradition

**Comment by codedsun** [comment]
@iamareebjamal - `speaker-image` is used everywhere in dev.

**Comment by iamareebjamal** [comment]
And profile isn't used?

**Comment by codedsun** [comment]
Nopes!

**Comment by iamareebjamal** [comment]
OK. Wow. Then change the logic of API to fetch by type and not ID, it should fix everything

**Comment by mariobehling** [comment]
Closing this in favof or https://github.com/fossasia/open-event-server/issues/6641
