### ISSUE TITLE
Session & Speaker: User can change his session/speaker details after CFS is closed

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6726]
**Describe the bug**

User can change his session/speaker details after CFS is closed.

**To Reproduce**

Steps to reproduce the behaviour:

1. Submit a Proposal and Confirm it.
2. Wait for CFS to get closed and then edit your proposal.
3. See error

**Expected behaviour**

User should not have the right to edit the proposal once CFS is ended.

See Also : https://github.com/fossasia/open-event-frontend/issues/3768#issuecomment-571141434

**Comment by hedonhermdev** [comment]
Can I work on this issue?

**Comment by codedsun** [comment]
@hedonhermdev Yes sure
