### ISSUE TITLE
Error while following installation missing library

### ISSUE THREAD

**Issue by diru1100** [fossasia/open-event-server#6730]
**Describe the bug**

Cannot run create_db.py without a certain library.
**To Reproduce**
1. Follow the installation steps
2. See  **ImportError: failed to find libmagic.**  Check your installation while running create_db.py

**Additional details (please complete the following information):**
 - OS:  MacOS
 - Python Version 3.7.1

**Additional context**

Additional library to be added in common.txt

**Comment by iamareebjamal** [comment]
Use linux. If not, install libmagic from brew. Not an issue of the server. We can't install the dependency for you
