### ISSUE TITLE
After-Event Email: Several identical mails sent out, if user has several sessions/roles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6731]
If a user has several sessions and roles, e.g. speaker and event organizer, several after-event emails are sent out. Expected: Only send one email per email address.

![Screenshot from 2020-01-08 11-02-59](https://user-images.githubusercontent.com/1583873/71952996-c8e70f80-3206-11ea-916f-f9e332d70faf.png)

**Comment by iamareebjamal** [comment]
Bug in APS, to be replaced by celery beat

**Comment by kushthedude** [comment]
APS: Python Scheduler ?

**Comment by codedsun** [comment]
Taking this up! 👍

**Comment by kushthedude** [comment]
> APS: Python Scheduler ? I will be looking into it.

Also there are already 3-4 PR opened by you which are not merged. Please work on them before making more new one's.

**Comment by codedsun** [comment]
> Also there are already 3-4 PR opened by you which are not merged. Please work on them before making more new one's.

It has been 3 days and no one was working and the priority is HIGH also.
@kushthedude If you are working on this, then no problem. Also yes they are in the pending state due to the solution being searched simultaneously as I m stuck in both and in sync with Areeb (You can see the conversation). And if you are not working on this, then I can send the patch, why not move the project forward simultaneously. Please tell what should be done?

**Comment by kushthedude** [comment]
There are a lot of issues already present,needless to say you should give
atleast a week to other dev before claiming the issue if they are working
on it. If you dont hear from them a week or dont see a patch you should
definitely go ahead after commenting.
Each contributor should get an equal opportunity for contribution whether
it be me, you or any new comer.
Anyway, If you don't have issue to work on, you can go ahead with it. No
issues 😄

**Comment by vishakhanihore** [comment]
@codedsun Are you working on it?

**Comment by codedsun** [comment]
No, @vishakhanihore You may ask @kushthedude if he is working on it.

**Comment by kushthedude** [comment]
Sure go ahead.

**Comment by codedsun** [comment]
@vishakhanihore - Are you still working on this?

**Comment by vishakhanihore** [comment]
Didnt get time to finish it. You may go ahead if you want.

**Comment by codedsun** [comment]
@iamareebjamal - In this, all the scheduled jobs will become a celery task and then be scheduled by celery beat. correct?

**Comment by iamareebjamal** [comment]
yes

**Comment by kushthedude** [comment]
When sending mail function is called, it sends to all speaker, organiser, owner irrespective of if it has already been sent to one.

**Comment by codedsun** [comment]
@kushthedude - Yes, but it runs after every 5:30 mins. Can you point more clearly what you want to say.

Also, @iamareebjamal mentioned that it was due to the gununicorn workers(4) which were causing this issue, that's why we replaced the APS with celery beat.

**Comment by kushthedude** [comment]
> @kushthedude - Yes, but it runs after every 5:30 mins. Can you point more clearly what you want to say.

I didn't know why you even mentioned this.

See this snippet
```py
 if current_time > event.ends_at and time_difference_minutes < 1440:
                for speaker in speakers:
                    if not speaker.is_email_overridden:
                        send_email_after_event(speaker.user.email, event.name, frontend_url)
                        send_notif_after_event(speaker.user, event.name)
                for organizer in organizers:
                    send_email_after_event(organizer.user.email, event.name, frontend_url)
                    send_notif_after_event(organizer.user, event.name)
                if owner:
                    send_email_after_event(owner.user.email, event.name, frontend_url)
                    send_notif_after_event(owner.user, event.name)
```

**Comment by kushthedude** [comment]
> > @kushthedude - Yes, but it runs after every 5:30 mins. Can you point more clearly what you want to say.
> 
> I didn't know why you even mentioned this.
> 
> See this snippet
> 
> ```python
>  if current_time > event.ends_at and time_difference_minutes < 1440:
>                 for speaker in speakers:
>                     if not speaker.is_email_overridden:
>                         send_email_after_event(speaker.user.email, event.name, frontend_url)
>                         send_notif_after_event(speaker.user, event.name)
>                 for organizer in organizers:
>                     send_email_after_event(organizer.user.email, event.name, frontend_url)
>                     send_notif_after_event(organizer.user, event.name)
>                 if owner:
>                     send_email_after_event(owner.user.email, event.name, frontend_url)
>                     send_notif_after_event(owner.user, event.name)
> ```

@iamareebjamal What should be the optimal approach for this, A bunch of conditionals with flag variable or something else?

**Comment by iamareebjamal** [comment]
Extract all emails in a set and loop over them to send the email

**Comment by kushthedude** [comment]
There is more this issue, being ab owner and Speaker of a event. I just
received 15 after event mail
