### ISSUE TITLE
Error in migrations

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#6753]
**Describe the bug**
Due to recent merging of PRs https://github.com/fossasia/open-event-server/pull/6744/ https://github.com/fossasia/open-event-server/pull/6748

The PR https://github.com/fossasia/open-event-server/pull/6744 has an invalid migration to remove the 'secret' column from the db which was unrelated to PR. Hence now we have two migration for  the same column `secret` from `settings` which
 drops column on upgrade and creates  on downgrade

**Additional context**
@iamareebjamal - Please chck

**Comment by iamareebjamal** [comment]
#6744 has wrong migration. Not #6748

Remove it from migration

**Comment by codedsun** [comment]
Sorry copy paste error.
