### ISSUE TITLE
Implement confirmation email when speaker add a session

### ISSUE THREAD

**Issue by Shehanka** [fossasia/open-event-server#6756]
**Is your feature request related to a problem? Please describe.**
Yes. 
**Describe the solution you'd like**
Confirmation emails 

**Describe alternatives you've considered**

**Additional context**
I would like to implement this feature

**Comment by crazzyflynn** [comment]
Hello Sir
I would like to work on this issue
and I think it's related to "creating triggers"

**Comment by iamareebjamal** [comment]
Umm no, and I am not sure what the issue is about

**Comment by crazzyflynn** [comment]
Can I get my hands on?

**Comment by iamareebjamal** [comment]
I don't even know what the issue is about

**Comment by crazzyflynn** [comment]
Okay Sir😅
