### ISSUE TITLE
Unable to like/dislike some events

### ISSUE THREAD

**Issue by rob729** [fossasia/open-event-server#6762]
**Describe the bug**
Unable to like/dislike some events in the open event attendee app.

**Expected behavior**
The user should be able to like/dislike the events without any error.

**Additional context**
URL: https://open-event-api-dev.herokuapp.com/v1/user-favourite-events 
Response: 
```
{"errors": [{"status": 409, "source": {"pointer": "/data/relationships/event"}, "title": "Conflict", "detail": "Event already favourited"}], "jsonapi": {"version": "1.0"}}
```

URL: https://open-event-api-dev.herokuapp.com/v1/user-favourite-events/16
Response: 
```
{"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}
```

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by codedsun** [comment]
@rob729 Thankyou for opening an issue, We also mention the client-side issue which was created for reference.

https://github.com/fossasia/open-event-attendee-android/issues/2553
