### ISSUE TITLE
Admin no longer able to edit and save an event of another user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6776]
In the wizard step 1 the system admin is no longer able to edit and save the event, e.g. the way we kept spam from the start page manually was to set events to private in wizard step 1.

![Screenshot from 2020-01-22 16-12-04](https://user-images.githubusercontent.com/1583873/72906241-2f554d00-3d32-11ea-94e9-34d6e9fb1790.png)

**Comment by kushthedude** [comment]
@iamareebjamal Is it due to the old version of the fork of `JSON-Rest` we are using ?

**Comment by iamareebjamal** [comment]
It didn't happen before, so no

**Comment by kushthedude** [comment]
@iamareebjamal The case is not for admin editing events, No one can create private events

**Comment by codedsun** [comment]
@kushthedude - The request from the frontend is 

```
{"data":{"attributes":{"name":"Testing","description":"Hey","starts-at":"2020-01-26T18:05:00.000Z","ends-at":"2020-04-01T11:30:41.280Z","timezone":"Asia/Calcutta","location-name":"Testing Singapore Lane Singapore Europe  Germany","searchable-location-name":"Singapore","longitude":0,"latitude":0,"logo-url":null,"original-image-url":null,"is-map-shown":true,"is-sponsors-enabled":false,"is-ticket-form-enabled":true,"is-sessions-speakers-enabled":false,"is-featured":false,"is-promoted":false,"is-billing-info-mandatory":false,"is-tax-enabled":false,"can-pay-by-paypal":false,"can-pay-by-paytm":false,"can-pay-by-stripe":false,"is-stripe-linked":false,"can-pay-by-cheque":false,"can-pay-by-bank":false,"can-pay-by-omise":false,"can-pay-by-alipay":false,"can-pay-onsite":false,"payment-country":null,"payment-currency":"USD","paypal-email":null,"cheque-details":null,"bank-details":null,"onsite-details":null,"schedule-published-on":"1970-01-01T00:00:00.000Z","has-owner-info":false,"owner-name":null,"owner-description":null,"external-event-url":null,"ticket-url":null,"code-of-conduct":null,"state":"published","privacy":"public","deleted-at":null},"relationships":{"event-type":{"data":{"type":"event-type","id":"15"}},"event-topic":{"data":{"type":"event-topic","id":"3"}},"event-sub-topic":{"data":{"type":"event-sub-topic","id":"46"}},"event-statistics-general":{"data":{"type":"event-statistics-general","id":"40"}},"user":{"data":{"type":"user","id":"2"}},"order-statistics":{"data":{"type":"order-statistics-event","id":"40"}},"owner":{"data":{"type":"user","id":"2"}},"organizers":{"data":[]},"coorganizers":{"data":[]},"track-organizers":{"data":[]},"registrars":{"data":[]},"moderators":{"data":[]}},"type":"event","id":"40"}}
```

The relationship here 
`"order-statistics":{"data":{"type":"order-statistics-event","id":"40"}}`


should be

`"event-order-statistics": {
                "data": {
                    "type": "order-statistics-event",
                    "id": "40"
                }
            },
`

which means  the key ~order-statistics~ renamed to `event-order-statistics` . It will work fine, please check

**Comment by iamareebjamal** [comment]
Why is frontend even sending order statistics? Makes no sense

And the relationship should be order-statistics only, not `event-order-statistics`

So, it is both a server issue and frontend issue. More severe issue on the frontend

**Comment by codedsun** [comment]
@iamareebjamal - The frontend is also sending event-general-statistics. This should also not be sent.

**Comment by iamareebjamal** [comment]
That is my point. It should not be sending any relationship

**Comment by codedsun** [comment]
@iamareebjamal - The relationship endpoint is `'/events/<int:id>/relationships/order-statistics'` oly. So not an issue on server

```
api.route(
    EventRelationship,
    'event_order_statistics',
    '/events/<int:id>/relationships/order-statistics',
    '/events/<identifier>/relationships/order-statistics',
)
```

**Comment by iamareebjamal** [comment]
Then the server should be able to expect 'order-statistics' and not fail like it is currently

**Comment by codedsun** [comment]
As per the discussion with @iamareebjamal sir. It's not a server issue.

Areeb: Then change the key in frontend. Nothing can be done on server for this for now

**Comment by kushthedude** [comment]
Open the issue on frontend with the problems discussed with @iamareebjamal .
