### ISSUE TITLE
Created_at set to NoneType in RoleInvite model

### ISSUE THREAD

**Issue by diru1100** [fossasia/open-event-server#6782]
**Describe the bug**

created_at variable set to NoneType while comparing
**To Reproduce**
1. Instantiate the RoleInvite class, and save_to_db
2. Compared it with the current time

**Expected behavior**

Expected it to print the current time 

**Additional details (please complete the following information):**
 -  MacOS

**Additional context**

The error I got while writing test functions :
![image](https://user-images.githubusercontent.com/39561007/73046229-43668f00-3e97-11ea-984b-82fa11493912.png)

How I called RoleInvite:
![image](https://user-images.githubusercontent.com/39561007/73046286-73159700-3e97-11ea-99c4-a21e74a279b3.png)

**Comment by iamareebjamal** [comment]
No need for new issue. The testing issue was created to catch all bugs like this
