### ISSUE TITLE
change from pep8 to pycodestyle for code checking

### ISSUE THREAD

**Issue by diru1100** [fossasia/open-event-server#6802]
pep8 has been renamed to pycodestyle 
The use of the pep8 tool will be removed in a future release.

**Comment by iamareebjamal** [comment]
Where are we using pep8?

**Comment by diru1100** [comment]
in requirements/dev.txt

**Comment by iamareebjamal** [comment]
It's unused

**Comment by diru1100** [comment]
can be used while writing code to avoid more hound issues, helped me doing the same

**Comment by diru1100** [comment]
black command solves most of hound problems we can remove I guess.

**Comment by imskr** [comment]
Can i work on this issue?

**Comment by iamareebjamal** [comment]
Not required
