### ISSUE TITLE
Add user name to the feedbacks

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-server#6806]
**Is your feature request related to a problem? Please describe.**
For now there is no fields for name of the person who has wrote a feedback, Adding it can make it look good as name of person would also be displayed with the feedback.

**Describe the solution you'd like**
Add the user name field to the feedback section

**Comment by Rits1272** [comment]
I would like to work on this issue!

**Comment by Deeksha2501** [comment]
Is the issue still unresolved?
I would like to work on this.

**Comment by iamareebjamal** [comment]
Low priority, please pick high priority issues or the ones created by maintainers

**Comment by Deeksha2501** [comment]
ok :)

**Comment by sravani2415** [comment]
can i work on this issue

**Comment by saif007sm** [comment]
Can I work on this issue

**Comment by mariobehling** [comment]
out of scope currently. Therefore closing it.
