### ISSUE TITLE
Ticket Email: Ticket Download not working. Wrong URL

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6818]
The ticket download email comes with a wrong URL to something like "https://api.eventyay.com/generated/tickets/orders/tickets/pdf/9bdedaa....".

It results in a page: "Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

![Screenshot from 2020-02-05 03-13-13](https://user-images.githubusercontent.com/1583873/73804964-a7f1ea00-47c5-11ea-9d9f-7f80612f5684.png)
![Screenshot from 2020-02-05 03-12-36](https://user-images.githubusercontent.com/1583873/73804966-a88a8080-47c5-11ea-8ed4-ac622269dce3.png)

**Comment by mrsaicharan1** [comment]
@abhiandthetruth Are you willing to work on this?

**Comment by abhiandthetruth** [comment]
Nope it's open

**Comment by mrsaicharan1** [comment]
Will fix this.

**Comment by abhiandthetruth** [comment]
All the best.

**Comment by mrsaicharan1** [comment]
@iamareebjamal @mariobehling If the user can access the ticket via a link, it would bring us back to this issue https://github.com/fossasia/open-event-server/issues/5608

**Comment by mrsaicharan1** [comment]
As the tickets are already attached, I don't think it's necessary for the link. If there was any error and the tickets/invoice could not be sent to the user, we could point them to eventyay.com so that they could download it.

**Comment by iamareebjamal** [comment]
The pdf link should still work. It won't lead to the above issue because of your PR itself

**Comment by mrsaicharan1** [comment]
Alright

**Comment by mrsaicharan1** [comment]
`https://<API_HOST>/generated/invoices/orders/invoices/pdf/1a523e55-7b46-46bd-90c1-85805384e9da/U3ZUQUZoTE/1a523e55-7b46-46bd-90c1-85805384e9da.pdf`.

The current link which is being stored would've had no errors if the files were stored in static/templates(where flask looks to serve static files like these). But all our tickets are at `generated/`.

@iamareebjamal What do you suggest as a plausible solution? I was wondering if we could create an exclusive `generated` route.

**Comment by iamareebjamal** [comment]
It was already created by you only

**Comment by iamareebjamal** [comment]
Thinking about this again, you are right. This can not work without it being accessible to the general public. @mariobehling It will either be available to anyone with the link or it'll throw an error for the user. There is no way to know who the user is with just the link of the PDF. So what should be done? We can either remove the link from the email and users can go to frontend to see the ticket. Or, we can allow it to be accessed by anyone who has the link

**Comment by mariobehling** [comment]
Best would be to provide a request for the user to login. The first step is to send the tickets by email and dont send the link in the confirmation email as a quick fix. We can simply say "Your ticket is enclosed. You can also download in the My ticket section in your account."

**Comment by mrsaicharan1** [comment]
@mariobehling Ticket attachments are already being sent. So that's covered. I'll add the request for the user to login.
