### ISSUE TITLE
Write tests for notification functions 

### ISSUE THREAD

**Issue by diru1100** [fossasia/open-event-server#6828]
**Description**
This is a sub issue of #5320
 
Tests are required for notification functions to ensure that they work properly. This increases the test coverage for the code.

**Additional context**
Working on it.

**Comment by iamareebjamal** [comment]
Please only create sub issues when the PR is ready

**Comment by diru1100** [comment]
In send_followup_notif_monthly_fee_payment and send_notif_monthly_fee_payment in helpers notification.py.

There is **no** title attribute in NOTIFS[MONTHLY_PAYMENT_FOLLOWUP_NOTIF] and NOTIFS[MONTHLY_PAYMENT_NOTIF]

**Comment by iamareebjamal** [comment]
Great. You can go ahead and fix it
