### ISSUE TITLE
Add gitpod integration

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6848]
https://gitpod.io

**Comment by NirmalManoj** [comment]
I would like to work on this issue.

**Comment by nisarhassan12** [comment]
Gitpod support would be nice for simplifying code contributions. A lot of popular OSS projects out there are using it:

- https://github.com/freeCodeCamp/freeCodeCamp
- https://github.com/facebook/docusaurus
- https://github.com/mozilla/pdf.js/

You can find a brief list of them at https://contribute.dev

![image](https://user-images.githubusercontent.com/46004116/77501629-64893300-6e7a-11ea-82d7-5599b0215bd4.png)

@NirmalManoj Any progress on this ^-^ ?
If you don't have time then I can make a PR.

**Comment by iamareebjamal** [comment]
@nisarhassan12 Go ahead

**Comment by NirmalManoj** [comment]
@nisarhassan12 Please go ahead. I got busy with some other work, and since no one responded, I thought it was not a high-priority issue, so I could do it later.

**Comment by nisarhassan12** [comment]
Thanks! I will soon make a PR.

**Comment by nisarhassan12** [comment]
Can anyone help me with Gitpodifying this project? this is what is automated so far via Gitpod what else is supposed to be automated?
![image](https://user-images.githubusercontent.com/46004116/78107931-cf54e400-740f-11ea-8a62-a2e36074746e.png)

You can try the current state via this link on my fork of the repo:

https://gitpod.io/#https://github.com/nisarhassan12/open-event-server/

I'm a Front-end Developer not very familiar with Python.

**Comment by iamareebjamal** [comment]
Hi, there's no need for yarn install and just installing requirements/dev.txt should be enough. I don't understand 2 init blocks. The command should be `python manage.py runserver`

The exports aren't needed. Instead .env.example should be copied to .env file and a `SECRET_KEY` should be generated. This process is given in the installation guide
