### ISSUE TITLE
Document about configuring pre-commit on local installation

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#6862]
There is no documentation about how to configure pre-commit hooks.
Please add the required documentation for the same.

**Comment by diru1100** [comment]
I had issues with pre-commit and black usage before. Would love to document it.

**Comment by scheleon** [comment]
I would like to work on it if it is not already assigned!

**Comment by imskr** [comment]
I would like to document this. Which file should I place this?

**Comment by iamareebjamal** [comment]
README.md

**Comment by salonigupta1** [comment]
Can I work on this issue, if this is available?

**Comment by prateekj117** [comment]
@salonigupta1 Sure, go ahead.

**Comment by XitizVerma** [comment]
May i work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mirajhad** [comment]
can I work on this issue.

**Comment by snitin315** [comment]
yes

**Comment by blossom2017** [comment]
@mirajhad  I noticed that there hasn't been any recent activity since a while now. Hence I have linked a PR. Hope it's okay.
