### ISSUE TITLE
Docker image eventyay/nextgen-api-server does not exists, preventing Kubernetes deployment

### ISSUE THREAD

**Issue by remaininlight** [fossasia/open-event-server#6874]
**Describe the bug**
The Docker image eventyay/nextgen-api-server referred to in the Kubernetes deployment yamls (https://github.com/fossasia/open-event-server/blob/development/kubernetes/yamls/api-server/deployment.yml#L21) does not exist.

![image](https://user-images.githubusercontent.com/4106946/76007480-02d24a80-5f06-11ea-914b-1ad3c8055801.png)

This means that when Kubernetes attempts to pull it it gives an error 'Back-off pulling image "eventyay/nextgen-api-server:latest": ImagePullBackOff'. I'm not sure if I'm doing something wrong? I'm following these instructions https://github.com/fossasia/open-event-server/blob/development/docs/installation/gce-kubernetes.md

**To Reproduce**
1. Go to this guide https://github.com/fossasia/open-event-server/blob/development/docs/installation/gce-kubernetes.md
2. Follow it until the step: 
$ ./kubernetes/deploy.sh create all
3. The deploy completes but when inspecting the service api-server it gives the error 'Back-off pulling image "eventyay/nextgen-api-server:latest": ImagePullBackOff'

**Expected behavior**
Kubernetes should find the image eventyay/nextgen-api-server, pull it and deploy it

**Stacktrace**

**Additional details (please complete the following information):**
Using Google Cloud Kubernetes

**Additional context**

**Comment by iamareebjamal** [comment]
Yes, kubernetes docs are quite outdated as we are currently using docker-compose in production

**Comment by mariobehling** [comment]
I think Kubernetes is out of scope these days for us. We need to delete the docker image possibly as it is not working as expected. Areeb passed away and we lost our development lead. Therefore closing this.
