### ISSUE TITLE
User Links should not be visible if user is deleted

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-server#6954]
**Describe the bug**
User Links are there even if user is deleted

**Expected behaviour**
User Links should not be visible if user is deleted

**Screenshots**
![u5](https://user-images.githubusercontent.com/19900978/56050087-93d98980-5d68-11e9-9ce9-40076fe4ab08.png)

**Additional context**
I am working on it

**Comment by satya7289** [comment]
I wanted to work on it. @iamareebjamal

**Comment by satya7289** [comment]
> This is a server issue. Why should frontend even receive something from server if it is deleted
@iamareebjamal please let me know, what's should return from the server if it is deleted.

**Comment by iamareebjamal** [comment]
I'm not sure if this is an issue now. Definitely not high priority. Someone will need to reproduce it and make sure it's still an issue
