### ISSUE TITLE
Support Signup Emails in Other Languages than English

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#6956]
If a user is signing up in a specific language e.g. uses Thai, then the signup email should also have Thai on the top of the email and English (as a backup) below.

**Comment by manakwadhwa2002** [comment]
@mariobehling I would like to work on this issue, should I start the work in following steps:

1. Detect the language user is using to signup.
2. Send that language as a language that will be used in email.
3. Push the email in same given language.

**Comment by iamareebjamal** [comment]
Duplicate of #7405
