### ISSUE TITLE
Add flask_graphql to requirements

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#6976]
**Describe the bug**

When running `python manage.py db upgrade`, it shows the following error, when if you update all the dependencies:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from app.instance import current_app as app
  File "/home/geeky_boy/PycharmProjects/open-event-server/app/instance.py", line 41, in <module>
    from app.graphql import views as graphql_views
  File "/home/geeky_boy/PycharmProjects/open-event-server/app/graphql/views.py", line 1, in <module>
    from flask_graphql import GraphQLView
ModuleNotFoundError: No module named 'flask_graphql'
```

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/blob/1afa3afb4fa1458a29f8d89a13c3a60329698e44/requirements/common.txt#L66-L69

Already present

**Comment by prateekj117** [comment]
Ohh. I also see it is present in the dependencies but I still get this error.

**Comment by iamareebjamal** [comment]
Maybe issue with virtual environment. Rerun pip install -r requirements.txt

**Comment by prateekj117** [comment]
`pip install -r requirements.txt` 
Ran this again inside the venv. Earlier also I ran it inside virtual env.
I again got the same error. I also got the message that requirement already satisfied in case of `pip install -r requirements.txt` and graphql dependencies.

It was solved when I ran `python3 -m pip install flask-graphql==2.0.1`

**Comment by prateekj117** [comment]
```
(venv) ➜  open-event-server git:(complete-orders-api) pip --version
pip 19.0.3 from /home/geeky_boy/PycharmProjects/open-event-server/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip (python 3.7)
(venv) ➜  open-event-server git:(complete-orders-api) python -m pip --version
pip 20.0.2 from /home/geeky_boy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by iamareebjamal** [comment]
Seems the project wasn't running in venv
