### ISSUE TITLE
Deduplicate get_new_slug method

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#6984]
`get_new_slug` method is duplicated many times through the project

**Comment by jerrycode06** [comment]
I want to work on this issue. Can I give it a try?

**Comment by iamareebjamal** [comment]
Sure

**Comment by sanjana-302** [comment]
I want to work on this issue. Can I try?

**Comment by iamareebjamal** [comment]
@jerrycode06 has already claimed it

**Comment by jerrycode06** [comment]
@iamareebjamal My system facing some problem so it will take time to fix that's why I am not working this issue right now. Anyone can work on it. 
Thanks

**Comment by iamareebjamal** [comment]
@sanjana-302 Go ahead

**Comment by sanjana-302** [comment]
Why mention get_new_slug method in open-event-server/app/api/helpers/db.py?
I think get_new_slug method is a Database-helper and is not restricted to any particular model as mention in line 10 open-event-server/app/api/helpers/db.py.
Line 10: #ONLY INCLUDE THOSE DB HELPERS WHICH ARE NOT SPECIFIC TO ANY MODEL

get_new_slug method is reused in the following models:
open-event-server/app/models/event_location.py
open-event-server/app/models/event_sub_topic.py
open-event-server/app/models/event_topic.py
open-event-server/app/models/event_type.py

Should I define get_new_slug in db.py?
Is this correct?

**Comment by iamareebjamal** [comment]
It is redefined in those models with subtle differences, you need to define a generic `get_new_slug` and remove it from these places:

```
open-event-server/app/models/event_location.py
open-event-server/app/models/event_sub_topic.py
open-event-server/app/models/event_topic.py
open-event-server/app/models/event_type.py
```
