### ISSUE TITLE
Remove repetitive safe_query

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7001]
You'll find a lot of unnecessary and repetitive `safe_query` calls like `safe_query(db, Session, 'id', view_kwargs['session_id'], 'session_id')`

First of all, all of this should be abstracted, manually calling this is the ultimate source of bugs. However, that will take massive restructuring of the project and hence, for now, just refactor it to be simpler, like `safe_query_kwargs(Session, view_kwargs, 'session_id')`, that's all the info it needs to do its thing, no need for extra verbosity. If possible, change to `safe_query_by_id(Session, view_kwargs['session_id'])`

**Comment by iamareebjamal** [comment]
See last commit of #6997 for more info

**Comment by satya7289** [comment]
@iamareebjamal I want to work on this issue.

**Comment by prateekj117** [comment]
@satya7289 Go ahead.

**Comment by iamareebjamal** [comment]
Not really?

**Comment by satya7289** [comment]
Yes, In the latest master branch. Nowhere I see the code start with safe_query(db.. or safe_query(self ..

**Comment by satya7289** [comment]
I got it. I have to convert the all safe_query(Session, 'id', view_kwargs['session_id'], 'session_id') 
1. self_query_by_id(Session,view_kwargs['session_id']) if view_kwargs['session_id']=='session_id'. and second parameter is 'id'.

Am I right? . @iamareebjama

**Comment by iamareebjamal** [comment]
No, you need to create a new method which takes the dictionary and key and does the same thing as safe query but without repetition

**Comment by satya7289** [comment]
> No, you need to create a new method which takes the dictionary and key and does the same thing as safe query but without repetition

I'm actually new in this, I do not understand 'safe query but without repetition' part, need some more clarification. @iamareebjamal

**Comment by iamareebjamal** [comment]
You have to change `safe_query(db, Session, 'id', view_kwargs['session_id'], 'session_id')` into `safe_query_kwargs(Session, view_kwargs, 'session_id')` so there's no repetition
