### ISSUE TITLE
Remove duplicate exceptions in api/helpers/errors and exceptions.py

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7008]
For some strange reason, duplicate errors like ForbiddenException, ConflictException and UnprocessableEntity are present in code in errors.py and exceptions.py. Remove duplicate types

**Comment by Satyam52** [comment]
@iamareebjamal Can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by Satyam52** [comment]
@iamareebjamal  these duplicates have a little different name so, should I import UnprocessableEntityError as UnprocessableEntity or should I change the error some function is throwing UnprocessableEntity to UnprocessableEntityError?

**Comment by iamareebjamal** [comment]
The point is to remove the duplicates, remove the ones which are less

**Comment by Satyam52** [comment]
#7019

**Comment by Satyam52** [comment]
@iamareebjamal I fixed remaining issue but coverage result is failing ? How to correct it?

**Comment by iamareebjamal** [comment]
Leave it

**Comment by Satyam52** [comment]
@iamareebjamal I rebased and also used pre-commit Formater. Can you look into PR?
