### ISSUE TITLE
Deduplicate get_new_identifier

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7016]
Like #6984, get_new_identifier is duplicated in event, order and event invoice. It should be refactored and reused

**Comment by jonodrew** [comment]
Can I take a look at this, please?

**Comment by snitin315** [comment]
Yes go ahead.

**Comment by jonodrew** [comment]
Why is the identifier for the `Event` model so different to the others? https://github.com/fossasia/open-event-server/blob/069d8f8cb80b347b641b57b311305838d14ae5ef/app/models/event.py#L29

**Comment by iamareebjamal** [comment]
Because it needed to be short. You can go with other identifiers for now

**Comment by Rachit420** [comment]
I am new and want to contribute can i get this project.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by rgrupesh** [comment]
Can I take a look at this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by kbhagi** [comment]
Folks , is this issue still open . I would like to contribute to this fix ?

**Comment by iamareebjamal** [comment]
Yes
