### ISSUE TITLE
event-invoices endpoint failing

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7063]
/event-invoices endpoint is failing because it has `has_organizer` decorator set up which either expects `event_id` param in URL or expects user to be an admin.

This is obviously not the case with the endpoint. Hence, it should be fixed

**Comment by God-father1** [comment]
I want to work on this issue, please assign me.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by God-father1** [comment]
Will you please guide me i'm not able to find the file.

**Comment by iamareebjamal** [comment]
You'll have to understand the codebase first

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this issue

**Comment by iamareebjamal** [comment]
Go ahead
