### ISSUE TITLE
Move initial custom form creation on server from frontend

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7071]
Currently, custom form's initial fields are created on frontend when an event is created first. This is not the correct behaviour. They should be created on server. In the `after_create_object` hook of the Event Post Handler, the custom form fields of attendee, speaker and session should be created and then the logic should be removed from frontend

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this?

**Comment by iamareebjamal** [comment]
This has work to be done on both frontend and backend. Go ahead

**Comment by HADES-01** [comment]
@iamareebjamal Is it still open? I would  love to work this issue.

**Comment by Tlazypanda** [comment]
@iamareebjamal Was checking the code for this I can see a create custom fields function for attendees in the after_create_object method only on the required fields so should I add this for speaker and session on the required fields? :sweat_smile: Didn't understand where the camelCase identifier code is present though?

**Comment by Tlazypanda** [comment]
@iamareebjamal is my understanding of this issue alright? :sweat_smile:

**Comment by iamareebjamal** [comment]
Leave camel case part

**Comment by mariobehling** [comment]
Closing this as it is now out of scope for V2.5
