### ISSUE TITLE
Remove modules from project

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7087]
Modules of Ticketing System, Payments and Donation are disabled by default and confuse beginners. Also, they are not even correctly implemented to prevent API usage in backend. They should be removed

**Comment by God-father1** [comment]
Do we need to keep the tickets module or not?

**Comment by iamareebjamal** [comment]
The modules functionality needs to be removed. All modules will be kept.

**Comment by God-father1** [comment]
I'm looking in models, is that where we need to edit the functionality? (new of opensource)

**Comment by iamareebjamal** [comment]
In models, schema, API, permissions, etc.

**Comment by God-father1** [comment]
Thank You! Working on it!

**Comment by DevanshD3** [comment]
Hey i am new to open source and want to be familiar with it . Can i work on this issue?

**Comment by snitin315** [comment]
Taking this up.

**Comment by snitin315** [comment]
> The module's functionality needs to be removed. All modules will be kept.

@iamareebjamal You mean the functionality to enable/disable modules? and Enable them by default.

**Comment by iamareebjamal** [comment]
It means that API, schema, db models will be removed. And similarly, they'll be removed from the frontend first and assumed to be always enabled

**Comment by snitin315** [comment]
Got it.
