### ISSUE TITLE
Black in pre-commit applying changes to migrations

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#7097]
**Describe the bug**

Black in pre-commit is applying changes to excluded directory like `migrations`.

**Expected behavior**

Shouldn't apply changes to excluded path.

**Additional details (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version [`3.7.0`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

Will work on this

**Comment by Haider8** [comment]
@iamareebjamal How should I start working on this

**Comment by prateekj117** [comment]
@Haider8 Looks like a known issue. This might help: https://github.com/psf/black/issues/395.

**Comment by Haider8** [comment]
Yeah. The workaround could be, explicitly adding excluded files in pre-commit config.

**Comment by prateekj117** [comment]
Not sure if we would call it a workaround. The behavior of `black` when processing through pre-commit is that it takes the files which are passed through the command line. I think you can find a good explanation in this answer: https://stackoverflow.com/a/61046953/9169348.
