### ISSUE TITLE
USD as currency for free tickets in invoice pdf total amount

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#7101]
**Describe the bug**

There is no need to show currency (in `Total Amount`) for free tickets in invoice pdf. We can just show it to be 0.

![invoice-screenshot](https://user-images.githubusercontent.com/43299408/86400062-96a20080-bcc5-11ea-849f-7ed0966d296d.png)

**To Reproduce**
1. Create event with free tickets
2. Complete order for that event
3. Download invoice of that order
4. See error (`Total Amount`)

**Additional details (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version [`3.7`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

Will work on this

**Comment by iamareebjamal** [comment]
Not a priority, adds more complexity
