### ISSUE TITLE
Remove deprecated Attendee Creation Endpoint

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7105]
Now attendee creation is controlled through create order API, and hence the Attendee Creation Endpoint must be removed

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this

**Comment by iamareebjamal** [comment]
To be done when everything is tested on web and migrated in Android

**Comment by prateekj117** [comment]
@iamareebjamal This issue is good to go now, right?

**Comment by iamareebjamal** [comment]
No, Android apps haven't been updated yet

**Comment by satya7289** [comment]
Can I work on this issue @iamareebjamal @mariobehling

**Comment by Tlazypanda** [comment]
@iamareebjamal is this issue active? :sweat_smile:

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/issues/7105#issuecomment-674539683

**Comment by arunchauhan02** [comment]
I wann work on thid issue. please assign this to me and since im new to this repo so please guide me through

**Comment by arunchauhan02** [comment]
external contributors means

**Comment by naokichau** [comment]
working on this
