### ISSUE TITLE
Ticket Email: Create a better Text Email for confirmed ticket orders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7148]
We need a better ticket email. An HTML email would require a number of changes, but we can already create a better text email to improve things in the first step. An Email sample below.

 Questions: 
* What if the user bought several tickets, what link do we provide?
* Would it be possible to create a link string to provide the option "Add to my calendar", e.g. Google, Outlook, iCal

---

SUBJECT: Your Tickets for [event name]

Hello,

this is your order confirmation for [Event Name] ([event page link]) organized by [organization name].

YOUR TICKETS

Please download your tickets here: [link to ticket page]
You need to be logged in to access your ticket.

ORDER SUMMARY

Date: [date of order]
Order #: [order number]
Ordered by: [Name of Person who ordered]

Type: [Ticket Type]
Quantity: [Number of Tickets of Ticket Type bought]

*/ If the user buys different ticket types show additional ticket types and quantity beloe /*

Type: [Ticket Type]
Quantity: [Number of Tickets of Ticket Type bought]

ABOUT EVENT

Date: [Date of Event]
Time: [Time of Event with tiemzone]
Location: [Address of Event or link to virtual event]
OpenStreetMap: [Link to Location in OpenStreetMap (only show if it is an venue based event]

Add to my calendar:
Google: [link string]
Office 365: [link string]
Outlook: [link string]
iCal: [link string]
Yahoo: [link string]

YOUR ACCOUNT

Login to your account and manage your orders: https://eventyay.com/login

This email was sent to [Email address of recipient here]
Copyright © [Current Year] eventyay.com

**Comment by snitin315** [comment]
Taking this up.

**Comment by maze-runnar** [comment]
@snitin315 are you still on it or I can start with this?

**Comment by snitin315** [comment]
You can go ahead with this.

**Comment by maze-runnar** [comment]
@iamareebjamal I have added sendgrid API to Admin panel, but still not getting mail service -
![Screenshot from 2020-08-11 21-06-25](https://user-images.githubusercontent.com/56407566/89917856-f372ce00-dc16-11ea-80a1-b1f8224b4c3d.jpg)

Do I need to add some thing else too.

**Comment by iamareebjamal** [comment]
You need to run celery to receive mails

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
@iamareebjamal I am getting error while trying to send an email after starting celery -
![Screenshot from 2020-08-12 08-23-21](https://user-images.githubusercontent.com/56407566/89969963-4c714f00-dc75-11ea-85e8-e5ebe7aa8c6a.png)

**Comment by iamareebjamal** [comment]
Sendgrid is rejecting the request.

**Comment by maze-runnar** [comment]
@iamareebjamal I have not find solution of the following part of email template, should I create a PR for rest. Or if you please help me with this in getting individual tickets and types. 
```
Type: [Ticket Type]
Quantity: [Number of Tickets of Ticket Type bought]

/ If the user buys different ticket types show additional ticket types and quantity beloe /

Type: [Ticket Type]
Quantity: [Number of Tickets of Ticket Type bought]
```

**Comment by iamareebjamal** [comment]
Create the PR and discuss it there

**Comment by vj-codes** [comment]
@mariobehling @iamareebjamal I would like to work on this , anything more that I should know?

**Comment by iamareebjamal** [comment]
@vj-codes Please take a look at the linked PR. Most of the work has been done. You can continue on that

**Comment by Aayush-hub** [comment]
@mariobehling I want to work on it!

**Comment by sravani2415** [comment]
@mariobehling I want to work on this can anyone explain me about this please
