### ISSUE TITLE
Add session status change validations

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7149]
These are the allowed state changes for session:

Draft -> Pending -> Confirmed, Accepted, Rejected -> Cancelled, Withdrawn

Draft: Not ready to be reviewed, won't be shown to the organizer
Pending: Ready to be reviewed by the organizer and accepted or rejected
Confirmed/Accepted: Don't know what's the distinction between these two
Rejected: Session was rejected
Cancelled: Organizer can cancel the session even after it was accepted. Only an organizer can cancel a session
Withdrawn: A session can be withdrawn by speaker

Of course things will get more complicated with the logistics about actions on each status change.

Currently, there are 2 state change triggers:

- Accepted
  - With Email
  - Without Email
- Rejected
  - With Email
  - Without Email

What other state changes are required? 

Cancelled Email? Contents and who to send it to? Speaker and Attendees?
Withdrawn Email? Contents and who to send it to? Organizers and Attendees?

Action Possible States:

Withdraw: This action can only take place when action is confirmed or accepted, or both?
Cancelled: Same as above

We can start implementing the state change and actions once these queries are clear

**Comment by mariobehling** [comment]
**SESSION ACCEPTANCE FLOW**
Draft (Speaker is working on a submission, but has not submitted it. Organizer can see "draft", but cannot accept it)
↓
Pending (Speaker submitted session. Organizer can see submission and change status to accepted or directly to confirmed)
↲ ↳
↲ 1) Accepted (Organizer has accepted the session. Usually at this stage the organizer communicates with the speaker about details. Some speakers cancel, other speakers confirm their session. Speaker sees in the system that their status has changed to "Accepted".)
↳ Rejected: (Session is rejected by organizer. Speaker can see the status.)
↲ ↳
↲ 1) Confirmed (Organizers confirmed the session of the speakers. Speakers see the status "Confirmed".)
↳ 2) Canceled (Organizers cancel the speaker session for some reason. Speakers see the status "Canceled".)
↳ 3) Withdrawn (Alternatively organizers or speakers have the option to change to "Withdrawn" status, which is technically the same as canceled. However, it helps in the organization sometimes to indicate the reason for a status change. As a matter of fact canceled or withdrawn status can be chosen at any time as well in the flow.)

**SCHEDULER**
For the scheduler. Which session can be added to the scheduler?
* Accepted
* Confirmed
For now it seems to work out best if both "Accepted" and "Confirmed" sessions could be added to the scheduler.

Does this make sense?

**Comment by mariobehling** [comment]
> Withdraw: This action can only take place when action is confirmed or accepted, or both?

The speaker can withdraw at any time after he/she submitted. (It would not make sense to withdraw in draft mode.)
The organizer can also mark a session "Withdrawn" at any time after the speaker submitted it. Sometimes speakers only write an email and dont login to perform this action. Therefore organizers should also have the right to do that.

> Cancelled: Same as above
Sessions can only be cancelled after the status "Accepted" or "Confirmed". A session that is in pending mode cannot be canceled as it has not been in the acceptance list or on the scheduler.

> Rejected: A session that was pending can be changed to "Rejected". Sometimes speakers cancel and slots become available. Rejected sessions can then be accepted and confirmed later. So, it should be possible to allow the organizer to change the mode from "Rejected" to "Accepted" or "Confirmed".

**Comment by mariobehling** [comment]
> Emails:

We need email actions for each state. Let's work this out in a separate issue and focus on the flow in this issue. If it is easier maybe just allow status changes without emails for now.

**Comment by iamareebjamal** [comment]
Everything else makes sense, but what operations should be allowed in withdrawn mode? Can a speaker put it back in pending mode? Can an organizer change status from withdrawn to accepted, confirmed, rejected?

**Comment by iamareebjamal** [comment]
These are the possible transition states as of now. If anything needs to be changed, please tell

```python
SESSION_STATE_DICT = {
    'organizer': {
        'draft': {}, # No state change allowed
        'pending': {'withdrawn': True, 'accepted': True, 'rejected': True, 'confirmed': True},
        'accepted': {'withdrawn': True, 'rejected': True, 'confirmed': True, 'canceled': True},
        'confirmed': {'withdrawn': True, 'accepted': True, 'rejected': True, 'canceled': True},
        'rejected': {'withdrawn': True, 'accepted': True, 'confirmed': True},
        'canceled': {'withdrawn': True, 'accepted': True, 'rejected': True, 'confirmed': True},
        'withdrawn': {'accepted': True, 'rejected': True, 'confirmed': True}
    },
    'speaker': {
        'draft': {'pending': True},
        'pending': {'withdrawn': True},
        'accepted': {'withdrawn': True},
        'confirmed': {'withdrawn': True},
        'rejected': {'withdrawn': True},
        'canceled': {'withdrawn': True},
        'withdrawn': {'pending': True}
    }
}
```

**Comment by mariobehling** [comment]
> Everything else makes sense, but what operations should be allowed in withdrawn mode? Can a speaker put it back in pending mode? 

No, I think the most logic thing is: If someone withdraws the withdraw is final. A message that says "Are you sure you want to withdraw this sessions? This cannot be reverted." would be good.

> Can an organizer change status from withdrawn to accepted, confirmed, rejected?

I think withdrawing is final. Of course we need to see if I am wrong here. We will use this and see how it works, but I think withdrawing is final. If a speaker wants to submit again, he/she needs to fill it in again.
 
> What about organizer changing accepted, rejected, confirmed, canceled sessions to pending mode? Should it be allowed?

I am unsure about this. There might be cases, where this is needed. It is a bit odd though: Imagine a speaker receives an accepted session info and suddenly is set to rejected or pending. On the other hand, we should probably leave the decision how to run things to organizers.

So, yes, lets allow organizers to revert to pending status again or to set to rejected status as well.
