### ISSUE TITLE
Session accept reject email sent without state changes

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7155]
In session after_update_object, session accept reject email is sent if the final state of session is 'accepted' or 'rejected'. This is not desirable as the email will be sent even when there is any update about the session and not necessarily change in state. Thus, email should only be sent when there a change in 'state' of session, and not any change in session data itself

**Comment by Haider8** [comment]
@iamareebjamal I get that here we want to remove `accepted` and `rejected` check. But do I also need to check that the status has actually changed?

**Comment by iamareebjamal** [comment]
Yes
