### ISSUE TITLE
Create recommended installation steps for docker-compose and link in frontend

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7161]
The recommended mode for installation of open event on servers is using docker-compose, which we use in production. Steps for that aren't available in the docs. So create steps for deployment of both server and frontend in respective repositories and link them respectively

**Comment by MaulikVarshney** [comment]
@iamareebjamal I want to work on this issue with you.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by MaulikVarshney** [comment]
Can you guide me a bit as I am a noob to open source and this is the first issue that I am working for.

**Comment by iamareebjamal** [comment]
I understand, but you need to solve this yourself. If I give you the exact instructions, that'll be spoonfeeding and you'll not learn anything in the process. Deploy the server using docker-compose locally and document those steps

**Comment by MaulikVarshney** [comment]
Hi Sir, I have successfully set up the docker in my system. Whenever I try to run the command "docker-compose up", an error:

Couldn't find env files:  /path/.env  
occurs. Do I need to change the code to run it locally?

**Comment by iamareebjamal** [comment]
You need to copy .env.example to .env

Like written in README

**Comment by MaulikVarshney** [comment]
Does it usually take huge time for the command 'docker-compose up' command to end or mine is taking very long on ubuntu terminal?

**Comment by iamareebjamal** [comment]
Depends on your internet connection. It shows you the progress about what it's doing

**Comment by MaulikVarshney** [comment]
![Screenshot from 2020-07-29 11-01-38](https://user-images.githubusercontent.com/46424707/88760778-5d0cca00-d18b-11ea-967f-15c0932caa02.png)
These processes keep on repeating. Am I on the right path?

**Comment by iamareebjamal** [comment]
It is running

**Comment by MaulikVarshney** [comment]
opev_pass as using as the password is ending in password authentication failed for user.

**Comment by MaulikVarshney** [comment]
![Screenshot from 2020-07-29 23-07-12](https://user-images.githubusercontent.com/46424707/88833698-4cdb0600-d1f0-11ea-8a95-7a104ab1c8c2.png)
Module 'sentry_sdk' is not found.

**Comment by MaulikVarshney** [comment]
DocType has been renamed to Document in newer versions. 
Shall I update the code and change the DocType to Document or do anything else as DocType is not able to be imported from elasticsearch_dsl.

**Comment by iamareebjamal** [comment]
Remove elasticsearch code. It isn't being used

**Comment by MaulikVarshney** [comment]
![Screenshot from 2020-07-30 17-36-58](https://user-images.githubusercontent.com/46424707/88920951-54032200-d28b-11ea-8d3d-dfecaf238f26.png)
Sir an Error 'Running outside of application context' is raising. How can I resolve this ishue?

**Comment by iamareebjamal** [comment]
That is strange. I recently set up the project and it didn't come up. I see you're not using virtual env, use that

**Comment by MaulikVarshney** [comment]
![Screenshot from 2020-07-30 22-14-32](https://user-images.githubusercontent.com/46424707/88950482-5462e380-d2b2-11ea-86be-88de3f41f132.png)
Even after changing to a virtual environment, same problem persist

**Comment by iamareebjamal** [comment]
If you installed requirements.txt, how was it missing qrcode dependency? Use pip and python, not pip3 and python3

**Comment by MaulikVarshney** [comment]
![Screenshot from 2020-07-31 01-01-59](https://user-images.githubusercontent.com/46424707/88966133-79168580-d2c9-11ea-9674-2b77a3da1589.png)
Sir I have even tried using  python create_db.py but the same error occurs.

**Comment by iamareebjamal** [comment]
We use python3.7

Project isn't compatible with 3.8

**Comment by progmatic-99** [comment]
Is this still open??
What does it mean by ```link in frontend```?

**Comment by iamareebjamal** [comment]
Link in frontend docs

**Comment by progmatic-99** [comment]
do we have to create a separate issue in the frontend repo?

**Comment by snitin315** [comment]
>So create steps for deployment of both server and frontend in respective repositories and link them respectively

**Comment by progmatic-99** [comment]
Link in frontend docs to  where ? 
Can you please specify?

**Comment by iamareebjamal** [comment]
In frontend repo

**Comment by progmatic-99** [comment]
I am building open-event-server using docker, after i run this command
```docker run web sh```
I get this error:
```
[LOG] Using redis: redis://redis:6379/0 failed to resize tty, using default size
```

**Comment by iamareebjamal** [comment]
You should use docker-compose, not individual docker command

**Comment by DiptoChakrabarty** [comment]
Hey can I attempt this too , I think I  will be able to run it  and then update the docs

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by godslayer201** [comment]
Hey @iamareebjamal does this still require help? Will try to help out.

**Comment by iamareebjamal** [comment]
Last section needs to be modified still

**Comment by godslayer201** [comment]
@iamareebjamal Will update and try to contribute.

**Comment by Aaryan-kapur** [comment]
Hey!
Would love to contribute to this in any matter possible. @iamareebjamal @godslayer201 @DiptoChakrabarty  are you guys still working on this? or **is it open to take up?**

**Comment by iamareebjamal** [comment]
Open

**Comment by Aaryan-kapur** [comment]
Thank you so much 
could you assign me please? @iamareebjamal

**Comment by iamareebjamal** [comment]
Please send a PR

**Comment by Shiwali735** [comment]
Hello! is it open to take up? i wanna work on this.

**Comment by iamareebjamal** [comment]
Green means open

**Comment by Shiwali735** [comment]
Okay!

**Comment by Ayushsunny** [comment]
I would like to work on this issue

**Comment by faisalkhandholpur** [comment]
I wanna work this issue
