### ISSUE TITLE
Handle passwords with '#' 

### ISSUE THREAD

**Issue by aj4ayushjain** [fossasia/open-event-server#7175]
**Handling password**
So this I encountered while setting up server locally on my machine. So if the  postgres password contains a '#' character inside the .env file specially 
DATABASE_URL = postgresql://open_event_user:passwordwith#@localhost:5432/oevent
 then it fail to complete the step 
$> Python3 create_db.py 
and encounters an error.  

**To Reproduce**
1. Go to 'Local Installation' instructions
2. During step 3 to 5 if u set password for postgres with '#' char
3. Encounter an error in step 5

**Expected behavior**
The passwords with '#' character are supported in Postgres so should be supported in the server as well.

**Stacktrace**

>  venv) ➜  open-event-server git:(development) python3 create_db.py
> 
> /home/ayush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1997: SAWarning: Setting 
> 
> 
> 
>   File "/home/ayush/open-event-server/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
>     self.port = int(port)
> ValueError: invalid literal for int() with base 10: 

**Additional details (please complete the following information):**
 - OS: Ubuntu
 - Python Version 3.7

**Additional context**
This may be due to # character making the further on right part nullified and inside the package sqlalchemy for handling port we encounter an error saying an ' ' null character received.

**Comment by iamareebjamal** [comment]
It is supported, you need to escape the # as in any other URL

**Comment by aj4ayushjain** [comment]
Sorry and Thanks, i wasn't aware about this @iamareebjamal .
Should I close this for now.

**Comment by iamareebjamal** [comment]
Yes
