### ISSUE TITLE
Deleted roles/invites in event are not handled correctly

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7193]
As most things with soft delete enabled, deleted invites/roles are not correctly handled/filtered. And there is little to no benefit in keeping soft deletion in these cases, so remove soft deletion for this

**Comment by Ranjit1312** [comment]
@iamareebjamal  

can I work on this issue ?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by Ranjit1312** [comment]
@mansiag 
You can work on the issue
