### ISSUE TITLE
Fix: Make the test_order creation time in test_humanize_helper timezone aware

### ISSUE THREAD

**Issue by mansiag** [fossasia/open-event-server#7194]
https://github.com/fossasia/open-event-server/blob/8612d914c6d49298211c2aaf4a4a4571f5113e87/tests/all/integration/api/helpers/test_humanize_helper.py#L10
Currently the creation time of the `test_order` object is timezone unaware, it should be timezone aware, as it is used in testing the functionality.

**Comment by pranavjandu** [comment]
Can I use pytz library for this ?

**Comment by mansiag** [comment]
Yes
