### ISSUE TITLE
Broken link to API description/blueprint

### ISSUE THREAD

**Issue by letmerecall** [fossasia/open-event-server#7213]
**Describe the bug**

A link to local changes in API blueprint is broken in `README.md`.
I think the file referenced here got deleted in [this](https://github.com/fossasia/open-event-server/pull/6300) PR.

**To Reproduce**
1. Go to https://github.com/fossasia/open-event-server#api-documentation
2. In first line, Click on [the description](https://github.com/fossasia/open-event-server/blob/development/docs/api/api_blueprint.apib).

**Comment by iamareebjamal** [comment]
Yes, it is generated using this command:

https://github.com/fossasia/open-event-server/blob/aa8fd3dfdb1c1067ee08a319aee6c63b5a4bb972/.circleci/config.yml#L73

**Comment by Ranjit1312** [comment]
@iamareebjamal  can I work on this issue ?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by progmatic-99** [comment]
Is this open?
Can I take this up??

**Comment by snitin315** [comment]
@progmatic-99 yes.
