### ISSUE TITLE
Wrong link generated for email verification during local open-event-frontend setup

### ISSUE THREAD

**Issue by blossom2017** [fossasia/open-event-server#7220]
**Describe the bug**
I set up open-event-frontend locally and signed up. The email verification link sent to my email was not working and always resulted in 'Not Found'.  I signed up using the prod version and successfully verified my mail, however on setting the local server up again it still showed unverified user.
**To Reproduce**
Explained Above

**Expected behavior**
The verification link sent via the local server setup should have been correct and the account should have been verified.
As pointed out in the gitter chat replacing link https://open-event.netlify.app/verify?token=TOKEN with 
https://open-event-frontend.now.sh/verify?token=TOKEN will point to the right link for verification.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS]

**Comment by iamareebjamal** [comment]
open-event-frontend.now.sh/verify?token=TOKEN will verify the token at production server, so it is wrong.

localhost:4200 should be the local server link

**Comment by MohitPatni0731** [comment]
Can I work on this issue
