### ISSUE TITLE
Disconnected role invites and actual role

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7235]
There's a problem in permissions system. In dashboard, it shows role invites and in backend it uses UserEventRoles so if you edit a role in dashboard, it changes nothing in the backend. No idea why these 2 are different things but you are still a co-organizer in backend

**Comment by iamareebjamal** [comment]
Either backend should disallow editing role invites because it is confusing, or update actual roles when edited

**Comment by mansiag** [comment]
Can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead. We have decided to remove the option of editing role invite

**Comment by mansiag** [comment]
And what about deleting role invite? Similar to editing, deleting accepted role-invite should either be reflected in UserEventRoles, or deletion should also not be allowed.

**Comment by iamareebjamal** [comment]
Deleting accepted role invite shouldn't be possible I think. Logically, an invite can only be deleted before it is accepted.

**Comment by iamareebjamal** [comment]
Unless there is some kind of unique constraint which disallows sending the invite again

**Comment by mansiag** [comment]
As of now, organizer can delete accepted role invite(although no email is being sent to the user, to inform about this deletion). So, I need to make changes so that it is not possible to delete accepted role invite.
But shouldn't there be functionality to allow organizers to delete any assigned role to other user, not using role-invites model, but other model(UserEventRoles)?

**Comment by iamareebjamal** [comment]
Yes

**Comment by mansiag** [comment]
As of now, anyone can get the details of a particular role_invite through its id. Is it alright that it is accessible to everyone?

**Comment by iamareebjamal** [comment]
Yes
