### ISSUE TITLE
New contributer

### ISSUE THREAD

**Issue by Rahul-3000** [fossasia/open-event-server#7265]
Hey folk!!
I m Rahul Pawar B.Tech 2nd year student. I have tried to set up the environment but wasn't able to set it up/build it. Can anyone mentor me to setup local environment of development

**Comment by iamareebjamal** [comment]
Hi, please use gitter channel for dev support - https://gitter.im/fossasia/open-event-server

**Comment by Rahul-3000** [comment]
Hey!
I have send a message but nobody responded. Really sorry can you help me.

**Comment by iamareebjamal** [comment]
Hmm, you sent the message at 14:00 and posted this comment at 13:58

Besides, people help voluntarily in their own time. And especially when you specify your problem in the question itself. No one wants another indirection of asking what was the problem. Please read this https://jvns.ca/blog/good-questions/
