### ISSUE TITLE
Schedule action to cache upcoming events with criteria

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7297]
Criteria for upcoming events is complex and cannot (and should not) run on every query of API on frontend, so there should be a 2-3 hour schedule action which runs the query and caches the result so we can readily return the cached results.

See this for remaining criteria to be implemented and used: https://github.com/fossasia/open-event-frontend/issues/4697

**Comment by ANIKET502** [comment]
Hi i wanna do work on this issue please assign it to me. Please notice this point that i came first on this issue so please do assign it to me to work.

**Comment by HimanshunVIDIA** [comment]
I want work on this issue please assign this issue to me

**Comment by mariobehling** [comment]
As we are moving to the next version soon this issue is no longer needed.
