### ISSUE TITLE
Use Poetry to manage dependency

### ISSUE THREAD

**Issue by hongquan** [fossasia/open-event-server#7319]
**Is your feature request related to a problem? Please describe.**

Managing packages with requirements.txt is too simple. For example when we want to upgrade packages, we want the packages are upgrade with newest version but still stay compatible with each other. Using requirements.txt means that we have to manually choose and try version for each packages, which is tiresome.

**Describe the solution you'd like**
Let's use [Poetry](https://python-poetry.org/).

**Comment by prakhargurunani** [comment]
@hongquan I have already implemented this previously in an app. I am working on it and will submit a PR soon.

**Comment by hongquan** [comment]
@prakhargurunani Thanks. Let's do it.

**Comment by HarryHuy** [comment]
@prakhargurunani @hongquan How is this going?

**Comment by prakhargurunani** [comment]
@HarryHuy I had got busy with my job and completely forgot about this issue. You can take this.

**Comment by HarryHuy** [comment]
Thanks for your quickly response @prakhargurunani,  I take it from now.

**Comment by mansijain980** [comment]
@hongquan sir, i am a participant at Codeheat.
 I am working on this repo from last some days so I want to make a PR on this issue.

May i fix this issue?
It will be great experience for me.
Thanks

**Comment by HarryHuy** [comment]
@mansijain980 I think it's almost done. I'm testing the deployment image.
