### ISSUE TITLE
Unable to proceed with payments on Paypal

### ISSUE THREAD

**Issue by bellaphan** [fossasia/open-event-server#7339]
When I try to make a payment using Paypal and want to proceed to checkout, then this occur 

<img width="1417" alt="Screen Shot 2020-10-07 at 12 07 38 am" src="https://user-images.githubusercontent.com/50802607/95236841-a8012880-0831-11eb-9723-bba297bdeed4.png">

<img width="1417" alt="Screen Shot 2020-10-07 at 12 07 10 am" src="https://user-images.githubusercontent.com/50802607/95236829-a5063800-0831-11eb-8535-034c3402fb97.png">

**Comment by iamareebjamal** [comment]
Keeping the conversation here to not divide discussion - https://github.com/fossasia/open-event-frontend/issues/5258
