### ISSUE TITLE
Substitute Google fonts and MaxCDN Bootstrap with local version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7366]
Please include Google fonts and Bootstrap on the local server instead of downloading it from CDN to improve the privacy of user.

**Comment by iamareebjamal** [comment]
@mariobehling This for the doc pages of https://api.eventyay.com I presume? The link os opened once a month by no other person than a developer. The effort will definitely be more than benefit in this case. We are not using a specialized bundler like frontend here. I can safely say that no user is impacted by this in regards of privacy

**Comment by mariobehling** [comment]
Ok, thanks for adding the details. Just keep it without priority.

**Comment by nitinosiris** [comment]
I would like to work on it  @mariobehling

**Comment by mdPial** [comment]
I am working on this 😊

**Comment by mdPial** [comment]
Could it be considered for the **codeheat**?

**Comment by mdPial** [comment]
Shoud I add **fonts** in `./static/font/` and bootstrap to `./static/framework` ?

**Comment by iamareebjamal** [comment]
Tell me your approach, how will you remove CDN references from an autogenerated file?

**Comment by mdPial** [comment]
@iamareebjamal I haven't found any approach to do that. Could you give me guidelines to do that?. I thought I don't have to remove those references for this issue. I looked earlier, from which files references are linking but didn't find any.

**Comment by mdPial** [comment]
Oh. I misunderstood then :sweat:

**Comment by mdPial** [comment]
Could you help me?

**Comment by iamareebjamal** [comment]
> The effort will definitely be more than benefit in this case. We are not using a specialized bundler like frontend here
