### ISSUE TITLE
PARSE_QSL issue in DB initialisation

### ISSUE THREAD

**Issue by sansyrox** [fossasia/open-event-server#7385]
**Describe the bug**
When using the commands in a `python3.8` venv:
1. `python3 manage.py db stamp head`
2. `python3 create_db.py`

 I get the following error

```
ImportError: cannot import name 'parse_qsl' from 'cgi' (/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cgi.py)
```

**To Reproduce**
1. Create a python3.8 venv
2. Use the following commands:
 - `python3 manage.py db stamp head`
 - `python3 create_db.py`

**Expected behavior**
It should work without this issue

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: MacOS
 - Python Version 3.8
 - `HEAD` Commit hash [e.g. `4629c62`]: `dd0bd76b2efdcfa94560090e132732d8b6d48c7d`

**Additional context**
I have a hacky patch in mind which can fix this issue till it is not fixed in the main repo.

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md#for-debianubuntu
