### ISSUE TITLE
Ticket PDF should exist for each attendee

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7397]
Ticket PDF is currently associated with an order which should instead be associated with an attendee as each attendee should have a ticket

**Comment by codedsun** [comment]
Ticket PDF if associated with an attendee, now for 2 events and same attendee how we will map the 2pdf and 1attendee? @iamareebjamal

**Comment by codedsun** [comment]
Taking this up!

**Comment by codedsun** [comment]
@iamareebjamal - The ticket holder has the column `pdf_url` which holds the value of the Ticket PDF. Can you explain me more here?

**Comment by iamareebjamal** [comment]
There is a single endpoint to download tickets for an order - https://github.com/fossasia/open-event-server/blob/47eb8e2adb18fc4b31ca8ea6c68f8b45ba36328a/app/api/custom/orders.py#L35-L38

This means I cannot download it for individual attendees

**Comment by mariobehling** [comment]
To clarify: Feature-wise we need both a) a way to download all tickets in an order in one PDF and b) a way to download each ticket and share access of different tickets within an order with the (intended) ticket holder. 

Who has access to tickets? 
1. The person who has made the order has access to all tickets of an order.
2. Different tickets within an order can be bought for different people. Each person has their own email address (and possibly existing account on the system, e.g. eventyay). So, each person should have access associated with their email address, but should not have access to other tickets within the same order.

**Comment by mariobehling** [comment]
Other questions that need to be handled in subsequent issues (this is getting rather complex permission-wise):
* Who has access to the order invoice? -> Only the person ordering the tickets has access. Other people should be able to see the button "invoice" on their complete ticket/order page, but when they click on it, they should see a message "Only the account that made the order is able to access the invoice."
* If a user has access to their tickets, they should not be able to see the list of all other tickets that are within that order, if they are not the account that made the order (the owner of the order). In that case show a message, e.g. with a star like at the bottom of the table and within the box `* Only the "owner" of this order will see all tickets in an order.`
