### ISSUE TITLE
Make emails translatable

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7405]
EMails are defined in https://github.com/fossasia/open-event-server/blob/development/app/api/helpers/system_mails.py

They should be translatable and extracted in the POT files

**Comment by sarvangjain** [comment]
My team wants to work on this issue.

**Comment by iamareebjamal** [comment]
Steps:

1. Extract emails from https://github.com/fossasia/open-event-server/blob/development/app/api/helpers/system_mails.py to email templates here https://github.com/fossasia/open-event-server/tree/development/app/templates/email
2. Change the syntax to Jinja 2

https://github.com/fossasia/open-event-server/blob/a6c2e2c26314138afa9a7857a6951892d6100ddb/app/api/helpers/system_mails.py#L240-L245

to like

https://github.com/fossasia/open-event-server/blob/b51eda5a4ba8488f5731d6a07b1ff847bb2d2d2f/app/templates/email/ticket_purchased.html#L1-L19

3. Change invocation from format to Jinja2

https://github.com/fossasia/open-event-server/blob/a6c2e2c26314138afa9a7857a6951892d6100ddb/app/api/helpers/mail.py#L355-L363

to 

https://github.com/fossasia/open-event-server/blob/b51eda5a4ba8488f5731d6a07b1ff847bb2d2d2f/app/api/helpers/mail.py#L346-L353

4. Integrate https://github.com/python-babel/flask-babel
5. Add gettext in templates https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiii-i18n-and-l10n#Marking%20Texts%20to%20Translate%20In%20Templates
6. Move forward with extraction, etc

**Comment by iamareebjamal** [comment]
@mariobehling As the steps are quite involved, can we first cherry-pick a few emails from https://github.com/fossasia/open-event-server/blob/development/app/api/helpers/system_mails.py to be converted and translated first?

**Comment by vedant-jam008** [comment]
I am starting with open source, so would you recommend me solving this issue

**Comment by mariobehling** [comment]
> @mariobehling As the steps are quite involved, can we first cherry-pick a few emails from https://github.com/fossasia/open-event-server/blob/development/app/api/helpers/system_mails.py to be converted and translated first?

Yes, agree. Could we do these emails first:
* Welcome
* Ticket Email
* Password Reset

**Comment by codedsun** [comment]
@sarvangjain - Are you working on this?

**Comment by sarvangjain** [comment]
@codedsun - I'd love to. But I could really use some guidance.

**Comment by codedsun** [comment]
@sarvangjain - You have commented on various task that you are working on it. If you are not working on any other task then please take this task and mmention that you are working on it. Also, the steps are mentioned here on how to complete the task. please have a look

**Comment by codedsun** [comment]
@sarvangjain ? taking this

**Comment by sarvangjain** [comment]
Unfortunately, I am unable to understand this properly. I'd work on some other issue
Sorry to bother you

**Comment by codedsun** [comment]
Taking this up!

**Comment by Siddhant-K-code** [comment]
@codedsun i would like to work on this, but i also some to help to resolve this issue.

**Comment by manakwadhwa2002** [comment]
@codedsun I would like to work with you on this issue. Can you please take me on this ?

**Comment by iamareebjamal** [comment]
Reopening for more emails

**Comment by codedsun** [comment]
@iamareebjamal - Will take this up for more emails

**Comment by iamareebjamal** [comment]
Work on other issues for now

**Comment by mariobehling** [comment]
Seems already resolved.
