### ISSUE TITLE
Prevent order from being deleted

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7423]
An order should not be deleted. If need be, it can be cancelled. Currently, our server does not handle the logic or soft deleted orders correctly.

**Comment by rajdesai24** [comment]
can I take this?

**Comment by codedsun** [comment]
wanted to ask, that order iss a soft deleted model. So when delete action is performed, the deleted at field is updated.

https://github.com/fossasia/open-event-server/blob/4c8922be1282ce694d5d0364e8fe58b50031d9c4/app/api/orders.py#L456

So, now it shall be marked as cancelled if delete action is performed, also should deleted_at field be updated or not?

**Comment by iamareebjamal** [comment]
Soft deletion should be removed, all orders which have deleted_at set should be actually deleted. And DELETE endpoint should not be allowed, once it'll be removed, server will throw 405 errors when someone tries to delete a ticket

**Comment by codedsun** [comment]
@iamareebjamal - If the DELETE endpoint is not allowed, then how an order will be deleted?

**Comment by iamareebjamal** [comment]
Migration
