### ISSUE TITLE
Return dummy user for deleted ones except for admin user endpoint

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7424]
Organizers/Admins can access user info such as for attendees. In cases a user deletes its account, they can still view their name and email and such. Please return a dummy user for such cases except on the admin page which shows deleted users.

Dummy user's name can be 'Deleted User' and email 'deleted.account@eventyay'

**Comment by rajdesai24** [comment]
can I take this?

**Comment by iamareebjamal** [comment]
Take one issue at a time

**Comment by rajdesai24** [comment]
where do you suggest I should begin?

**Comment by PawanVerma1337** [comment]
@rajdesai24 are you working on this issue ?
If not then can i work on this issue ?
@iamareebjamal

**Comment by rajdesai24** [comment]
@PawanVerma1337  I actually didn't get an update, maybe we can both take it up if you want

**Comment by HimanshunVIDIA** [comment]
can I work on this issue I really want to work on it
