### ISSUE TITLE
Test email is being sent

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7430]
Using mail recorder, test that email is being sent and to a particular user

Test for user registration, order confirmation and password reset first and expand to more emails

**Comment by amansohal8654** [comment]
hello, I would like to work on this issue. could you please guide me

**Comment by ANIKET502** [comment]
Hi i wanna do work on this issue please assign it to me.

**Comment by imSanko** [comment]
I wanna take this issue and word on it kindly assign it to me

**Comment by iamareebjamal** [comment]
We don't assign issues q

**Comment by sneha281** [comment]
Hi , I want to work on this , please assign me @iamareebjamal

**Comment by iamareebjamal** [comment]
Read the comment just above yours please

**Comment by Bhavik-Ardeshna** [comment]
@iamareebjamal can you plz elaborate issue .
I'm not getting it properly..

**Comment by rishabhrathore055** [comment]
Hi i wanna do work on this issue please assign it to me.

**Comment by geegatomar** [comment]
Hi, is anyone still working on this issue? If not, can I please get more info on the issue? I'd like to take it up.

**Comment by mariobehling** [comment]
Closing this as Emails have been tested.
