### ISSUE TITLE
Handle the maxQuantity being negative

### ISSUE THREAD

**Issue by daretobedifferent18** [fossasia/open-event-server#7474]
**Describe the bug**

Presently maxQuantity for discount codes is 100000.
Handle the maxQuantity being negative, i.e. -1
If it is negative, server should not limit the discount code count.

**Comment by satishhhh** [comment]
@daretobedifferent18 i would like to work on this issue 
you mean that if -1 is the quantity it should not limit the discount count but now it is limiting

**Comment by daretobedifferent18** [comment]
> @daretobedifferent18 i would like to work on this issue
> you mean that if -1 is the quantity it should not limit the discount count but now it is limiting

Pls refer [fossaisa/open-event-frontend](https://github.com/fossasia/open-event-frontend/pull/5758)

**Comment by b-thebest** [comment]
I want to work on this issue, Could you please assign me

**Comment by iamareebjamal** [comment]
We don't assign external contributors, please send a PR

**Comment by b-thebest** [comment]
Hello @iamareebjamal I have made one pull request. Could you please review it. Please correct me / suggest me if I am wrong
