### ISSUE TITLE
order.user should not be available to the ticket holder

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#7476]
**Describe the bug**
order.user should not be available to the ticket holder and be only available when the holder is ticket purchaser

Steps:
 - [ ] Remove the user relation when holder is not purchaser
 - [ ] Make the changes in frontend also

**Comment by parmeshwar1807** [comment]
I wanna take up this issue. Assign me

**Comment by b-thebest** [comment]
I want to work on this, Could you assign it to me

**Comment by imSanko** [comment]
I wanna work on to this project can you assign it to me.

**Comment by sneha281** [comment]
Please assign it to me sir @codedsun.I am a Python devloper.

**Comment by sneha281** [comment]
Please assign it to me @codedsun

**Comment by Atri22** [comment]
please assign it to me

**Comment by codedsun** [comment]
You guys can take up the issue if someone has claimed that he/she may work on the issue but no PR is submitted till 5-6 days. their is no need of assigning the issue to anyone.

**Comment by Atri22** [comment]
Sir when I click on the fork button it say that "You don't have the permission to fork to these organization" and when I try to download the code via git these appears.
![Screenshot (34)](https://user-images.githubusercontent.com/72877136/103153729-a011ae80-47b8-11eb-85ed-0e903f39d1dd.png)
![Screenshot (35)](https://user-images.githubusercontent.com/72877136/103153731-a1db7200-47b8-11eb-8f99-4a3d565713cd.png)
![Screenshot (35)](https://user-images.githubusercontent.com/72877136/103153732-a1db7200-47b8-11eb-9a6a-ae09c232f681.png)
![Screenshot (34)](https://user-images.githubusercontent.com/72877136/103153734-a2740880-47b8-11eb-9018-6c6dd3617d73.png)
Please help me.

**Comment by Atri22** [comment]
Sorry to disturb you. The problem has been solved

**Comment by Atri22** [comment]
No sir this problem is not solved. I was having problem in forking (that is solved). I am still having issues in cloning the code.
some screenshots.
![Screenshot (37)](https://user-images.githubusercontent.com/72877136/103156416-59c74a00-47ce-11eb-94cc-1be2d9110d18.png)
![Screenshot (38)](https://user-images.githubusercontent.com/72877136/103156418-5df36780-47ce-11eb-9e80-7ee57e738884.png)
please help me

**Comment by codedsun** [comment]
@Atri22 - I would request you to clean the directory containing the code and clone the project again.

**Comment by iamareebjamal** [comment]
Use Linux or WSL

**Comment by Atri22** [comment]
@codedshun -  I cleaned the directory containing the code but nothing happened, I even created a new directory in the D drive for cloning the code but still the same problem is arising. I tried to clone codes of some other projects to see if there is something wrong with my pc, but other projects were cloned properly. Please help me solve the issue sir. 
here are some screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/72877136/103177279-12f55500-489f-11eb-9cb2-c2fc009a88d6.png)
![Screenshot (43)](https://user-images.githubusercontent.com/72877136/103177283-18529f80-489f-11eb-9e2f-2c253b720186.png)
![Screenshot (44)](https://user-images.githubusercontent.com/72877136/103177286-1b4d9000-489f-11eb-8538-d116f40d7c7c.png)
![Screenshot (45)](https://user-images.githubusercontent.com/72877136/103177287-1dafea00-489f-11eb-8eff-de2409dd59ab.png)
![Screenshot (46)](https://user-images.githubusercontent.com/72877136/103177291-20aada80-489f-11eb-9595-f2b96c8ce93a.png)
@iamareebjamal - As of now I don't know how to use Linux. But I will surly learn it sir.

**Comment by Tlazypanda** [comment]
@codedsun For approaching this issue do we add a post_dump method in the order schema file that checks against the current user and accordingly eliminates the order.user relation or do we make changes elsewhere? :sweat_smile:
