### ISSUE TITLE
User registration  email should contain "Login ID" not just "Login

### ISSUE THREAD

**Issue by Creatoon** [fossasia/open-event-server#7521]
**Describe the bug**
User registration email is missing "ID" word after "login"

To Reproduce
    1. Go to https://eventyay.com/ 
    2. Register 
    3. Check the welcome email , After this line "Your account has been created on Open Event. Congratulations!" 
    4. "Your Login is" 
    
Expected behavior
"Your Login Id is"

Screenshots
![Screenshot_2020-12-20 (1) assacdscdscdscascdscdsvfdbgfbfdbdfvbdfsvsvgd mailsac com](https://user-images.githubusercontent.com/65965202/102701402-92ba6880-427c-11eb-999c-d832f36cfb2a.png)

**Comment by Creatoon** [comment]
@mariobehling  if it's a mistake , I want to fix this.

**Comment by MohitPatni0731** [comment]
Can I work on this issue.

**Comment by Creatoon** [comment]
@MohitPatni0731 Actually I have created an PR on this issue,  please find another issues.

**Comment by MohitPatni0731** [comment]
Np @Creatoon
Thanks for letting me know
