### ISSUE TITLE
Implement Organizer API with list of EventIDs of Organizers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7538]
Here is a question of a user about REST APIs which we also need for the organizer feature:

Is it possible to use this REST interface to query all upcoming events of an organizer? Specifically, that means, can I query all upcoming published events of a user with a web service request and receive the EventIDs? I can then use the EventIDs for the individual queries of the specific event data.

**Comment by iamareebjamal** [comment]
Once group feature is implemented, yes. Currently, the events of a user are private to them

**Comment by Aniruddh1709** [comment]
Can I work on this issue?

**Comment by nayanvayada** [comment]
I wanna work on this isssue

**Comment by iamareebjamal** [comment]
Group feature has been implemented now
