### ISSUE TITLE
Add redis start instruction for Linux in installation

### ISSUE THREAD

**Issue by Tlazypanda** [fossasia/open-event-server#7549]
Currently the local setup instruction lacks the redis-server start instruction for Linux that can introduce errors on hitting endpoints. Adding the instruction `sudo service redis-server start` to the local installation instructions can help new comers avoid this error.

## Screenshot of error 
![image](https://user-images.githubusercontent.com/33183263/103363541-56d79c80-4ae1-11eb-9ebb-f7046c138660.png)

`

**Comment by Tlazypanda** [comment]
@iamareebjamal @mariobehling can you please approve this issue if it seems fit? Thank you :v:

**Comment by nitinosiris** [comment]
Hey @Tlazypanda ,
I just followed the instructions from https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md
I am using Ubuntu 20.04.1 LTS and the error you mentioned never appeared.
I guess it is not compulsory to run that command.

**Comment by nitinosiris** [comment]
Hey @Tlazypanda,
I just followed the instructions listed https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md here. I am using Ubuntu 20.04.1 LTS and I got no such error about redis-server.

**Comment by iamareebjamal** [comment]
Yes, it gets started automatically

**Comment by nitinosiris** [comment]
Maybe in Mac, we need to do it manually as per instructions.

**Comment by Tlazypanda** [comment]
@iamareebjamal @nitinosiris In my case the server was working fine but when I was hitting any endpoint then it was showing this error :sweat_smile: can you try that out?

**Comment by Tlazypanda** [comment]
Closing this since not reproducible.
