### ISSUE TITLE
Add functionality to delete User Event Role

### ISSUE THREAD

**Issue by Tlazypanda** [fossasia/open-event-server#7558]
**Is your feature request related to a problem? Please describe.**
Currently there is no functionality to delete User Event Role. Adding this functionality can allow event organizers to delete role assigned to any user.

Ref issue: #7235

**Comment by Tlazypanda** [comment]
@iamareebjamal @mariobehling can we approve this issue? :sweat_smile:

**Comment by Tlazypanda** [comment]
@iamareebjamal for creating this endpoint I was wondering if we can pass the id of user event role for deletion or not since I don't see it returned otherwise at any place. So should I instead pass role_invite id and from that query the user event role object and delete? Thanks :v:

**Comment by iamareebjamal** [comment]
No, event user role, like all other endpoints

**Comment by Tlazypanda** [comment]
@iamareebjamal so I should add this as a standalone misc endpoint in role_invites,py or create the api and schema file and set up the resource manager architecture since right now I don't see those files and creation for this model is handled in accept_invite function itself? :sweat_smile:

**Comment by iamareebjamal** [comment]
create the api and schema file and set up the resource manager architecture

**Comment by iaryangoyal** [comment]
can I work on this issue?
