### ISSUE TITLE
Wrong value given to one of the backref attributes in discount_code.py

### ISSUE THREAD

**Issue by deo002** [fossasia/open-event-server#7598]
**Describe the bug**
 Wrong value given to one of the backref attributes in discount_code.py.

marketer = db.relationship('User', backref='discount_codes_') 
The value of backref attribute of this line should be changed to 'discount_codes'.

**To Reproduce**
1. Go to open-event-server/app/models/discount_code.py
2. Check the value of *marketer* inside of DiscountCode class

**Expected behavior**
marketer = db.relationship('User', backref='discount_codes') 

**Screenshots**
![](https://res.cloudinary.com/douc4ze4x/image/upload/v1610557902/git/error_dcp25r.jpg)

**Comment by ujjwallabh** [comment]
Hey i am new here can you help me out with its working procedure?
how to work on the issue.

**Comment by mansijain980** [comment]
@deo002 sir, I would like to fix this issue. 

May i ? 
It will be great for me.
Thanks

**Comment by ujjwallabh** [comment]
@mansijain980 can i be a part of ur contribution so that i can learn?
please take look if thats possible i am new to open source contribution

**Comment by SAP-20** [comment]
a newbie to open source .Can i work on this??

**Comment by maze-runnar** [comment]
@MeghalBisht I don't think this is an issue, discount_codes_ in not even used anywhre. If so then please close it.
