### ISSUE TITLE
Delete space in front of colons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7615]
Some text pieces coming from the server has a space in front of colons " :". Please check all text including email texts and delete the space in front of colons.

**Comment by tanay13** [comment]
please assign this to me

**Comment by iamareebjamal** [comment]
please assign this to me

**Comment by deo002** [comment]
I would like to work on this issue.

**Comment by gopal0208** [comment]
I would like to work on this issue
