### ISSUE TITLE
Order Email: Translate it to German

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7630]
We need more emails translated to other languages preferably through weblate. Below an example translation for the order email to German.

If possible please also take out a space in front of " :" (colons) in the English version.

![Screenshot from 2021-01-19 01-29-06](https://user-images.githubusercontent.com/1583873/104973716-df1cd380-59f5-11eb-83ed-a0a02169b0bf.png)

**Subject:** Rechnung und Tickets für {event name}

**Email text**

Hallo,

Vielen Dank für Ihre Ticketbestellung für Codeheat Ask Me Anything - Februar Edition.

Dies ist Ihre Auftragsbestätigung. Sie können Ihre Tickets unter folgender Adresse herunterladen: https://eventyay.com/orders/ed4a6544-0efe-4182-993f-6b5552448f41/view 

Bestellübersicht:
Bestellung: O1610756870-16282
Name: Mario Behling

Ticket: Community-Singup
Anzahl: 1

Über diese Veranstaltung:
Datum: 11. Februar 2021, 14:30 Uhr - 11. Februar 2021, 16:00 Uhr
Online

Beste Grüße,
eventyay Team

Folgend finden Sie eine Nachricht vom Veranstalter:

**Comment by mariobehling** [comment]
Date and messages "Below you find a message from the organizer:" are not translated in the current version.

**Comment by mariobehling** [comment]
![Screenshot from 2021-01-19 17-34-52](https://user-images.githubusercontent.com/1583873/105064120-cc011680-5a7c-11eb-871c-fa6b54c6ecbd.png)

**Comment by iamareebjamal** [comment]
"Below you find a message from the organizer:" is translatable but is not translated
