### ISSUE TITLE
Order Email: Add ics as attachment and standardize for calendar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7632]
When an email arrives from other event platforms Gmail and other email clients automatically provide an option to add it to the calendar. 

1. Please research and implement the structure of the email and possibly tags, so these emails provide the same functionality.
2. Add an .ics file as an attachment to order emails for the event as well.

Example how an event shows up on Gmail.

![Screenshot from 2021-01-19 10-53-13](https://user-images.githubusercontent.com/1583873/105017866-95a7a500-5a44-11eb-9cb6-060c726f7d62.png)

**Comment by ShauryaAg** [comment]
I would like to work on this issue.

**Comment by ShauryaAg** [comment]
I can't figure out how to set the `SMTP_HOST`, `SMTP_USERNAME` etc for development purposes, some help would be appreciated.

**Comment by iamareebjamal** [comment]
Set in settings table

**Comment by ShauryaAg** [comment]
Is there any easy way to do it other than using SQL queries in the Postgres Container?

**Comment by iamareebjamal** [comment]
Run frontend and change through it

**Comment by ShauryaAg** [comment]
I am unable to create a super user for it. I tried running `python manage.py initialize_db -c admin@example.com:password`, but still the user doesn't exist.

Even though the command executes without any exceptions.

![image](https://user-images.githubusercontent.com/31778302/106036536-7cb18a80-60fb-11eb-9ae0-6edd27892e61.png)

**Comment by iamareebjamal** [comment]
Should have run create_db.py while installing like mentioned in the docs

**Comment by ShauryaAg** [comment]
I have installed using docker.

**Comment by ShauryaAg** [comment]
Even when I run `python create_db.py example@example.com password`, it doesn't create a new user.

This is the output I get:
```
/data/app # python create_db.py example@example.com password
/opt/pysetup/.venv/lib/python3.8/site-packages/envparse.py:195: UserWarning: Could not any envfile.
  warnings.warn('Could not any envfile.')
/opt/pysetup/.venv/lib/python3.8/site-packages/envparse.py:195: UserWarning: Could not any envfile.
  warnings.warn('Could not any envfile.')
WARNING:app.instance:Using random secret "45ab1b0c5a8cb8cb2f04a98162b95cbad71d83987dd0b38c25754b3da3dcf95b" for development server. This is NOT recommended. Set proper SECRET_KEY in .env or environment variables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
/data/app #
```

**Comment by iamareebjamal** [comment]
I don't understand why are you using docker?

**Comment by ShauryaAg** [comment]
It is easier to setup using docker. Is it not possible to use docker for development purpose?

**Comment by iamareebjamal** [comment]
No, it is for deployment only

**Comment by ShauryaAg** [comment]
Can we create another issue to do necessary changes in order to make docker available for development purposes too?
After solving this issue.

**Comment by iamareebjamal** [comment]
What's difficult in local installation?

**Comment by ShauryaAg** [comment]
There aren't any issues, but docker installation is easier.

**Comment by iamareebjamal** [comment]
And development harder

**Comment by ShauryaAg** [comment]
Upon some research through [here](https://github.com/sendgrid/sendgrid-python/issues/179#issuecomment-244974054), [here](https://stackoverflow.com/questions/45055188/calendar-invite-is-received-as-ics-file-in-outlook-laravel), and [here](https://github.com/PHPMailer/PHPMailer/issues/175#issuecomment-33802847). It looks like outlook and some other clients (excluding Gmail) needs `Method: Request;` in the file headers for it to display the "Add to calendar" and "RSVP" button.

Upon my testing, there is currently no way add that header using Sendgrid or marrow-mail (for SMTP) as of now. However Gmail displays the "Add to calendar" button just by add a `.ics` file.
