### ISSUE TITLE
Event Order Mail: Time of event wrong

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7633]
In the order email of events the timing is wrong. 

It is:
Datum: February 12, 2021 01:00 PM - February 12, 2021 03:00 PM

It should be 
Datum: February 12, 2021 02:00 PM - February 12, 2021 04:00 PM

compare https://eventyay.com/e/e366f5ca

**Comment by mariobehling** [comment]
Also the dates are not translated.

Question: Should they have the timezone added as in other views maybe?

**Comment by iamareebjamal** [comment]
Translation of dates is not that easy in server, I'll add timezone though
