### ISSUE TITLE
Sign up/Verification Emails shows "Message clipped" in Gmail

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7640]
Gmail clips messages that are larger than 102 KB. As the our signup/verification email only has very little content, it is unclear why it should appear bigger than that or what other reason there is that it clips in Gmail. Please research the cause and implement a solution to ensure the email does not clip in Gmail.

![Screenshot from 2021-01-20 01-24-33](https://user-images.githubusercontent.com/1583873/105110472-f07de280-5abe-11eb-9243-8fe8bc5642b0.png)

**Comment by iamareebjamal** [comment]
No message is clipped above, the entire message is being shown

![image](https://user-images.githubusercontent.com/3874064/105110968-dc99a700-5ae5-11eb-8735-b5cc5c935fb3.png)

**Comment by mariobehling** [comment]
@iamareebjamal Yes, it is the entire message, but the clipped message is still being shown, which confuses users. How can we get rid of that "Clipped Message" option?

**Comment by mariobehling** [comment]
I corrected the title of the issue.

**Comment by iamareebjamal** [comment]
Don't know, it might be a bug in gmail, nothing I found on internet suggests anything that can be done by us AFAIK

**Comment by sudipg4112001** [comment]
> Don't know, it might be a bug in gmail, nothing I found on internet suggests anything that can be done by us AFAIK

It may be due to some storage issues in the respective mail or attachment.  The attachments are not included in the code.

**Comment by 309666** [comment]
i would like to work on this issue
