### ISSUE TITLE
Ticket Invoice: Make it translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7668]
The ticket invoice is not translated to other languages. Please make it translatable.

![Screenshot from 2021-01-26 07-46-59](https://user-images.githubusercontent.com/1583873/105810217-d22a5200-5faa-11eb-9473-e47ad583d55e.png)

**Comment by Akshansh99** [comment]
Hey @mariobehling ! Can you explain what you mean by **translatable** ?

**Comment by 17sushmita** [comment]
Hi @mariobehling, Please clarify what do you mean my translatable and how to reproduce the bug?

**Comment by avats-dev** [comment]
I couldn't find exactly which templates we need to edit here to add translation for invoices. I have found that some are [here](https://github.com/fossasia/open-event-server/tree/development/app/templates/pdf) but I am not sure which one. Also, do we need to implement this in templates only? 
> I would love to work on this.

**Comment by avats-dev** [comment]
@iamareebjamal

**Comment by iamareebjamal** [comment]
> Also, do we need to implement this in templates only?

Yes

**Comment by gyanprakash0221** [comment]
Is this issue still open or closed.
