### ISSUE TITLE
Migrate from flask-script to flask inbuilt cli

### ISSUE THREAD

**Issue by ashutoshc8101** [fossasia/open-event-server#7692]
**Feature Request**
It would be better if functionality to create, populate and drop the database is available using the `manage.py` file instead of using three additional files `create_db.py`, `drop_db.py`, and `populate_db.py`.

The developer should be able to create a database using `python manage.py create_database`, drop a database using `python manage.py drop_db`, and populate using `python manage.py populate_db`

**Do you want to work on this?**
Yes, I want to work on this and make the developer experience better.

**Comment by ashutoshc8101** [comment]
@iamareebjamal What do you think?

**Comment by iamareebjamal** [comment]
We want to shift to flask script, so manage.py is deprecated. If you shift existing commands to flask script and add these new commands, then go ahead

**Comment by ashutoshc8101** [comment]
@iamareebjamal what about this warning??
![Screenshot from 2021-02-02 14-04-04](https://user-images.githubusercontent.com/24855641/106573381-915cab00-655f-11eb-8e85-3f68a71cbfd1.png)

Should I use Flask's built-in command-line interface or ignore this warning?

**Comment by iamareebjamal** [comment]
Sorry, I meant use Flask CLI script, not flask script

**Comment by ashutoshc8101** [comment]
Ok, I am working on this. I will send a PR as soon as possible.
