### ISSUE TITLE
Invoice Email: Amount not showing two digits after dot

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#7743]
In the invoice emails the invoice amount shows only one digit after the dot, e.g. 180.6 USD instead of 180.60 USD.

![Screenshot from 2021-02-14 08-26-16](https://user-images.githubusercontent.com/1583873/107871260-318bcb80-6ea0-11eb-82da-16edd7bd6e4a.png)

**Comment by rudrani1964** [comment]
Hey @mariobehling can I work on this issue?

**Comment by avats-dev** [comment]
I would like to contribute if no one else is working on this. Any tips would be great to start with.

**Comment by lordnodd** [comment]
Since it was defined as Float in database so I believe the bug is the value getting type-casted in calculation of invoice_amount. I would like to debug this if it is not assigned to somone yet.

**Comment by Paras0-7** [comment]
Can I work on this issue?

**Comment by prateekj117** [comment]
@iamareebjamal @mariobehling I noticed this is only happening when the second digit after the decimal is zero. In case the amount is say something like `180.66`, it does not happen.

**Comment by iamareebjamal** [comment]
Yes
