### ISSUE TITLE
favourite_sessions Docs not included in api_blueprint_source

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-server#7781]
**Describe the bug**

`favourite_sessions.apib` (contains docs regarding `/v1/user-favourite-sessions` endpoint) file is not included in `api_blueprint_source.apib` file because of which the docs are not displayed. There might be some tests failing as well in case the file is included. Also, look into that.

**To Reproduce**
1. Go to 'locahost:5000'
2. Search for favourite-sessions docs.
3. Not found. Though the docs file exists in the codebase.

**Expected behavior**

Favourite-sessions docs should be present in API docs.

**Additional context**

Working on this.

**Comment by cybergeekgyan** [comment]
I would like to work on this issue and improve further @prateekj117 
help needed to understand the issue and to be able to fix the issue
