### ISSUE TITLE
Api Schema: Extra spaces in constants 

### ISSUE THREAD

**Issue by SwapnilSoni1999** [fossasia/open-event-server#7786]
Found some extra spaces in [message_settings.py](https://github.com/fossasia/open-event-server/blob/development/app/api/schema/message_settings.py) this might cause some formatting issues in future mails.

**Comment by AbhiSahane0** [comment]
Can I complete the last task plzz 
.

**Comment by SwapnilSoni1999** [comment]
> Can I complete the last task plzz
> .

Okay sure

**Comment by iaryangoyal** [comment]
can I fix this?

**Comment by SwapnilSoni1999** [comment]
@iaryangoyal  I've already sent a PR

**Comment by iaryangoyal** [comment]
ok @SwapnilSoni1999 my bad
