### ISSUE TITLE
Calendar link in calendar not working properly

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-server#7842]
In the description, "Join using link:  https://eventyay.com/e/fa96ae2c/video/Main Hall/187"

The space is treated as a break, clipping the link at Main"

"Main Hall" should be HTTP encoded to Main%20Hall

**Comment by kaiwalyakoparkar** [comment]
I would like to work on this issue. Could you please help me out?

**Comment by rajpratyush** [comment]
hi @mishari Can I take up this issue

**Comment by ashutosh264** [comment]
I think we can't address this issue just by adding (%20), as in this scenario we are the one deciding particular string is link or not.
For example: In the description, "Join using the link: https://eventyay.com/e/fa96ae2c/video/Main Hall/187 at 8:00 pm"
our code will end up adding (%20) in place of each space.
What we can do is just remove auto conversion to link, as there is option to covert string in link in editor.
Views @mishari sir @iamareebjamal sir?

**Comment by iamareebjamal** [comment]
Space should be replaced by %20, or `Main Hall` should be converted to `main-hall`
