### ISSUE TITLE
Role Invite: Allow users to resend invitations of event transfer from the settings page itself.

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-server#7953]
**Is your feature request related to a problem? Please describe.**

Currently whenever we try to resend role invite from event transfer from setting page we get error message that role invite is already sent.

**Describe the solution you'd like**

If there is no role invite, create role invite. If role invite already exist, resend email to user.

**Comment by PrasanthChettri** [comment]
Can I be assigned to this issue ?
