### ISSUE TITLE
Clean out-of-tree code

### ISSUE THREAD

**Issue by hongquan** [fossasia/open-event-server#8034]
Some places use undefined code, like here:

https://github.com/fossasia/open-event-server/blob/b3f8a4669c43237f0c5f914a4b52d21da0ae783f/manage.py#L101-L106

The import path "app.helpers.sessions_speakers.speakers" no longer exists.

**Comment by NamamiShanker** [comment]
I would like to work on this issue

**Comment by NamamiShanker** [comment]
Hey @hongquan, would you like me to search and drop these functions/classes? They are not being used anywhere either.

**Comment by NamamiShanker** [comment]
@hongquan I used `pylint` to find `Unable to import` messages. I couldn't find any other out-of-tree code portions. I have removed this function and corrected some import syntaxes.

**Comment by NamamiShanker** [comment]
@hongquan Please review PR #8041
