### ISSUE TITLE
Ticket Emails: Calendar the attached ics does maintain formatting

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8098]
The calendar ics that is sent out with the ticket email does not maintain its formatting. It converts html to text and displays the html. Please fix this. Screenshots are below.

![file-4](https://user-images.githubusercontent.com/1583873/125454034-f8e82414-4d5d-43e5-8128-c14bb228cbe6.png)
![file-6](https://user-images.githubusercontent.com/1583873/125454047-fe418863-2b81-404b-b990-982eb45655a8.png)
b
![file-3](https://user-images.githubusercontent.com/1583873/125454052-8f04b695-67f2-4900-9680-936f9f7fb5bf.png)

**Comment by maze-runnar** [comment]
No follow up on it, so closing it.
