### ISSUE TITLE
Discount Codes selecting "All tickets" in API call does not select all tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8214]
An API call of a partner creates discount codes in our system. This API call selects "apply to all tickets". However when checking in the UI we can see that "All tickets" is selected, but the actual ticket is not selected.

![unnamed (2)](https://user-images.githubusercontent.com/1583873/133616454-a7ed70e6-c627-4777-9764-a9b1d0127d05.png)

Expected would be:
![unnamed (3)](https://user-images.githubusercontent.com/1583873/133616467-43aeff38-1bf4-479b-a4bc-fb88e2bc639e.png)

**Comment by pc-beast** [comment]
Maybe the payload of the endpoint got updated or they are sending the wrong payload.
