### ISSUE TITLE
Order Summary Pages Missing Total, Tax, Grand Total

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8227]
The final payment page of orders is missing important information in the order summary. Please add the missing information.
* It does not show tax name, e.g. Mehrwertsteuer
* It does not show overall calculation Total, Tax, Grand Total

![Screenshot from 2021-09-23 17-13-36](https://user-images.githubusercontent.com/1583873/134534887-355d5607-8a16-420d-8453-beef94f88124.png)

**Expected is**

![Screenshot from 2021-09-23 17-20-12](https://user-images.githubusercontent.com/1583873/134535949-59e77b60-295b-4f81-b678-e31c0274fb45.png)

**Comment by progmatic-99** [comment]
working on it

**Comment by progmatic-99** [comment]
tax and grand total is visible for me
![ss_1632553829](https://user-images.githubusercontent.com/42090582/134762481-c7d078c9-c32f-44fc-bc97-65af27d76025.png)

**Comment by maze-runnar** [comment]
yeah, the changes have been done by @daretobedifferent18 so this issue is resolved I think.

**Comment by progmatic-99** [comment]
@maze-runnar, @mariobehling was talking about a different step, let's wait for him to confirm

**Comment by mariobehling** [comment]
Ok, great. Thanks.
