### ISSUE TITLE
Ticket Email: Timezone of Event Time/Date and Purchase Time/Date should be following event Timezone

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8248]
The organizer and attendee ticket email show the time and date in UTC instead of the event timezone.

Expected: Always show the emails in the event date and time following the event timezone.

- Currently the Purchase Date and Time are also wrong. They do not actually show the correct UTC time.
- The Purchase Date and Time are should follow the 24 hour format same as the event date/time.

![Screenshot from 2021-09-28 14-51-00](https://user-images.githubusercontent.com/1583873/135091906-c4c75909-5afa-45be-ab80-23dcf71dc429.png)

**Comment by pc-beast** [comment]
![image](https://user-images.githubusercontent.com/56963647/135107960-2d84a818-b7cb-422f-b2c6-6c3aaffbfcac.png)
Fix it here too

**Comment by maze-runnar** [comment]
@progmatic-99 use `astimezone()` in mail.py for event_time. `event_time=event.starts_at.astimezone().strftime("%H:%M (%Z)")` 
and see if this works. Or if you have better way please implement that.

**Comment by progmatic-99** [comment]
@maze-runnar This won't work.
