### ISSUE TITLE
The event ticket email misses the timezone information. It should be displayed behind the date and time, e.g. (CEST).

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8260]
Please add the timezone to event tickets. Currently the event ticket email misses the timezone information. It should be displayed behind the date and time, e.g. (CEST).

![Screenshot from 2021-10-04 19-38-04](https://user-images.githubusercontent.com/1583873/135898376-bc6f9dea-1266-486a-ad67-9ca82680ff05.png)

**Comment by progmatic-99** [comment]
This will be solved in this [PR](https://github.com/fossasia/open-event-server/pull/8253)
