### ISSUE TITLE
Make invoices and emails fully translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8293]
Emails and invoices are not fully translated. This results in email with mixed languages. Some strings are not labeled ready for translations. Therefore Weblate will not recognize them as translatable. For example in Weblate German shows up as 100% translated even though text is not translated. If Weblate shows up 100% translated, but areas are not really translated something is wrong. Compare https://hosted.weblate.org/projects/open-event/server/de/

For example check the ticket order email. Only the first sentence is translatable.

**Comment by progmatic-99** [comment]
Reopening for some changes

**Comment by mariobehling** [comment]
Payment status and payment method are not yet translatable, e.g. in Emails.

![Screenshot from 2021-11-04 13-20-23](https://user-images.githubusercontent.com/1583873/140312780-75bcb92c-8b40-48e7-9c9c-b6d5edf209f9.png)

**Comment by mariobehling** [comment]
Still need to make email subjects translatable.

**Comment by progmatic-99** [comment]
I will solve that in #8333

**Comment by mariobehling** [comment]
Thank you for the recent changes.

I still find the following not translated in emails:

"Online (Please login to the platform to access the video room on the event page)"

![Screenshot from 2021-11-06 18-46-01](https://user-images.githubusercontent.com/1583873/140618968-d44cee59-3e79-4c0c-9c3f-a0d2fcbaa4a9.png)
