### ISSUE TITLE
Make subjects of all mails translatable

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-server#8333]
Currently session state mails and subjects of all mails are not translatable. Please make it possible to translate them.

For example, where are the strings for this email? Where can this be translated?

```
        },
        'canceled': {
            'subject': 'Canceled! Your submission for {event_name} titled {session_name} has been Canceled',
            'message': "Hello,<br/><br/>"
            "This is an automatic message from {app_name}.<br/><br/>"
            "Your session status for the submission {session_name} for {event_name} was changed to \"Canceled\".<br/><br/>"
            "The status change was done by event organizers. If there are questions about this change please contact the organizers.<br/><br/>"
            "You can also check the status and details of your submission on the session page {session_cfs_link}. You need to be logged in to view it.<br/><br/>"
            "More details about the event are on the event page at {event_link}.<br/><br/>"
            "Thank you.<br/>"
            "{frontend_link}",
        },
```

_Originally posted by @mariobehling in https://github.com/fossasia/open-event-server/issues/8321#issuecomment-954752178_

**Comment by mariobehling** [comment]
After the last PR in the mails "New order for" there is a quote sign in front of eventyay (appName).

![Screenshot from 2021-11-10 15-35-12](https://user-images.githubusercontent.com/1583873/141132851-3af91908-c4e6-4235-95e2-fbebf78477b8.png)

**Comment by progmatic-99** [comment]
will correct this in this PR

**Comment by mariobehling** [comment]
The subject of mails is translatable in the translation system, but it does not show up in the subject of recipients if an email is in German for example. Therefore reopening this.

![Screenshot from 2021-11-20 07-02-12](https://user-images.githubusercontent.com/1583873/142716343-1b03a722-2a28-4197-87ca-f11e29835d31.png)

**Comment by anjali1102** [comment]
Kindly asign me this issue

**Comment by progmatic-99** [comment]
@anjali1102 We don't assign issues to external contributors. Please start working on the issue and make a draft PR. We'll help you along the way.

**Comment by mariobehling** [comment]
Subjects still are not translatable after the last PR got merged. There are no additional translation options in Weblate. Mails of orders in other languages have the content in another language than English, but the subject is still not translated.

**Comment by progmatic-99** [comment]
https://stackoverflow.com/questions/17380165/python-gettext-different-languages-at-same-time
