### ISSUE TITLE
Change language of date and time based on user choice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8337]
The language for date and time is not changed in messages even if the message is not in English.

**Comment by sourav-mishra-889** [comment]
please assign me this issue,I'll fix it within an hour or so.

**Comment by sourav-mishra-889** [comment]
I am working on the issue, after checking that no one else is.

**Comment by codedsun** [comment]
@sourav-mishra-889 - No need to assign the issue, you can start working

**Comment by maze-runnar** [comment]
@mariobehling we have to make this change in invoice and mails, right?
