### ISSUE TITLE
HTML Code in email messages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8345]
After the recent changes of creating translations of messages HTML code shows up in those messages.

![Screenshot from 2021-11-02 15-24-46](https://user-images.githubusercontent.com/1583873/139866372-de3d0cc6-693b-4615-b694-da23a207c2c9.png)

**Comment by codedsun** [comment]
@progmatic-99 - I am afraid that the technique didnt work, what are your thoughts about it? What could be failing?

**Comment by mariobehling** [comment]
Somewhere the format of this email is not recognized as HTML anymore.

**Comment by progmatic-99** [comment]
looking into it
