### ISSUE TITLE
Pre-commit not working as expected

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#8346]
**Describe the bug**
Pre-commit hook is failing while committing code

Stack trace:

```
[INFO] Initializing environment for https://github.com/hadialqattan/pycln.
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/git/2.33.0/libexec/git-core/git', 'checkout', '0.0.1')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec '0.0.1' did not match any file(s) known to git
    
Check the log at /Users/codedsun/.cache/pre-commit/pre-commit.log
```

**Comment by progmatic-99** [comment]
clear the pre-commit cache and reinstall it.

**Comment by codedsun** [comment]
@progmatic-99 - This isnt' working from day 1, i dont think this is caching issue.

**Comment by progmatic-99** [comment]
I encountered this issue and did a Google search. The article solved this issue, but I couldn't find the article now. This is not an issue with the repo. I will try to find the link.

**Comment by codedsun** [comment]
@progmatic-99 - Should this issue occur for every user and for every fresh setup?, if not then I am facing this after every fresh setup
