### ISSUE TITLE
Integrate Klarna, Sepa in Stripe

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-server#8366]
Integrate Klarna, Sepa payment methods in Stripe

**Comment by mariobehling** [comment]
![Screenshot from 2021-11-15 20-31-39](https://user-images.githubusercontent.com/1583873/141843095-98ff3650-ee15-4435-9295-c4d9114880fd.png)

Actually Klarna (Sofort) and Sepa are active both live and test mode. They just need to be implemented to show up in the "live" section.

Stripe states:
> Once you start to receive payments with a payment method, it will move from the “eligible” section to the “live” section on your payment settings dashboard.
