### ISSUE TITLE
Celery task failing due to `column events.live_stream_url does not exist`

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-server#8464]
![ss_1640341329](https://user-images.githubusercontent.com/42090582/147344610-15dc8409-319f-4b6a-bb93-c8c8f4670560.png)

**Comment by progmatic-99** [comment]
@pc-beast When I check the `celery worker` logs, this is what I get

![ss_1640353916](https://user-images.githubusercontent.com/42090582/147357224-d83c923d-b635-49dc-b41b-ac7ca26a1b14.png)

**Comment by pc-beast** [comment]
Is it on test server?

**Comment by progmatic-99** [comment]
Yes

**Comment by hongquan** [comment]
This error occurs when the models (ORM) code is different from actual database structure, normally due to missing DB migration.

Please check the container which runs this Celery worker, it may contains old code.

**Comment by progmatic-99** [comment]
As I pointed out in the meeting, too, the celery container doesn't have the latest code.
There is an issue in how we deploy the containers.

**Comment by progmatic-99** [comment]
**Update the celery container by running this inside the celery container: `docker-compose up -d --no-deps --build celery`**
