### ISSUE TITLE
Sales admin page of eventyay not accessible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8533]
The sales admin page of eventyay gives an error message and is not accessible.

Compare https://eventyay.com/admin/sales/live

![Screenshot from 2021-11-03 14-30-37](https://user-images.githubusercontent.com/1583873/140069204-02b1b973-3e51-4df1-8bfe-ac8825209f7e.png)

https://test.eventyay.com/admin/sales/live

**Comment by arunchauhan02** [comment]
please assign these issue to me

**Comment by arunchauhan02** [comment]
I am working on this issue
