### ISSUE TITLE
I can't access the api from my website

### ISSUE THREAD

**Issue by fen31** [fossasia/open-event-server#8587]
I can't access the API from my local web page, nor from my localhost server with axiosjs. In the first case it gives me a cross domain error. In the second case, there is simply no answer. I

1. I create asynchronous request using ajax
2. For example, I use the get POST and the url "https://localhost:8080/v1/auth/login"
3. ContentType: application/json
4. data: {"email"."email@example.com","password":"password"}

I wait for a response from the server,

 - OS: from Docker image
 - Python Version 3.9.2
 - `HEAD` Commit hash 

I can access from postman or curl.

**Comment by fen31** [comment]
Sorry, I meant : "I use the POST method.." on line 7

**Comment by progmatic-99** [comment]
Use the Accept header in your payload.
