### ISSUE TITLE
Transfer Ownership Email does not get send out

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8600]
If a user wants to transfer ownership, the "Transfer Ownership" email does not get send. From the senders point of view everything seems to work fine, but the expected email does not arrive in the recipients inbox.

![Screenshot from 2022-03-20 23-09-01](https://user-images.githubusercontent.com/1583873/159188103-3369b284-1688-474a-83fc-0071f6931d1d.png)

**Comment by pc-beast** [comment]
![image](https://user-images.githubusercontent.com/56963647/159310692-43638513-a7f6-4b9c-974f-f12cddbdc0d3.png)

Tested it on the production server. Works fine for me.
