### ISSUE TITLE
Docker Deployment Fail

### ISSUE THREAD

**Issue by Dnouv** [fossasia/open-event-server#8739]
**Describe the bug**

I am trying to Deploy the server on Docker, but after following through with the README, I get the following error as listed in Stacktrace.

**To Reproduce**
1. Run `docker-compose build`
2. Run `docker-compose up -d`

**Expected behavior**
Go to localhost:8080 on the web browser and Open Event Orga Server will be live.

**Stacktrace**
```
opev-celery | [LOG] Deploying celery
opev-celery | [LOG] Using database: postgresql://open_event_user:opev_pass@postgres:5432/open_event
opev-celery | [LOG] Using redis: redis://redis:6379/0
opev-celery | [LOG] Starting celery worker
opev-celery | /opt/pysetup/.venv/lib/python3.8/site-packages/envparse.py:195: UserWarning: Could not any envfile.
opev-celery |   warnings.warn('Could not any envfile.')
opev-celery | Usage: celery [OPTIONS] COMMAND [ARGS]...
...
...
opev-celery | ImportError: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/pysetup/.venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
opev-celery |
```

**Additional details (please complete the following information):**
 - OS: Ubuntu @ WSL2
 - Python Version `3.8.10`
 - `HEAD` deployment branch

**Additional context**

**Comment by 7yl4r** [comment]
I am also having this issue. Things I have tried:

* added to `Dockerfile`: 
    * `libc6-compat`
    * `gcompat`
    * `py-cryptography`
* added to `pyproject.toml`: 
    * `interface = "2.11.1"`
    * `pyopenssl = "22.0.0"` 
    * `cryptography = "*"`
* added to `deb-packages.txt`:
    * `libc6-compat`
    * `gcompat`
    * `py-cryptography`

references
* https://github.com/grpc/grpc/issues/6126
* https://stackoverflow.com/questions/32518458/importerror-no-module-named-cryptography-hazmat-bindings-openssl

None of the above affected the issue at all.
