### ISSUE TITLE
Local development on Mac M1

### ISSUE THREAD

**Issue by ancs21** [fossasia/open-event-server#8840]
We have some issues running this project on a Macbook M1 chip.

**Comment by ancs21** [comment]
hi @marcoag,
I try to run the project on my MacBook (M1 Pro), but because the project's old, I get a lot of issues with the library and dependency version, so I raise it and write guidelines to help other people using Mac M1 can run projects on local.

**Comment by cweitat** [comment]
@ancs21 There was an update to the README with regards setting up on M1. Could you try that?
