### ISSUE TITLE
Error cloning repo

### ISSUE THREAD

**Issue by JS-E** [fossasia/open-event-server#8846]
**Describe the bug**
I cannot git clone this repo using the steps in the readme for docker

**To Reproduce**
1. I run 'git clone https://github.com/fossasia/open-event-server.git'
2. The clone succeded but the checkout failed with the following error (see stacktrace)

**Expected behavior**
I expect all the data to be within the cloned folder

**Stacktrace**
Cloning into 'open-event-server'...
remote: Enumerating objects: 75359, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 75359 (delta 123), reused 133 (delta 73), pack-reused 75156
Receiving objects: 100% (75359/75359), 54.68 MiB | 8.68 MiB/s, done.
Resolving deltas: 100% (53231/53231), done.
error: invalid path 'migrations/versions/rev-2019-08-03-05:18:10-4925dd5fd720_add_user_token_blacklist_time_table.py'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'Cloning into 'open-event-server'...

**Additional details (please complete the following information):**
- OS Win11

**Comment by cweitat** [comment]
@JS-E this is because path name/URL is too long or because of the `:` in the file name
