### ISSUE TITLE
Schedule displays sessions twice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8850]
The schedules of larger event at times display sessions twice, compare https://eventyay.com/e/8f889410/schedule

![photo1681489034](https://user-images.githubusercontent.com/1583873/235285193-6672dba4-9b18-482f-ba5d-ef1f1d8c8d94.jpeg)

**Comment by cweitat** [comment]
@thongphp have transferred the issue here to work on

**Comment by mariobehling** [comment]
Currently this issue does not seem to appear anymore. Therefore closing it.
