### ISSUE TITLE
CORS request is failing

### ISSUE THREAD

**Issue by AvatarBoss** [fossasia/open-event-server#8905]
Seeing the below message on open-event-frontend.  Seems like the CORS request headers aren't coming through.  Errors come up on initial page load.  Accessing the server at localhost:8080 doesn't produce any issues.  A follow-on promise is also unfulfilled due to the failed CORS request. 

--Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/v1/settings?cache=true&public=true. (Reason: CORS request did not succeed). Status code: (null).

--Error while processing route: index The adapter operation was aborted n@http://10.57.62.14:4200/assets/vendor-f27cb0c95970101c6329bc1e94d786a3.js:10683:19...                        router.js:1250

I built both the server and FE via Docker.  Also, it .env file isn't being located by opev-web.  I can open up a separate issue if desired:
--(/opt/pysetup/.venv/lib/python3.8/site-packages/envparse.py:195: UserWarning: Could not any envfile.

  warnings.warn('Could not any envfile.'))

I built both the server and FE from Docker.

**Comment by mariobehling** [comment]
Hi @AvatarBoss Please join us on the chat channel to follow up https://app.gitter.im/#/room/#fossasia_open-event-server:gitter.im

**Comment by cweitat** [comment]
@AvatarBoss usually that is because one of the request failed. Somewhere error 500 or how. The error handling can be further improved
