### ISSUE TITLE
Return a PDF for badge printing from server

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8955]
API to call for the checkin app to print the badge
The badge should be in PDF with details specified in the wizard that contains QR code in VCF format with custom field `EVENTYAY` that contains the ticket_id

Need APIs for follow:
- needs to accept list of information that the attendee wants to show before generating PDF and sending via API

**Comment by cweitat** [comment]
@lthanhhieu upon printing, mark ticket as printed and printed date time

**Comment by lthanhhieu** [comment]
API for #8955
## Return a PDF for badge printing from server [/v1/badge-forms/print-badge-pdf]
### Return a PDF for badge printing from server [POST]
Return a PDF for badge printing from server using JWT token

+ Request

    + Headers

            Accept: application/json

            Authorization: JWT <Auth Key>

    + Body

            {
              "attendee_id": 1,
              "list_field_show" : ["email", "fluent_language"]
            }

+ Response 200 (application/pdf)
    + Return File PDF

**Comment by lthanhhieu** [comment]
Close as PR merged: https://github.com/fossasia/open-event-server/pull/8968
