### ISSUE TITLE
Store and Retrieve check in and out data on server

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8957]
Currently check-in on the front end is done by updating the attendee profile with the date. We need proper data storage.

APIs required for check-in:
FE: On scan, ticket id and station id will be sent and check in type (registration/session) and the type like whether is it entering or leaving (in/out)
BE: To store the ticket id, datetime (with timezone), station_id, session details - if applicable (track name, session name and speaker name)

If user is already check-in for the **session**, API should returned that the user is already check in and don't create an entry unless:

1.  User has check out for the same session
2.  Same location but new session

If user is already check-in for the **day**, API should returned that the user is already check in and don't create an entry unless:

1.  User has check out for the same **day**

https://github.com/fossasia/open-event-server/issues/8958 needs to be completed first

**Comment by lthanhhieu** [comment]
FE: in the check in app. Not implement in eventyay app.

**Comment by lthanhhieu** [comment]
Hi @cweitat @mariobehling  @DonChiaQE 
Could you please share me the sample request (CURD) for this API.

**Comment by cweitat** [comment]
@lthanhhieu 
This requires new DB table

For POST:
send in EVENTYAY ID from the VCF on badge
station_id

Expected response: true/false

BE uses station_id to get the station_type and do the checks:
If station_type is check-in:
Check If user is already check-in for the session, API should returned that the user is already check in and only create an entry when:

- User has a check out entry for the same session
- Same location but new session

BE should be able to:
Store data with the datetime. and  session details. refer to the above description

**Comment by nnhathung** [comment]
Hi @cweitat , could you help me clarify some question?
so this is info check in app request to us for checking in
{
	"ticket_holder_id": {},
	"station_id": {},
	"session_id": {}, // if station_type is session, session_id must be populated
	"is_check_in": true or false
}
1. is the eventyay id (or ticket id) you mentioned is ticket_holder_id?

2. session_id must be populated if user check in session, so there're 2 ways for BE to know which session user checking in:
 - we have another column in station table (#8958) is session_id if station_type is session.
 - check in app should pass the session_id in the request if station_type is session.

please help me with these 2 points.

FYI: @lthanhhieu

**Comment by cweitat** [comment]
@nnhathung for registration is the ticket_id. for check session/daily, it will be badge id (VCF EVENTYAY id)

ok; passing the session_id wont be an issue.

**Comment by nnhathung** [comment]
yup, thanks @cweitat

**Comment by nnhathung** [comment]
Response for Check in/check out
case success:
{
success: true,
message: "Attendee already checked in"
{

case fail:
success: false,
message: "Attendee already checked in"
}

 badge id (VCF EVENTYAY id) = ticket_holder_id
