### ISSUE TITLE
Store check in kiosk id to mark association

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8958]
Allow organiser to create station name for each event

- station name
- location (based on the locations available for the venue) - if registration is selected, location can be empty
- type (registration / daily / check in / check out )

**Comment by lthanhhieu** [comment]
Hi @cweitat @mariobehling  @DonChiaQE 
Could you please share me the sample request (CURD) for this API.

**Comment by cweitat** [comment]
This is for creating POST in database only
Can refer to the video

**Comment by cweitat** [comment]
Can refer to the video
We need the list via eventId

**Comment by cweitat** [comment]
@lthanhhieu 
There should be two APIs for this one

First is storing a new station POST
eventId, microlocation_id, station_name, station_type 

Second need GET
microlocation_id, room, station_name, station_type 
For microlocation_id and room pls refer here https://test-api.eventyay.com/#microlocations-microlocation-details

**Comment by nnhathung** [comment]
Hi @cweitat 

APIs spec for create and get station, could you help me to take a look and let me know if it okay

**POST: /v1/station**
_Request_

{
  "data": {
    "attributes": {
      "event-id": {event-id},
      "microlocation-id": {microlocation-id}, // can be empty if station-type is registration & daily
      "station-name": {station-name},
      "station-type": {},  // registration | daily | session
    }
  }
}

_Response_

{
  "data": {
    "attributes": {
      "id: {station-id},
      "event-id": {event-id},
      "microlocation-id": {microlocation-id},
      "station-name": {station-name},
      "station-type": {},  // registration | daily | session
    }
  }
}

**GET: /v1/station/{station-id}**

_Response_

{
  "data": {
    "attributes": {
      "microlocation_id": {microlocation_id}, // null if station-type is registration & daily
      "room": {room}, // null if station-type is registration & daily
      "station-name": {station-name},
      "station-type": {},  // registration | daily | session
    }
  }
}

**Comment by cweitat** [comment]
@lthanhhieu what if not successful? what does it returns for POST

Also another GET which is to get all stations of the event

**Comment by nnhathung** [comment]
> @lthanhhieu what if not successful? what does it returns for POST
> 
> Also another GET which is to get all stations of the event

Hi @cweitat 
I have updated APIs spec in previous comment since there're the relationship between station with event and microlocation, for event, it has one-to-many with station, but with microlocation, is it also one-to-many or 1:1 with station?
and another one is does we need paging for API get all stations of event?

@lthanhhieu, @mariobehling  : FYI

**Comment by cweitat** [comment]
@nnhathung don't need pagination

**Comment by nnhathung** [comment]
Hi @cweitat , thanks for confirming.
