### ISSUE TITLE
API to download check in data in a CSV

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8959]
Allow organiser to download check in data in a CSV from event dashboard

Possible filters include

- Date
- Track Type
- Session
- Type (registration, daily, check in, check out, check in & check out)

Data to return
- ticket id
- date time
- session details (track name, session name and speaker name)
- type

**Comment by avinashyadav0027** [comment]
hey I would like to work on this, can you assign me this task.

**Comment by avinashyadav0027** [comment]
I am working on it

**Comment by cweitat** [comment]
@avinashyadav0027 there's nothing to work on. The database is not even setup for this

**Comment by avinashyadav0027** [comment]
oh okay, : ) sorry i am a newbie.
