### ISSUE TITLE
Stats API for registration and stations

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8961]
Stats needed for registration:

- Total attendees
- Total Checked In
- Total checked Out
- Total have yet to check in

If event has multiple days, provide also the same stats for current day

Stats needed for stations (params to send in could be event_id and session_id) :

- Session Total attendees
- Session Total Checked In
- Session Total checked Out
- Session details (current track, current session, session speaker)

- Track Total attendees
- Track Total Checked In
- Track Total checked Out
- Track details (current track, current session, session speaker)

**Comment by nnhathung** [comment]
Hi @cweitat 
From the last meeting,

![image_2023_07_19T04_08_26_426Z](https://github.com/fossasia/open-event-server/assets/139526485/cccd1b59-7dd2-49ef-8d6a-ac69eed6b290)

From the BE, we will response:

1.  for overall:
 + total check in for all session on event
 + total check out for all session on event
 + total registered on event
 + total attendee not registered on event

2.  on each station:

 + total check in on session
 + total check out session

could you please confirm?
and another thing, if same attendee check in or out for multiple time, we count it just one or else?

FYI: @lthanhhieu @mariobehling

**Comment by cweitat** [comment]
@nnhathung 
pls note that for overall, it is for track, not all sessions. apologise for the mistake. For example check in for same location has multiple sessions so for that particular session.

**Comment by lthanhhieu** [comment]
> @nnhathung pls note that for overall, it is for track, not all sessions. apologise for the mistake. For example check in for same location has multiple sessions so for that particular session.

Hi @cweitat 
Can we init the meeting to clarify it?
