### ISSUE TITLE
Export CSV files of Attendees with random, duplicate and unsorted data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#8972]
There are several issues with the exported CSV file of attendees and orders. To replicate the issue download a CSV from the attendee or order overview.

![Screenshot from 2023-06-26 13-50-37](https://github.com/fossasia/open-event-frontend/assets/1583873/c791b410-32a8-47c2-9150-cb0c8006708c)

Then check the CSVs of attendees and orders. They have random and duplicate data.

1. Firstly in a perfect way the columns would be ordered according to the order of questions on the web front-end.
2. Secondly, the columns with the data on Email consent, photo consent and other columns appear several times
3. Thirdly specifically the following columns are in the wrong place:
* Column AF "Email" should be behind column "O (Zipcode)
* Column P "áa" seems to have some random information
* Column Q to AE should be coming after column BG
4. The answer in the forms shows "True" or "False". Normal users do not know what this means. Just show the answer in the default language, e.g. "Yes".

[attendees-dc360898141111eea9e90242c0a87005.csv](https://github.com/fossasia/open-event-frontend/files/11868359/attendees-dc360898141111eea9e90242c0a87005.csv)

**Comment by mariobehling** [comment]
The issue is unfortunately not solved for existing events.
1. Questions are not sorted according to the order laid out in the form.
2. Questions appear twice. The reason why this is happening is probably because there are two ticket types with two different forms. If forms of different ticket types have the same question, there should only be one column in the CSV.

**Comment by lthanhhieu** [comment]
Reopen due to revert code for fix #9031
