### ISSUE TITLE
API to return list of badge fields to print

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8982]
API should return the list of badge fields that organiser chose to display on the badge according to the ticket type that the attendee belongs to.

related: https://github.com/fossasia/open-event-server/issues/8955

**Comment by lthanhhieu** [comment]
Hi @mariobehling, @cweitat 
The API return list of fields in badge will have the format as following:
Please help me confirm that or we need to change .
API: `v1/attendees/<attendee-id>/badge-forms`
Response: 

> {
>     "data": [
>         {
>             "type": "badge-form",
>             "attributes": {
>                 "badge-size": "3 x 4 inch (76.2 x 101.6mm )",
>                 "badge-id": "82efc797-a29f-414e-a6e6-b8dcfba00b1b",
>                 "badge-color": null,
>                 "badge-image-url": null,
>                 "badge-orientation": "Landscape",
>                 "badge-fields": [
>                     {
>                         "id": 1,
>                         "field_identifier": "email",
>                         "custom_field": "Email",
>                         "sample_text": "lthanhieu@tma.com.vn",
>                         "badge_id": "82efc797-a29f-414e-a6e6-b8dcfba00b1b",
>                         "font_size": null,
>                         "font_name": "Courier New",
>                         "font_weight": null,
>                         "font_color": "#891414",
>                         "text_rotation": null,
>                         "text_alignment": "center",
>                         "text_type": "Lowercase",
>                         "is_deleted": false,
>                         "margin_top": null,
>                         "margin_bottom": null,
>                         "margin_left": null,
>                         "margin_right": null,
>                         "qr_custom_field": null
>                     },
>                     {
>                         "id": 2,
>                         "field_identifier": null,
>                         "custom_field": "QR",
>                         "sample_text": null,
>                         "badge_id": "82efc797-a29f-414e-a6e6-b8dcfba00b1b",
>                         "font_size": null,
>                         "font_name": null,
>                         "font_weight": null,
>                         "font_color": null,
>                         "text_rotation": null,
>                         "text_alignment": "center",
>                         "text_type": null,
>                         "is_deleted": false,
>                         "margin_top": null,
>                         "margin_bottom": null,
>                         "margin_left": null,
>                         "margin_right": null,
>                         "qr_custom_field": [
>                             "Email",
>                             "Age Group",
>                             "Address",
>                             "First Name",
>                             "Last Name",
>                             "Phone",
>                             "custom field short anwser"
>                         ]
>                     }
>                 ]
>             },
>             "relationships": {
>                 "event": {
>                     "links": {
>                         "self": "/v1/badge-forms/1/relationships/event",
>                         "related": "/v1/badge-forms/1/event"
>                     }
>                 }
>             },
>             "id": 1,
>             "links": {
>                 "self": "/v1/badge-forms/1"
>             }
>         }
>     ],
>     "links": {
>         "self": "/v1/attendees/1/badge-forms"
>     },
>     "meta": {
>         "count": 1
>     },
>     "jsonapi": {
>         "version": "1.0"
>     }
> }

**Comment by cweitat** [comment]
@lthanhhieu can only send in the ticket ID and event ID

**Comment by cweitat** [comment]
Flow is attendee scan ticket > server response with badge fields of attendee ticket type > attendee choose fields to print on badge > response sent to server (another API URL) > server generate pdf for printing

**Comment by lthanhhieu** [comment]
> @lthanhhieu can only send in the ticket ID and event ID

Hi @cweitat 
So the API will be:
GET: `v1/tickets/int:<tickets-id>/badge-forms`

How about the response?

**Comment by cweitat** [comment]
[{"id": 1,
"field_identifier": "email",
"custom_field": "Email",}]

@lthanhhieu

**Comment by lthanhhieu** [comment]
API for #8982
## Get list of badge fields to print [/v1/tickets/<int:ticket_id>/badge-forms]
### Get list of badge fields to print [GET]
Get the list of badge fields to print using JWT token

+ Request

    + Headers

            Accept: application/json

            Authorization: JWT <Auth Key>

+ Response 200 (application/json)

        [
            {
                "custom_field": "Email",
                "field_identifier": "email",
                "id": 8200
            },
            {
                "custom_field": "Are you fluent in any other of the following languages?",
                "field_identifier": "fluent_language",
                "id": 8202
            },
            {
                "custom_field": "Age Group",
                "field_identifier": "ageGroup",
                "id": 8201
            }
        ]

**Comment by cweitat** [comment]
@lthanhhieu are the ids all consistent ? Because for example, it's not good to show the question for fluent language but just show Fluent Language in the list of fields to seelct. 

If IDs are consistent we will use that to parse the field names into the list. Else pls return a readable field names rather than questions

**Comment by cweitat** [comment]
@lthanhhieu i think it's fine then, we will just use custom fields.

also, i realised the field_identifier quoted in the example uses snake case but camelCase is used for fluent language. just want to be consistent.

**Comment by lthanhhieu** [comment]
> @lthanhhieu i think it's fine then, we will just use custom fields.
> 
> also, i realised the field_identifier quoted in the example uses snake case but camelCase is used for fluent language. just want to be consistent.

Hi @cweitat 
I am not sure if I can get your point correctly. As checked, and fluent language is now using snake case, I could not find where is camelCase for fluent language.

**Comment by cweitat** [comment]
@lthanhhieu just quoting if not is fine :)
![image](https://github.com/fossasia/open-event-server/assets/11439477/9575faec-54bc-4bd2-af5b-0facc759afe9)

**Comment by lthanhhieu** [comment]
> @lthanhhieu just quoting if not is fine :) ![image](https://user-images.githubusercontent.com/11439477/254868771-9575faec-54bc-4bd2-af5b-0facc759afe9.png)

Hi @cweitat 
Some fields that have been created for a long period. As far as I know, you have a ticket for shifting the creation custom fields to the server, then changing camelCase to snakeCase afterwards. This is why ageGroup is still shown as camelCase ;).
I realize that should be in the same format, but the other ticket will handle it, won't it?

**Comment by lthanhhieu** [comment]
Close as PR merged: https://github.com/fossasia/open-event-server/pull/8968
