### ISSUE TITLE
Add new APIs to documentation

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#8998]
To add new APIs that were created here first to save time as a draft copy before adding via blueprint

* [ ] Add user check in API
* [ ] Add badge printing documentation

**Comment by cweitat** [comment]
User check in API not added

**Comment by cweitat** [comment]
Missing badge printing documentation

**Comment by nnhathung** [comment]
[Badge.postman_collection.zip](https://github.com/fossasia/open-event-server/files/12297680/Badge.postman_collection.zip)
collection for badge printing.

Working on add it on blueprint

**Comment by cweitat** [comment]
@nnhathung what happened to this? i still dont see print PDF api in documentation

**Comment by lthanhhieu** [comment]
> @nnhathung what happened to this? i still dont see print PDF api in documentation

Hi @cweitat, I thought we've already discussed about this issue right? PDF print API cannot add to the APIs doc and we just provided to you the postman collection for this case.

**Comment by cweitat** [comment]
@lthanhhieu PDF Print API returns a download link instead of file from previous so it should be documented.

**Comment by cweitat** [comment]
currently it's only get fields but did not mention about posting fields to get a PDF link in response

**Comment by lthanhhieu** [comment]
> currently it's only get fields but did not mention about posting fields to get a PDF link in response

oh got it @cweitat let I ask him to do the change.

**Comment by khangon** [comment]
Hi @cweitat 
As checked I found that we have 2 APIs for print badge.
1. Get all fields that setup in badge:
> https://test-api.eventyay.com/#badge-forms-get-badge-form-by-ticket

2. Send the badge fields that user wants to print and return the link download;
> https://test-api.eventyay.com/#event-export-start-badge-export-as-pdf

Please let me know if you need the other thing.

**Comment by cweitat** [comment]
@khangon can I confirm that the download API will always return with QR even when fields are empty?

If yes, what other are the other fields that always return without stating.

**Comment by lthanhhieu** [comment]
> @khangon can I confirm that the download API will always return with QR even when fields are empty?
> 
> If yes, what other are the other fields that always return without stating.

Hi @cweitat 
1. If the badge form has a QR code, the QR code will always appear in the print badge regardless of whether the user selects the QR code. Actually, the QR code always contains the Eventyay ID.

2. The other field if has no data and still shows in the print badge, I will test it again, if it is the bug I will raise the ticket for this.

**Comment by cweitat** [comment]
@lthanhhieu okay cool. wwaiting for the update to documenttion

**Comment by lthanhhieu** [comment]
> @lthanhhieu okay cool. wwaiting for the update to documenttion

Hi @cweitat 
I think @khangon already updated
https://test-api.eventyay.com/#badge-forms-get-badge-form-by-ticket
https://test-api.eventyay.com/#event-export-start-badge-export-as-pdf
