### ISSUE TITLE
Non-latin characters of names not rendered in ticket and order PDF

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#9000]
Non-latin characters like Chinese are not rendered in ticket and order PDFs. Probably the font does not support it.

![Screenshot from 2023-07-21 10-39-42](https://github.com/fossasia/open-event-server/assets/1583873/cc11f7d9-4960-492f-8cf5-16d1f23c6682)

**Comment by norbusan** [comment]
I reopened the issue since:
- the original PR did not build docker images, thus no fix
- my PR I just merged uses different fonts (https://github.com/fossasia/open-event-server/pull/9061)
and thus we need to recheck this issue

**Comment by norbusan** [comment]
Confirmed that it works on test server. Closing this
![image](https://github.com/fossasia/open-event-server/assets/1735589/7aa8ea0a-10c4-450b-a1ac-419b95054265)
