### ISSUE TITLE
Unable to get all stations from API

### ISSUE THREAD

**Issue by shaunBoahCodes** [fossasia/open-event-server#9016]
**To Reproduce**
1) Call API from 'v1/events/{eventId}/stations)'
2) 'Internal Server Error' returned

<img width="1366" alt="Screenshot 2023-07-27 at 10 43 58 PM" src="https://github.com/fossasia/open-event-server/assets/131640457/52f26f89-9248-46ea-af4a-9bf1da922f9f">

**Expected behavior**
Receive JSON data of all stations for a particular event

**Additional details:**
 - OS: MacOS

**Comment by cweitat** [comment]
https://github.com/fossasia/open-event-server/pull/8991

**Comment by lthanhhieu** [comment]
Hi @shaunBoahCodes 
I think that test environment has not migrated yet.
![image](https://github.com/fossasia/open-event-server/assets/135117837/af51283e-f329-4d96-8ba3-37fbb2076f28)

**Comment by cweitat** [comment]
@lthanhhieu we are doing on test

**Comment by lthanhhieu** [comment]
Hi @cweitat , 
Can you check the database that has the table station or not? As I checked in test server, I could not find it, I am not sure if you have another server test or not.

**Comment by cweitat** [comment]
@norbusan there's new database tables created. not sure if that was done
