### ISSUE TITLE
Cannot store all data for video translations channels

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#9019]
On the bottom of video pages there is an option to add translation channels. The idea is that organizers can have a video channel (Jitsi, Youtube etc.) and additionally an audio track with a translation. So, the video will always be the same, but audio channels can be switched by the attendee.

For the audio source we intend to use Streamyard. Streamyard provides video and audio, but we will only be using the audio source from Streamyard.

Currently the links of the source, the "Translation Channels" for these audio channels do not get saved and the Patch API throws a 404.
Please ensure that the links can get stored and the UI works as expected. Currently it looks like a translation channel can neither be deleted, but it is unclear if the API issue is the reason for that.

![Screenshot from 2023-07-31 18-50-55](https://github.com/fossasia/open-event-server/assets/1583873/83ae7ca0-eae0-4af7-9a6a-fb8f33bdfb8c)

**Describe the bug**
The `PATCH` API of `v1/translation_channels?` keeps throwing `404 NOT FOUND`

**To Reproduce**
1. Go to `Manange Event`
2. Choose some event to test, click on `Event Dashboard`
3. Move to `Video` tab
4. Choose a Video Room, click `edit` button to go to the `Video Channel` page
5. Click to `Add Channel`, input some URL and choose a language and click the button with the Add icon
6. Save
7. Go back to the `Video Channel` page, edit the newly added channel, and click the Add icon again, this shall send the Patch API. Use `Network` tab in the browser `Devtool` to check the error

**Expected behavior**
The PATCH API should have an OK response and the channel information is edited

**Comment by minhho89** [comment]
The DB implementing can be found in this discussion:
https://github.com/fossasia/open-event-server/issues/8870

The new table named translation_channels with the following fields as in the screenshot.
Please confirm if the new db table added or not.

![Screenshot_20230731-073600_GitHub](https://github.com/fossasia/open-event-server/assets/61931543/7dd11328-e228-4ed8-ac9c-6475b88719f1)

**Comment by mariobehling** [comment]
**Describe the bug**
The `PATCH` API of `v1/translation_channels?` keeps throwing `404 NOT FOUND`

**To Reproduce**
Steps to reproduce the behavior:
1. Go to `Manange Event`
2. Choose some event to test, click on `Event Dashboard`
<img width="408" alt="image" src="https://github.com/fossasia/open-event-server/assets/61931543/323adebf-a62e-40df-8f28-c3947ee6b789">

3. Move to `Video` tab
4. Choose a Video Room, click `edit` button to go to the `Video Channel` page
5. Click to `Add Channel`, input some URL and choose a language and click the button with the Add icon
6. Save
7. Go back to the `Video Channel` page, edit the newly added channel, and click the Add icon again, this shall send the Patch API. Use `Network` tab in the browser `Devtool` to check the error

**Expected behavior**
The PATCH API should have an OK response and the channel information is edited
