### ISSUE TITLE
Add API docs for video interpretation / translation channels

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#9020]
The recently added translation video channels are not documented in the docs yet. Please add details into the API docs.

**Comment by cweitat** [comment]
https://test-api.eventyay.com/#video-streams-video-streams-get
Information is all wrong
![image](https://github.com/fossasia/open-event-server/assets/11439477/8ea8981a-a655-4c0d-9ae1-eac1fa7be659)
