### ISSUE TITLE
Need API to show details of a ticket whether or not it is checked in/registered.

### ISSUE THREAD

**Issue by shaunBoahCodes** [fossasia/open-event-server#9040]
- Get API
- payload with ticket ID
- response with boolean value whether ticket is checked in/registered
- related to #8957 API. before posting [/v1/user-check-in] for registration the response should include 'is_checked_in: false'. After posting it should be 'is_checked_in: true'

**Comment by cweitat** [comment]
https://test-api.eventyay.com/#attendees-search-attendees-under-an-event-get

**Comment by nnhathung** [comment]
Hi @cweitat , @shaunBoahCodes ,
do we need to know attendee is check in for specific session? or is_check_in is true if attendee check in any session of event?

**Comment by shaunBoahCodes** [comment]
@nnhathung parameters would be something like attendee_id and event_id because this is to check whether the attendee has registered/checked in to the event

**Comment by nnhathung** [comment]
> @nnhathung parameters would be something like attendee_id and event_id because this is to check whether the attendee has registered/checked in to the event

okay @shaunBoahCodes , so you mean this is to check if attendee is registered to the event, not on session.
it clear now
