### ISSUE TITLE
Cannot update tickets because of Unexpected Error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#9049]
Currently it is not possible to edit forms of ticket because of an unexpected error.

Test at https://eventyay.com/orders/0b44d36e-6718-4468-a218-014961c0425a/view

![Screenshot from 2023-08-07 14-04-00](https://github.com/fossasia/open-event-server/assets/1583873/f120d2ab-8471-4b18-83fa-79668aab0253)

**Comment by mariobehling** [comment]
It looks like a change this morning resulted in issues. The registration of people shows "Invalid Date" as well.

![Screenshot from 2023-08-07 14-24-49](https://github.com/fossasia/open-event-server/assets/1583873/48d59294-1c65-4313-9d94-0ff64369fc45)

**Comment by norbusan** [comment]
@lthanhhieu can you please check whether this is fixed now?

**Comment by mariobehling** [comment]
This was fixed. Seems it was because of the server storage.
