### ISSUE TITLE
Refactor download PDF request due to unable to receieve on frontend

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-server#9059]
v1/badge-forms/print-badge-pdf?attendee_id=<id>&list_field_show=email+qr+custom_question

Print badge to convert from current POST with body to GET in URL to act as download link

**Comment by nnhathung** [comment]
Hi @cweitat , 
it is invalid when using '+' from the request URL, so we gonna change it like below url:
v1/badge-forms/print-badge-pdf?attendee_id=&list_field_show=email,qr,custom_question
separate by comma
