### ISSUE TITLE
Add the unique ticket code into the downlad CSV file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-server#9127]
The CSV download file of the attendee list does not include the numbers on the QR Code. Please add this field "Ticket-ID".

The ticket ID has the following format: 135ccbd7-9b23-4a52-a7fd-326fec1b2c1c
Whereas the order has a format like this: #O1691408152-34896

![Screenshot from 2024-03-18 11-40-16](https://github.com/fossasia/open-event-server/assets/1583873/97568f6a-bd5a-4706-899f-64400c2f4da6)

Expected: The exported CSV should have a table column "Ticket ID" with the ticket ID number that is encoded in the QR code as well.

![Screenshot from 2024-03-18 11-48-30](https://github.com/fossasia/open-event-server/assets/1583873/be8e84dd-7088-4a71-8d03-a89d4414904e)

**Comment by lthanhhieu** [comment]
Hi @mariobehling

I have a query:
When will the ticket ID column data be generate? when the ticket is created by events or when the attendee purchasing the ticket?

Please help me confirm it. Thanks

**Comment by mariobehling** [comment]
> I have a query: When will the ticket ID column data be generate? when the ticket is created by events or when the attendee purchasing the ticket?
> 
> Please help me confirm it. Thanks

The CSV is generated when the user (organiser) clicks "Export as CSV". Into this CSV generation process one column ticket ID is missing.

As you can see in the screenshot below. The web UI already shows the ticket ID in the table column "Order". Every order has an order number (it can be several tickets in one order) and every ticket has a ticket ID (the long string that we see also in the table).

![Screenshot from 2024-03-19 10-17-44](https://github.com/fossasia/open-event-server/assets/1583873/27d1f7d8-3583-4a81-841a-29474653c697)

**Comment by mariobehling** [comment]
Currently the ticket ID and the QR code are 90% identical, but there is an additional number at the end of the ticket ID in the QR code which should not be there.

Ticket ID in download CSV: b8f78f85-b602-43dc-b639-fd2e5114de56
Ticket ID in QR code: b8f78f85-b602-43dc-b639-fd2e5114de56-960

![Screenshot from 2024-03-21 09-59-36](https://github.com/fossasia/open-event-server/assets/1583873/8556c32f-8387-4b2e-8704-90a1cf4d4ff1)

@lthanhhieu Please compare here: https://test.eventyay.com/orders/b8f78f85-b602-43dc-b639-fd2e5114de56/view
(This is an old ticket from you)

**Comment by mariobehling** [comment]
@lthanhhieu Ok, now I understand what happened. By deleting the last digits, now several Ticket-IDs have the same ID. For example see this:
![Screenshot from 2024-03-22 19-11-17](https://github.com/fossasia/open-event-server/assets/1583873/16028e6d-acb4-4820-9cd5-7f6ab2914df4)

This can happen if one person orders two tickets. 

An order can be several tickets in one order, but every single ticket needs to have its own ID, e.g. imagine one order with 5 tickets. Each ticket should have its own ticket ID!

The ID of the tickets in the ticket list > must < be the same as the QR code. Therefore the solution to the problem here is: 
a) to revert the last PR and re-add the unique number at the end. This number should be 5 digits e.g. "12345" to support events with more people. For example 0c6a220b-0aba-43f4-a454-f9018ef9e571-**12345**
b) Please change the system to generate QR codes that show the ID including the last digits, e.g. 0c6a220b-0aba-43f4-a454-f9018ef9e571-**12345**
